### ISSUE TITLE
HttpCallAssertion WithQueryParam

### ISSUE THREAD

**Issue by engenb** [tmenier/Flurl#102]
Was thinking I'd ask before I start work on a PR for this.  Is there a good, or preferred, approach that you are aware of for asserting that specific query params were added to the url?

I'm looking for something aside from `.ShouldHaveCalled` - something more explicit like `WithQueryParam(string name, object value)` on `HttpCallAssertion`.  I was thinking I could probably do something in a `.With` using `new Url(call.Url).QueryParams` or maybe `new Url(call.RequestUri.Absoluteuri).QueryParams` but this could get tricky because query params parsed form a `Url` ctor are handled a little differently than params set with `.SetQueryParam` in `Url`

Thoughts?

**Comment by tmenier** [comment]
Hi Brian. Sorry for the delay, been cranking out a few final things for an official Flurl.Http 1.0 release. On the surface `WithQueryParam` sounds like a good idea to me, I'll get it on the 1.1 roadmap.

**Comment by ScottGuymer** [comment]
Has this gotten any further?

Is there currently a way to do this?

**Comment by tmenier** [comment]
Haven't gotten to this yet, but I think `ShouldHaveCalled` combined the `*` wildcard should be able to do what you need. Something like:

```c#
httpTest.ShouldHaveCalled("http://some-api.com/*?*myparam=*");
```

**Comment by TimWilde** [comment]
https://gist.github.com/TimWilde/d42a15edb987a50c60f4526cea6a71eb

This is a quick fix extension method I'm using to work around this for now so the query params can be checked in line with other assertions about the call.

You'll have to excuse the abuse of the RouteValueDictionary - I didn't feel like reinventing the object to dictionary wheel.

Just call `.WithQueryParams( ... )`  inline with other assertions on the httpTest instance:

```
         httpTest.ShouldHaveCalled( $"{apiUrl}/some/path" )
                 .WithVerb( HttpMethod.Get )
                 .WithQueryParams( new { key = "value", other = 12 } )
                 .With( call => call.Request.Headers.Authorization.Parameter == AUTHENTICATION_TOKEN );
```

**Comment by ScottGuymer** [comment]
Never got round to this. Was putting together a PR with this but got sidetracked

@TimWilde has a nice solution!

**Comment by tmenier** [comment]
Nice. @TimWilde If you really want to avoid RouteValueDictionary, Flurl has already [reinvented the object to dictionary wheel](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Shared/Util/CommonExtensions.cs#L24). ;)

**Comment by tmenier** [comment]
Flurl.Http 1.1 will be released shortly, and will include this enahancement. You'll now have:

- `WithQueryParam(string name)` - just checks for existence
- `WithQueryParam(string name, object value)` - checks for name/value, with support for "*" wildcard in value
- `WithQueryParam(object values)` - checks for multiple names/values, supports POCO (parses object properties to name/value pairs) or dictionary

**Comment by tmenier** [comment]
This is now in prerelease. Please test and provide feedback at your earliest convenience. https://www.nuget.org/packages/Flurl.Http/1.1.0-pre

**Comment by TimWilde** [comment]
Just gave this a try but unfortunately it breaks with repeating parameters. Here's an example:

`new { first = "normal", second = new Collection<string> { "qwer", "asdf", "zxcv" } }`

Becomes:

```
first=normal
second=System.Collections.ObjectModel.Collection`1[System.String]
```
Whereas `second` should become three entries with the same name:

```
first=normal
second=qwer
second=asdf
second=zxcv
```

**Comment by tmenier** [comment]
@TimWilde Thanks for the feedback! Just to be clear, I want to make sure I understand the scenario.

If the test subject calls this url: 

`http://api.com?x=1&x=2&x=3`

And I do this in my test:

`test.ShouldHaveCalled("*").WithQueryParams(new { x = new[] {1, 2, 3} });`

The test will fail?

Although it seems like a bit of a stretch that someone would write a test like that, I do agree with you that it should pass. It's consistent with how `SetQueryPararms` handles collections. So I'll try to get this fixed.

Thanks again!

**Comment by tmenier** [comment]
@engenb @ScottGuymer @TimWilde I'm adding several more variations of query param checking and I wanted to get your opinion on something. Given this method that checks NON-existence of multiple query params (just name, forget values for now):

`test.ShouldHaveCalled("*").WithoutQueryParams("a", "b", "c");`

I'm trying to decided whether checking for not ANY or not ALL would be more intuitive. For example, would you expect the above test to pass for `myurl.com?a=foo`? I'm leaning toward that failing. In other words, check for not ANY rather than not ALL.

Thoughts?

**Comment by tmenier** [comment]
[Flurl.Http 1.1.1 prerelease is now available on NuGet](https://www.nuget.org/packages/Flurl.Http/1.1.1-pre). Here are new query param assertions that have been added:

````
WithQueryParam(string name)
WithoutQueryParam(string name)
WithQueryParams(params string[] names)
WithoutQueryParams(params string[] names)
WithQueryParamValue(string name, object value)
WithoutQueryParamValue(string name, object value)
WithQueryParamValues(object values)
WithoutQueryParamValues(object values)
````

Please test if you are able to. I hope to get the full release out soon.

**Comment by TimWilde** [comment]
I've updated to 1.1.1-pre and I've updated all of our tests to use WithQueryParamValues( object values ) and they all pass (including enumerable properties converted to repeated parameters,) so that looks good to me! :)

And for the _Without_ variants, I agree with you: I think the presence of _any_ of the named params should fail the test as I think it makes most sense as "It is expected that none of these will be present, if any are, that breaks the expectation."
