### ISSUE TITLE
NuGet Package installation issue

### ISSUE THREAD

**Issue by tylerlong** [tmenier/Flurl#103]
```
Install-Package : Could not install package 'Flurl.Http 0.10.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile5', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Flurl.Http
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

![image](https://cloud.githubusercontent.com/assets/733544/15889320/5b1486a2-2d9d-11e6-869b-6b15f8d35d2a.png)

**Comment by tylerlong** [comment]
According to this issue: https://github.com/tmenier/Flurl/issues/94  .NET 4.0 should be supported.

**Comment by kroniak** [comment]
@tylerlong Flurl.Http didn't support net 4. Only Flurl package supports net 4.

**Comment by tmenier** [comment]
Yes, that is correct, as documented [here](http://tmenier.github.io/Flurl/installation/). (Sorry @kroniak, missed that!)

**Comment by tylerlong** [comment]
@kroniak @tmenier Does it depend on any libraries which are not compatible with .NET 4.0? May I create a NuGet package myself and mark it compatible with .NET 4.0?

**Comment by kroniak** [comment]
@tylerlong I can add support separate NET40 framework, but not PCL40 libraries. https://www.nuget.org/packages/PCLStorage/ does not support NET40.

**Comment by Im-PJ** [comment]
@tylerlong are you using Flurl.http in .net 4?  Pls suggest if there is any way?

**Comment by tylerlong** [comment]
@Im-PJ  as far as I can remember, we have given up .net 4.0
