### ISSUE TITLE
Deseralizing object with `PostJsonAsync`

### ISSUE THREAD

**Issue by piedoom** [tmenier/Flurl#126]
Hi - 
I use the generic parameter a ton for getting Json, e.g. `.GetJsonAsync<MyJSONObject>()`.  I was wondering if there was a reason why `.PostJsonAsync()` doesn't have the same functionality.  It's easy enough to deserialize afterwards, but wrapping it up might be a nice addition.

**Comment by tmenier** [comment]
You can deserialize it in the fluent chain via `ReceiveJson<T>()`. See the example on the home page:

http://tmenier.github.io/Flurl/
