### ISSUE TITLE
Exception in thrown even when ExceptionHandled is set to true

### ISSUE THREAD

**Issue by XiteZ** [tmenier/Flurl#127]
Hey,

Either I don't understand correctly that function or there is something wrong.
Let's look at this code:
```
private ApiClient()
{            
            FlurlHttp.Configure(c =>
            {
                c.OnError = HandleError;
            });
}
private void HandleError(HttpCall httpCall)
        {
            httpCall.ExceptionHandled = true;
            //something
            
        }
```
and then:
`url.AppendPathSegment("media").GetJsonAsync<List<Media>>();`

if something wrong happens now, HandleError method is called properly but above line of code still throws an flurl exception. It should not throw an exception I guess. Am I right?

**Comment by tmenier** [comment]
I was unable to reproduce this. (See [test](https://github.com/tmenier/Flurl/commit/466fea2a2ae48866f9cbdefe8f2a79db0acdc7f0).) Can you post a full code sample? I think something else is going on.
