### ISSUE TITLE
FileNotFoundException in Framework 4.6.1

### ISSUE THREAD

**Issue by rmbrunet** [tmenier/Flurl#128]
Hello, I am having a problem using Flurl.Http. When calling 
```
   var response = url
       .WithBasicAuth(client.client_id, client.client_secret)
       .PostUrlEncodedAsync(pars)
       .ReceiveJson<token_response>()
       .Result;
```
I get a **FileNotFoundException** for **System.Reflection.TypeExtensions**. I can reproduce the problem simple console app just referencing **Flurl** and **Flurl.Http**. At the same time "http://...".GetStringAsync() works perfectly well. 

Any idea what could be happening?

Great library!

Roberto

**Comment by rmbrunet** [comment]
Great!

**Comment by rmbrunet** [comment]
Any idea when this fix will be available?

Thanks!

**Comment by kroniak** [comment]
@rmbrunet I have no rights to upload it to nuget. By it is avaliable on myget today.

**Comment by rmbrunet** [comment]
Thanks @kroniak!

Btw, you are missing an 's' in St. Petersburg, mednii vsadnik won't be happy :-)

**Comment by kroniak** [comment]
@rmbrunet you are right. I was using russian to english transcription without s char. I'll change it.

**Comment by rmbrunet** [comment]
@kroniak, I updated my Flurl.Http to 1.0.2 from MyGet. Everything seems to be working fine. But I observed something (unrelated) that happens to me always. I am doing my testing in Linqpad (the paid edition allows me to import Nuget Packages) and, after importing Flurl.Http I always get a MissingMethodException in PostUrlEncodedAsync. Then I have to manually add a reference to System.Net.Http  to make it work. That is strange as Sytsem.Net.Http is a dependency. This behavior is not new.

**Comment by kroniak** [comment]
@Rembrandt I have a some idea about it. What version of net do you use with linqpad?

**Comment by rmbrunet** [comment]
I am using Linqpad 5 implying Framework 4.6.*

**Comment by tmenier** [comment]
didn't mean to close, not "officially" fixed yet :)

**Comment by tmenier** [comment]
ok, this is up on [NuGet](https://www.nuget.org/packages/Flurl.Http/1.0.2). Thanks to both of you for reporting/fixing!
