### ISSUE TITLE
.NET 4.6.1 dependencies

### ISSUE THREAD

**Issue by oliverjanik** [tmenier/Flurl#135]
Hello, I'm using just Flurl not Flurl.Http.

Correct me if I'm wrong, but are these needed?
```
			<group targetFramework="net461">
				<dependency id="System.Globalization" version="4.0.11" />
				<dependency id="System.Linq" version="4.1.0" />
				<dependency id="System.Reflection.TypeExtensions" version="4.1.0" />
			</group>
```

Doesn't the fact that you're targeting FULL .net guarantee presence of those namespaces?

**Comment by kroniak** [comment]
@oliverjanik There are NET45 dll and NETSTD1.3 dll. Project on Full NET461 does not use NET45 lib and uses NETSTD1.3 dll which require these deps.
