### ISSUE TITLE
Trace http traffic

### ISSUE THREAD

**Issue by wvdvegt** [tmenier/Flurl#136]
Is it possible to trace the http network traffic?

I would like to see the full http request and response of web services I call for debugging purposes. So be able to see the Json before it gets de-serialized etc..

As a workaround I created a couple of extension methods that do so (but a build-in option would have y preferences, in order to avoid update issues). 

Example:

```
      public static async Task<T> ReceiveJsonTrace<T>(this Task<HttpResponseMessage> response, String prefix = "Flurl:")
        {
            var resp = await response.ConfigureAwait(false);
            var call = HttpCall.Get(resp.RequestMessage);
#if DEBUG
            Debug.WriteLine(String.Format("{0} {1}", prefix, resp.RequestMessage.RequestUri.ToString()).TrimStart());

            Debug.WriteLine(String.Empty);
            Debug.WriteLine(String.Format("{0} {1}", prefix, "Request Headers:").TrimStart());
            foreach (KeyValuePair<String, IEnumerable<String>> header in resp.RequestMessage.Headers)
            {
                Debug.WriteLine(String.Format("{0} {1}={2}", prefix, header.Key, String.Join("; ", header.Value)).TrimStart());
            }

            Debug.WriteLine(String.Empty);
            Debug.WriteLine(String.Format("{0} {1}", prefix, "Response Headers:").TrimStart());
            foreach (KeyValuePair<String, IEnumerable<String>> header in resp.Headers)
            {
                Debug.WriteLine(String.Format("{0} {1}={2}", prefix, header.Key, String.Join("; ", header.Value)).TrimStart());
            }

            Debug.WriteLine(String.Empty);
            Debug.WriteLine(String.Format("{0} {1}", prefix, "Response Body:").TrimStart());
#endif
            try
            {
                using (var stream = await resp.Content.ReadAsStreamAsync().ConfigureAwait(false))
                {
#if DEBUG
                    using (StreamReader reader = new StreamReader(stream, Encoding.UTF8))
                    {
                        stream.Position = 0;

                        if (!String.IsNullOrEmpty(prefix))
                        {
                            Debug.WriteLine(String.Format("{0}", prefix).TrimStart());
                        }
                        Debug.WriteLine(reader.ReadToEnd());

                        stream.Position = 0;
#endif
                        return call.Settings.JsonSerializer.Deserialize<T>(stream);
#if DEBUG
                    }
#endif
                }
            }

            catch (Exception ex)
            {

                call.Exception = ex;

                throw new FlurlHttpException(call, ex);

            }
        }
```

**Comment by tmenier** [comment]
If this works how you need it to then I think you did it exactly the right way. I wouldn't worry about this breaking due to future updates. Other than `FlurlHttpException` at the end, you're not even dealing with Flurl APIs at all. (`HttpMessage` is part of the underlying HttpClient APIs.) Everyone likes to debug a little differently, so I'd say this is better left as a nice example of Flurl's extensibility rather than adding it to the core.

As a side note, deserializing the body would probably be a lot easier using `Content.ReadAsStringAsync` instead of `ReadAsStreamAsync`.

**Comment by wvdvegt** [comment]
I agree that everybody's thought on debugging are different. Personally I would personally like some hook to be able to do debugging my way. One or two delegates I can pass to the method doing the actual work, that get called if assigned and get passed the request and/or response objects.
That way everybody could do debugging the way he/she likes (or not).

Problem with the fluent approach is that you never get to see what URL actually created and requested.

Having said this, it's a really nice way of handling rest request which I really like.

**Comment by tmenier** [comment]
Just another note: [the `BeforeCall` and `AfterCall` callbacks ](http://tmenier.github.io/Flurl/configuration/) are also very effective mechanisms for inspecting/debugging calls.

**Comment by wvdvegt** [comment]
Hi

Excellent solution. 

One drawback when making calls to reset services is that you cannot (as far as my knowledge goes), dump the response body (as it's still in the stream). 

So one more callback (just before serialization) when the stream is read would be a great addition.

So in ReceiveJson() just before the
