### ISSUE TITLE
Flurl.Http NuGet package doesn't include some system dependencies.

### ISSUE THREAD

**Issue by MNF** [tmenier/Flurl#138]
The sample console app with just added Flurl.Http sequentially reported that it
Could not load file or assembly 'System.Diagnostics.DiagnosticSource',
System.Security.Cryptography.X509Certificates, Microsoft.Win32.Primitives.

I had to manually install correspondent NuGet packages to make application working.

Could you please add missing dependencies to the NuGet package.
The sample application can be found at https://github.com/MNF/CommonDotNetHelpers/tree/master/Samples/CheckFiddlerWithSystemNetHttp

Please see below exceptions and NuGet logs

Message=Request to http://en.wikipedia.org/ failed. Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
       Source=Flurl.Http
       StackTrace:
            at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs:line 59
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Flurl.Http.FlurlClient.<SendAsync>d__28.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\FlurlClient.cs:line 128

            FusionLog==== Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///D:/GitRepos/MNF/CommonDotNetHelpers/Samples/CheckFiddlerWithSystemNetHttp41/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\bin\Debug\CheckFiddlerWithSystemNetHttp41.vshost.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

            StackTrace:
                 at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs:line 37
           

The installation log didn't try to include Diagnostics DLL
Attempting to gather dependency information for package 'Flurl.Http.1.0.3' with respect to project 'CheckFiddlerWithSystemNetHttp41', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Flurl.Http.1.0.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Flurl.Http.1.0.3'
Resolved actions to install package 'Flurl.Http.1.0.3'
Adding package 'Flurl.2.2.1' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'Flurl.2.2.1' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'Flurl.2.2.1' to 'packages.config'
Successfully installed 'Flurl 2.2.1' to CheckFiddlerWithSystemNetHttp41
Adding package 'Newtonsoft.Json.9.0.1' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'Newtonsoft.Json.9.0.1' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
Executing script file 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 9.0.1' to CheckFiddlerWithSystemNetHttp41
Adding package 'Flurl.Http.1.0.3' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'Flurl.Http.1.0.3' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'Flurl.Http.1.0.3' to 'packages.config'
Successfully installed 'Flurl.Http 1.0.3' to CheckFiddlerWithSystemNetHttp41
========== Finished ==========
I've installed System.Diagnostics.DiagnosticSource.4.0.0:
Attempting to gather dependency information for package 'System.Diagnostics.DiagnosticSource.4.0.0' with respect to project 'CheckFiddlerWithSystemNetHttp41', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'System.Diagnostics.DiagnosticSource.4.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'System.Diagnostics.DiagnosticSource.4.0.0'
Resolved actions to install package 'System.Diagnostics.DiagnosticSource.4.0.0'
Adding package 'System.Diagnostics.DiagnosticSource.4.0.0' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'System.Diagnostics.DiagnosticSource.4.0.0' to folder 'D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\packages'
Added package 'System.Diagnostics.DiagnosticSource.4.0.0' to 'packages.config'
Successfully installed 'System.Diagnostics.DiagnosticSource 4.0.0' to CheckFiddlerWithSystemNetHttp41
========== Finished ==========
Then I've got next 
       Message=Request to http://en.wikipedia.org/ failed. Could not load file or assembly .

       InnerException: System.IO.FileNotFoundException
            _HResult=-2147024894
            _message=Could not load file or assembly 'System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
            HResult=-2147024894
            IsTransient=false
            Message=Could not load file or assembly 'System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
            Source=System.Net.Http
            FileName=System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
            FusionLog==== Pre-bind state information ===
LOG: DisplayName = System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///D:/GitRepos/MNF/CommonDotNetHelpers/Samples/CheckFiddlerWithSystemNetHttp41/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\GitRepos\MNF\CommonDotNetHelpers\Samples\CheckFiddlerWithSystemNetHttp41\bin\Debug\CheckFiddlerWithSystemNetHttp41.vshost.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///D:/GitRepos/MNF/CommonDotNetHelpers/Samples/CheckFiddlerWithSystemNetHttp41/bin/Debug/System.Security.Cryptography.X509Certificates.DLL.
LOG: Attempting download of new URL file:///D:/GitRepos/MNF/CommonDotNetHelpers/Samples/CheckFiddlerWithSystemNetHttp41/bin/Debug/System.Security.Cryptography.X509Certificates/System.Security.Cryptography.X509Certificates.DLL.
LOG: Attempting download of new URL file:///D:/GitRepos/MNF/CommonDotNetHelpers/Samples/CheckFiddlerWithSystemNetHttp41/bin/Debug/System.Security.Cryptography.X509Certificates.EXE.
LOG: Attempting download of new URL file:///D:/GitRepos/MNF/CommonDotNetHelpers/Samples/CheckFiddlerWithSystemNetHttp41/bin/Debug/System.Security.Cryptography.X509Certificates/System.Security.Cryptography.X509Certificates.EXE.

            StackTrace:
                 at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs:line 37
            InnerException:
Then the similar message for next assembly
Additional information: Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

**Comment by kroniak** [comment]
@MNF sorry, I cant reproduce this issue on fresh console net 461 app from vs2015 console app template.

I use https://github.com/MNF/CommonDotNetHelpers/blob/master/Samples/CheckFiddlerWithSystemNetHttp/CheckFiddlerWithSystemNetHttp41/Program.cs code.

All dependencies were installed with flurl.http package.

**Comment by tmenier** [comment]
My findings were the same. I think there was a problem with your package references. I forked your repo, removed the console app project and recreated it from scratch, copied your original program.cs into it, and installed Flurl.Http from NuGet. Everything built and ran fine. Feel free to reject my PR and try the above steps yourself if you want.

**Comment by Maxhodges** [comment]
i also get 
```
7cac4331-a{"Could not load type 'Flurl.Http.HttpExtensions' from assembly 'Flurl.Http, Version=2.3.2.0, Culture=neutral, PublicKeyToken=null'.":"Flurl.Http.HttpExtensions"}a58-3108-a83c-c4a2e02959ce
```
