### ISSUE TITLE
HttpTest Call List race condition?

### ISSUE THREAD

**Issue by kenhahn85** [tmenier/Flurl#141]
I'm encountering strange race condition when trying to assert against the number of times an http request was made through Flurl (using the `.Times`) method, but the results of the `Times` method are inconsistent -- the hallmark of a race condition. I'm just not sure where the race condition is, and `HttpTest` is my best guess, seeing as I've read that `List.Add` is not threadsafe.

**Comment by kenhahn85** [comment]
Nvm, figured it out.

**Comment by tmenier** [comment]
Related to #67? HttpTest and related methods need a big disclaimer that they are by no means threadsafe. Known issue and being worked on right now. For now it is just a known limitation that testing multithreaded code or running tests in parallel doesn't play nice with Flurl's testing methods.
