### ISSUE TITLE
Replace constructor with factory method in HttpExtensions class

### ISSUE THREAD

**Issue by Deilan** [tmenier/Flurl#143]
In some cases it is needed to configure `FlurlClient` instance (e.g. modifying `FlurlHttpSettings`) before invokation of the extension methods of `HttpExtensions` class. For example, recently I've encountered a situation when I needed to replace naming strategy of the underlying `NewtonsoftJsonSerializer`. Yes, there is corresponding method: 
```
public static FlurlClient ConfigureClient(this Url url, Action<FlurlHttpSettings> action) 
{
    return new FlurlClient(url, true).ConfigureClient(action);
}
```
which gets the job done, but the problem is: one need to call it everywhere in client code, because on invoking `HttpExtensions`'s methods, the instantiation happens exactly there. So it is proposed to replace `FlurlClient` constructor invokation in `HttpExtensions` class with some sort of a factory method or resolver, which defaults to invoking the constructor but could be replaced with a user's definition. Probably the same should be done in the other places: for example aforementioned `ConfigureClient()` method.

**Comment by tmenier** [comment]
I think [configuring those options at the global level](http://tmenier.github.io/Flurl/configuration/) is what you're looking for. Each `FlurlClient` instance still gets its own copy of those settings, but the global config provides a mechanism for setting defaults for every instantiated instance app-wide.

**Comment by tmenier** [comment]
Closing this issue because I think global configuration is what you're looking for. If I'm wrong, feel free to re-open and we can discuss further.
