### ISSUE TITLE
Creating a new HttpClient every request

### ISSUE THREAD

**Issue by JulianRooze** [tmenier/Flurl#144]
I really love using Flurl.Http, but I have some concerns with its use of the `HttpClient`. Unless I'm overlooking something, every call to something like `PostJsonAsync` or `GetAsync` creates a new `HttpClient` and then disposes it at the end. For a number of reasons, this is not recommended as explained in this article:

http://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

What this means is that every call made using Flurl.Http leaves a connection open for a while and it's easy to reproduce a case where using Flurl can exhaust your sockets:

```csharp
int i = 0;

while (true)
{
	await "http://localhost:80".GetStringAsync();
	i++.Dump();
}
```

That script will reliably crash for me in LINQPad at around 16K iterations. While I haven't had a production scenario yet where this has been a problem, doing 16K HTTP requests over a period of 240 seconds (the time before the first connection is truly closed) isn't unthinkable. 

The .NET `HttpClient` class is poorly documented and designed, but even if it isn't clear it's really meant to be shared and reused, not thrown away quickly. However, simply creating a static instance and never disposing it wouldn't be sufficient, as you might run into DNS issues as explained here:

https://www.infoq.com/news/2016/09/HttpClient

So ideally the `HttpClient` class would be wrapped inside a class that would hold a single instance of an `HttpClient` and would keep track of all endpoints used so far so that it could set the connection lease timeout per endpoint (as that is the only option).

Any thoughts?

**Comment by tmenier** [comment]
Thanks. I'm well aware of the advice, and you're right - at a high enough volume (probably higher than most applications need to worry about) you really ought to be reusing instances rather than rapidly creating/disposing, and the string extension methods don't really give you a way to do that.

HttpClient lifetime is directly tied to that of the containing FlurlClient, so for high-volume scenarios [there is an alternative pattern](http://tmenier.github.io/Flurl/client-lifetime/) of managing FlurlClient instances explicitly. It's not quite as succinct and "cute" as the string extensions, but certainly recommended for these scenarios. There was a time when I toyed with the idea of smartly managing one instance per host being called, but in the end it was hard to get just right - there always seemed to be the potential for unexpected behavior. Allowing the consuming application to manage this by managing FlurlClient instances seemed much more straightforward and predictable.

**Comment by JulianRooze** [comment]
Thanks for the reply! I agree that solving this correctly would be fairly complex and the `FlurlClient` reuse workaround seems acceptable in terms of extra code. Like I said, it hasn't been an issue in production, but it's more that it's this nagging feeling in the back of my mind that every URL I call leaves this expensive resource alive that continues to live for 4 more minutes, which takes away a little bit of the awesomeness that is using Flurl :)

I've seen a wrapper class for HttpClient that manages the reuse and DNS lease online somewhere when reading about this HttpClient issue, but I can't find it anymore sadly.

**Comment by tmenier** [comment]
I'm leaving this open as a roadmap item for 2.0. Flurl has matured a lot since I first contemplated "smart" instance management based on host and might be worth another look.

**Comment by gitfool** [comment]
I think Flurl should continue to keep it simple. Given it hangs FlurlClient instances off HttpClient instances, the same best practices can be used to manage instance lifetime.

For example, I use the Autofac IoC container to wire everything up and inject a shared IFlurlClient instance as required. This would usually be a singleton _but_ can be wired up as instance per lifetime scope when used with xUnit for integration tests, where each test needs its own instance since the logger injected into the http pipeline writes to a different sink. (This needs to be balanced with the ability to isolate and customize instances via copy-on-write.)

The point is I have complete control of the FlurlClient <=> HttpClient instances and their lifetimes and I'd like it to stay that way.

**Comment by JulianRooze** [comment]
@gitfool I understand that, but I'm not sure if keeping a singleton IFlurlClient is even a valid solution, because the `WithHeader` method adds headers to the `DefaultRequestHeaders` of the `HttpClient` instance. So if you use a singleton HttpClient (effectively) and `WithHeader` then I think you'll end up with race conditions. Correct me if I'm wrong. 

Honestly, in a perfect world I'd like to see `Flurl.Http` rewritten to use good old `WebRequest` internally instead of `HttpClient`, as `HttpClient` is just a irredeemably bad API. Perhaps I'm not aware of the glaring issues with the `WebRequest` API (aside from it being much more verbose to use than `HttpClient, but that'd be hidden by Flurl) but I don't think it has the issues of `HttpClient`. Flurl would just be a much nicer to use RestSharp. 

I might take a swing at contributing a `Flurl.WebRequest` project, as `Flurl.Http` needs to stay around without breaking changes.

**Comment by gitfool** [comment]
@JulianRooze Yeah using singletons you need to be isolate changes, ideally using copy-on-write semantics to avoid excessive redundant copying. I'm proposing a solution [here](https://github.com/tmenier/Flurl/issues/189#issuecomment-315191231).

**Comment by tmenier** [comment]
@JulianRooze This is probably the wrapper class you mentioned:

https://github.com/NimaAra/Easy.Common/blob/master/Easy.Common/RestClient.cs

**Comment by tmenier** [comment]
@JulianRooze I agree that `HttpClient` never should have implemented `IDisposible` if wasn't intended to be disposed after each use. But I'm curious, aside from that, what do you find so irredeemably bad about it that would make you want to switch back to `WebClient`?

**Comment by JulianRooze** [comment]
@tmenier - Because it doesn't work well as a singleton, either. It has the weird notion of `DefaultRequestHeaders`, which is shared state that can cause concurrency issues when a single `HttpClient` is used as a global singleton. In addition, when used as a singleton it suffers from the DNS issues mentioned above. It's a "damned if you do, damned if you don't" API. Perhaps the best approach with `HttpClient` is some sort of factory class that would keep a `ThreadLocal<HttpClient>` that is refreshed on a 1 minute timer for a new instance, on a per thread basis. 

I haven't ever really used WebClient, but I've used plenty of `WebRequest.Create` which is, as far as I know, a sane and stable API that doesn't have any glaring issues, aside from being a pain to use, but that would be managed by Flurl.

**Comment by tmenier** [comment]
I don't think `DefaultRequestHeaders` is a design flaw nor weird. I think it's just what it says, and it's handy if you want to call the same API multiple times. If your app interfaces with 6 different APIs, then you probably want 6 singletons, not 1.

You'll be glad to know that most of what you've mentioned in this issue will be the centerpiece of Flurl.Http 2.0. I'll have some announcements soon, probably in the form of an issue so it can spur a conversation, but they probably won't involve switching to WebClient. :)

Stay tuned!

**Comment by tmenier** [comment]
@gitfool @JulianRooze Could either you provide an example of how you might manage `IFlurlClient` instances with an IoC container in a situation where your app is calling multiple distinct APIs? I would think, generally, that a singleton _per API called_ would be a best practice here, especially if you want to configure different default headers, etc. I have an idea of what this would look like but curious what you come up. An actual code sample using AutoFac or whatever would be very helpful.

I should mention that while I want to introduce "smart" client instance management (largely based on the 2 articles cited in this issue) it will _not_ apply to cases where you're managing `IFlurlClient` instances explicitly. I completely agree with @gitfool about keeping it simple and predictable, and the lifetime of a `FlurlClient` will always be tightly bound to that of an `HttpClient`. The new behavior will be for cases where you're _not_ managing clients explicitly, i.e. `url.GetJsonAsync()`.

Thanks!

**Comment by JulianRooze** [comment]
@tmenier - Thanks for your active participation! 

We don't currently manage `IFlurlClient` instances through dependency injection. We either use Flurl by simply calling the extension methods on string, or inside a long running batch job where we know we'll be doing thousands of requests we `new` up an instance of `FlurlClient` and reuse that for the duration.

One "problematic" example I can give is we have a component that lets you input an URL and it does an API call with an external party that returns a NSFW score for that URL. It's a component that might be called enough to cause a problem with the unclosed connections, so it's a candidate for a singleton. However, we run a multi-tenant platform and each tenant might have a different API key that's passed to the API through the request headers. If it's a singleton, then this might cause concurrency problems because of the `DefaultRequestHeaders`. 

If Flurl is going to smartly manage `HttpClients` so that I can call `url.GetStringAsync()` thousands of times inside a loop without worrying or having to manage `IFlientClient` myself, then that would be great and I'd be happy.

**Comment by gitfool** [comment]
@tmenier I'll definitely throw together something when I get some spare time - soon!

I'd much prefer a global singleton across everything. That's the root scope and you can always add inner scopes from there, but not the other way around, so it really needs to start with that(!)

There are two immediate issues in the way:

- [FlurlClient.cs:165](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlClient.cs#L165) causes `InvalidOperationException`
  - So this setting must be moved to when the `HttpClient` is created
- `DefaultRequestHeaders` should be avoided
  - So _per request_ headers must be surfaced ... somehow

**Comment by tmenier** [comment]
@JulianRooze @gitfool Thanks for your feedback. I think you'll be pleased with what's coming: https://github.com/tmenier/Flurl/issues/205

**Comment by JulianRooze** [comment]
@tmenier sounds great to me, thanks! :)

**Comment by tmenier** [comment]
The prerelease is published on NuGet, please test it when you have a chance.

@JulianRooze The DNS issue is still not explicitly dealt with, main reason being that the recommended fix is [not available in .NET Core](https://github.com/dotnet/corefx/issues/11224). Since you brought it up, how do you propose Flurl should deal with this?

@gitfool Let me know what you think about the [new usage pattern for FlurlClient](https://github.com/tmenier/Flurl/issues/211). I'm already using it and wondering how I lived without it. :)

**Comment by adrianm64** [comment]
Note that HttpClient is just a holder for url, headers and timeout. All work is done in the HttpMessageHandler. i.e. if you just reuse the same HttpMessageHandler for all created HttpClients you can create/dispose as many as you like. Makes it a lot easier to deal with changing headers and timeout since you can work with a fresh HttpClient for each request.

    private static Lazy<HttpClientHandler> _defaultHandler = new Lazy<HttpClientHandler>()

    // Allow users to specify their own handler e.g. for logging
    public HttpMessageHandler MessageHandler { get; set; }

    private HttpClient CreateClient() {
        var client = new HttpClient(MessageHandler ?? _defaultHandler.Value, disposeHandler: false);
        // set base url, headers etc
        return client;
    }

    private void UseClient(Uri uri) {
        using (var client = CreateClient())
        using (var response = client.GetAsync(uri)) {
            ...
         }
    }

**Comment by tmenier** [comment]
@adrianm64 That's actually a really good point, and one that never seems to get mentioned in any of the articles or blog posts on the subject. All correct though, to the best of my knowledge. In 2.0 I've stopped piggybacking on HttpClient for most stateful things like default headers and timeouts, so at this point I don't think there's much to gain by _not_ resuing HttpClient. Would you agree? Either way, I'll keep this in mind as I give things a final review. Thanks!

**Comment by adrianm64** [comment]
Agree. If you already got code to build url and set all headers per request there is no need to change it. Only benefit would be timeout since you can't change it after first request is sent.

**Comment by tmenier** [comment]
I moved the DNS problem mentioned in this issue to a [separate issue](#222). Please comment there with any thoughts you might have on my proposed solution.

**Comment by tmenier** [comment]
@gitfool Please let me know if you have any thoughts on #226. I'm hoping it's a nice enhancement/pattern for using Flurl with IoC.

**Comment by delta25** [comment]
Apologies for commenting on an issue that was closed almost 2 years ago, however I have a somewhat related question, which didn't warrant opening a new ticket.

I'm running Flurl.HTTP 2.4.0, and using the URL builder API to set up my request and then send it off, as shown below.

```
var x = await Url.Combine(_baseUrl, endpoint, objectId).WithHeader("Key", "Value").GetJsonAsync<T>();
```
In this case, am I correct in assuming that a NEW Flurl client is being used to issue the request every time? I.e. I have a problem and need to fix it before I run out of ports!?

**Comment by delta25** [comment]
Further apologies are required!
I've now read the HttpClient Lifetime page on the site (why didn't I do this in the first place), and my question has been answered.
