### ISSUE TITLE
SUT is overriding HttpTest 's HttpClientFactory

### ISSUE THREAD

**Issue by pmorelli92** [tmenier/Flurl#145]
Hi guys, so the problem I am having is that when I execute this:

```c#
// Setup
using (var httpTests = new HttpTest())
{
	httpTests.RespondWith("<Response />");

	// Exercise
	var response = sut.Post(request).Result;

	// Verify outcome
	AssertHttpAvailabilityCall(serviceConfig, request, httpTests);
}
```

Inside the ctor of the HttpTest we can see that this code is executed:

```c#
public HttpTest() {

	FlurlHttp.Configure(settings => {
		settings.HttpClientFactory = new TestHttpClientFactory(this);
		settings.AfterCall = call => CallLog.Add(call);
	});
	
	ResponseQueue = new Queue<HttpResponseMessage>();
	CallLog = new List<HttpCall>();
}
```

And when I call my sut.Post this happens:

```c#
var responseMsg = await
	_serviceConfig.AvailabilityUrl
	.SetQueryParams(new
        {
		api_key = request.ApiKey,
		auth_token = request.AuthToken,
	})
	.GzipDeflateEncoding()
	.PostUrlEncodedAsync(encodedData: request.HotelsId)
	.ConfigureAwait(continueOnCapturedContext: false);
```

Where GzipDefalteEncoding is an extension method that does the following:

```c#
public static FlurlClient GzipDeflateEncoding(this Url url)
{
	var client = new FlurlClient(url, autoDispose: true);
	client.Settings.HttpClientFactory = new DeflateGzipEncodingHttpFactory();
	return client;
}

public class DeflateGzipEncodingHttpFactory : IHttpClientFactory
{
	public HttpClient CreateClient(Url url, HttpMessageHandler handler)
	{
		var httpClient = new HttpClient(new FlurlMessageHandler(handler), disposeHandler: true);
		httpClient.BaseAddress = new Uri(url.ToString());
		return httpClient;
	}

	public HttpMessageHandler CreateMessageHandler()
	{
		var handler = new HttpClientHandler();
		handler.AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate;
		return handler;
	}
}
```

Then, when the call is executed, it is against the real url because the TestHttpClientFactory was overriden.

I tried these 3 ways but the results are always the same (the TestHttpClientFactory  got overriden)

```c#
client.Settings.HttpClientFactory = new DeflateGzipEncodingHttpFactory();
```

```c#
client.ConfigureClient(f => f.HttpClientFactory = new DeflateGzipEncodingHttpFactory());
```

```c#
client.ConfigureHttpClient(f => {

	var factory = new DeflateGzipEncodingHttpFactory();

	f = factory.CreateClient(
			url: client.Url,
			handler: factory.CreateMessageHandler());
});
```

Is there other way to do this?
Thanks!

**Comment by pmorelli92** [comment]
Yesterday I read this issue #144 and I concluded that I was using (pun intended) the HttpClient in a bad way. 
So now my SUT receives the FlurlClient by injection with the DeflateGzipEncodingHttpFactory shown before already set (instead of creating a FlurlClient with an HttpClient per request) and now my `sut.Post` execute the following:

```c#
var responseMsg =
	await _client
		.WithUrl(
			_url
			.SetQueryParams(new
			{
				api_key = request.ApiKey,
				auth_token = request.AuthToken,
			}))
		.PostUrlEncodedAsync(encodedData: request.HotelsId)
		.ConfigureAwait(continueOnCapturedContext: false);
```

Even tough the  `.WithUrl` extension creates a new instance of the FlurlClient, the underlying HttpClient and HttpMessageHandler is the same.

With this change not only I reuse the HttpClient but I indirectly solved the problem in the tests because now I can do something like this:

```c#
// Setup
using (var httpTests = new HttpTest())
{
	httpTests.RespondWith("<Response />");
	var sut = new AvailabilityService(url, new FlurlClient());

	// Exercise
	var response = sut.Post(request).Result;

	// Verify outcome
	AssertHttpAvailabilityCall(request, httpTests);
}
```

I dont think the original issue is solved but if anyone is having the same problem that me, here is one workaround that works.

**Comment by tmenier** [comment]
There's some major refactoring to HttpTest in Flurl.Http 1.1 that I believe will fix the quirks you found originally. Give it a try: https://www.nuget.org/packages/Flurl.Http/1.1.0-pre

**Comment by tmenier** [comment]
I'll be closing this issue with the next full release of Flurl.Http (1.1.1) because I believe the changes to HttpTest. I'd still encourage you to verify with the prerelease.
