### ISSUE TITLE
Test mode does not function as documented when tests are run in parallel.

### ISSUE THREAD

**Issue by TimWilde** [tmenier/Flurl#148]
This behavior affects 1.1.0-pre.

The documentation says:

> test mode, where all HTTP activity in the test subject is automatically faked and recorded

and

> By default, fake HTTP calls return a 200 (OK) status with an empty body.

However, I've found that if I don't explicitly call `.RespondWith(...)`, then the test will fail when run as part of a test fixture, but will pass when run in isolation. Specifically, when run as part of a test fixture, Flurl attempts to make a web request as if HttpTest were not in effect.

Example which fails when run as part of a fixture, but passes when run in isolation:

```
      [ Test, AutoData ]
      public void Should_configure_the_api_call_correctly( Guid userId )
      {
         using( var httpTest = new HttpTest() )
         {
            HttpClientUserResource resource = System_under_test();

            resource.GetAsync( userId )
                    .ConfigureAwait( false )
                    .GetAwaiter()
                    .GetResult();

            httpTest.ShouldHaveCalled( $"{apiUrl}path/{userId}" )
                    .WithVerb( HttpMethod.Get )
                    .With( call => call.Request.Headers.Authorization.Parameter == AUTHENTICATION_TOKEN )
                    .With( call => call.Request.Headers.Accept.Contains( new MediaTypeWithQualityHeaderValue( "application/vnd.myApp.v1+json" ) ) );
         }
      }

```

by just adding `httpTest.RespondWith( string.Empty, 200 );` as the first line inside the using block, the problem goes away: the test passes both when run in isolation and as part of a larger test fixture.

I originally thought this may have been related to #67 but the fix for that didn't affect my tests when run in parallel by either the Resharper test runner or by NCrunch.

**Comment by tmenier** [comment]
Thanks for testing. I've tried to repro this in many different ways and cannot. Some thoughts:

1. The symptoms sound suspiciously like how this would have behaved prior to 1.1-pre. Try uninstalling Flurl and Flurl.Http, cleaning your solution, re-installing Flurl.Http 1.1-pre, and re-building. Just want to be sure nothing is cached.

2. What version of .NET are you using? If 4.5 or greater (or .NET Core), why are you doing `GetResult()` instead of `await`? Much like the underlying HttpClient, Flurl was designed for async use only and I strongly advise against using it in a blocking manner. If < 4.5, parallel testing is not supported.

**Comment by tmenier** [comment]
FYI, [here](https://github.com/tmenier/Flurl/blob/dev/Test/Flurl.Test.Shared/Http/RealHttpTests.cs#L213-L222) is a rather extreme case of parallel testing that proves real and fake calls can even run in parallel in the same test, which is something I didn't set out to support but I think shows the isolation is solid.

**Comment by tmenier** [comment]
I'll be closing this issue as unable to reproduce with the next full release of Flurl.Http (1.1.1). Have you tried my suggestions?

**Comment by TimWilde** [comment]
Sorry for the delay.

Yep, happy to close this as a peculiarity of our codebase. We've got a work-around, and I'll chase up why we're testing the way we are.

Thanks for taking a look :)
