### ISSUE TITLE
Fix release tag?

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#149]
I mistakenly pushed tag `Flurl.Http.1.1.0` to master too soon. There will be at least one more prerelease, then the final. I could [rename the tag](http://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag), but then others would have to make sure to do a prune. Or, I could cut my losses and go forward with 1.1.1.

What would @kroniak do?

**Comment by kroniak** [comment]
@tmenier in the dev brunch change version to 1.1.1, wait for build, merge to master, and release 1.1.1 tag with nugget package.

**Comment by tmenier** [comment]
Thanks! 1.1.1-pre is out, and I don't think I screwed up the tag this time :)
