### ISSUE TITLE
Allow for multiple queryparam values

### ISSUE THREAD

**Issue by stefandevo** [tmenier/Flurl#15]
I am trying to use Flurl with the disqus api (https://disqus.com/api/docs/).
They have in their api the possibility to define multiple values.

https://disqus.com/api/docs/forums/listPosts/

for example, you can provide "include" param multiple values.
Basically you get &limit=100&include=deleted&include=spam&include=approved

When using the library this is not possible... 

I tried to build the url myself and then call the .GetJsonAsync but I get an error that there are multiple values...

Maybe it needs to be possible to set an override?

**Comment by janissimsons** [comment]
Thank you for implementing this, I have a similar use case.
It would be good if this was documented, at least in method description you could add a different description for this overload.
