### ISSUE TITLE
Can't pass a list nulls

### ISSUE THREAD

**Issue by codymullins** [tmenier/Flurl#151]
Here's the scenario: I have a filter object which accepts a list of `AssignedToUserIds` which is a `List<int?>`. 

If the API is passed a null, it knows to filter for where the `AssignedToUserId == null`. Looks like flurl isn't adding this as a query string parameter. In most cases this is probably preferred, but it would be nice to have a way to accept this in places where it's the desired functionality.

**Comment by tmenier** [comment]
How would you pass null in a query string? The literal string `null`?

**Comment by codymullins** [comment]
Yup, that's how it's currently working in the application. So `https://api.foobar.com/v1/books?authorIds=null` or `https://api.foobar.com/v1/books?authorIds=null&authorIds=12123`

**Comment by tmenier** [comment]
I guess I would argue that it's not common or even a good practice necessarily for an API to interpret the literal string "null" as a null value. Rather than supporting an odd convention in Flurl, I'd suggest just handling it on the calling end. Something like:

````
.SetQueryParam("authorIDs", ids ?? "null")
````

**Comment by codymullins** [comment]
Just curious, why wouldn't it be good practice? Do you know of other ways to query for specifically items with no value? I supposed I could always introduce an enum:

```
public enum AuthorFilter
{
    NotSet = 0,
    Assigned = 1,
    Unassigned = 2
}
```

The only problem is that I have this pattern for querying multiple properties, this would get a little overwhelming. 

Any others ideas of typical conventions for querying specifically where these properties are null?

**Comment by tmenier** [comment]
How about a new route, like: `https://api.foobar.com/v1/books/unassigned`?

**Comment by codymullins** [comment]
Yeah, unfortunately this is being used for a search function that the user can specify multiple types so this probably wouldn't work.

No worries, thanks for the quick replies and appreciate the help.

**Comment by tmenier** [comment]
BTW, the not necessarily a good practice comment was because it's a bit magic-stringy, but I can see how it might be hard to avoid here. Maybe just have a good string parser on the API side that looks for an authorIds value of `all` (the default), `none` (a little more intuitive than `null`), or a comma-delimited list of integers.
