### ISSUE TITLE
WithAuth

### ISSUE THREAD

**Issue by DixonDs** [tmenier/Flurl#158]
Would it be useful to have something like this?
```
public static IFlurlClient WithAuth(this IFlurlClient client, string scheme, string token)
{
    client.HttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme, token);
    return client;
}
```

**Comment by DixonDs** [comment]
I use some third-party service that requires to pass the Authorization header as follows: `"Authorization: Token token=your_api_token"` .

**Comment by tmenier** [comment]
Hmm, that's not exactly a standard approach on their part. Your extension method is a great way to deal with it in your app and a good example of extending Flurl for your specific needs (you could make it even more specific to your app), but I'm going to hold off on adding this to the core. I might change my mind at some point, but until now I haven't had any requests for other auth schemes.

**Comment by tmenier** [comment]
Cleaning up some older issues. Here's an alternative without an extension method:

```c#
.WithHeader("Authorization", $"Token token={myToken}")
```

Not as clean as what you asked for, but it's just not a common enough scenario to add to the core imo.
