### ISSUE TITLE
FlurlMessageHandler bug when raised OperationCanceledException. "Handler did not return a response message."

### ISSUE THREAD

**Issue by thiagolunardi** [tmenier/Flurl#159]
First of all, I am a Flurl fan and evangelist. All Kudus for you, @tmenier!

Implementing at UWP W10M app, it is crashing the entire application everytime the `OperationCanceledException` is raised, as example, when reach the preseted timeout.

After several exausting hours trying to solve the problem, I decided to remove the Flurl as NuGet package and attach the source code directly. That was when I could identify that, everytime that `FlurlMessageHandler` returns a _null_ `HttpResponseMessage`, the app crashed with the following exception message: "**Handler did not return a response message.**"

I believe that this occur because the `DelegatingHandler` is excepting a successful HTTP call, or throwing an `Exception`. But it do not expect to return _null_ `HttpResponseMessage` and no `Exception` at all.

I checked that you are testing that as unit test, and sadly I also do not know how to create this test scenario for make it to fail and prevent that happen again.

Anyhow, the best workaround that I could find is to return a `HttpResponseMessage` when `OperationCanceledException` is raised. As all `HttpResponseMessage` requires a `StatusCode`, the best one that has the closest meaning is `RequestTimeout`. After that, no more crashing and the world become great again.

Just to note, probably the same situation will happen when general `Exception` is raised. But, for now, I will wait it crash to be able to analisy better the reason.

I just forked and added the "fix" for this at my branch. If you judge that is conviente, I may create a pull request for you. Ofc I will **love** to contribute with this awesome project.

**Comment by tmenier** [comment]
Thank you and sorry for the delay. Unfortunately I can't accept your PR for a couple reasons:

1. There is no test demonstrating the problem. Without that it's difficult to understand what exactly the bug is and how your change fixes it. (At the very least sample code in the issue would have been helpful. Saying your app "crashes" gives me little to go on.)

2. You are providing responses with status codes as if they came from the server when in fact there was no response, which is misleading. In my mind, a `null` response more accurately conveys the state of things.

3. The PR [broke a test](https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-dev-109-wdgmpgba). I'm not exactly sure why to be honest, but I did re-run the build to make sure it wasn't a fluke.

I have an alternative suggestion for you that doesn't require any change to the core library. You can create your own `DelegatingHandler` that deals with this scenario and insert it into the pipeline from a custom HttpClient factory (as described at the bottom of [this page](http://tmenier.github.io/Flurl/extensibility/)). The factory would look something like this:
````c#
public class MyCustomHttpClientFactory : DefaultHttpClientFactory
{
    public override HttpClient CreateClient(Url url)
    {
        return new HttpClient(
            new MyNullResponseHandler(
                new FlurlMessageHandler(handler)));
    }
}
````
Let me know if this is a workable solution.

**Comment by thiagolunardi** [comment]
Fair enougth! I will create the evidences and docs for that. 
This project deserves a honest contribution.
Tks for the reply, I will be touch ASAP.
Cheers!

**Comment by thiagolunardi** [comment]
Here, I could reproduce the error.

```
        [Test]
        public async Task can_simulate_timeout_with_exception_handled()
        {
            HttpTest.SimulateTimeout();
            try
            {
                await "http://www.api.com"
                    .ConfigureClient(c => c.OnError = call => call.ExceptionHandled = true)
                    .GetAsync();
                Assert.Fail("Exception was not thrown!");
            }
            catch (FlurlHttpTimeoutException ex)
            {
                Assert.IsInstanceOf<TaskCanceledException>(ex.InnerException);
                StringAssert.Contains("timed out", ex.Message);
            }
        }
```

**Comment by thiagolunardi** [comment]
Just reforcing it.

> I believe that this occur because the DelegatingHandler is expecting a successful HTTP call with a not null HttpResponseMessage, or raising an Exception. But it do not expect to return null HttpResponseMessage and no Exception at all.

I will try to create a proper fix for that.

**Comment by thiagolunardi** [comment]
OK!
A new [Pull Request](https://github.com/tmenier/Flurl/pull/162) is there:

1. With a proper demonstration test reproducing the error: `can_simulate_timeout_with_exception_handled`;
2. Providing proper response, so if there is an exception, and it's marked as handled, it just return *null* HttpResponseMessage;
3. All tests are green and happy!

**Comment by tmenier** [comment]
Ah, I get it now. Good test. I did some digging and it seems the real "culprit" (in my opinion) is HttpClient itself.  You're right, it doesn't like null responses. I [questioned the CoreFX team](https://github.com/dotnet/corefx/issues/15191) on this, we'll see what they come back with for an explanation.

As far as the fix, this is much better. I might make some very minor tweaks (this really cuts to the core of the library), but by and large I like your approach here, and the test is perfect. I'll try to get this done and released in the coming days.

**Comment by thiagolunardi** [comment]
Nice! I really glad that I could contribute a bit with this awesome project. Looking forward for next updates. Thanks for your replies, cheers!

**Comment by tmenier** [comment]
Pulled your PR and did a little refactoring. Mainly:

1. To be a good citizen, made sure FlurlMessageHandler always either returns a legit non-null response or throws. FlurlClient deals with the ExceptionHandled setting.
2. What you did with `ReceiveJson` was good but needed to fix up a the other `Receive*` methods to deal with null.

But the essence of your fix is there and your test as-is. Thanks again!

**Comment by tmenier** [comment]
Fix is released: https://www.nuget.org/packages/Flurl.Http/1.1.2
