### ISSUE TITLE
Add first-class support for query parameters without a value

### ISSUE THREAD

**Issue by lvermeulen** [tmenier/Flurl#164]
Flurl can parse query params without a value, but doesn't have internal support for this, as evidenced by the fact that it will change the URL that it parses (it adds an = sign):

```C#
[Test]
public void can_add_query_param_without_value()
{
    string urlString = "http://example.com?123456";
    var url = new Url(urlString);
    Assert.AreEqual("http://example.com", url.Path);
    Assert.AreEqual(1, url.QueryParams.Count);
    Assert.AreEqual(true, url.QueryParams["123456"]);
    Assert.AreEqual(urlString, url.ToString());
}
```

**Comment by tmenier** [comment]
I like the idea of supporting this. I'll even go so far as to say that if you do `url = new Url(x)`, don't manipulate it, and `url.ToString()` does not equal `x`, that's a bug.

I disagree with one aspect of your implementation. You're basically interpreting a query string like your example as a name without a value. I think I'd argue for it being a value without a name. (There's no actual standard for what a "query parameter" is so we can be opinionated here.)

Flurl already does this:

`SetQueryParam("x", "")` => `?x=`
`SetQueryParam("x", null)` => (exclude the parameter altogether)

So I feel like we've already settled on what a "name without a value" is, even though what you've done doesn't actually break any tests. I do find it confusing that `QueryParams["123456"]` evaluates to `true` though, especially considering `SetQueryParam("123456", true)` will give you `?123456=true`.

One option is to simply say anything that doesn't conform to `name=value` isn't a query parameter at all and is excluded from the QueryParams collection. But I think a better way to go is to say it's a value with a `null` name. That should even work fine if there are multiple no-name values separated by `&`. This behavior already exists:

`?x=123&x=abc` => `QueryParams["x"]` is `{ "123", "abc" }`

Similarly, this would work:

`?123&abc` => `QueryParams[null]` is `{ "123", "abc" }`

Thoughts?

**Comment by lvermeulen** [comment]
>  I think I'd argue for it being a value without a name.

Never looked at it in this way. Yeah, sure.

As far as the true value goes, I never gave that much thought so you're right to call that out. That's also why I pointed it out in the PR description. Basically I would like a .SetQueryParam extension method that accepts a value without a name.

**Comment by tmenier** [comment]
This turned into a larger effort than I anticipated but I wanted to get it right. A couple points:

First, I flip-flopped and did it the way you envisioned it originally, i.e. name without value. Most web frameworks tend to interpret it that way ([ASP.NET is a notable exception](http://stackoverflow.com/a/7519540/62600), ironically.)

Second, the most complicated aspect of this was that in terms of building a query string, I've already settled on `SetQueryParam("foo", null)` meaning to exclude the parameter entirely, and now we're saying a null value means something different in some scenarios. I still like the excluding behavior, especially when passing objects, and of course maintaining that means no breaking change. So here's what I settled on:

1. `SetQueryParam(string)`, `SetQueryParam(IEnumerable<string>)`, and `SetQueryParam(params string[])` are all new, and result in name without value in the query.

2. Other overloads of `SetQueryParam` and `SetQueryParams` behave the same as they did by default but a new optional parameter of type `NullValueHandling`, which has these possible values:

`NameOnly` - sets name without value
`Remove` - excludes param, removing if it already exists (default)
`Ignore` - excludes param, ignoring if it already exists

Let me know your thoughts. I'll be doing a prerelease soon if you want to try it out.

**Comment by tmenier** [comment]
https://www.nuget.org/packages/Flurl/2.3.0-pre

**Comment by tmenier** [comment]
Flurl 2.3 full release pushed

**Comment by lvermeulen** [comment]
Sorry, I was out of the country for a bit. Just tried it out: works like a charm and it's exactly what I was looking for. Thanks!
