### ISSUE TITLE
Stop overriding my url

### ISSUE THREAD

**Issue by imperat0r** [tmenier/Flurl#173]
How to stop overriding my url;
I want url that looks like http://www.something.com?adaten%5bagentur_nr%5d=SOMETHING1&v=SOMEZTHING2

I use SetQueryParam method.
But I get this url : http://www.something.com?adaten=[agentur_nr]=SOMETHING1&amp;v=SOMETHING2

1.)Why you change key of my query parametar (I want it encoded but end up decode)?
2.)Why is there &amp; instead of & metween query parameters. My request does not work because of that?

**Comment by thiagolunardi** [comment]
It's just [URL Encoding](https://www.w3schools.com/tags/ref_urlencode.asp).

**Comment by imperat0r** [comment]
Don't understand comment. Request is sent to different Url than it was defined using flurl

**Comment by thiagolunardi** [comment]
URL Enconding is required, and it's a good practice when building URL.

> URLs can only be sent over the Internet using the ASCII character-set.
> 
> Since URLs often contain characters outside the ASCII set, the URL has to be converted into a valid ASCII format.
> 
> URL encoding replaces unsafe ASCII characters with a "%" followed by two hexadecimal digits.
> URLs cannot contain spaces. URL encoding normally replaces a space with a plus (+) sign or with %20.

And Fluent URL is doing that for you in advance. So you don't need to be concerned. Furthermore, it's the same URL, just properly encoded.

**Comment by imperat0r** [comment]
Ok, but my url does not work because of that. I will use plain HttpClient and make it work.

**Comment by thiagolunardi** [comment]
I got it, it's because your're trying to create the URL with already encoded values.

```
var url = "http://www,something.com"
    .SetQueryParams("adaten[agentur_nr]", "SOMETHING1")
    .SetQueryParams("v", "SOMETHING2");
```

**Comment by imperat0r** [comment]
Thanks

**Comment by tmenier** [comment]
`SetQueryParam` also has an optional `isEncoded` argument that, when set to true, indicates that the value is already encoded, so Flurl should leave it alone:

`url.SetQueryParam("x", "don%27t%20touch%20me", true);`

**Comment by timothyeckert** [comment]
Coming back to this years later and reading how many people "jumped" on this person for no wanting the url to be modified by default is sad, OP might not have been able to word his question right but the blind assumption that url encoding is by default required isn't good either.
