### ISSUE TITLE
Customize datetime-format for posting data

### ISSUE THREAD

**Issue by TheMiller2015** [tmenier/Flurl#174]
Hello,

when I post a DateTime-Field with "PostJsonAsync()", the Dateformat is sth like "2017-01-01T13:22:00Z". But I am posting to a php framework which stores the data in a mysql database. MySQL wants the dateformat without the cases "T" and "Z" like this: "yyyy-mm-dd hh:ii:ss". 

Is there a way (and if so, what way), to customize this dateformat to be a mysql-friendly format?

Thanks in advance.

**Comment by thiagolunardi** [comment]
Fluent URL is using Newtonsoft.Json to serialize object. You certainly can configure it using global settings and change that. But, IMHO, recommend you not do that, at least not for that reason. Here is why:

JavaScript - JSON stands for JavaScript Object Notation - specify how dates should be represented, and it uses ISO 8601.

- It's human readable but also succinct
- It sorts correctly
- It includes fractional seconds, which can help re-establish chronology
- It conforms to ISO 8601
- ISO 8601 has been well-established internationally for more than a decade
- ISO 8601 is endorsed by W3C, RFC3339, and XKCD

You can use the `DATE_FORMAT(date, '%Y-%m-%dT%TZ')` at MySQL to proper format this.

Also, you can read this discussion about [MySQL Inserting DateTime using ISO 8601](http://stackoverflow.com/questions/11053941/mysql-insert-to-datetime-is-it-safe-to-use-iso8601-format).

Furthermore, changing that as default from your API, may turn your responses not compatible with other consumers.

**Comment by tmenier** [comment]
I concur with @thiagolunardi that ideally you should you should handle the date formatting on the server side. (You guys know more about MySQL than I do, but I trust that is sound advice.)

That said, if you must you can tap into Json.NET's [JsonSerializerSettings](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonSerializerSettings.htm) like so:

```
var settings = new JsonSerializerSettings { /* set defaults here */ };

FlurlHttp.Configure(c => {
    c.JsonSerializer = new Flurl.Http.Configuration.NewtonsoftJsonSerializer(settings);
});
```

You would do this once at app startup.

**Comment by TheMiller2015** [comment]
Thanks for your answers, helped me a lot!

I came up with modifying the entity on the php-side right before saving it to the datebase. In that way one can be sure, that always the right datetime-syntax is being stored, no matter which client posted data in what format. So nobody has to care.

Thanks!
