### ISSUE TITLE
FlurlClient.Clone() should return IFlurlClient, not FlurlClient

### ISSUE THREAD

**Issue by markdakers** [tmenier/Flurl#182]
The current signature makes it impossible to provide a custom implementation of IFlurlClient effectively (unless this is the intentionion).

**Comment by tmenier** [comment]
Confirmed. Fix is pushed and will go out in the next release.

**Comment by gitfool** [comment]
@tmenier It would be nice to have a `DeepClone` too.

A common scenario, for me at least, is to always inject a shared IFlurlClient (to control HttpClient instances and their reuse). It's not common, but a few instances require customization to settings, which must be carefully isolated to that instance only, so I have to do the following dance:
```
public class MyServiceProxy
{
    public MyServiceProxy(IFlurlClient client)
    {
        Client = client.Clone(); // clone client and settings to avoid sharing changes
        Client.Settings = Client.Settings.Clone();
        Client.Settings.BeforeCallAsync = BeforeCallAsync;
    }

    private Task BeforeCallAsync(HttpCall call)
    {
        // ...
    }

    public IFlurlClient Client { get; }
}
```
Thoughts?

**Comment by tmenier** [comment]
Could you create a new issue for that? For tracking purposes, as it's a completely different topic.

**Comment by gitfool** [comment]
Sure.

**Comment by tmenier** [comment]
Done and released to NuGet
