### ISSUE TITLE
FlurlMessageHandler should have a default ctor

### ISSUE THREAD

**Issue by gitfool** [tmenier/Flurl#186]
I can't use [HttpClientFactory.Create](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpClientFactory.cs#L41) to create a custom delegating handler pipeline that includes [FlurlMessageHandler](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http.Shared/Configuration/FlurlMessageHandler.cs#L12) because it doesn't have a default ctor.

For example, I'd like to be able to do the something like the following:
```c#
public class LoggerHttpClientFactory : DefaultHttpClientFactory
{
    public LoggerHttpClientFactory(LoggerDelegatingHandler loggerHandler)
    {
        _loggerHandler = loggerHandler;
    }

    public override HttpClient CreateClient(Url url, HttpMessageHandler handler)
    {
        return HttpClientFactory.Create(handler, new FlurlMessageHandler(), _loggerHandler);
    }

    private readonly LoggerDelegatingHandler _loggerHandler;
}
```
This is a simple example, but imagine a more complicated pipeline with more delegating handlers. It's very convenient to use HttpClientFactory to construct such a pipeline.

I can't use `HttpClientFactory.Create(handler, new FlurlMessageHandler(_loggerHandler))`, or similar, as HttpClientFactory [throws an exception](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpClientFactory.cs#L80) if any inner handler is already set.

FlurlMessageHandler should have a default ctor ~~and I'd argue it probably only needs a default ctor - [DefaultHttpClientFactory.CreateClient](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http.Shared/Configuration/DefaultHttpClientFactory.cs#L18) could be changed to use the same pattern, or it could use property initialization to set the inner handler~~. Edit: Having both ctors is best.

**Comment by tmenier** [comment]
Agree with fix. I'd like to merge it into dev instead of master, but since it's so small I'll just add the change manually. Will go out with next release.

**Comment by gitfool** [comment]
Cool. I'll switch to dev for future PRs.

**Comment by tmenier** [comment]
Done and released to NuGet.
