### ISSUE TITLE
Add DeepClone to FlurlClient

### ISSUE THREAD

**Issue by gitfool** [tmenier/Flurl#189]
A common scenario, for me at least, is to always inject a shared IFlurlClient (to control HttpClient instances and their reuse). It's not common, but a few instances require customization to settings, which must be carefully isolated to that instance only, so I have to do the following dance:
```c#
public class MyServiceProxy
{
    public MyServiceProxy(IFlurlClient client)
    {
        Client = client.Clone(); // clone client and settings to avoid sharing changes
        Client.Settings = Client.Settings.Clone();
        Client.Settings.BeforeCallAsync = BeforeCallAsync;
    }

    private Task BeforeCallAsync(HttpCall call)
    {
        // ...
    }

    public IFlurlClient Client { get; }
}
```
Thoughts?

**Comment by gitfool** [comment]
Thinking about this some more; the problem with DeepClone is it depends on how deep you want the copy to be, but the common case would most likely be just to clone Settings for isolated configuration.

Also, given Clone is currently only implemented on FlurlClient and FlurlHttpSettings, and they're not implementing ICloneable.Clone, the best approach might be to add a default parameter to FlurlClient.Clone that either specifies whether to also clone Settings:

```c#
/// <summary>
/// Creates a copy of this FlurlClient with a shared instance of HttpClient and HttpMessageHandler
/// </summary>
/// <param name="cloneSettings">Indicates whether to also copy settings for isolated configuration. Optional.</param>
public IFlurlClient Clone(bool cloneSettings = false) {
    return new FlurlClient {
        _httpClient = _httpClient,
        _httpMessageHandler = _httpMessageHandler,
        _parent = this,
        Settings = cloneSettings ? Settings.Clone() : Settings,
        Url = Url,
        Cookies = Cookies
    };
}
```
... or, similarly to the ctor overloads, and my preference, specifies whether to override copied settings inline, which internally ensures the override is isolated:
```c#
/// <summary>
/// Creates a copy of this FlurlClient with a shared instance of HttpClient and HttpMessageHandler
/// </summary>
/// <param name="configure">Action allowing you to override copied settings inline.</param>
public IFlurlClient Clone(Action<FlurlHttpSettings> configure = null)
{
    var settings = Settings;
    if (configure != null) {
        settings = Settings.Clone();
        configure(settings);
    }
    return new FlurlClient {
        _httpClient = _httpClient,
        _httpMessageHandler = _httpMessageHandler,
        _parent = this,
        Settings = settings,
        Url = Url,
        Cookies = Cookies
    };
}
```
If you like this approach then I'm happy to submit a PR. 😉

**Comment by tmenier** [comment]
To be honest, not cloning the settings on FlurlClient.Clone may have just been an oversight. I'll do some thinking on whether just changing it is likely to cause unexpected behavior in any realistic scenarios.

Also note that Clone's main reason for existing is to support FlurlClient.WithUrl and Url.WithClient. I don't expect most people would have any need to call it directly, but I did make it public for reasons I don't exactly recall so I guess I should expect it might get used. :)

**Comment by gitfool** [comment]
I see. In that case I'd try to avoid generating garbage and that's easy and predictable with copy-on-write semantics. Interestingly, that's what you're already doing for FlurlClient.WithUrl and Url.WithClient but not consistently with everything else.

The best way forward would be a breaking change to remove Clone from the public interface and leave it for internal use only, or removed if an internal ctor suffices. Then all other ClientConfigExtensions should also implement copy-on-write semantics. My original scenario would be handled with `Client = client.ConfigureClient(settings => { })`. This should also cover all modifications to HttpClient like WithTimeout, WithHeader(s) etc; ultimately those should go through `client.ConfigureHttpClient` that does a copy-on-write on the underlying HttpClient.

This would elegantly allow maximum sharing of clients, both FlurlClient and HttpClient, while removing the pitfalls when naively configuring either without isolation. Sharing of modifications is still available by choosing where to configure and when to pass the references around.

Also, while making a breaking change I'd rename WithHeader(s) to WithDefaultHeader(s). I'd like to consider adding support for per request headers, which is what I expected WithHeader(s) to represent in the first place. They're almost redundant with the above changes, but not quite, although the changes to expose them might not work so well with the current Flurl style.

**Comment by tmenier** [comment]
I agree that copy-on-write should be followed more consistently. I have some ideas of my own that will also solve the headers issue and improve HttpClient reuse in scenarios where FlurlClient isn't managed explicitly.  I'm pretty sure it'll involve breaking changes, so I'd like to hold off on until Flurl.Http 2.0. That could be coming sooner than later though; I have someone working on compatibility-related changes (VS 2017 support, possibly ditching PCL profiles, etc.) that could also be breaking, so the timing is good.

In the very short term, I'm willing to do the simple change that clones Settings in FlurlClient.Clone. Technically even that's a breaking change, but I find it highly unlikely that anyone would be relying on the current behavior specifically. All tests are passing as-is with that change. I'm leaning toward going forward with it in the next maintenance release (hopefully today), let me know if you have thoughts.

**Comment by tmenier** [comment]
@gitfool Sorry, disregard that last comment. I definitely do NOT want to clone Settings by default. I just needed to think about why Clone exists in the first place and I had sort of an a-ha moment. :) I'll explain in another comment, going to delete these so they don't cause confusion.

**Comment by tmenier** [comment]
To add more clarity to why `FlurlClient.Clone` exists (I had to remind myself actually), it is so that a **FlurlClient can be reused with multiple URLs**. That's it. You could say I painted myself into a bit of a corner with the `FlurlClient.Url` property, and creating new FlurlClients _with as much shared state as possible_ (including HttpClient and Settings) is really an implementation detail to allow WithUrl and WithClient to _behave_ as though the FlurlClient is actually shared. 
So changes to Settings or HttpClient should propagate to all cloned instances. (I intend to break that coupling in Flurl.Http 2.0, which should eliminate that need to do this at all.)

I'll keep this open but I'm undecided on implementing a DeepClone or an enhanced Clone method signature. If your goal is to use HttpClient as a singleton without sharing FlurlClient settings, you might want to look into [using a custom HttpClientFactory](http://tmenier.github.io/Flurl/extensibility/) instead. I plan on improving how HttpClient gets reused and fixing the header issue in 2.0.

**Comment by gitfool** [comment]
Thanks for the background. I think what I've proposed would work if you continue to share as much state as possible by default. Breaking that coupling would work too, but I'd hope this approach wouldn't force me to repeat myself where I want to share state like settings and default headers at global or inner scopes.

I'm already using HttpClientFactory wired up to a FlurlClient _per test_. In other contexts I'm using a singleton where possible to follow current recommended best practices with HttpClient. (This obviously requires avoiding default headers.) Managing Flurl settings is a separate concern that then comes into the picture.

I look forward to seeing your ideas for v2. The only problem is what I should do in the meantime with v1. Let me know how I can help. 

PS. I love Flurl and your efforts are much appreciated!

**Comment by tmenier** [comment]
Thanks. Couldn't you achieve the same (avoid repeating yourself) by writing it as an extension method of FlurlClient in your app? The reason I'm resisting adding this to the core is that it just doesn't strike me as a very common scenario.

**Comment by tmenier** [comment]
^^^ Specifically for solving the Settings problem anyway. I'm still open to solving the headers issue in 1.x, but let's discuss that in #157.

**Comment by tmenier** [comment]
This has been a good conversation and interestingly has brought to light some of the things I'd like to change in Flurl.Http 2.0. Bottom line is there's going to be better ways to reuse HttpClient; cloning was a means to an end and I'd really rather get rid of it than enhance it. I'll post some issues soon laying out my plans so far, hope to hear your feedback.
