### ISSUE TITLE
InvalidOperationException when reusing HttpClient

### ISSUE THREAD

**Issue by xxMUROxx** [tmenier/Flurl#198]
Following code throws a 

> InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.

```
internal class SingleInstanceC : DefaultHttpClientFactory
{
    private static HttpClient single;

    public override HttpClient CreateClient(Url url, HttpMessageHandler handler)
    {
        if (single == null)
        {
            single = base.CreateClient(url, handler);
        }
        return single;
    }
}

FlurlHttp.Configure(i =>
                                {
                                    i.AutoDispose = true;
                                    i.HttpClientFactory = new SingleInstanceC();
                                });


"somestring".AppendPathSegments("somestring").GetAsync().Wait();
"somestring".AppendPathSegments("somestring").GetAsync().Wait();
```

**Comment by gitfool** [comment]
I've seen the same `InvalidOperationException`. IIRC it comes from [FlurlClient.cs:165](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlClient.cs#L165). I worked around it by reusing the FlurlClient (and the underlying HttpClient) via [WithUrl](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/ClientConfigExtensions.cs#L24). i.e. the above becomes:

```c#
var fc = new FlurlClient();
await fc.WithUrl("somestring").AppendPathSegments("somestring").GetAsync();
await fc.WithUrl("somestring").AppendPathSegments("somestring").GetAsync();
```

**Comment by gitfool** [comment]
You've probably seen `ObjectDisposedException` too, since configuring `AutoDispose = true` will cause Flurl to dispose your singleton HttpClient which you then try to reuse in your custom HttpClientFactory. That combination doesn't make sense.

It looks like you've tried playing with the AutoDispose setting and seen both exceptions depending on its value.

**Comment by xxMUROxx** [comment]
@gitfool Ops, sorry. The `AutoDispose = true` was introduced in the issue by mistake. I forgot to remove it before posting it here.

I know that with `WithUrl` the `HttpClient` is reused. Maybe I understand something wrong. I see an issue when using any `WithXXX` method e.g. `WithHeaders`. Why is there a call to autodispose: `FlurlClient(url, true)` Shouldn't the `autodispose` property of `FlurlClient` be set to false if I set `Autoconfigure` to false during  `FlurlHttp.Configure`?

**Comment by xxMUROxx** [comment]
Ok, now the question: It is not directly related to this issue but if this clarifies my understanding, than this might be solved for mee too. I, for my understanding, expect the following tests to pass:
 
    [Test]
    public void Test1()
    {
        var client = new FlurlClient("http://test.local/");

        var client1 = client.Url.AppendPathSegments("test1");
        var client2 = client.Url.AppendPathSegments("test2");

        Assert.That(client1.ToString(), Is.EqualTo("http://test.local/test1"));
        Assert.That(client2.ToString(), Is.EqualTo("http://test.local/test2"));
    }

    [Test]
    public void Test2()
    {
        var client = new FlurlClient("http://test.local/");

        var client1 = client.Url.ResetToRoot().AppendPathSegments("test1");
        var client2 = client.Url.ResetToRoot().AppendPathSegments("test2");

        Assert.That(client1.ToString(), Is.EqualTo("http://test.local/test1"));
        Assert.That(client2.ToString(), Is.EqualTo("http://test.local/test2"));
    }

As I see in the code each method on `Url` returns `this`. For that the instance is shared and thus modifierd with AppendPathSegment.  Is there any possibility to deep-copy the `Url` and get a new `Url` instance?

**Comment by tmenier** [comment]
Currently the best way to use HttpClient as a singleton with Flurl:

- Manage a singleton instance of `FlurlClient` (such as with your favorite IoC container).
- Make calls by fluently building the URL part first and use `.WithClient` to attach that singleton.

See [here](http://tmenier.github.io/Flurl/client-lifetime/).

**Comment by tmenier** [comment]
I'm going to close this as a known issue and suggest using the work-around. However, better reuse of HttpClient _by default_ is going to be a huge priority in Flurl.Http 2.0, which I plan to start working on very soon.
