### ISSUE TITLE
Support operator /

### ISSUE THREAD

**Issue by xxMUROxx** [tmenier/Flurl#201]
It would be a cool feature if `Url` would support overloading the `/` operator:

    public static Url operator /(Url url, object path)
    {
        return url.AppendPathSegment(path);
    }

This would allow to write following code:

    Url baseUrl = "http://someurl"
    var otherUrl = baseUrl / "segment1" / "segment2" ....

In my opinion this would increase readability dramatically.
@gitfool what do you think?

**Comment by gitfool** [comment]
I'm wary of operator overloading but that does look appealing and makes sense given the domain. 😉 

What I think doesn't matter though; I'd ask @tmenier...

**Comment by tmenier** [comment]
I see what you did there, cute. :)

One hesitation I have is that something like baseUrl here will usually be a string and not a Url object. (Url is mutable, so once you start fluently building from baseUrl, you're actually changing it.) So in that case if you want to do `baseUrl / "segment1"`, you'd need to overload `/` for `string`, which seems a little weirder.

Not sure if that's a show-stopper in your mind. Maybe let it exist in your app(s) for a while and report back whether you liked it enough to stick with it. :)

**Comment by gitfool** [comment]
@tmenier That's a good point about mutability. `Flurl.Url` is simple enough with only 3 field backed properties, especially compared to `System.Uri`, that there's a good case for it to be an immutable struct; a breaking change that could go into v2.

**Comment by xxMUROxx** [comment]
@gitfool I agree that is a big breaking change. But to be honest, First, I assumed that `Flurl.Url` is immutable.

@tmenier It's not my position to decide whether or not mutability/immutability is a good choice. In my opinion this would make the use of this library much easier. I have an example of my initial situation that resulted in a problem.

> I have a helper class that manages all the `URI` and the base `URI`s are stored in a `readonly field` (e.g. uris that do not have query parameters). When I first tried this library I thought that I have to change URI to `Flurl.Url`. At execution time I added query paremeters and and exacly that was the trap. The `Flurl.Url` stored in the readonly field is now modified.

> Workaround: Create all the base-uri any time a web request is done.

If `Flurl.Url` would be immutable then following code would work:

    Url baseUrl = "http://somehost";
    Url otherUrl = baseUrl.AppendPathSegment("sub");

    var other = otherUrl.AppendPathSegment("sub1").SetQueryParam("filterfor","blabla");
    var other = otherUrl.AppendPathSegment("sub2").SetQueryParam("filterfor","blabla");

currently I have to construct it every time:

``` 
"http://somehost".AppendPathSegments("sub", "sub1").SetQueryParam("filterfor","blabla");
"http://somehost".AppendPathSegments("sub", "sub2").SetQueryParam("filterfor","blabla");
```

**Comment by tmenier** [comment]
`Url` is a builder, and I do worry that changing the nature of it that significantly would break a lot of people's code. I personally use it like this from time to time:
```C#
var url = baseUrl.AddStuff();
if (something)
    url.AddSomething();
else
    url.AddSomethingElse();
// etc.
```
If it's immutable that won't work; I'd have to update a lot of code to prepend `url = ` in a lot of places, and worse still, the compiler wouldn't catch it.

I encourage people building off "base" URLs to just start with a string:
```c#
string baseUrl = "http://somehost";
string otherUrl = $"{baseUrl}/sub";
```
If you really want to use the builder methods to build a base URL, you could do a property so that you get a new `Url` every time:
```c#
Url otherUrl => baseUrl.AppendPathSegment("sub");
```
Or even convert it to a string implicitly:
```c#
string otherUrl = baseUrl.AppendPathSegment("sub");
```
You may not like those options as much as an immutable `Url`, but I'm just demonstrating that you do have plenty of options that don't involve repeating yourself.

**Comment by tmenier** [comment]
Thanks for the suggestion but I've decided not to add this to core. It's an interesting idea, but it's another way to do something already supported and there are a few concerns with it as discussed.
