### ISSUE TITLE
Flurl.Http 2.0 Prerelease

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#205]
I'll use this issue to announce the many big changes coming in Flurl.Http 2.0 and hopefully spark some good discussion and feedback. I'll make changes/additions to this as things progress, so please subscribe to this issue or follow [@FlurHttp](https://twitter.com/FlurlHttp) on Twitter to stay on top of the latest updates.

First a little background. When Flurl.Http was first conceived, `HttpClient` was relatively new. There wasn't much in the way of documentation or best practices. (You might know where this is going already.) `HttpClient` implements `IDisposable`, and like many I believed this implied that it should be short lived and disposed as soon as possible. So most of the basic use cases like `"http://myapi.com".GetJsonAsync()` do just that under the hood. But new information started to emerge suggesting this is not ideal. Creating and opening new connections is relatively expensive, and when you rapidly dispose and recreate `HttpClient`, you're doing that a lot, and taking a performance hit (or [worse](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)). So in a later release I introduced an [alternative usage pattern](http://tmenier.github.io/Flurl/client-lifetime/) that allows you to reuse `HttpClient` instances by managing `FlurlClient` instances explicitly and "attaching" them (fluently of course) to a `Url`. This works and is IoC-friendly, but maintaining backward compatibility was a struggle, largely due to that pesky `FlurlClient.Url` property that effectively couples a client with a single URL. To work around this, I had to resort to shallow cloning, and if you didn't follow the pattern just right you could encounter some [unexpected](https://github.com/tmenier/Flurl/issues/178) [behavior](https://github.com/tmenier/Flurl/issues/198). There are other shortcomings, like [lack of support for per-request headers](https://github.com/tmenier/Flurl/issues/157), all due to the fundamental one-client-per-request design.

I've concluded that solving this correctly means breaking the coupling between client and URL, and making aggressive reuse of `HttpClient` the _default_ behavior. These are among the biggest changes coming in Flurl.Http 2.0. So without further ado, here's a summary of the _tentative_ changes:

- [x] When not managing `FlurlClient` instances explicitly, the default behavior will be to cache and reuse one `FlurlClient` **per host being called**. I considered literally one global singleton, but one per host made a couple things (mainly cookie management) a little easier. (Besides, if you call 1000 different hosts, you're opening up 1000 sockets whether you use 1 `HttpClient` or 1000.) I am open to differing opinions on this decision.

- [x] Decoupling `FlurlClient` and `Url` means something else needs to marry them together before a call is made. A new **FlurlRequest** object is being introduced to do just that. Most of `IFlurlClient`'s methods will move to `IFlurlRequest`, including all methods that make the actual call (`GetJsonAsync`, etc), but this won't break most [typical use cases](http://tmenier.github.io/Flurl/fluent-http/) because fluent methods off `string` and `Url` will now return this new object.

- [x] `Url.WithClient` ~~and `FlurlClient.WithUrl`~~ will return `FlurlRequest` as well. [UPDATE: `WithUrl` is succeeded by `Request` method as detailed in #211.]

- [x] Headers, Settings, and Cookies will be setable on both `FlurlClient` and `FlurlRequest`, the former acting as defaults for all requests on that client and the latter are request-specific.

- [x] `FlurlClient.Url`, `FlurlClient.Clone` and all things related to auto-dispose behavior are being dropped.

- [x] I'm investigating the possibility of making `WithTimeout` work per request. ~~Unfortunately that one's a little trickier as the concept simply doesn't existing in the `HttpClient` APIs, but after glancing at the source code I believe it's doable.~~ Doable, and done!

- [x] Long-lived `HttpClient`s introduce [a new potential problem](https://github.com/dotnet/corefx/issues/11224) related to DNS. ~~I haven't made a decision on how best to address it but I'll likely open a new issue for that discussion. (I'll link to it here when I do.)~~ I decided to mimic what the popular `ServicePointManager`/`ConnectionLeaseTimeout` solution does, in a way that works across all platforms. (#222)

I've made the first couple commits toward these goals but more work remains. Feedback is greatly appreciated.

**Comment by tmenier** [comment]
Another important point I missed:

- `IHttpClientFactory` will be replaced by `IFlurlClientFactory`. `CreateHttpClient` and `CreateMessageHandler` will still exist, but a `GetFlurlClient(Url)` method will be added. This (and not the other 2 methods) should be used to define client lifetime/scope. So if I go with one-client-per-host and you don't like it, this is where you can change it to whatever you like.

**Comment by gitfool** [comment]
Excellent summary that captures all the pitfalls to be navigated. The best way to know if these changes feel right is by trying to use the library, so let me know when you've got the critical mass in place for me to play with. 😉

**Comment by tmenier** [comment]
I lied when I said everything in the prerelease will be in this issue (but I'll at least link them from here):

#211

**Comment by tmenier** [comment]
Some details about Settings in 2.0. A Settings property (not new for the most part) will exist uniformly at 4 levels, with a strict order of precedence:

`IFlurlRequest` > `IFlurlClient` > `HttpTest` > `FlurlHttp` (global)

These are the specific properties that will exist at each level:

Property                | FlurlHttp (global) | HttpTest | IFlurlClient | IFlurlRequest
------------------------|:------------------:|:--------:|:------------:|:-------------:
Timeout                 |         x          |    x     |      x       |       x         
AllowedHttpStatusRange  |         x          |    x     |      x       |       x         
CookiesEnabled          |         x          |    x     |      x       |       x         
JsonSerializer          |         x          |    x     |      x       |       x         
UrlEncodedSerializer    |         x          |    x     |      x       |       x         
BeforeCall              |         x          |    x     |      x       |       x         
BeforeCallAsync         |         x          |    x     |      x       |       x         
AfterCall               |         x          |    x     |      x       |       x         
AfterCallAsync          |         x          |    x     |      x       |       x         
OnError                 |         x          |    x     |      x       |       x         
OnErrorAsync            |         x          |    x     |      x       |       x         
HttpClientFactory       |         x          |    x     |      x       |                 
FlurlClientFactory      |         x          |    x     |              |                 

One subtlety to note is that the hierarchy is never "flattened"; at any level, Settings continues to reflect changes to the defaults from a level up until they are _explicitly_ set at the current level. For example, if you create a `FlurlRequest`, change some settings from their global defaults, then attach a `FlurlClient` and change some settings at the client level, the request will reflect those client-level settings, but only the ones that were not explicitly set at the request level.

**Comment by tmenier** [comment]
_BREAKING CHANGE_ related to Settings: The `ConfigureClient` extension method defined on several objects is going away. You can still change settings fluently with a lambda, just note the method names:

````c#
FlurlHttp.Configure(settings => ...)
HttpTest.Configure(settings => ...)
IFlurlClient.Configure(settings => ...)
IFlurlRequest.ConfigureRequest(settings => ...)
Url.ConfigureRequest(settings => ...)
string.ConfigureRequest(settings => ...)
````

One naming oddity: `IFlurlRequest.Configure` might seem preferable to `IFlurlRequest.ConfigureRequest`, until you look at certain fluent expressions, especially in light of #211 where `IFlurlRequest` will get URL builder methods:

 ````c#
"http://api.com"
    .AppendPathSegment("path") // returns Url
    .ConfigureRequest(...)

"http://api.com"
    .WithHeader(x, y)
    .AppendPathSegment("path") // returns IFlurlRequest
    .Configure(...)
````

I think the configure method name should be consistent in those 2 scenarios, so I'm going with `IFlurlRequest.ConfigureRequest`. I'm open to differing opinions on that.

**Comment by gitfool** [comment]
I had a quick look at the changes. LGTM.

If I was to nitpick, I'd prefer consistent predictable naming, so `ConfigureSettings` could be applied to all contexts above, for example.

Also, one potential issue is that [FlurlHttp.GlobalSettings](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlHttp.cs#L20-L34) is publicly accessible when it's also protected by a lock. It could be made internal only and marked as visible to the unit tests; then the only way to configure the global settings would be via Configure[Settings]. 😉

**Comment by tmenier** [comment]
@gitfool Now is the time to nitpick, once 2.0 goes to stable release it's too late. :)

I actually considered `WithSettings` for the chainable versions (all but global), but what I didn't like about that (and `ConfigureSettings`) is that it might seem odd to discover that method as a string extension. At least `ConfigureRequest` tips the hat a little that it's coming from the Flurl world. No option seems perfect here but I think I'm going to go with how I have it for now.

Regarding global settings:
1. If they're internal, there's no easy way to read them.
2. The documented correct way to do global config is once at startup, so I don't know that additional protection is really important. If for some reason you need to change 1 setting, public access makes it easy. Last-in wins either way; the lock just guarantees that the last _batch_ wins when you use `Configure`.

**Comment by tmenier** [comment]
Flurl.Http 2.0 prerelease 2 is now [published](https://www.nuget.org/packages/Flurl.Http/2.0.0-pre2). Additions:

1. New shortcut on the global config object to configure settings for a specific client:
`FlurlHttp.ConfigureClient(url, settings => ...);`
This is for cases where you're not managing `FlurlClients` explicitly, hence the client you're configuring will be the the one reused in all calls to the same **host** (by default), not just those to that _specific_ URL. Let me know if that seems counter-intuitive, but I think the 99% case is where you have some `BASE_URL` constant you're using in both the call above and all fluent HTTP calls, and it will work as expected.

2. `HttpCall` and the `BeforeCall` event are getting some tweaks as described in #213.

**Comment by tmenier** [comment]
Flurl.Http 2.0 prerelease 3 is now [published](https://www.nuget.org/packages/Flurl.Http/2.0.0-pre3). Additions:

1. `ConnectionLeaseTimeout` setting to deal with potential DNS issue (#222)
2. `DefaultFlurlClientFactory` renamed to `PerHostFlurlClientFactory` (breaking change from pre2) and `PerBaseUrlClientFactory` added (#226)
3. `WithHeaders(object)` converts underscores in property names to hyphens in header names (#44)
4. Much more robust `FlurlHttpException.Message` (#217)
5. Testing enhancement: `WithHeader` / `WithoutHeader` assertions (#223)

**Comment by tmenier** [comment]
One more [prerelease](https://www.nuget.org/packages/Flurl.Http/2.0.0-pre4) to address #229. May it be the last one!
