### ISSUE TITLE
FlurlClient.SendAsync() reads Cookies after failed HttpRequest

### ISSUE THREAD

**Issue by Toine-db** [tmenier/Flurl#208]
When using Cookies and an request fails it still tries to get the Cookies from the response.
But most likely call.Response will be NULL at this time, resuting an exception inside a finally section. 
https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/FlurlClient.cs#L209
This caused an breaking issue for me when upgrading from Flurl.http 1.1.1.0 to 1.2.

I think its probably better to add a little check inside ReadResponseCookies(HttpResponseMessage response).
to check the input value of 'response'

PS: sorry I can't create a PR because my current dev environment does work that well with this solution.

**Comment by Toine-db** [comment]
I created a PR that would solve the problem, but its on the current master version.
https://github.com/tmenier/Flurl/pull/210

**Comment by tmenier** [comment]
I think I may have (inadvertently?) fixed this issue with an earlier commit, but just in case `Uri` could still be null there (not sure), I [tweaked it](https://github.com/tmenier/Flurl/commit/45f5514933d11de0e292b8ece72d0d48a8e863b7) to match your fix basically. Watch for it in Flurl.Http 2.0 (prerelease coming soon). Thanks!

**Comment by tmenier** [comment]
I'd like to keep everything in 2.0 milestone open until it's released. The "ready" tag indicates the code is done.

**Comment by Toine-db** [comment]
OK, that makes sense
