### ISSUE TITLE
Ability to modify FlurlRequest from BeforeCall handler

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#213]
**Scenario:**

I'm making authenticated calls to an API, and I'd like to ensure that I have a valid auth token added to the headers (via `WithHeader` or `WithOAuthBearerToken`, etc.) with every call made with the same `FlurlClient`, even if it requires an asynchronous call to an authentication endpoint. Something like:

```c#
var client = new FlurlClient();
client.Configure(settings => settings.BeforeCallAsync = EnsureTokenAsync);
```

**Problem:**

In 1.x, this won't work for a couple reasons:

1. The argument passed to the handler is an `HttpCall`, which includes the lower-level `HttpRequestMessage` but not Flurl's fluent abstractions.

2. Even if the the `FlurlClient` were in scope here (such as with a closure), the event fires _after_ the data gathered by Flurl is written to the `HttpRequestMessage`.

**Solution:**

1. Include a `FlurlRequest` property on `HttpCall`. (BREAKING: Since they're defined on `FlurlRequest`, `Url` and `Settings` will be removed from `HttpCall` to avoid redundancy.)

2. Ensure that `BeforeCall` / `BeforeCallAsync` fire before the `HttpRequestMessage` is finalized, allowing one to fluently build on the `FlurlRequest` (including tweaking the `Url` if so desired).

**Comment by mxstudios** [comment]
@tmenier ,

Was this implemented? I am trying to figure out how to change the authorization header in the BeforeCall method.

Thanks

**Comment by tmenier** [comment]
Yes it was, that should work.

**Comment by marcinwasik1** [comment]
@tmenier could you give a code example?

I would like to call an endpoint to get an access token from "BeforeCallAsync" method and add it to "httpCall.FlurlRequest.Headers". Is it possible?
