### ISSUE TITLE
How to use with bearer?

### ISSUE THREAD

**Issue by biapar** [tmenier/Flurl#215]
I'm able to call the authorization, but when I use the bearer the call goes in the catch with FlurlHttpException ex with call.Response.StatusCode null.
Why?

> catch (FlurlHttpException ex) {
>     if (ex.Call.Response != null)
>         LogError("Failed with response code " + call.Response.StatusCode);
>     else
>         LogError("Totally failed before getting a response! " + ex.Message);
> }

**Comment by tmenier** [comment]
Does it take a long time to fail? It could be timing out.

**Comment by biapar** [comment]
This is my workaround:

```
var _client2 = new FlurlClient("http://192.168.214.1:45455/umbraco/api/HDApp/getAllNews");
                string bearer = "Bearer " + name;
               dynamic data2 = await _client2.WithHeader("Accept", "application/json").WithHeader("Authorization", bearer).GetJsonListAsync();

                var json2 = JsonConvert.SerializeObject(data2);

                List<NewsModel> myNames = JsonConvert.DeserializeObject<List<NewsModel>>(json2);
```

**Comment by tmenier** [comment]
You're doing a lot more work than you need to. The whole thing can be reduced to this:

```c#
var myNames = await "http://192.168.214.1:45455/umbraco/api/HDApp/getAllNews"
    .WithOAuthBearerToken(data.access_token)
    .GetJsonAsync<List<NewsModel>>();
```
