### ISSUE TITLE
More robust FlurlHttpException.Message

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#217]
Include URL, verb, status code, and request/response bodies (if present). Example:

```
POST https://myapi.com/foo failed with status code 400 (Bad Request).
Request body:
{"data":"bad"}
Response body:
{"message":"bad data!"}
```

Note that all values are plucked out of `FlurlHttpException.Call` object, so rolling your own error message from a `catch` block is easy, i.e. no need to parse the text above.

**Comment by desmondgc** [comment]
I'm not a fan of this "enhancement." I make quite a few requests with rather large bodies and now I'm logging unreadable exception messages with 12,000 characters! This seems to go against the general framework designs where Exception subtypes are enriched with additional properties rather than dumping everything in the message. The old behavior was preferable.

**Comment by tmenier** [comment]
@desmondgc Thanks for the feedback. The rationale was that, typically, request bodies are not huge (only those that derive from `StringContent` are included, it's not going to dump a binary file upload or anything like that), and that, typically, _error_ response bodies are not huge. So anything that logs exception messages now gets much more helpful troubleshooting information with no additional effort.

Of course, "typically" does not mean "always". If you have very large request or response bodies, I'd recommend adding a global error handler that catches `FlurlHttpException` and builds/throws an exception containing only what you want. Most types of apps (including ASP.NET) provide a place to do this, or you could use Flurl's global error handling mechanism:

```c#
FlurlHttp.GlobalSettings.OnErrorAsync = httpCall => {
    httpCall.ExceptionHandled = true;
    // build and throw your own exception here
}
```

Probably not the answer you wanted, but I still suspect the change will be more welcomed than not for most people. Time will tell.

**Comment by jaredrsowers** [comment]
I just got bit by this... 

Suddenly I am getting sensitive data written to the logs when it shouldn't be...  Wish there was a better way to disable this feature...

**Comment by tmenier** [comment]
@jaredrsowers See the example above on setting up a global error handler.

**Comment by jaredrsowers** [comment]
Yeah, already implemented and deployed to production, but it just seems hackey... I just wish there were a more robust and elegant way to do it...

**Comment by tmenier** [comment]
To me, hacky would be littering your code with try/catches all over the place. This is a mechanism to provide error handling in a single, well-defined way that is decoupled from the rest of your code. `HttpCall` is a robust object providing a wealth of details to construct whatever message you want for logging purposes. You're calling this hacky. If you have something more robust/elegant than this to suggest I'm all ears. Otherwise I think we'll have to agree to disagree on how hacky this approach is.

**Comment by michael-freidgeim-webjet** [comment]
In general, I prefer to have as much information in exception details as possible. However include potentially sensitive Request and Response in Message string is not a good. Normally Message [can be shown to end user](https://stackoverflow.com/questions/2176707/exception-message-vs-exception-tostring/2176824#2176824), but log can include ToString() if it doesn't have sensitive information.

I don't want to show request in the Message for some calls, but it's OK for other calls. I considered to parse message and remove "Request body:" section -quite ugly fix to workaround of putting different fields in a single message . 
Global handle will do the work, but I effectively will replace FlurlHttpException with my own propitiatory exception.
Any chance  to revert the change and keep Message concise, but put extra details into ToString?

**Comment by LeslieMurphy** [comment]
My concern is to avoid accidentally logging access credentials during authentication.  

I used this instead, in my catch for sending an auth request.  It logs the requested URI but not any of the sensitive POST information (login name and password).

I also logged up to 2 inner exceptions, which (for example) can  be:

Inner 1 - An error occurred while sending the request. 
Inner 2 - Couldn't resolve host name


```
catch (FlurlHttpException ex) {
      ErrMessage = $"Exception in authentication request to {ex.Call.Request.RequestUri.AbsoluteUri}";
      var inner = ex.InnerException;
                    if (inner != null)
                    {
                        
                        ErrorMessage += $" Inner(1): {inner.Message}";
                        if (inner.InnerException != null)
                        {
                            ErrorMessage += $" Inner(2): {inner.InnerException.Message}";
                        }
                    }
      }
```

**Comment by jaredrsowers** [comment]
Yeah, I continue to think that the request and response should not be part of the message, it just makes the need for ugly hacks. In my mind the message should just be something short and sweet to describe what the problem was, and that is it. This is the approach everything else takes, including .Net itself. The FlurlHttpException already had all of the request and response information in it and if you wanted to log it, you could. (I was already logging all of the non sensitive information about the call).

**Comment by LeslieMurphy** [comment]
I think Flurl is great, overall.  It's hugely helpful.  Could this be set via some global preference, to control what gets logged on exceptions?  

For my 2 cents, it seems pretty helpful and reasonable to show the request and response IF the exception is related to serialization / deserialization.  But other than that it really does not seem appropriate as default behavior.  I would want to always know the URI in the exception, and only the details when serialization is in play.  

Also, in a case such as my test for "Couldn't resolve host name" - that error should ideally be the part of the top level exception, not 2 levels deep (not sure if this is an HttpClient weirdness or what causes it)

**Comment by tmenier** [comment]
I am warming up @michael-freidgeim-webjet 's idea to keep `Message` limited to just the `"{HttpMethod} {Url} failed with {HttpStatus}"` part and render the larger message to `ToString()`. Would that solve the logging problem for everyone, or are some logging `exception.ToString()` rather than `exception.Message`?

I'll have to brace myself for blowback from people who like it the way it is, but that's just how these things go. :)

**Comment by LeslieMurphy** [comment]
I am currently just using ex.Message.

Is there an easy way to catch serialization errors and log the payload
contents only when that happens?

**Comment by tmenier** [comment]
@LeslieMurphy Doubtful. Something similar came up in [another issue](https://github.com/tmenier/Flurl/issues/288), see my response there.

**Comment by tmenier** [comment]
Re-closing, moved un-enhancement to #297. Please provide any further thoughts there.

**Comment by tapika** [comment]
Just if someone will come across the need of displaying original server error message, here could be one approach - assuming server replies with json, and error message is within `message` property.

```
catch (Exception ex)
{
    if (ex is AggregateException aggex)
    {
        ex = aggex.InnerException;

        if (ex is Flurl.Http.FlurlHttpException fhttpex)
        {
            string serverErrorMessage = null;
            try
            {
                string json = fhttpex.Call.Response.GetStringAsync().Result;
                serverErrorMessage = JObject.Parse(json)["message"].ToString();
            }
            catch
            { 
                // Could not extract server side error , just continue with original exception.
            }

            if (serverErrorMessage != null)
            { 
                throw new Exception(serverErrorMessage);
            }
        }
        throw ex;
    }

    throw ex;
}
```
