### ISSUE TITLE
Request: Add OPTIONS as verb

### ISSUE THREAD

**Issue by cryo75** [tmenier/Flurl#220]
Add the OPTIONS verb to the list of verbs known by Flurl.

**Comment by tmenier** [comment]
There are several other obscure verbs in the HTTP 1.1 standard that Flurl doesn't support explicitly, like TRACE and CONNECT. But Flurl methods like `SendAsync`, `SendJsonAsync`, and `SendStringAsync` make it very easy to specify whatever verb you want.

I'm not convinced OPTIONS deserves first-class support like GET/POST/PUT/PATCH/DELETE/HEAD, but I'll keep this open and see if anyone else chimes in.

**Comment by tmenier** [comment]
I think I'm going to implement this suggestion. I wasn't sure if OPTIONS calls were used much other than CORS preflights in browsers, but after a little R&D it does seem like they're about equally common/useful as HEAD calls in REST APIs. I'll add `OptionsAsync` to Flurl.

**Comment by tmenier** [comment]
This is implemented and released in Flurl.Http 2.3.1.
