### ISSUE TITLE
Simulate ConnectionLeaseTimeout to deal with potential DSN issue with long-lived HttpClients

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#222]
Related:
http://byterot.blogspot.co.uk/2016/07/singleton-httpclient-dns.html

Flurl.Http 2.0 is moving to a model that makes long-lived HttpClient instances the default. A potential issue with this is that in some scenarios a DNS change could get missed. (Personally I find the article to be a bit too alarmist, and I urge you to read the comments below it, particularly those by Darrel Miller and Mani Gandham, to better understand the limited scope of the issue.)

The popular solution (as discussed in the article) is to set `ServicePoint.ConnectionLeaseTimeout` to some reasonable value so connections are periodically closed and re-established. However, this [isn't supported on all platforms](https://github.com/dotnet/corefx/issues/11224) that Flurl targets. Luckily it's not hard to replicate what it does, which is simply send a `Connection: close` header at regular intervals as specified by the timeout value. So Flurl will provide this behavior and include its own `ConnectionLeaseTimeout` property on both the global settings (default) and on `FlurlClient.Settings`. The default value will be `null`, effectively disabling the behavior.

As a side note, I'm not sure I love the name `ConnectionLeaseTimeout`. I'm defaulting to it because people familiar with the issue are likely also familiar with the popular solution and will know what this means, but I'm open to other suggestions.

**Comment by cremor** [comment]
@tmenier In case you are still searching for a different property name:

.NET Core 2.1 added `SocketsHttpHandler` as a completely new implementation that is used by `HttpClient`. It has a property named `PooledConnectionLifetime` which serves the same purpose as `ServicePointManager.ConnectionLeaseTimeout` according to https://github.com/dotnet/corefx/issues/11224#issuecomment-394396643

**Comment by tmenier** [comment]
@cremor Thanks for pointing that out. Too late for a name change (at least in 2.x), but I think an [implementation change](https://github.com/tmenier/Flurl/issues/330) might be in order.
