### ISSUE TITLE
Latest Flurl.Http not referecing Flurl 2.5.0

### ISSUE THREAD

**Issue by xzuttz** [tmenier/Flurl#224]
Hi,

The nuget package Flurl.Http is referencing Flurl 2.4.0, but the latest version of Flurl is 2.5.0. 
It may not be an issue, just letting you know.

Regards

**Comment by tmenier** [comment]
Thanks. Actually it does have the latest and greatest if you count prereleases. :)
https://www.nuget.org/packages/Flurl.Http/2.0.0-pre2

I normally update Flurl.Http whenever there's an update to Flurl, but I made an exception with 2.0 being so close.
