### ISSUE TITLE
Outdated signed packages

### ISSUE THREAD

**Issue by gravity00** [tmenier/Flurl#230]
Hey there!

Any plan to update `Flurl.Signed` and `Flurl.Http.Signed` to the most recent versions?
Right now you have the following final versions, at least in Nuget.org:

| Package | Not Signed | Signed |
| --- | --- | --- |
| Flurl | 2.5.0 | 2.3.0 |
| Flurl.Http | 1.2.0 | 1.1.2 |

**Comment by tmenier** [comment]
I don't maintain the signed packages. They are maintained [here](https://github.com/carolynvs/Flurl.Signed), and I believe they're looking for a new maintainer, so if you're interested in helping out I'm sure they'd greatly appreciate it.

**Comment by gravity00** [comment]
@tmenier ah, didn't realized that! Thanks for the info!
