### ISSUE TITLE
Deserialize JSON to Anonymous Type

### ISSUE THREAD

**Issue by bgmulinari** [tmenier/Flurl#231]
I think it would be nice to have an overload of the methods `ReceiveJson` and `GetJsonAsync` that allows me to specify an `Anonymous Type` object as a parameter for the return type. As of now these methods either return me a `dynamic` (which can give you trouble at run time) or a explicitly defined `Type`.

Currently this can be achieved using the `JsonConvert.DeserializeAnonymousType` method from the Newtonsoft.Json library, like this:

```
string jsonResponse = await "http://what.ever".GetStringAsync();
var responseObj = JsonConvert.DeserializeAnonymousType(jsonResponse, new { Id = 0, Message = string.Empty });
```

With my suggestion, maybe we could have something like this:

`var responseObj = await "http://what.ever".GetJsonAsync(new { Id = 0, Message = string.Empty });`

**Comment by tmenier** [comment]
Thanks for the suggestion, I didn't even know that existed in Json.NET. But after thinking on it a bit, I'm going to decline for a couple reasons:

1. API bloat. Declared types and dynamics give you 2 nice options that I think most people are satisfied with. I don't think this third option adds enough value to justify the additional code, documentation, etc.

2. Doing it right would mean expanding the [`ISerializer`](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/Configuration/ISerializer.cs) interface, which is a breaking change.

3. If you like this approach, you're not stuck - t's quite easy to add this yourself via extension methods. :)
