### ISSUE TITLE
Auth header get's messed up

### ISSUE THREAD

**Issue by IsmailHassani** [tmenier/Flurl#233]
Hi @tmenier, today I've updated to version 2.0.0 of Flurl.Http but my header gets somehow corrupted.
This is the code to authenticate:

```c#
result = await new Url(_context.TokenUrl)
                    .WithClient(RestClient)
                    .PostUrlEncodedAsync(new ISynergy.Entities.General.Grant
                    {
                        grant_type = Grant_Types.password,
                        username = _context.Username,
                        password = password,
                        client_id = _context.Client_Id,
                        client_secret = _context.Client_Secret,
                        scope = Grant_Scopes.password
                    })
                    .ReceiveJson<Token>();
```

![screenshot](https://ibin.co/3csBh3AVzj5I.png)

As you can see here the client_id get's combined with refreshtoken.
If I go back to the previous version the error is gone.

**Comment by tmenier** [comment]
Hmm. Sounds like there could be an issue here but hard to tell from what you've provided. Please provide the following:

1. The class definition of `Token`

2. In the call above, replace `ReceiveJson<Token>()` with `ReceiveString()` and provide the _exact_ returned string.

With that I can hopefully reproduce the issue and help figure out what happened.

**Comment by IsmailHassani** [comment]
Token:
`public class Token
    {
        public string access_token { get; set; }
        public string id_token { get; set; }
        public string refresh_token { get; set; }
        public int expires_in { get; set; }
        public string token_type { get; set; }
    }`

**Comment by IsmailHassani** [comment]
I dont't get a result back. Breaks with error directly.

```POST http://localhost.:5000/oauth/token failed with status code 400 (Bad Request).
Request body:
grant_type=password&username=###&password=###&refresh_token&client_id=i-synergy&client_secret=###&scope=openid+offline_access
Response body:
{"error":"invalid_request","error_description":"The mandatory 'client_id' parameter is missing."}

**Comment by IsmailHassani** [comment]
The Grant looks like this.
Maybe it's because the class Grant has the property refresh_token which is not checked for null-value?

```public class Grant
    {
        public string grant_type { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string refresh_token { get; set; }
        public string client_id { get; set; }
        public string client_secret { get; set; }
        public string scope { get; set; }
    }

    public class Grant_Types
    {
        public const string password = "password";
        public const string refresh_token = "refresh_token";
        public const string client_credentials = "client_credentials";
    }

    public class Grant_Scopes
    {
        public const string password = "openid offline_access";
        public const string client_credentials = "openid";
    }

**Comment by IsmailHassani** [comment]
I would guess, the issue is in this change [https://imagebin.ca/v/3czH7oyQ9eaH](url)
In the previous code you did a value check. In the new version not. That's why the refresh_token parameter is probably send along despite the fact it's null.

**Comment by IsmailHassani** [comment]
I Added the test for you.

**Comment by IsmailHassani** [comment]
I realized that this exception only occurs when you use a class like I did. When you use an anonymous object, everything would run fine.

**Comment by tmenier** [comment]
Nicely done. I agree that this is a regression bug - properties with `null` values shouldn't get serialized at all. The reason it works fine with an anonymous object is the property doesn't exist at all like it does with the class. If you add `refresh_token = (string)null` to an anonymous object you'd see the same problem as with a class.

**Comment by tmenier** [comment]
Released: https://www.nuget.org/packages/Flurl.Http/2.0.1
