### ISSUE TITLE
PostJsonAsync: Why this works and not with passing variable?

### ISSUE THREAD

**Issue by biapar** [tmenier/Flurl#236]
Why?

Don't work

var jsonPostData = JsonConvert.SerializeObject(login);
await _client.WithHeader("Accept", "application/json").WithHeader("Authorization", bearer).PostJsonAsync(jsonPostData ).ReceiveString();

Works
await _client.WithHeader("Accept", "application/json").WithHeader("Authorization", bearer).PostJsonAsync(
                    new
                    {
                        Username = "",
                        Email = model.Email,
                        Password = "",
                        RedirectUrl = "",
                        Nome = model.Nome,
                        Cognome = model.Cognome,
                        Targa = model.Targa,
                        Citta = "",
                        Provincia = model.Provincia,
                        ModelloMoto = model.Moto,
                        Telefono = model.Telefono
                    }

                    ).ReceiveString();

**Comment by tmenier** [comment]
Because in the first example you're serializing the object twice.

here: `JsonConvert.SerializeObject(login)`
and here: `.PostJsonAsync(jsonPostData )`

Remove the `JsonConvert` line and just call `PostJsonAsync(login)`. Flurl will serialize `login` for you in that call.
