### ISSUE TITLE
Support content-disposition filename header in DownloadFileAsync

### ISSUE THREAD

**Issue by aharkness** [tmenier/Flurl#240]
I have a situation where I was making a get request for a file, but the filename is unknown and passed back in the Content-disposition header.  I was hoping to use DownloadFileAsync, but I couldn't figure out how to access the response headers when doing so.

Regardless, I wish there was an easier way to accomplish this:
```c#
var response = await "http://mydomain.com/not_the_filename".GetAsync();
var filename = response.Content.Headers.ContentDisposition.FileName.Replace("\"", "");
var fullFilePath = Path.Combine(downloadDirectory, filename);
using (var httpStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
using (var filestream = new FileStream(fullFilePath, FileMode.Create, FileAccess.Write, FileShare.None, 4096, useAsync: true))
{
     await httpStream.CopyToAsync(filestream, 4096).ConfigureAwait(false);
}
````

It seems more intuitive to me that the default return value for download file would be the filename specified in the header, rather than the last part of the URL.  This would be a breaking change, so perhaps there is a better alternative.  Maybe an argument in DownloadFileAsync, or an additional fluent call before the download, like:
```c#
var file = url.UseServerFilename().DownloadFileAsync(folder)
```

**Comment by tmenier** [comment]
Hmm, I see your point, enough so I _might_ be willing to accept a breaking change. If the optional `localFileName` arg isn't passed, and a filename is returned in the content-disposition, that should take precedence over the last segment of the URL.

It'll have to wait until at least 2.1 and I'll need to communicate it carefully, but I agree with the suggestion. Thanks.

**Comment by tmenier** [comment]
This is ready, please test the prerelease: https://www.nuget.org/packages/Flurl.Http/2.1.0-pre

**Comment by aharkness** [comment]
Confirmed.  Nice job, and thank you!

**Comment by tmenier** [comment]
released
