### ISSUE TITLE
Where to define base url in v2.0

### ISSUE THREAD

**Issue by Im-PJ** [tmenier/Flurl#244]
Earlier I was setting base address in custom HTTPClient Factory  
```
 var client = base.CreateClient(url, handler);
            // customize the client here         
            client.BaseAddress = new Uri(rootUrl);
```
But now this code doesn't work in v2.0 
I have read through docs but still confusing where to set base url globally?
I also tried this:
         `   FlurlHttp.ConfigureClient(rootUrl, settings => { settings.Timeout = TimeSpan.FromSeconds(25);});
`

**Comment by tmenier** [comment]
There's basically 2 ways to use Flurl: manage clients explicitly or implicitly.

Implicit:
```c#
T result = await rootUrl.AppendPathSegment("path/to/endpoint").GetJsonAsync<T>();
```

Explicit:
```c#
var cli = new FlurlClient(rootUrl);
T result = await cli.Request("path/to/endpoint").GetJsonAsync<T>();
```

There should not be any need to set `HttpClient.BaseAddress` yourself in either case. Does that answer the question?

**Comment by Im-PJ** [comment]
Thanks. Im finally doing it explicitly using dependency injection.
` Container.RegisterInstance<IFlurlClientFactory>(new CustomFlurlClientFactory(),Reuse.Singleton);`

and 
```
public class CustomFlurlClientFactory : PerHostFlurlClientFactory
    {
        protected override IFlurlClient Create(Url url)
        {   var client =  base.Create(url);
            client.BaseUrl = AppConstants.rootUrl;
            client.Headers.Add("Api-Key", AppConstants.ApiKey);
            return client;
        }
    }

```
and then Im injecting IFlurlClientFactory wherever needed and using like this. 
` var  client = flurlClientFac.Get(AppConstants.rootUrl);`
Pls advice if this is ok? Also I think your answer should be in doc.

**Comment by tmenier** [comment]
Have you read the section entitled "Using Flurl With an IoC Container"? The recommended instance-per-key pattern should work perfectly for your scenario, and you shouldn't need a custom factory at all. Just register `PerBaseUrlClientFactory` with your IoC container and see the sample code on that page for the rest. You'll want to set your `Api-Key` header in the constructor. You can even do it on the same line:

    _flurlClient = flurlClientFac.Get(AppConstants.rootUrl).WithHeader("ApiKey", AppConstants.ApiKey);

**Comment by Im-PJ** [comment]
Thanks. Flurl 2.0 is awesome. Great work.
I think there is typo in this line of code in the doc
`container.RegisterSingleton<IFlurlClientFactory, PerBaseUrlClientFactory>();
`
It should be `PerBaseUrlFlurlClientFactory`

**Comment by tmenier** [comment]
Good catch on the typo, fixed. Thanks
