### ISSUE TITLE
random (cookie related) race condition FlurlHttpExceptions

### ISSUE THREAD

**Issue by springy76** [tmenier/Flurl#245]
After upgrading from 1.x to 2.x previously fine running multi threaded code now sometimes throws "The collection has changed..." exceptions:

```
Flurl.Http.FlurlHttpException: GET http://xxx failed. Die Auflistung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden. ---> System.InvalidOperationException: Die Auflistung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   bei Flurl.Http.FlurlRequest.WriteRequestCookies(HttpRequestMessage request)
   bei Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

**Comment by tmenier** [comment]
Can you provide a sample of your code? I'm guessing you are _not_ creating `FlurlClient` instances explicitly? In this case, 2.0 switched from creating a new `FlurlClient` (and `HttpClient`) for every request to reusing them as much as possible (one per host). But if you're calling the same host on multiple threads concurrently with cookies enabled, I can see that being a problem. If you can provide a snippet of code, I can show you how you might prevent this.

**Comment by springy76** [comment]
All my requests start with `new FlurlRequest(this.BaseUrl)` where `this.BaseUrl` is a `string`. Then everything is changed fluently against `IFlurlRequest`, for example `.EnableCookies()`.

I'm definitely calling the same host concurrently on multiple threads.

**Comment by tmenier** [comment]
`FlurlClient` is the cookie container, and multiple `FlurlRequest`s to the same host will use the same cached instance of `FlurlClient` by default. So in order to prevent concurrent "sessions" of cookie-enabled calls to conflict, you need to create new instances of `FlurlClient`, not `FlurlRequest`.

I would suggest doing it like this:
```c#
using (var cli = new FlurlClient(this.BaseUrl).EnableCookies())
{
    cli.Request("path/to/endpoint")...GetAsyc();
    // additional calls
}
```
`cli.Request` allows you to build and send a request fluently, very similar to how you would do it if you started with a URL string except you're being explicit about the `FlurlClient` you want to use.

**Comment by springy76** [comment]
When I create a new FlurlClient instance for each request do I then have the pending sockets problem of 1.x again?

**Comment by tmenier** [comment]
Don't create a new `FlurlClient` for every request. You need to at least reuse it for every request in a given cookie "session". If you can get more reuse out of it than that, great, just avoid sharing it between threads or you'll be sharing the cookie container as well, which will cause conflicts.

And just to clarify, 2.0 fixes the socket problem when you are _not_ managing FlurlClient explicitly, e.g. `url...GetJsonAsyn()`. Your scenario requires creating `FlurlClient`s yourself, so it's totally up to you how you manage the lifetime of those instances.

**Comment by springy76** [comment]
Hmm. I replaced `EnableCookies` with a single `WithCookie` call and still same random exception. So since cookies in these case are only a fixed request header I have to assume that every `WithHeader` which I apply to `IFlurlRequest` will likely cause race condition exceptions as well?
