### ISSUE TITLE
Breaking change: SetQueryParam appears to always encode spaces as pluses in v2.5.2

### ISSUE THREAD

**Issue by michael-wolfenden** [tmenier/Flurl#258]
The following

```csharp
"https://www.google.com"
	.SetQueryParam("utm_source", "some source")
	.ToString()
```

Returns the following results

| Flurl v2.5.2  | Flurl v2.5.1 |
| ------------- | ------------- |
| https://www.google.com?utm_source=some+source  | https://www.google.com?utm_source=some%20source  |

I get the same results even if `encodeSpaceAsPlus` is set to `false`

```csharp
var encodeSpaceAsPlus = false
	
"https://www.google.com"
	.SetQueryParam("utm_source", "some source")
	.ToString(encodeSpaceAsPlus)
```

Returns the following results

| Flurl v2.5.2  | Flurl v2.5.1 |
| ------------- | ------------- |
| https://www.google.com?utm_source=some+source  | https://www.google.com?utm_source=some%20source  |

**Comment by tmenier** [comment]
Thanks for reporting. This was an unintentional consequence of switching from `Uri.EscapeDataString` to `WebUtility.UrlEncode` to fix #185. My test coverage wasn't as good as I thought here. I'll give this top priority and release a fix soon.

**Comment by tmenier** [comment]
One thing's for sure - [I am no longer a fan of `WebUtility.UrlEncode`](https://stackoverflow.com/a/47877559/62600).

**Comment by tmenier** [comment]
Fix is released, please test and let me know if everything appears to be back to the way it was. https://www.nuget.org/packages/Flurl/2.6.0
