### ISSUE TITLE
can't load 2.1.0 in visual studio mac

### ISSUE THREAD

**Issue by rcpemberton** [tmenier/Flurl#259]
I'm receiving the following error from vs mac.  Can you help me resolve this please.

Could not install package 'Flurl.Http 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by tmenier** [comment]
See **PCL Compatibility** toward the bottom of this page:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Flurl.Http targets .NET Standard 1.1, which is not compatible with PCL profile259. You could switch to profile111 and all you'd lose is Windows Phone Silverlight 8. Or better still, switch to .NET Standard 1.1. :)

**Comment by rcpemberton** [comment]
Thanks Todd.
