### ISSUE TITLE
Use InvariantCulture on SetQueryParams ToString

### ISSUE THREAD

**Issue by julianpaulozzi** [tmenier/Flurl#26]
Got some problems au try to use the "SetQueryParams" in other cultures.
When using the extension "ToString ()" as .ToString (CultureInfo.InvariantCulture) resolves the problem I had with floating types.

I believe that passing culture as invariant does not affect most and can solve many cases of problems with numbers.

Is this possible? 
Or is there any other way around this?

**Comment by tmenier** [comment]
Good suggestion, I agree completely. I'll make this change to SetQueryParams and anywhere else it may be applicable.

**Comment by julianpaulozzi** [comment]
Cool, thank you.

**Comment by tmenier** [comment]
Pushed this change to NuGet. It was a bit more involved than I thought as there's no `Object.ToString` overload that takes a `CultureInfo`, but it will happen for any `IFormattable` or `IConvertable`. Let me know if this works for you.

**Comment by julianpaulozzi** [comment]
Yes works great.
I tested in geocoding api (the problem), and now I could remove the model parses and runs fine and more cleanest code.

Thank you.

**Comment by thiagoburgo** [comment]
Hi @tmenier, 

I wanna suggest allow change culture, and let InvarianteCulture as default.

What do you think?

**Comment by tmenier** [comment]
@thiagoburgo I will give that some thought. Could you create a new issue and give an example where this would be helpful?
