### ISSUE TITLE
Downgrade Json.net to version 9.0.1

### ISSUE THREAD

**Issue by juchom** [tmenier/Flurl#260]
Flurl is actually targetting Json.net 10.0.3, it seems that it's not using anything from this version.

I'm currently working on a build with Json.net 9.0.1 and everything looks fine:

> Build started, please wait...                                                                             
> Build completed.                                                                                          
>                                                                                                           
> Test run for C:\dev\Flurl\Test\Flurl.Test\bin\Release\net45\Flurl.Test.dll(.NETFramework,Version=v4.5)    
> Microsoft (R) Test Execution Command Line Tool Version 15.5.0                                             
> Copyright (c) Microsoft Corporation.  All rights reserved.                                                
>                                                                                                           
> Starting test execution, please wait...                                                                   
> NUnit Adapter 3.8.0.0: Test execution started                                                             
> Running all tests in C:\dev\Flurl\Test\Flurl.Test\bin\Release\net45\Flurl.Test.dll                        
> NUnit3TestExecutor converted 241 of 241 NUnit test cases                                                  
> NUnit Adapter 3.8.0.0: Test execution complete                                                            
>                                                                                                           
> Total tests: 241. Passed: 241. Failed: 0. Skipped: 0.                                                     
> Test Run Successful.                                                                                      
> Test execution time: 9,7088 Seconds                                                                       
> Test run for C:\dev\Flurl\Test\Flurl.Test\bin\Release\netcoreapp1.1\Flurl.Test.dll(.NETCoreApp,Version=v1.
> 1)                                                                                                        
> Microsoft (R) Test Execution Command Line Tool Version 15.5.0                                             
> Copyright (c) Microsoft Corporation.  All rights reserved.                                                
>                                                                                                           
> Starting test execution, please wait...                                                                   
> NUnit Adapter 3.8.0.0: Test execution started                                                             
> Running all tests in C:\dev\Flurl\Test\Flurl.Test\bin\Release\netcoreapp1.1\Flurl.Test.dll                
> NUnit3TestExecutor converted 240 of 240 NUnit test cases                                                  
> NUnit Adapter 3.8.0.0: Test execution complete                                                            
>                                                                                                           
> Total tests: 240. Passed: 240. Failed: 0. Skipped: 0.                                                     
> Test Run Successful.                                                                                      
> Test execution time: 7,4307 Seconds                                                                       
> 

This would allow to have it working on Azure Functions for example.

If everything is fine for you, let me know if I do the PR on the master or dev branch.

Thanks

**Comment by tmenier** [comment]
You can maintain your own fork if you need to have an older version of Json.NET, but 10.0.3 is the most current and stable so I don't want to pull this into the core. Sorry.

**Comment by juchom** [comment]
Ok, it's a bit disappointing for a library to use all the latest dependencies when there is no need for that.

Older projects can't use your library just because of that.

Anyway thanks for the lib and your work.
