### ISSUE TITLE
Support automatic decompression of GZIP and DEFLATE by default

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#266]
Currently Flurl defaults to whatever `HttpClient` defaults to for this, but [that's not consistent between platforms/versions](https://docs.microsoft.com/en-gb/dotnet/api/system.net.http.httpclienthandler.automaticdecompression). By [most](https://github.com/dotnet/platform-compat/issues/22) [accounts](https://docs.microsoft.com/en-gb/dotnet/api/system.net.http.httpclienthandler.automaticdecompression), the decision _not_ to enable these by default has to do solely with backward compatibility. For Flurl I think it makes sense to enable them by default.

**Comment by ongun23** [comment]
Throws exceptions on Ubuntu but works fine at Windows machine.
