### ISSUE TITLE
.NET Standard 2.0 package

### ISSUE THREAD

**Issue by MihaMarkic** [tmenier/Flurl#267]
Hi guys,

It'd be nice if you included a .NET Standard 2.0 package. Otherwise a lot of NuGet references is dragged into a Xamarin project.

**Comment by tmenier** [comment]
Makes sense to me. Will plan on getting this in the next release.

**Comment by kroniak** [comment]
Hi. You can use flurl.http 1.4 package in your 2.0 lib.

**Comment by MihaMarkic** [comment]
@kroniak I know. But that's not the point.

**Comment by kroniak** [comment]
Why do you want exactly 2.0?

пт, 9 февр. 2018 г., 0:41 Miha Markič <notifications@github.com>:

**Comment by MihaMarkic** [comment]
@kroniak As I wrote. When adding existing NuGet package to Xamarin, it would reference a ton of other NuGet packages. Which isn't the case if it is build for .NET Standard 2.

**Comment by tmenier** [comment]
@MihaMarkic Out of curiosity, is the "ton of other NuGet packages" just something developers see when they install Flurl or does it actually result in a more bloated compiled app that end-users install on their phone?

**Comment by tmenier** [comment]
@kroniak everything builds fine by just adding `netstandard2.0` to <TargetFrameworks> and making a tweak to one of the #if directives. However, would doing this "right" mean lots of changes to build/test scripts etc?

**Comment by kroniak** [comment]
@tmenier #273

**Comment by MihaMarkic** [comment]
@tmenier TBH I do not know if there is a bloat added to the compiled app. It is bad enough (to me) that I get my nuget references polluted so I never went investigating what actually happens.

**Comment by tmenier** [comment]
@kroniak Thanks! I was already working on it myself and we ended up with the same results, which tells me I was probably doing it right. :)

Do you have an opinion on having package testers for both .NET Core 1.x and 2.x? I sometimes wonder if they're needed at all, but the way they share code, adding a new one requires [almost](https://github.com/tmenier/Flurl/blob/master/PackageTesters/PackageTester.NETCore/Program.cs) no new code.

**Comment by kroniak** [comment]
@tmenier I think we can have only .netcore app 2.0

**Comment by tmenier** [comment]
@kroniak Is it strange that `System.Reflection.TypeExtensions` is required in netstandard1.3 but not 1.0 or 2.0?

https://github.com/tmenier/Flurl/blob/master/src/Flurl/Flurl.csproj#L28-L30

Could be right, I just wanted to make sure.

**Comment by tmenier** [comment]
@MihaMarkic The latest prerelase contains a netstandard2.0 target. Please test it and let me know if it's what you're expecting:

https://www.nuget.org/packages/Flurl.Http/2.2.0-pre1

**Comment by kroniak** [comment]
@tmenier I think same. It is strange.

**Comment by tmenier** [comment]
Well this isn't very nice:

![dependencies](https://content.screencast.com/users/tmenier/folders/Jing/media/7cf9b114-3300-41f7-8eef-112378427b10/2018-02-19_1132.png)

That's for the .NET Core 2.0 package tester. Fortunately I found the culprit - Json.NET 10.0.3 accounts for most of it. 11.x has a netstandard2.0 target with exactly zero dependencies. So needless to say there will be another prerelease.

**Comment by tmenier** [comment]
That's better...

![dependencies](https://content.screencast.com/users/tmenier/folders/Jing/media/235341cd-0377-49a8-8308-9573dcadb3ca/2018-02-19_1401.png)

CodePages is necessary because of [this](https://stackoverflow.com/questions/46119872/encoding-issues-with-net-core-2).

**Comment by tmenier** [comment]
Full version is released.

**Comment by MihaMarkic** [comment]
Thanks guys. It works fine now.
