### ISSUE TITLE
WithQueryParamValues(object values) lacks a NullValueHandling property.

### ISSUE THREAD

**Issue by aivascu** [tmenier/Flurl#271]
The method ```WithQueryParamValues(object values)``` needs to have the same functionality as ```SetQueryParams(object values, NullValueHandling nullValueHandling)```.
The current implementation of ```WithQueryParamValues()``` treats null values as having set the null value handling as ```NullValueHandling.NameOnly```.

**Comment by tmenier** [comment]
Makes sense to me.

**Comment by tmenier** [comment]
Could you provide an example of a realistic test that would benefit from this? Thinking about it some more, I'm struggling to understand how it would be useful.

**Comment by aivascu** [comment]
@tmenier see #275, it has test that demos the issue I was having.

**Comment by tmenier** [comment]
I think your test would actually be simpler/better if it didn't rely on an abstraction like `NullValueHandling`. Asserts should generally be more hard-coded than what you've done here. I'd suggest one of these:

`WithQueryParamValue("FirstName", "John");`

or

`WithQueryParamValues(new { FirstName = "John" });`

**Comment by aivascu** [comment]
```NullValueHandling``` in this case is not an abstraction, it's a configuration and the default configuration is different for methods that are supposed to be used together. 
Production code, in which I am using ```Flurl```, handles much more complex objects. Asserting each individual property is a real chore. To make it work I had set everywhere the ```NullValueHanding``` param as ```NameOnly``` to match the behavior of ```WithQueryParamValue```.
I would be grateful if this functionality would be implemented. If you don't have the time for it I could attempt to contribute the code for it.
