### ISSUE TITLE
Encode name in SetQueryParam when set isEncoded argument true

### ISSUE THREAD

**Issue by DEEKEEN** [tmenier/Flurl#272]
Steps to reproduce:
"http://foo.com".SetQueryParam("$format", "json", true);
Actual result:
http://foo.com?%24format=json
Expected result:
http://foo.com?$format=json

Could you help me not to encode name?

**Comment by tmenier** [comment]
This is in the current prereleases if you'd like to test it:

https://www.nuget.org/packages/Flurl/2.7.0-pre2
https://www.nuget.org/packages/Flurl.Http/2.2.0-pre2

**Comment by tmenier** [comment]
Full releases are now available.
