### ISSUE TITLE
Array query params cannot be asserted on using WithQueryParamValue()

### ISSUE THREAD

**Issue by aivascu** [tmenier/Flurl#276]
When asserting if a named array object has been passed as a query parameter, the assertion fails.

```csharp
[Test]
public async Task can_assert_array_query_param()
{
      var arr = new[] { 1, 2, 3 };
      var result = new FlurlClient("http://api.com")
           .Request("api/path")
           .SetQueryParam("array", arr)
           .GetAsync();

       HttpTest
           .ShouldHaveCalled("http://api.com/api/path")
           .WithQueryParamValue("array", arr);
 }
```

**Comment by tmenier** [comment]
I'll consider this. Here's a work-around for now:

`.With(call => call.FlurlRequest.Url.Query == "array=1&array=2&array=3");`

**Comment by aivascu** [comment]
When I discovered this bug it was an array inside a complex object. I believe I ended up copying the query string into the ```.ShouldHaveCalled()``` parameter.

**Comment by tmenier** [comment]
Ah, first time around I forgot that this is already a feature, which puts this issue squarely in the "bug" category.

**Comment by tmenier** [comment]
This is fixed in the most recent prerelease of Fllurl or Flurl.Http. Please test and let me know if your issue is resolved.
