### ISSUE TITLE
Using Authorization Token

### ISSUE THREAD

**Issue by leroygumede** [tmenier/Flurl#278]
Framework : Xamarin Forms , (IOS), Prism 7 , .Net
flurl : 2.6.0
Api says I have not included headers in my api , I have no idea why. (It works in post-man so it has to be my side)

```
                var result2 = await "http://xxxx.xxx.xxxx.co/api/xxxx/me"
                    .WithHeader("Authorization", "Token bcxxxxxxxxxxxxxxxxxxxxxxxx")
                    .AllowAnyHttpStatus()
                    .GetStringAsync();
```
**Response I get :** 

`"{\"detail\":\"Authentication credentials were not provided.\"}"`

What my header looks like when debug with` .GetAsync();`

![screen shot 2018-02-21 at 9 24 51 am copy](https://user-images.githubusercontent.com/20415678/36467891-8db55082-16e9-11e8-8d03-d6e5e888d2e3.png)

I have a feeling that it might be the {} brackets around the Token

It works here using postman

<img width="958" alt="screen shot 2018-02-21 at 9 29 44 am copy" src="https://user-images.githubusercontent.com/20415678/36467990-1a3ee6e4-16ea-11e8-91cc-2095cb503f64.png">

and I cannot use `.WithOAuthBearerToken("Token bcxxxxxxxxxxxxxxxxxxxxxxxx")` because I need to say `"Token "`

**Comment by tmenier** [comment]
I couldn't tell you. Based on everything you provided it looks right to me. the {} is not actually in the header - that's just a UI thing in the debugger.

**Comment by leroygumede** [comment]
@tmenier Thanks, your right, I'm still debugging the issue but I doubt its from Flurl.

**Comment by Mystogun** [comment]
I'm having exactly the same problem, @leroygumede can you please tell me if you were able to resolve it?

**Comment by ankita-sky** [comment]
i did not find any solution to this issue here .. i am  facing the exact same thing ..can anyone help
