### ISSUE TITLE
Configure which HTTP status codes throw exceptions

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#28]
Currently any non-2XX response throws a FlurlHttpException. (The reasoning is that there's no other mechanism to capture a failed status in a convenience method like this: `url.GetJsonAsync<T>()`)

It's been suggested to allow configuring other non-exception-thrown statuses. I'm considering something along these lines:

```C#
AllowHttpStatuses("202,206,400-499")
AllowAnyHttpStatus()
```

These would be methods on FlurlClient and would of course be chainable. Comments/suggestions welcomed!

**Comment by lmcnearney** [comment]
:+1:

**Comment by tmenier** [comment]
Apologies for the delay. I've opted to go with just pattern (string) based approach for setting this as it allows for the most flexibility. As of Flurl.Http 0.5.1, this is configurable globally like so:

```C#
FlurlHttp.Configure(c => {
    c.AllowedHttpStatusRange = "100-299,4xx";
});
```

I anticipate this may lead to requests for making this configurable per call. Let me know if that's something you need.

**Comment by lmcnearney** [comment]
> I anticipate this may lead to requests for making this configurable per call. Let me know if that's something you need.

Yes please, per-call configuration would be helpful as most of the time the built-in exception throwing is appreciated (like when using the Json extension methods). It's only in certain cases where I may be checking for the existence of an object/route where I would be manually checking the response code and need to allow it to not throw on a 404, etc.

**Comment by tmenier** [comment]
Noted, I'll re-open this. I agree that it's a much more useful/complete feature if you can control it per call.

**Comment by tmenier** [comment]
Ok, let's try this again. You can now set patterns at the individual call/client level. Tests to demonstrate:

```c#
[Test, ExpectedException(typeof(FlurlHttpException))]
public async Task fails_on_non_success_status() {
    await "http://httpbin.org/status/418".GetAsync();
}

[Test]
public async Task can_allow_non_success_status() {
    await "http://httpbin.org/status/418".AllowHttpStatus("4xx").GetAsync();
}
```

You can also allow anything:
```c#
var result = url.AllowAnyHttpStatus.GetAsync();
```

If you're reusing the client and need to clear them (including the global config setting, but just for this client instance):
```c#
myFlurlClient.AllowedHttpStatusRanges.Clear();
```

This is pushed to v0.5.2 on [NuGet](https://www.nuget.org/packages/Flurl.Http). Let me know your thoughts.

**Comment by lmcnearney** [comment]
Thanks, those changes look good!
