### ISSUE TITLE
Inheritance problem.

### ISSUE THREAD

**Issue by Maly-Lemire** [tmenier/Flurl#281]
I need to wrap FlurlClient in my own class (For default settings, X-Http-override support, Updated Json settings, etc).

But the main problem is with the extensions that cannot be overridden. 
- Not all extensions use generics return.
- Some extensions instantiate classes that I may need to inherit (FlurlRequest for example). 
- I also have the namespace problem. My class will have a different namespace and extensions won't be available without Flurl.Http namespace. Not that I want to hide Flurl.Http but a class that does almost nothing without another namespace is bad.

I know I ask a lot but with generated virtual methods in partial classes and definitions like `Flurl <T> where T : IFlurl` with fluent methods that return T, I would be able to inherit from any `Flurl <T>.`

You would have your classes with something like : 

`FlurlClient : FlurlClient<FlurClient>, IFlurlClient where T : IFlurlClient`

and I can have

`MyFlurlClient : FlurlClient<MyFlurlClient>. IMyFlurlClient  where T : IMyFlurlClient `

Thanks

**Comment by tmenier** [comment]
Inheritance is likely not the best way to solve the types of problems you're trying to solve. You really just need a `FlurlClient` that's _configured_ a certain way by default, and there are multiple ways to do that:

- [Global settings](http://tmenier.github.io/Flurl/configuration/) via `FlurlHttp.Configure`.
- [Host-specific settings](http://tmenier.github.io/Flurl/configuration/) via `FlurlHttp.ConfigureClient`.
- Wrap `FlurlClient` in your own class via _containment_, not inheritance. In the simplest case, configure it in your constructor and expose a `Request` method that simply delegates to `FlurlClient.Request`.

As for the specific reasons you listed, there's an example of configuring JSON settings [here](http://tmenier.github.io/Flurl/configuration/#serializers), and "default" headers are supported via `FlurlClient.Headers`.
