### ISSUE TITLE
FlurlHttpException.GetResponseString() returns null when the inner exception is a Json exception

### ISSUE THREAD

**Issue by matteocontrini** [tmenier/Flurl#288]
Hi,
I'm not sure if this is a normal behaviour, but it appears that when the JSON deserialization fails with an exception, the wrapped FlurlHttpException doesn't give access to the raw response content string.

The following code reproduces the issue:

```csharp
Url url = "https://reqres.in/api/users";

try
{
    await url.GetJsonAsync<List<int>>();
}
catch (FlurlHttpTimeoutException)
{
    Debugger.Break();
}
catch (FlurlHttpException ex)
{
    string rawResponseContent = ex.GetResponseString();
                

    Debugger.Break();
}
```

The InnerException of `ex` is a `Newtonsoft.Json.JsonSerializationException` that says that the response content cannot be deserialized because it doesn't match the given T, and that's fine.
But the call to `ex.GetResponseString()` returns null. I think the request should be considered as failed when there's a deserialization error, so that GetResponseString() actually returns something that can be logged, or maybe attempted to be parsed as an error...

Thanks.

**Comment by matteocontrini** [comment]
Thinking about this again... does `GetResponseString()` return null specifically for knowing when there hasn't been an HTTP response error but an error parsing the response? Are there other cases when the `FlurlHttpException` instance doesn't have the error response body property populated with something?

**Comment by tmenier** [comment]
Thanks for reporting. I haven't had a chance to dig into this yet but I suspect the string response can't be captured without taking a slight performance hit to how responses are deserialized. For [efficiency](https://www.newtonsoft.com/json/help/html/Performance.htm), Flurl deserializes directly from the response stream to the C# object without pulling the string into memory first. Since the stream can only be read once, I don't believe it's possible to capture it if deserialization fails.

**Comment by LeslieMurphy** [comment]
Seems like we can get at the errant server response payload. Not sure if this is the case in all runtimes.   I am using .Net Core 2.0 and the following seems to work.

Could you have GetResponseString obtain the string in the case of a SerializationException?  I also checked  - ex.Call.Response.StatusCode is OK (as expected).

```
 catch (FlurlHttpException ex)
     {
            if (ex.InnerException != null && ex.InnerException is Newtonsoft.Json.JsonSerializationException)
                {
                    string respIsAlwaysNullHere = ex.GetResponseString();  // null
                    System.Net.Http.HttpContent res2 = ex.Call.Response.Content;
                    string errantJsonContent = res2.ReadAsStringAsync().Result;
                }
   }
```

**Comment by tmenier** [comment]
Ok, I can investigate whether that works across platform. If so I'll work in some sort of fix for this. But for now, there's your work-around. :)

**Comment by tmenier** [comment]
It's looking like Flurl.Http 2.3 will be centered around error handling enhancement, some potentially breaking (but easy to find and fix). This particular bug will be fixed as part of #299.

**Comment by tmenier** [comment]
This has been fixed in the most recent prerelease. Please test. Also note that `GetResponseString` has been replaced by `GetResponseStringAsync` in this release as well (#300).

https://www.nuget.org/packages/Flurl.Http/2.3.0-pre1

**Comment by matteocontrini** [comment]
Working fine here 😊

**Comment by astrohart** [comment]
Has anyone ever thought of making the field

```
  public class FlurlHttpException : Exception
  {
    private readonly string _capturedResponseBody;
    ///...
   }
```
as a public ```String``` read-only property?  I am trying to call an API and am getting ```400 Bad Request``` and it throws a ```FlurlHttpException``` but I have no obvious way of getting at the response string.

**Comment by matteocontrini** [comment]
It's already exposed through the `GetResponseStringAsync` method

**Comment by astrohart** [comment]
That method throws an ObjectDisposedException.  And besides, the way it is implemented makes no sense. I’ve dug into the code and, when, eg, PostJson has an error, that method sucks the response body down all in one gulp right into that field and it is just a string value.  

GetResponseStringAsync is useless inside a catch block because of not being able to await.  Making a public String property makes more sense. 

Regards,
 
Brian

**Comment by tmenier** [comment]
> GetResponseStringAsync is useless inside a catch block because of not being able to await.

What version of C# are you on? `await`ing in `catch` blocks has been [available](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#await-in-catch-and-finally-blocks) since C# 6, which was released more than 4 years ago.

**Comment by astrohart** [comment]
I am utilizing C# 6 but the function I am making the call in is one I don’t necessarily care to put the “async” keyword on.  I just don’t see the point of having an awaitable function just to read a string field’s value.  The value has already been populated by prior code; it is too easy just to wrap the field in a property that has just a getter. 

Regards,
 
Brian

**Comment by tmenier** [comment]
> The value has already been populated by prior code

I'm not sure what you think you've spotted in the code but there is no scenario where an error response is downloaded eagerly. `GetResponseStringAsync` is asynchronous for that very reason. There is a scenario with `GetJsonAsync<T>` where, if a successful response is received but fails to deserialize (either the JSON is invalid or doesn't match the shape of `T`), an exception is thrown with the response body already captured. The internals of `FlurlHttpException` are equipped to handle that and maybe that's what you spotted, but it's not a code path that's taken in the case of an error (non-200) response.

**Comment by astrohart** [comment]
Hi Todd-

Okay, that makes sense.  In C#6, I have an app that references a API library built on top of Flurl.  I am using C#6, .NET 4.72.  

Let’s suppose I get a non-200 response (“400 Bad Request” in this case.”  So, obviously, I want to look at the JSON response body from the server to know why.   And Flurl will throw an exception. 

Could you please provide some sample code that implements a catch block — and please kindly help me figure out which exception type is to be caught — that grabs the response body string.   The offending call that raises it is ReceiveJson<T>. 

I am kind of new to task based programming.  Any help would be appreciated. 

Brian

**Comment by snekbaev** [comment]
@astrohart it's a bit unrelated, but Flurl has an option not to throw the exception by adding `.AllowAnyHttpStatus()` to the request object. Then you can use it like:
```
var request = _flurlClient.Request( requestUri ).AllowAnyHttpStatus();

using (var response = await request.SendAsync(httpMethod, httpContent, completionOption: HttpCompletionOption.ResponseContentRead).ConfigureAwait(false))
{
	if (!response.IsSuccessStatusCode)
	{
		throw some custom exception if needed?
	}

	content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
        ...
}
```
Recently I have added Flurl to an older library and this implementation matched the old HttpClient behaviour. Hope this is useful :)

**Comment by astrohart** [comment]
Thanks, but I am actually utilizing an API library that is built on top of Flurl.  

Such library does not call AllowAnyHttpStatus and instead throws an exception whose InnerException is the FlurlHttpException, and I am trying to get the JSON response body inamidst the catch block.

**Comment by tmenier** [comment]
@astrohart here's one way I suppose:

```c#
try
{
    await DoTheCallAsync();
}
catch (Exception ex)
{
    if (ex.InnerException is FlurlHttpException fex)
    {
        var resp = await fex.GetResponseStringAsync();
    }
}
```
But you say you can't await in a catch block and I still have no idea why if you're on C# 6.
