### ISSUE TITLE
GetJsonAsync causes Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject

### ISSUE THREAD

**Issue by karpikpl** [tmenier/Flurl#289]
Hi,
this:
`await "https://jsonplaceholder.typicode.com/users".GetJsonAsync();`

is causing 

> GET https://jsonplaceholder.typicode.com/users failed. Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject

it works with `GetJsonAsync<object>()`.
I was wondering if that's a bug or a feature.

If that's a bug I can look into fixing it. Maybe checking the type first would help and using `IEnumerable<dynamic>` instead of `List<object>`?

**Comment by tmenier** [comment]
Looks like the JSON is an array at the root. Use `GetJsonListAsync` instead.

**Comment by karpikpl** [comment]
ok thanks!
I was kind of expecting that `GetJsonAsync` would work for any JSON content.
I had a case where I didn't really know if it's going to be a list or not

**Comment by tmenier** [comment]
Is the shape unknown because it could be an error object? If so, Flurl's try/catch pattern works nicely to handle that case. It would be very unusual to not know what the shape of a successful response will be, and hard to work with even if it's a `dynamic`.

**Comment by karpikpl** [comment]
I think you're right and my case was more edgy than I anticipated.
It's a great library! Thanks for sharing it with us.

**Comment by tmenier** [comment]
You might be interested to know that JSON parsing errors are getting some enhanced treatment in the next release: https://github.com/tmenier/Flurl/issues/299

The prerelease is available now.
