### ISSUE TITLE
Flurl http post with Client Cert authentication?

### ISSUE THREAD

**Issue by hozjanmarko** [tmenier/Flurl#291]
Could you provide a simple sample or snippet of how to do a post request with client cert authentication enabled?

**Comment by tmenier** [comment]
https://stackoverflow.com/a/41044686/62600

**Comment by hozjanmarko** [comment]
Thank you... I still have a long way to go :)

**Comment by tmenier** [comment]
no worries, glad to help :)

**Comment by rshillington** [comment]
The stackoverflow link references `WebRequestHandler`, which I don't think is part of .NET Core 3.1 or .NET 5? Is there an updated approach to use?
