### ISSUE TITLE
How to add multiple same keys with different values?

### ISSUE THREAD

**Issue by kkorus** [tmenier/Flurl#293]
How to create url like: `http://google.com?key=value1&key=value2`? 
This doesn't work:

```c#
  url = url.SetQueryParam("key", "value1");
  url = url.SetQueryParam("key", "value2");
((Url)url).ToString(true) // http://google.com?key=value2 
```

**Comment by tmenier** [comment]
```c#
url.SetQueryParam("key", new[] { "value1", "value2" });
```

**Comment by kkorus** [comment]
What if I don't in advance how many parameters I need to add? What If url already exits query with given key?

**Comment by tmenier** [comment]
Build up a list and pass that instead of an array. `SetQueryParam` overwrites; you can't use it to append to a list, so just keep that in mind when designing your code.
