### ISSUE TITLE
Issue with DELETE

### ISSUE THREAD

**Issue by psboies** [tmenier/Flurl#294]
Hi,

I have an issue with .DeleteAsync() extension. With about 60 tests running on specflow some of my DELETE tests on an API call were randomly failing when tests are run in parallel. 
The tests pass when not run in parallel.
The error I have is "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server" 
The fix found was to use instead .SendJsonAsync(HttpMethod.Delete, null) extension

It seems that there is an issue with concurrent calls on .DeleteAsync()

Thanks

**Comment by tmenier** [comment]
DeleteAsync calls SendAsync [directly](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/GeneratedExtensions.cs#L694), so I really don't see how that's possible. The message clearly indicates a server side issue.
