### ISSUE TITLE
Filter sent cookies by domain

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#296]
The following doesn't work:

```c#
var fc = new FlurlClient().EnableCookies();
var resp1 = await fc.Request("https://www.google.com").GetAsync();
var resp2 = await fc.Request("https://www.bing.com").GetAsync();
```

Error message:

    System.Net.CookieException : The 'Domain'='.google.com' part of the cookie is invalid.

Flurl is taking the response cookies from the first domain and trying to pass them to the 2nd, and `HttpClient` is being a good cop about it. The fix would be for Flurl to filter which cookies to send by domain, but there are a few pattern matching [rules](https://www.mxsasha.eu/blog/2014/03/04/definitive-guide-to-cookie-domains/) to consider so it's not entirely trivial.

**Comment by johnwc** [comment]
I found out that the URL is the issue when it starts with a period by debugging the .Net source. I fixed it buy changeing [**WriteRequestCookies**](https://github.com/tmenier/Flurl/blob/39cf3fe165e2d1effa0a55ab466e75779558e3ac/src/Flurl.Http/FlurlRequest.cs#L162) method to the below, and verified that the url part of the method **CookieContainer.Add** does not actually do the filtering of what cookies to send. Cookies from _abc.com_ in the cookie container where not sent to domain _xyz.com_

Also, as you can see, I had to do a conditional compiler clause for .NetStandard 1.1 & 1.3, as they did not support the Add method without a URL.

On line 174 in [FlurlRequest.cs](https://github.com/tmenier/Flurl/blob/39cf3fe165e2d1effa0a55ab466e75779558e3ac/src/Flurl.Http/FlurlRequest.cs#L174)
```CSHARP
private void WriteRequestCookies(HttpRequestMessage request) {
	if (!Cookies.Any()) return;
	var uri = request.RequestUri;
	var cookieHandler = FindHttpClientHandler(Client.HttpMessageHandler);

	// if the handler is an HttpClientHandler (which it usually is), put the cookies in the CookieContainer.
	if (cookieHandler != null && cookieHandler.UseCookies) {
		if (cookieHandler.CookieContainer == null)
			cookieHandler.CookieContainer = new CookieContainer();

		Cookies.Merge(Client.Cookies);
		foreach (var cookie in Cookies.Values)
#if (NETSTANDARD1_1 || NETSTANDARD1_3)
            cookieHandler.CookieContainer.Add(uri, cookie);
#else
            cookieHandler.CookieContainer.Add(cookie);
#endif
    }
    else {
		// http://stackoverflow.com/a/15588878/62600
		request.Headers.TryAddWithoutValidation("Cookie", string.Join("; ", Cookies.Values));
	}
}

```

**Comment by mindekm** [comment]
Are there any workarounds available for this issue?

**Comment by tmenier** [comment]
@mindekm At the very least use a different `FlurlClient` instance per domain. If you're simulating concurrent browser sessions, use a different `FlurlClient` instance per user session, even if they're hitting the same domain.

**Comment by johnwc** [comment]
@mindekm @tmenier I gave the workaround and the fix for this issue in the previous comment...

**Comment by tmenier** [comment]
It would be great if anyone following this issue could have a look at the plan for cookies in 3.0 detailed in #506. I'd like to gather as much feedback as possible before this is set in stone.

**Comment by tmenier** [comment]
Closing due to massive overhaul per #506. Flurl no longer depends on `CookieContainer`. The new implementation follows the spec and simply ignores any "." prefix in a domain.
