### ISSUE TITLE
Reign in verbosity of FlurlHttpException.Message

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#297]
Based on a decent amount of blowback on #217, I'm going to remove the request and response bodies from `FlurlHttpException.Message`, reducing it to just this:

    Call failed with status code {status} ({status descrip}): {verb} {url}

Exploring other possible enhancements such as:
- Moving the fully robust version to `ToString()`.
- Providing a mechanism for custom formatting via config settings.

Open to thoughts/ideas.

**Comment by tmenier** [comment]
Coincidentally, #300, which is also going in this release, will make it harder to put the full request & response in `ToString`, and simple formatting from a config setting would have similar challenges. So I'm going to keep it simple for now and just shorten `Message`.

**Comment by MNF** [comment]
Can you move url to the end of the message? E.g.
`
{verb} failed with status code {status} ({status descrip}). URL  {url} `

I found that for long urls (with multiple parameters) the actual reason for failure is not immediately visible in debugger or logs (e.g. SumoLogic)


Example of  exception with long url:
Request to http://localhost:14453/Introspection/get?RedirectUri=http%3A%2F%2Flocalhost%3A14453%2FMicroserviceClientTest%2FAfterLogin&token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1MDc1MjQ3MTQsImV4cCI6MTUwNzUyODMxNCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzMiLCJhdWQiOlsiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzMvcmVzb3VyY2VzIiwiSW50cm9zcGVjdG9yQXBpIl0sImNsaWVudF9pZCI6IkludHJvc3BlY3RvciIsInNjb3BlIjpbIkludHJvc3BlY3RvckFwaSJdfQ.ZsHGvA61tQJNzT4R1BW-YzxmaTYPwLqaEDx7KbjEMjHvozseUTl3KlEKsCndDCp23H3_Emh10i8_uJ_Vv0LfStP3DdjqG6DCM0vCWzLjnkjebp6VNuYJptNEFpmWMHFVJsCQf7ofhnDkVZeeGw9l-ojP3U4Wai-61gB5U5Zg8uDmDjAJoXNsPBVPfevX1YlpHngiq1S65IYX5rzMwXhNqD6dV0vZP_APj-8bgloNakCqanGfxATT4zvg4v1bn_bryEhbfZOaW6AHDCT6b0Ul-mvqljSj-LHeqdEk36N-gT7Tf37wW5MQJPi9KXBCQU7V3PqqbGOwGn1NMKbtniZ_OIgVYFuvErhZCmx3IJtS8qOTxZCfvU2QtBr34he8Bp34QR2ofuonpGgmiF9vgNlWEGrPK3yMHwWbYh_jYWh9AFg98WQgKfiKvZhe83nfDw2ai8HOLKyKgWnZzOxwqi6Isrclho37is-oe8t5jecxKJl4LR0CweRUfQiA2JM4SiUr failed. A task was canceled.

**Comment by tmenier** [comment]
@MNF Sure, why not.

**Comment by tmenier** [comment]
This update is now in the latest prerelease:

https://www.nuget.org/packages/Flurl.Http/2.3.0-pre1
