### ISSUE TITLE
Provide FlurlClient constructor to wrap existing HttpClient

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#298]
With all the great work currently happening in the .NET Core world, I've run into 2 instances in the past week where a framework-level thing is providing a new'd up `HttpClient`, and it would be handy to "replace" it with a `FlurlClient`. One was in ASP.NET Core's [TestHost](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs#L64-L67) (used for [integration testing](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing)), the other was in [Blazor](https://github.com/aspnet/Blazor/blob/a9c45fe78ac18b6bd524904b40896c249f9f09c0/src/Microsoft.AspNetCore.Blazor.Browser/Services/BrowserServiceProvider.cs#L47-L50).

One of Flurl.Http's core jobs is managing HttpClient instances for you, so generally I don't want to encourage creating them and then wrapping them. But if a framework or library is creating them for you, you don't really have a choice.

You _can_ make it work with a custom `HttpClientFactory`, but that's more complicated than it needs to be. A FlurlClient constructor that wraps an existing HttpClient should be all that's needed to deal with this scenario much more easily.

**Comment by ThisNoName** [comment]
Hi, trying to make this work with .NET TestServer for integration testing?  I have something like this 

    var client = new FlurlClient(new TestServer(builder).CreateClient())

but keeps getting 500 errors.  When I inspect the client, it shows 

    'Client.HttpMessageHandler' threw an exception of type 'System.NullReferenceException' 

I must have missed something?

**Comment by tmenier** [comment]
@ThisNoName Please create a new issue for this. (Sorry, but comments in closed issues have a way of slipping off my radar.) Most likely it's a bug. If you can provide the full stack trace that might be helpful too.

**Comment by ThisNoName** [comment]
Trying to create simple test project to dig deeper, turned out your constructor works fine.  In my project, I have a filter trying to audit IP address and TestHost.TestServer does not have IP.  Because I was alternating between TestServer and trying separate kestrel instance, missed the opportunity debugging it earlier.

As for the missing handler message, that seems the standard behavior when using HttpClient.  You can watch it like this, but it runs fine

    var client = new FlurlClient(new HttpClient())

Thanks for your help and the wonderful framework.

**Comment by tmenier** [comment]
@ThisNoName Great! So just to be clear, you don't think there's any sort of Flurl bug or quirk to be fixed here?
