### ISSUE TITLE
Add support for XML

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#3]
At a minimum, support XDocuments (get, post, etc). XPath and deserialization are other possibilities.

**Comment by tmenier** [comment]
Anyone actually want XML support in Flurl? I'd planned it originally but it may not be worth bloating the library if nobody wants it.

**Comment by lvermeulen** [comment]
I just created some Flurl extensions for this. Can I submit a PR? Crazy about Flurl, BTW. :-)

**Comment by lvermeulen** [comment]
@tmenier Uploaded to nuget:

https://www.nuget.org/packages/Flurl.Http.Xml/
https://github.com/lvermeulen/Flurl.Http.Xml
https://ci.appveyor.com/project/lvermeulen/flurl-http-xml

**Comment by kroniak** [comment]
@lvermeulen Thanks, I think owner will see your PR, please add it to **dev** branch, It will be reviewed after move to net core RC2.
I think there are a merge conflict.

**Comment by tmenier** [comment]
Nice! I fully endorse endorse maintaining this as its own project/package. Happy to put a shout out on Twitter if you think it's ready for prime time?

**Comment by lvermeulen** [comment]
@tmenier I think its own package might be the right way to go, since I'm worried about polluting Flurl.Http with all the XML references. Yeah I think it's ready for prime time, will see if anyone reports issues. Thanks!!

**Comment by tmenier** [comment]
@lvermeulen Got a twitter handle?

**Comment by lvermeulen** [comment]
@tmenier yeah it's @lukvermeulen
