### ISSUE TITLE
Support for multiple key value pairs in query string with same key

### ISSUE THREAD

**Issue by miiihi** [tmenier/Flurl#30]
Currently, new Url("http://abc.com/?a=1&a=2") throws an error - which it shouldn't as this is valid URL. 
As for behavior in this case, there are multiple options, but I guess best would be to create an array of strings in this case...

Thanks, Mihi

**Comment by tmenier** [comment]
Thanks for reporting, indeed a bug. Fixed in the latest Flurl and Flurl.Http NuGet packages.
