### ISSUE TITLE
Headers in PostMultipartAsync

### ISSUE THREAD

**Issue by rmbrunet** [tmenier/Flurl#311]
Hello Guys,

making some PostMultipartAsync calls and having some issues due to particularities of the receiving server (like enforcing multipart/mixed instead of multipart/form-data. Or protesting because of the present Accept-Encoding header (where that is coming from?). 

Is there any way (I am sure there is one but can't find it) to control the request headers and the generated boundary? 

Best Regards!

Roberto

**Comment by tmenier** [comment]
Multipart is documented in #113. If you're looking to vary the headers and other things for each part, you'll need to look to the lower-level `.Add(content)` method, where you build an `HttpContent` object exactly as you need, including adding headers.

**Comment by tmenier** [comment]
Here's an example of setting headers/boundary at the content level that could easily be adapted to Flurl:

https://stackoverflow.com/questions/18500040/httpclient-setting-boundary-with-content-type

**Comment by tmenier** [comment]
I believe this is resolved right? I think I just forgot to close it. Glad you found a "Flurl-ish" solution. :)
