### ISSUE TITLE
NullReferenceException when setting a content-type header but not actually sending content

### ISSUE THREAD

**Issue by Im-PJ** [tmenier/Flurl#313]
I have a strange issue. All Post requests are working fine but any variant of GET requests are failing with below error
```
Exception- System.NullReferenceException: Object reference not set to an instance of an object.Exception- System.NullReferenceException: Object reference not set to an instance of an object.
  at Flurl.Http.FlurlRequest.WriteHeaders (System.Net.Http.HttpRequestMessage request) [0x0013c] in <0b8ec929b0304612945586497daf7e3c>:0 
  at Flurl.Http.FlurlRequest+<SendAsync>d__19.MoveNext () [0x001cc] in <0b8ec929b0304612945586497daf7e3c>:0 
```
I'm re-using flurlclient across all post & get requests since its calling to same domain. Pls help me out how to find original issue.
I should add that this is happening after updating to latest Nuget.

**Comment by tmenier** [comment]
Most likely it's a regression bug related to #256. But I need a little more info. Can you post the code where you create/configure your `FlurlClient`, as well as the specific GET call? I'm looking for anything that might directly or indirectly affect the request headers. Thanks.

**Comment by Im-PJ** [comment]
I'm injecting flurlcient as singleton and configuring as below 
```
_flurlClient = flurlClientFac.Get(rootUrl)
           .WithHeader(APIHeader, ApiKey)
          .WithHeader(SessionHeader, SessionToken)
           .WithHeader("Content-Type", "application/json");
```
GET request
`var result = await _flurlClient.Request(ApiUrl + "/getEmpData").GetJsonAsync();
`

**Comment by tmenier** [comment]
What are `APIHeader` and `SessionHeader`? I'm guessing one of them is null.

**Comment by Im-PJ** [comment]
They are just string constants and not null. Request headers are set correctly as validated during debugging and its working with POST requests.

**Comment by tmenier** [comment]
Ah! I think I see what's happening. You're setting a `content-type` but not sending any content. My guess is you're doing that so you can reuse this when you are sending content (i.e. POSTs), so I should definitely add a null check in Flurl.

However, if you're using Flurl's `PostJsonAsync` for your POST requests, content-type is set to `application/json` automatically, so I think if you just remove the line that sets that, all should be good.

**Comment by Im-PJ** [comment]
Thanks. removing content-type header works. I don't know why did it I set it explicitly.

**Comment by tmenier** [comment]
Great. You probably set it because the API you're calling requires it, or just that it's a best practice for sending any JSON request body. Flurl doing it for you is sort of a subtle feature. :)

This is still a bug in general though. Thanks for reporting.

**Comment by tmenier** [comment]
This fix has been released: https://www.nuget.org/packages/Flurl.Http/2.3.2
