### ISSUE TITLE
ErrorCode:10054, when execute FlurlClient.SendAsync(...)

### ISSUE THREAD

**Issue by ghforgaofeng** [tmenier/Flurl#326]
Hi,
    Version: (Flurl.Http.Signed, 0.7.0), it's old.
    Method: POST
    When execute FlurlClient.SendAsync(...), return error 10054, ConnectionReset
    thanks.

**Comment by tmenier** [comment]
I don't maintain or support a signed version of Flurl. Please submit your issue [here](https://github.com/carolynvs/Flurl.Signed).
