### ISSUE TITLE
Fusillade support?

### ISSUE THREAD

**Issue by julianpaulozzi** [tmenier/Flurl#33]
There a way to use the [Fusillade](https://github.com/paulcbetts/Fusillade) RateLimitedHttpMessageHandler?
For something similar as described here: [Resilient network services](http://arteksoftware.com/resilient-network-services-with-xamarin/).

**Comment by tmenier** [comment]
Sure is, but I see my docs are a little out of date.

Have a look at the bottom of [this page](http://tmenier.github.io/Flurl/extensibility) under "Providing a custom HttpClient factory". That is the basic approach, but what it fails to mention is that the factory also exposes a `CreateMessageHandler` method that you can override. That would be your hook to provide `RateLimitedHttpMessageHandler` instances. See [here](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/Configuration/DefaultHttpClientFactory.cs) for the default implementation.

Hopefully that's enough to go on but let me know if you need an example. I'll get my docs updated soon here.

**Comment by julianpaulozzi** [comment]
This can work however did not see how to change the priority by passing parameter.
It would be something like this:

    public class ModernHttpClientFactory : DefaultHttpClientFactory
    {
        public override HttpMessageHandler CreateMessageHandler()
        {
            return new ModernHttpClient.NativeMessageHandler();
        }
    
        public override HttpClient CreateClient(Url url, HttpMessageHandler handler)
        {
            /*return new HttpClient(new FlurlMessageHandler(handler))
            {
                Timeout = FlurlHttp.Configuration.DefaultTimeout
            };*/
            // How change this priority by calling "GetJsonAsync"
            var priority = Priority.Background;
            return new HttpClient(new RateLimitedHttpMessageHandler(handler, priority))
            {
                Timeout = FlurlHttp.Configuration.DefaultTimeout
            };
        }
    }

Config on ctor:

    FlurlHttp.Configure(c =>
    {
        c.HttpClientFactory = new ModernHttpClientFactory();
    });

Usage ex:

    public async Task<MobileClientLookupResponse> GetLookupsAsync(Priority priority)
    {
        // priority?
        return await _configuration.RemoteServiceUri
            .AppendPathSegment(ApiConstants.ApiRoutes.MobileClientLookups)
            .WithOAuthBearerToken(_oauthToken)
            .GetJsonAsync<MobileClientLookupResponse>();
    }

**Comment by tmenier** [comment]
Sorry for the delay. Good question.

For starters, I don't think you need to override `CreateClient` at all. I'd lean toward this for your factory:

````c#
public class ModernHttpClientFactory : DefaultHttpClientFactory
{
    public override HttpMessageHandler CreateMessageHandler()
    {
        var innerHandler = new ModernHttpClient.NativeMessageHandler();
        
        // How change this priority by calling "GetJsonAsync"
        var priority = Priority.Background;
        return new RateLimitedHttpMessageHandler(innerHandler, priority);
    }
}
````

But that's more of a side note. Your real question is how to pass an argument into `CreateMessageHandler` and there really isn't a clean way to do that. I'm envisioning you might want to add a `WithPriority(x)` extension method on `FlurlClient` (and probably on `string` and `Url` for completeness). The problem is where to store x so `CreateMessageHandler` can later get at it. Best I can think of (assuming this is a multithreaded app) is the logical call context. (See [here](http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html) for some guidance.)

I'll leave this open. I might be open to an enhancement to better accommodate this; let me know if you have any specific ideas.

**Comment by julianpaulozzi** [comment]
I was actually thinking also one parameters bag with key value. I believe (believe) that using a Lazy <Dictionary <string, object >> I will not have a multithreaded problems.
However use the "URL as Key" to retrieve the value would be weird.

I was thinking is something that returns a token of the request by ref, some extension like "GetToken(out token)" and this token available in "CreateMessageHandler".

Even better if the method "CreateMessageHandler" had a "Dictionary<string, object>" parameter. It could be provided within the call context.
I'm not sure if this is possibly more would open flexibility for various uses.

**Comment by julianpaulozzi** [comment]
Thinking a little I do not know the factory call cycle. It may not be possible to add these contextual information.
More can be no other solution that would be introduce something like a "Keyed Factory" beyond the default factory in configuration.

So it would be possible to maintain (not sure if that is so) the instance created by the factory. And in case of nonstandard call use something like "WithFactory(key)".

Thanks for regards.

**Comment by tmenier** [comment]
FlurlClient is the only thing that that calls those factory methods, and it usually gets created/disposed on the fly for each call (unless the code is explicitly reusing it), so some sort of data bag on FlurlClient would probably work well. On the other hand, methods like `WithHttpClient` and `WithMessageHandler` that let you override the factory methods per call would work too.

I'll think on it. Let me know if you have a preference between those 2 approaches. In either case I think you'd still want to create a `WithPriority` extension for your own use - these would just be hooks to help you build that.

**Comment by julianpaulozzi** [comment]
I believe that the two approaches can be useful to someone at some point.
What would be better and would open more flexibility for use in other cases not only mine?

**Comment by tmenier** [comment]
Sorry for dropping the ball on this. Making a fresh push to get Flurl.Http to 1.0, so I'll take a fresh look at this issue in the coming week or so.

**Comment by memorex700mb** [comment]
Im also trying to implement fusillade with flurl. I wonder if there is a support like refit have. Sorry Im new to both fusillade and flurl.y

**Comment by jefkeijers** [comment]
Up 👍

**Comment by tmenier** [comment]
This one continues to slip off my radar, sorry. I don't want to promise when, but it is the very next issue I will address.

**Comment by tmenier** [comment]
It's been a while since I've read through this thread, and I should have updated it when Flurl.Http 1.0 was released, because there is a solution now. The problem was that there was no hook into `HttpClient` construction on a per-call basis. But those `FlurlHttpSettings` (which include an `HttpClientFactory` instance)  are no longer strictly static - each `FlurlClient` gets a _copy_ of the global settings, and you can modify them per `FlurlClient`.

So here's how I'd do this. Start by creating a factory like this:
````c#
public class FusilladeHttpClientFactory : DefaultHttpClientFactory
{
    private readonly Priority _priority;

    public FusilladeHttpClientFactory(Priority priority) {
        _priority = priority;
    }

    public override HttpMessageHandler CreateMessageHandler()
    {
        var innerHandler = new ModernHttpClient.NativeMessageHandler();
        return new RateLimitedHttpMessageHandler(innerHandler, _priority);
    }
}
````
Then create your `WithPriority` extension method:
````c#
public static FlurlClient WithPriority(this FlurlClient fc, Priority priority) {
    fc.Settings.HttpClientFactory = new FusilladeHttpClientFactory(priority);
    return fc;
}
````
Note you may want overloads of this for `string` and `Url`.

Let me know if this will work for you guys.

**Comment by tmenier** [comment]
Haven't heard back on this but I'm going to assume the solution above addresses the issue and close it. Feel free to re-open or create a new issue if you disagree.
