### ISSUE TITLE
ConnectionLeaseTimeout implementation improvements

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#330]
Flurl's implementation of `ConnectionLeaseTimeout` sends a `Connection:Close` header at regular intervals for the given `FlurlClient` (which in typical apps is a single instance per host being called). This doesn't account very well for pooled connections, and those pools are internal to the network stack and inaccessible via the `HttpClient` stack.

I think this is probably a better way to go:

- On platforms that support `ServicePointManager` (full framework only?), use [`ServicePoint.ConnectionLeaseTimeout`](http://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html).

- On .NET Core 2.1 or above, use [`SocketsHttpHandler.PooledConnectionLifetime`]( https://github.com/dotnet/corefx/issues/11224#issuecomment-394396643).

- Use the existing implementation as a fallback, and document its shortcomings.

**Comment by tmenier** [comment]
This most likely implies adding a .NET Core 2.1-specific target, which is fine.

**Comment by tmenier** [comment]
On the [advice](https://github.com/dotnet/corefx/issues/11224#issuecomment-415850524) of Karel Zikmund from Microsoft (who I consider an authority on the topic), I've opted for a strategy that simply swaps out the `HttpClient`  instance for a new one at the timeout interval. Although he also suggested I don't even need to dispose the old instance, I'm not entirely comfortable with that (based on [other authoritative advice](http://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html?showComment=1472494802315#c4936062004437927573)), but I can't dispose the old one immediately when it's swapped out because there may be requests pending. So I opted for a simple solution that I believe should be effective: dispose the previous instance on the _next_ lease timeout. This was also reasonably simple to implement without timers, which kept things "lazy" and responsive any mid-stream change to `ConnectionLeaseTimeout`.

Here's an example of how it works. Say you set `ConnectionLeaseTimeout` to 10 minutes.

Call is made on a `FlurlClient`.
- `HttpClient` is lazily instantiated and request is sent.

10 minutes pass, another call is made on the instance.
- Current `HttpClient` becomes a "zombie" (no longer used but not disposed).
- New `HttpClient` is created and the request is sent.

10 more minutes pass, another call is made on the instance.
- `Dispose()` is called on the zombie instance.
- Current `HttpClient` becomes new zombie.
- New `HttpClient` is created and the request is sent.

The relevant code is [here](https://github.com/tmenier/Flurl/blob/6458c507b7f891a3830f3a11071fbf4505704ce3/src/Flurl.Http/FlurlClient.cs#L103-L141), if anyone cares to review it and provide feedback that would be welcomed.

I realize this solution isn't absolutely perfect, and using `ServicePointManager` or `PooledConnectionLifetime` when possible might be slightly more performant, but keep in mind this is something that, typically, will happen once every several minutes to a single instance (per host) app-wide once. Having a single solution that works on all targeted platforms has its advantages. I welcome your opinions on this direction.

**Comment by cremor** [comment]
Although I'm not very deep in this discussion, the solution looks good to me. If I understand it correctly the `HttpClientFactory` from ASP.NET Core 2.1 does something similar.

Just one question: By default the `ConnectionLeaseTimeout` is still not set, right? Maybe this is also worth considering a change. I'm not 100% sure right now if this is still correct, but according to [a blog post ](https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore) `HttpClientFactory` uses 2 minutes by default.

**Comment by tmenier** [comment]
@cremor Thanks for taking a look. Good question about a default. I thought about that but decided against it, just in case people are taking care of it a different way, most likely through `ServicePointManager`. It's also possible that the new `SocketsHttpHandler`, used by default in .NET Core 2.1, has a default `PooledConnectionLifetime`. (That might even be what's behind HttpClientFactory's default, though I'm not sure.)  I think it's a little safer to make it opt-in.

**Comment by tmenier** [comment]
This is now in prerelease. If you're interested in using the feature, I strongly recommend testing. Feedback appreciated.

https://www.nuget.org/packages/Flurl.Http/2.4.0-pre

**Comment by rcollette** [comment]
Just became aware of this via twitter.

I am wondering why FlurlClientFactory and this type of logic is necessary at all now that MS is attempting to address the issues via HttpClienFactory?

Tangentially, I'm not thrilled with the fact that Typed clients (via services.AddHttpClient<>) require and register the client as a concrete type, that then must be referenced in other services by that concrete type.  At the moment I'm opting to inject IHttpClientFactory.

**Comment by tmenier** [comment]
@rcollette Because if Flurl takes a dependency on ASP.NET Core 2.1 bits, it breaks a lot of people. If that's what your app is targeting, great, I'd say use it - it's probably a better implementation than what I did. But folks on other platforms like .NET Core 1.x don't have that option. I just wanted to provide an opt-in solution that works on every platform.

**Comment by rcollette** [comment]
Makes sense.   I took
>This most likely implies adding a .NET Core 2.1-specific target, which is fine.

To mean that you were updating to 2.1 dependency.  

Thanks for the work on this release.

**Comment by tmenier** [comment]
Yeah, my original plan was to platform-sniff and do multiple implementations, but I decided to keep it simple.

**Comment by tmenier** [comment]
2.4 is in [full release](https://www.nuget.org/packages/Flurl.Http/2.4.0).
