### ISSUE TITLE
FlurlClient throws a NullReferenceException when disposing

### ISSUE THREAD

**Issue by aignas** [tmenier/Flurl#334]
Hi,

I am having this issue where the disposing of the client fails because of the mentioned exception. The simplest way to repro is the following class. I am using the latest versions of `Flurl` and `Flurl.Http`:

The actual code:
```
    public sealed class TestServerFixture : IDisposable
    {
        private readonly TestServer _server;
        private HttpClient _client;
        public IFlurlClient Client { get; }

        public TestServerFixture()
        {
            _server = new TestServer(
                Program.BuildWebHost());
            _client = _server
                .CreateClient();
            Client = new FlurlClient(_client);
        }

        public void Dispose()
        {
            _client.Dispose();
            Client.Dispose();
            _server.Dispose();
        }
    }
```

This show where it fails:

![image](https://user-images.githubusercontent.com/240938/41897569-5d3e6232-7930-11e8-87e7-3be81bb07636.png)

As you can see from the coverage on the left hand side, the client disposing itself does not fail, but the `FlurlClient` does fail. I looked at the code and it looks like we do not check that the value in the `Lazy` is not null, but I don't know if that is the reason of the bug.

**Comment by tmenier** [comment]
Confirmed. Thanks for reporting. Will fix this for the next maintenance release.

**Comment by tmenier** [comment]
This fix has been released: https://www.nuget.org/packages/Flurl.Http/2.3.2
