### ISSUE TITLE
HttpTest.ShouldHaveCalled() throws NullReferenceException 

### ISSUE THREAD

**Issue by nicemd** [tmenier/Flurl#335]
When not using Flurl for sending the http request, HttpTest.ShouldHaveCalled() throws NullReferenceException.

I was trying to use HttpTest to test a client that uses an ordinary injected HttpClient for sending request.

```
        [Fact]
        public async Task Not_Working()
        {
            using (var httpTest = new HttpTest())
            {
                httpTest.RespondWith("Hello");
                var flurClient = new FlurlClient();
                await flurClient.HttpClient.GetStringAsync("http://google.com/");
                httpTest.ShouldHaveCalled("http://google.com/");
            }
        }

        [Fact]
        public async Task Working()
        {
            using (var httpTest = new HttpTest())
            {
                httpTest.RespondWith("Hello");
                var flurClient = new FlurlClient();
                await "http://google.com/".GetStringAsync();
                httpTest.ShouldHaveCalled("http://google.com/");
            }
        }
```
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Flurl.Http.Testing.HttpCallAssertion.<>c__DisplayClass5_0.<WithUrlPattern>b__0(HttpCall c)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Flurl.Http.Testing.HttpCallAssertion.With(Func`2 match)
   at Flurl.Http.Testing.HttpCallAssertion.WithUrlPattern(String urlPattern)
```
Version 2.3.1

**Comment by tmenier** [comment]
Confirmed. Thanks for reporting. Will fix for the next maintenance release.

**Comment by tmenier** [comment]
@nicemd Just to be clear, if you're using the `HttpClient` directly (like in your first test), you still shouldn't expect that test to pass. `HttpTest` only records calls made by `FlurlClient`. This fix will only resolve the `NullReferenceException`, which is clearly a bug.

**Comment by nicemd** [comment]
Ok! But if it would be possible to record calls made to the inner http client, FlurlTest would be much more useful as a general purpose http mocking framework.

**Comment by tmenier** [comment]
Perhaps, but that was never the intent. It would require some refactoring/decoupling, and maybe even a repackaging of just the testing framework. Not sure I want to go there. Flurl and its testing features were designed to be used together.

**Comment by tmenier** [comment]
This fix has been released: https://www.nuget.org/packages/Flurl.Http/2.3.2
