### ISSUE TITLE
Add Url.ToUri() method

### ISSUE THREAD

**Issue by Marusyk** [tmenier/Flurl#339]
I'm going to use only `UrlBuilderExtensions` with my `httpClient` like:

```cs
using (var requestMessage = new HttpRequestMessage())
{

    var requestUri = "http://localhost:5050".SetQueryParams(new
    {
        search = "text",
        LabelId = 11,
        excludeInherited = 1,
        skip = 0,
        take = 10
    });
   requestMessage.RequestUri = new Uri(requestUri);
   // send message
}
```

What do you think about add implicit conversion operator from `Flurl.Url` to `System.Uri` for simplify using

```cs
requestMessage.RequestUri = requestUri;
```
I would prepare a PR

**Comment by tmenier** [comment]
I like it. You could even drop it down to 1 line:

```c#
requestMessage.RequestUri = "http://localhost:5050".SetQueryParams(...
```

PR would great. Please review the [contribution guidelines](https://github.com/tmenier/Flurl/wiki/Contribution-Guidelines) carefully.

**Comment by Marusyk** [comment]
The `HttpRequestMessage` has the following constructors:

```
public HttpRequestMessage();
public HttpRequestMessage(HttpMethod method, Uri requestUri);
public HttpRequestMessage(HttpMethod method, string requestUri);

```

So when we add an implicit conversion operator from `Flurl.Url` to `System.Uri` then in this place

```
var request = new HttpRequestMessage(verb, Url) { Content = content };
```
we got the error message

> Error	CS0121	The call is ambiguous between the following methods or properties: 'HttpRequestMessage.HttpRequestMessage(HttpMethod, string)' and 'HttpRequestMessage.HttpRequestMessage(HttpMethod, Uri)'	Flurl.Http(netstandard1.1), Flurl.Http(netstandard1.3), Flurl.Http(netstandard2.0)	...\Flurl\src\Flurl.Http\FlurlRequest.cs	112	Active

**Comment by tmenier** [comment]
Not a showstopper, the caller just needs to cast it:

```c#
var request = new HttpRequestMessage(verb, (Uri)Url);
```

This is new functionality so that error isn't going to break anyone's existing code.

**Comment by Marusyk** [comment]
Yeah, but it looks awful 😧
We add implicit conversion in one place but explicit in other. Is it ok?

**Comment by tmenier** [comment]
I apologize, I think I missed a crucial point here. I said this wouldn't break anyone's existing code, but I think you demonstrated just the opposite! Flurl's `Url` already implicitly converts to `String`, so anyone using it in a constructor or method that takes either a `String` or a `Uri` (probably a lot of them in the wild) would suddenly break with the ambiguous call error you encountered.

I think the best options are either [_explicit_](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/explicit) conversion, or, perhaps better, a `ToUri()` method. (Better in that it's more discoverable and, in the spirit of Flurl, more fluent. :) )

**Comment by Marusyk** [comment]
I agree. Please review the latest commit.

**Comment by tmenier** [comment]
This has been released https://www.nuget.org/packages/Flurl/2.8.0
