### ISSUE TITLE
Improvement flexibility: Extend IFlurlRequest and add extension methods

### ISSUE THREAD

**Issue by Marusyk** [tmenier/Flurl#340]
This is a cool package, thanks for that. I'm looking for flexibility `HttpRequestMessage` builder like:

```cs
var requestMessage = "http://localhost:5050"
	.AppendPathSegment("job")
	.AppendPathSegment(id)
	.AppendPathSegment("configuration")
	.WithHeader("Temp-Relations", string.Join(",", request.LabelRelations))
	.WithHeader("Temp-Access", string.Join(",", request.LabelAccess))
	.WithHttpMethod(HttpMethod.Post)
	.WithJsonContent(request.LabelRelations)
	.ToHttpRequestMessage();
```

What do you think about add extension methods `WithHttpMethod` and `WithJsonContent`  and property to store that data in `IFlurlRequest`?

I know about `PostJsonAsync` and other but I don't want to send request in that way. We use own httpclient, so I just need HttpRequestMessage with Url. Is it possible to extend it? 

There is no problem to add `ToHttpRequestMessage` in my code but some problems with `WithHttpMethod` and `WithJsonContent`  because `IFlurlRequest ` doesn't have properties like `IDictionary<string, object> Headers { get; }` or `IDictionary<string, Cookie> Cookies { get; }`. So, what do you think?

For now I've implemented it in this way

```cs
public class ExtendedFlurlRequest : FlurlRequest
    {
        public HttpMethod HttpMethod { get; set; }
        public HttpContent Content { get; set; }
    }

    public static class HttpRequestMessageExtensions
    {
        public static ExtendedFlurlRequest WithHttpMethod(this IFlurlRequest request, HttpMethod httpMethod)
        {
            var extendedFlurlRequest = new ExtendedFlurlRequest
            {
                HttpMethod = httpMethod,
                Url = request.Url
            };

            foreach (var keyValuePair in request.Headers)
            {
                extendedFlurlRequest.Headers.Add(keyValuePair);
            }

            return extendedFlurlRequest;
        }

        public static ExtendedFlurlRequest WithJsonContent(this ExtendedFlurlRequest request, object content)
        {
            string jsonContent = JsonConvert.SerializeObject(content);
            request.Content = new StringContent(jsonContent, Encoding.UTF8, "application/json");
            return request;
        }

        public static HttpRequestMessage ToHttpRequestMessage(this ExtendedFlurlRequest request)
        {
            var requestMessage = new HttpRequestMessage
            {
                RequestUri = new Uri(request.Url),
                Method = request.HttpMethod,
                Content = request.Content
            };

            foreach (var requestHeader in request.Headers)
            {
                requestMessage.Headers.Remove(requestHeader.Key);
                if (requestHeader.Value != null)
                    requestMessage.Headers.TryAddWithoutValidation(requestHeader.Key, requestHeader.Value.ToString());
            }

            return requestMessage;
        }
    }
```

Can something like that be supported out of the box? Thanks

**Comment by tmenier** [comment]
> I know about PostJsonAsync and other but I don't want to send request in that way. We use own httpclient, so I just need HttpRequestMessage with Url.

Could you expand on that? I don't understand why you wouldn't use Flurl to send the request.

**Comment by Marusyk** [comment]
Because we are developing something like SKD for our services when we should throw our custom exceptions and add some default headers for each request then convert response to `ServiceResponse<TResponse>`

**Comment by tmenier** [comment]
Understood. I think it's a very unusual situation though, so I'm declining adding it to the core. I'm not even sure if Flurl.Http is a good fit for this. Have you considered using [just the URL builder](https://www.nuget.org/packages/Flurl/) along with the HttpClient stack?
