### ISSUE TITLE
Support CancellationToken for DownloadFileAsync

### ISSUE THREAD

**Issue by lunim** [tmenier/Flurl#360]
Currently DownloadFileAsync doesn't accept a cancellation token.  It appears that the Stream CopyToAsync method does have an overload that accepts a token.

**Comment by tmenier** [comment]
Good catch. Seems like a no-brainer, was probably an oversight. I'll add it.

Thanks.

**Comment by tmenier** [comment]
This has been [released](https://www.nuget.org/packages/Flurl.Http/2.4.0).
