### ISSUE TITLE
Complex type and enumerable query parameter formatting

### ISSUE THREAD

**Issue by rodrigo-speller** [tmenier/Flurl#361]
Hi people.

In not so far away...

I need to set an object for a set of query string attributes. I'm using ASP.NET MVC as server and (as we knows) it implements model binders to binding complex and enumerables types.

---

Imagine this scenario in the ASP.NET MVC:

```csharp

public class NameValueType
{
    public string Name { get; set; }
    public object Value { get; set; }
}

public class AnotherTypeInTheWall
{
    public NameValueType Property1 { get; set; }
    public NameValueType Property2 { get; set; }
    public IEnumerable<NameValueType> SetOfProperties { get; set; }
}

```

this action:

```csharp
public class TestController : Controller
{
    public IActionResult Index([FromQuery] AnotherTypeInTheWall sample)
    {
        return Ok(sample);
    }
}
```

If I request this action with this query:
```
http://localhost/Test?Property1.Name=Prop1&Property1.Value=123&Property2.Name=Prop2&Property2.Value=234&SetOfProperties[0].Name=Elem0&SetOfProperties[0].Value=Val0&SetOfProperties[1].Name=Elem1&SetOfProperties[1].Value=Val1
```

the result must be there:
```json
{"property1":{"name":"Prop1","value":"123"},"property2":{"name":"Prop2","value":"234"},"setOfProperties":[{"name":"Elem0","value":"Val0"},{"name":"Elem1","value":"Val1"}]}
```

---

I need to make the inverted way to consume the above API. So, I need to build the Url.

My proposed code to get the same Url is:

```csharp

var sample = new AnotherTypeInTheWall()
{
    Property1 = new NameValueType
    {
        Name = "Prop1",
        Value = "123"
    },

    Property2 = new NameValueType
    {
        Name = "Prop2",
        Value = "234"
    },

    SetOfProperties = new[]
    {
        new NameValueType {
            Name = "Elem0",
            Value = "Val0"
        },

        new NameValueType {
            Name = "Elem1",
            Value = "Val1"
        }
    }
};

var url = "http://localhost/"
    .SetQueryParam(sample)
    .ToString()

```

I started to develop formatters to obtain this result.

Do you have any suggestions?

**Comment by tmenier** [comment]
Currently Flurl doesn't support nested objects in query strings. You have 3 options:

1. Do it manually:

```c#
var url = "http://localhost/Test"
    .SetQueryParam("Property1.Name", sample.Property1.Name)
    .SetQueryParam("Property1.value", sample.Property1.Value)
    ...
```

2. Serialize the object to JSON, send that string in 1 query param, and deserialize it on the server side.

3. Change the server to require POSTing this as JSON in the body. If possible, that's your best option. The query string is rarely the right place for sending complex data. You can also then take advantage of Flurl's built-in JSON serialization and ASP.NET's built-in JSON deserialization.

**Comment by tmenier** [comment]
Did my response clear things up? In short, it's not a common scenario so Flurl doesn't support it directly (nor do I plan on adding anything like this), so you'll need to adapt your code for it somehow. Feel free to re-open if this doesn't answer your question.
