### ISSUE TITLE
Add support for Google Protocol Buffers....

### ISSUE THREAD

**Issue by natiki** [tmenier/Flurl#362]
Hi,

I wanted to suggest adding support for Google Protocol Buffers ([link](https://developers.google.com/protocol-buffers/)) out of the box. While I realise this can be done by implementing ISerializable ([by following](https://flurl.io/docs/configuration/#serializers)).

The reason for suggesting this is that this protocol is often used when you want something lighter bandwidth wise and also self healing when the wire protocol changes. This is typically used in a microservice architecture.

So any chance of adding this out of the box?

**Comment by tmenier** [comment]
I don't want to add this to the core as it will add library dependencies that most people don't need. I think it's a better fit for an add-on lib, similar to the [Flurl.Http.Xml](https://github.com/lvermeulen/Flurl.Http.Xml). If you're interested in starting a project like that I'd be happy to answer questions along the way and help "advertise" it.

**Comment by natiki** [comment]
Cool. I will create a project similair to that and let you know.
