### ISSUE TITLE
Since #249 ISO 8601 some settings required

### ISSUE THREAD

**Issue by Ganssy** [tmenier/Flurl#367]
Since #249 we can't change datetime format and it force on ISO 8601 can we have some setting for?

[Feature#249](https://github.com/tmenier/Flurl/commit/b9628b12f025ad2f4974accbaca8903adf500b36)

**Comment by tmenier** [comment]
There was no setting for that before #249 either. All I changed was how Flurl formats dates; it was never customizable. Are you requesting a new feature? Please be a little more specific about how you think that should work.
