### ISSUE TITLE
SetQueryParams with collection of KV pairs, duplicate keys should append, not overwrite

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#370]
Flurl allows setting multiple query parameters via object notation, with special handling for things that look like collections of key/value pairs. It's possible that these collections could contain duplicate keys, and in this case every value should be appended. Instead they get overwritten each time, so this test fails:

```c#
var url = "http://foo.com".SetQueryParams(new[] {
    new { key = "x", value = 1 },
    new { key = "x", value = 2 },
});

Assert.AreEqual("http://foo.com?x=1&x=2", url.ToString());
// fail! actual value is http://foo.com?x=2
```
In a nutshell, that should pass.

**Comment by Marusyk** [comment]
It seems to be a breaking changes. Could you please advise if you wanna replace that logic or add some parameter for that? Then I'll try to prepare PR. Thx

**Comment by rcollette** [comment]
In the case where all the values are passed in the single set method and squashed, it seems like an obvious bug to be patched.

**Comment by tmenier** [comment]
I was hoping I could piggyback off existing code to fix this but it's a little trickier than I thought. I'm considering adding `AppendQueryParam(s)` that, unlike `SetQueryParam(s)`, don't overwrite. With that in place this will be much easier.

**Comment by AskYous** [comment]
Hello. Is there any solution to this yet? I would like to have duplicate query parameters.

**Comment by tmenier** [comment]
Although I still think this seems like an obvious quirk, now that I'm pushing it out to 4.0 I'll play it safe and call it breaking. #688 will be a prerequisite.

**Comment by tmenier** [comment]
Now available in prerelease 4 https://www.nuget.org/packages/Flurl/4.0.0-pre4
