### ISSUE TITLE
CommonExtensions.ObjectToKV calls GetValue on set-only properties

### ISSUE THREAD

**Issue by springy76** [tmenier/Flurl#373]
I have an options object purely filled _(1)_ using C#s object initializer syntax where one of the properties only has a setter which assigns multiple values at once _(2)_. The options object then is given to `SetQueryParams` where a `ArgumentException`is thrown: "Property Get method was not found"

Please exclude all properties which don't have a get method.

(1)
`await client.CallAsync(new Options{Multi = fi}, cancellation);`

(2)
```
class Options{
  public string Name {get; set;}
  public long Size {get; set;}
  public FileInfo Multi {
    set
    {
      this.Name = value.Name;
      this.Size = value.Length;
    }
  }
}
```

**Comment by tmenier** [comment]
This sounds legit, thanks for reporting.
