### ISSUE TITLE
Feature request: adding client certificates for 2-way ssl

### ISSUE THREAD

**Issue by andrewrudman** [tmenier/Flurl#376]
Greetings,

Apologies if this has been raised elsewhere, but it would be great if Flurl supported adding of an ssl certificate to a request. Here is an example of how this would be done in RestSharp:

            var client = new RestClient(url);
            client.ClientCertificates = new X509CertificateCollection() { cert };

Is this something that could be done?

**Comment by tmenier** [comment]
Here's how you'd do it:
https://stackoverflow.com/a/41044686/62600

There's no inline/"fluent" way to do it on a request because chances are you need to provide it on every request to that host, so it's something you just need to configure once at startup.

**Comment by andrewrudman** [comment]
Thank you, much appreciated. Flurl rocks, btw.
