### ISSUE TITLE
Encoding Path Segment

### ISSUE THREAD

**Issue by SonOfPear93** [tmenier/Flurl#381]
I am experiencing the exact same issue as this old bug ticket.
https://github.com/tmenier/Flurl/issues/253

Could someone let me know if this is a re-occurrence of the bug, or if I have done something wrong.

More detail can be found here; https://stackoverflow.com/q/52739577/10494808

**Comment by tmenier** [comment]
I am unable to repro what you're seeing. See my my comments in your SO post.

**Comment by tmenier** [comment]
Answered on SO. Not a Flurl bug as it turns out.
