### ISSUE TITLE
Cookies enabled by default?

### ISSUE THREAD

**Issue by matteocontrini** [tmenier/Flurl#383]
While developing I found something weird happening with cookies. If you take this code and run it:

```csharp
HttpResponseMessage resp;

resp = await "https://matteocontrini.it/setcookie.php".GetAsync();
Console.WriteLine(resp.Headers);

resp = await "https://matteocontrini.it/setcookie.php".GetAsync();
Console.WriteLine(resp.Headers);
```

The output will be something like the following. The requested URL is an example PHP script that starts a session.

```
Date: Mon, 12 Nov 2018 21:51:33 GMT
Server: Apache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=ctisr994g7ec7t80cpv4ovtf27; path=/
Upgrade: h2,h2c
Connection: Upgrade

Date: Mon, 12 Nov 2018 21:51:33 GMT
Server: Apache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
```

As you can see, only the first time the `Set-Cookie: PHPSESSID=...` header is set. This is also reproducible using `HttpClient` directly:

```csharp
HttpClient client = new HttpClient();

resp = await client.GetAsync("https://matteocontrini.it/setcookie.php");
Console.WriteLine(resp.Headers);

resp = await client.GetAsync("https://matteocontrini.it/setcookie.php");
Console.WriteLine(resp.Headers);
```

From what I found, this happens because on the second request the cookies created during the first one are sent automatically. While this may be ok when using HttpClient, I thought Flurl required cookies to be enabled manually, calling `EnabledCookies()`.

This seems to happen because `HttpClientHandler.UseCookies` is set to true [by default](https://docs.microsoft.com/en-GB/dotnet/api/system.net.http.httpclienthandler.usecookies?redirectedfrom=MSDN&view=netcore-2.1). If I set that property to false, previous cookies are not sent with the second request, so the `PHPSESSID` cookie is set at each request.

So the question is: is this the intended behaviour in Flurl? I thought that by default requests were independent. What I'm thinking is that with the current behaviour, multiple requests to the same host from different threads could get you to different results if they're run in a different order...

**Comment by tmenier** [comment]
Flurl doesn't change the default setting of the handler. It maintains a `Cookies` dictionary on FlurlClient, and  `EnableCookies()` is just to get that higher-level functionality. There's a little overhead in copying the values back and forth from the headers, which is why it's not "on" by default.

The problems/work-around associated with cookies existing at the client level rather than the request level are documented in #318. I know it's not ideal and it will be fixed in a future release.

**Comment by tmenier** [comment]
@matteocontrini One other thing I forgot to mention - I'm pretty sure I tried disabling cookies at the handler level by default and it complained if I tried to enable it after the first request was sent.  (A lot of handler properties do that.) To me that doesn't play nice with how I wanted `EnabaleCookies` to work, and I'm pretty sure that's the reason I didn't do it.
