### ISSUE TITLE
Allow overriding Exception type in FlurlRequest.HandleExceptionAsync when changed in ClientFlurlHttpSettings.OnError

### ISSUE THREAD

**Issue by trygvelo** [tmenier/Flurl#384]
I am trying to replace HttpClient with Flurl in a project. This project depends on a certain type of Exception being thrown that replaces the regular HttpClient exceptions (with the HttpClient exceptions as InnerException). To avoid duplicating error handling code with a lot of catching of FlurlHttpException's and then build my desired exception, I try to handle this in ClientFlurlHttpSettings.OnError where I build my desired Exception type and set call.Exception to that new Exception object.

However, the Exception thrown in HandleExceptionAsync does not take the call.Exception into consideration, it always throws FlurlHttpException as default. I think throwing call.Exception instead would break a lot of existing code, so is there any other way to solve this?

**Comment by trygvelo** [comment]
Perhaps the best would be to change my custom exception a little bit and inherit from FlurlHttpException. It would then throw that exception in HandleExceptionAsync.

**Comment by tmenier** [comment]
Inheriting from `FlurlHttpException` isn't necessary to do what you want to do so that part is purely optional. The important part (which you figured out) is to _throw_ your custom exception from the global handler, rather than replacing `call.Exception`.
