### ISSUE TITLE
Is http/2 supported?

### ISSUE THREAD

**Issue by hanabi1224** [tmenier/Flurl#385]

**Comment by tmenier** [comment]
Flurl wraps HttpClient, so HTTP/2 is supported only if the targeted platform's version of HttpClient and its underlying HttpMessageHandler support it.

https://stackoverflow.com/questions/32685151/how-to-make-the-net-httpclient-use-http-2-0

In Flurl, the way to ensure a partiular HttpMessageHandler is used is to create a [custom factory](https://flurl.io/docs/configuration/#httpclientfactory).
