### ISSUE TITLE
Appveyor CI is not properly setup

### ISSUE THREAD

**Issue by hanabi1224** [tmenier/Flurl#390]
@tmenier  Tests are failing but not blocking PRs, if you look at latest build:
https://ci.appveyor.com/project/kroniak/flurl/branch/master

Total tests: 286. Passed: 285. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 32.5615 Seconds
Test run for C:\projects\flurl\Test\Flurl.Test\bin\Release\netcoreapp2.0\Flurl.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation. All rights reserved.
Starting test execution, please wait...
Failed ConfigureClient_is_thread_safe
Error Message:
Expected is <System.Int32[4]>, actual is <System.Collections.Generic.List`1[System.Int32]> with 4 elements
Values differ at index [1]
Expected: 2
But was: 3
Stack Trace:
at Flurl.Test.Http.FlurlClientFactoryTests.ConfigureClient_is_thread_safe() in C:\projects\flurl\Test\Flurl.Test\Http\FlurlClientFactoryTests.cs:line 70
Total tests: 286. Passed: 285. Failed: 1. Skipped: 0.
Test Run Failed.

**Comment by hanabi1224** [comment]
fixed in PR: https://github.com/tmenier/Flurl/pull/388

**Comment by tmenier** [comment]
Closing per comments in PR

**Comment by kroniak** [comment]
fixed by #426

**Comment by tmenier** [comment]
Failing test fixed, so I think that resolves this issue?
