### ISSUE TITLE
problem with reusing FlurlClient

### ISSUE THREAD

**Issue by andrewrudman** [tmenier/Flurl#393]
Greetings,

I'm sure i must be missing something pretty obvious, but here is my issue:

I have an IFlurlClientFactory that is registered in an IOC container (Castle.Windsor) using PerBaseUrlFlurlClientFactory>().LifeStyle.Singleton

This gets passed into a service via constructor injection and is used to create a client that is declared at class level: _flurlClient = flurlClientFac.Get(BASE_URL)

The service has a GET and a POST method, both of which use the shared FlurlClient (both have the same base url).
 
The POST method requires a Content-Type header:

               var resp = await _flurlClient
                    .WithHeader("Content-Type", "application/vnd.api+json")

If i call the POST method and then call the GET method, the GET fails with the error "Cannot send a content-body with this verb-type.", which makes perfect sense, as they share the same client which now has the Content-Type header.

How do i ensure that the Content-Type header is only set for the POST method and not the GET?

**Comment by tmenier** [comment]
You want to set the header on the request, not the client:

```c#
await _flurlClient
    .Request("endpoint")
    .WithHeader("Content-Type", "application/vnd.api+json")
    .PostAsync(...);
```

**Comment by andrewrudman** [comment]
Doh! I suspected it would be obvious... Thanks!
