### ISSUE TITLE
Consider adding a SimulateAbort method to HttpTest

### ISSUE THREAD

**Issue by jehof** [tmenier/Flurl#394]
I´m not sure if it could be added, but it would be nice to have a **SimulateAbort** method, similar to **SimulateTimeout**, for tests cases when the server aborts a request. This should result in that we do not have a response. 

Today I tried to track down a NullReferenceException in our system, where a FlurlException did not have a response, cause the server aborted the request. To reproduce this failure I had to run an integrationtest using MockServer, which allowed me to specify an expectation to drop a connection.

I would be glad to run a simple lightweight unittest using HttpTest, to verify such bugs.

**Comment by tmenier** [comment]
What would be the difference between `SimulateAbort` and `SimulateTimeout`? In the real world, the client simply wouldn't receive a response, either after some fixed amount of time (the timeout) or ever if you set the timeout to infinite. `SimulateTimeout` basically just sets that timeout to zero. My guess is you _are_ getting timeouts from the client's perspective (`FlurlHttpTimeoutException` inherits from `FlurlException`, so you're catching both), and `SimulateTimeout` is exactly what you want. Not certain though, I could be missing something here.

**Comment by tmenier** [comment]
I haven't heard back, and I still don't believe the there's a meaningful difference between "abort" and timeout from the client's perspective. If I'm wrong, feel free to reopen.
