### ISSUE TITLE
Missing dispose of timeout CTS

### ISSUE THREAD

**Issue by sacgod** [tmenier/Flurl#395]
Hi,
During my long running test of my dotnetcore source code, I found some really strange memory consumption. After several thousand calls memory goes up to 1Gigs. My first guess I forgot to dispose something, so I created a memory dump.  Dump told me managed heap was less than 100MB. So rest is unmanaged. My code has no direct resource access so they came from somewhere else.

Step-by-step I try to reach my communication model with a simple service.
1, Client to service to service communication with a simple .netcore. It posts JSON object with a default http client.
25000 calls with multi threads on a single client:
- It starts from 77MB than jump up to 290 where GC is triggered (WS GC = 250MB) and reduces it to 130. It more or less ok (my object was huge because my first guess was JSON)

2, Replace http client with default Flurl client.
- It starts from 80MB than jump up to 310 where GC is triggered and reduces it to 260... Hmmm, it is a bit too much for a simple wrapper from my point of view.
![timeouton_virtualsize](https://user-images.githubusercontent.com/20184894/48996044-c7fe3600-f14a-11e8-8990-15dc3deb7f72.jpg)

Let's dump it: 
![timeouton_heapsize](https://user-images.githubusercontent.com/20184894/48996058-dba99c80-f14a-11e8-982b-86e480e8424e.jpg)

Soo... managed heap looks fine. Unmanaged Gotcha...
![timeouton_heap](https://user-images.githubusercontent.com/20184894/48996094-085db400-f14b-11e8-842d-128be86c63d9.jpg)

CancellationTokenSource army which is belongs to a timer. And I replaced only the http client implementation. As far as I remember cancellation system based on reset-events which based on file access which needs unmanaged access.
Cut the story to short, I found a CTS creation in Flurl code. In Flurl request, when client timeout has value.
`if (Settings.Timeout.HasValue) {
    var cts = CancellationTokenSource.CreateLinkedTokenSource(userToken);
    cts.CancelAfter(Settings.Timeout.Value);
    token = cts.Token;
}`

Ok. Set timeout to null and test it.
![timeoutoff_virtualsize](https://user-images.githubusercontent.com/20184894/48996254-b5383100-f14b-11e8-8242-0e05afa73620.jpg)

Bit better.
![timeoutoff_heapsize](https://user-images.githubusercontent.com/20184894/48996263-c1bc8980-f14b-11e8-9f13-9c8a5687cbbf.jpg)

![timeoutoff_heap](https://user-images.githubusercontent.com/20184894/48996273-c719d400-f14b-11e8-8037-d642f6d737b2.jpg)

Hurray, No timer.
I made a small modification on request: Store created CTS in a variable and dispose it  in finally if it is not null. It looks solve this problem.

Workaround: 
- set Flurl timeout to null and set back the HTTPClient timeout. *Warning* WithTimeout calls will behave differently and continue to leak.

**Comment by tmenier** [comment]
Nice detective work, thanks!

Fixed by #396
