### ISSUE TITLE
Support AWS Signature Authentication

### ISSUE THREAD

**Issue by sirdarkstone** [tmenier/Flurl#397]
Would be nice to easily authenticate a request with the AWS Signature:

[https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html)

Despite it's complexity, the AWS Signature has become a standard-enough concept that non-AWS APIs have started using it as well.

I'm not terribly familiar with the Flurl source, so I wanted to open the idea for discussion. If desired, I'm willing to contribute that implementation myself with a little guidance.

**Comment by whoiskevinrich** [comment]
Consider wiring up an HttpClientHandler implementation to add the parts needed for authentication.

**Comment by whoiskevinrich** [comment]
Are there any plans to support DI for Message Handlers?

My biggest hurdle is that my AWS Authentication HttpClientHandler leverages DI for a couple things. With the System.Net.Http.HttpClient, I can do this:

```csharp

                {
                    client.BaseAddress = new Uri(config.MwsResource.BaseAddress);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/xml"));
                })
                // HttpClientBuilderExtension that supports DI
                .ConfigurePrimaryHttpMessageHandler<AwsSignatureV2Handler>();
```

The Flurl.HttpClient allows me to override the HttpMessageHandler, but I have to "new it up"

**Comment by tmenier** [comment]
FlurlClient has a ctor that takes an HttpClient, so that should all be pretty easily wire-able, unless I'm missing something. [This](https://stackoverflow.com/a/51125263/62600) might help as well.

**Comment by tmenier** [comment]
Thanks for the suggestion, unfortunately I still don't think it's ubiquitous enough to warrant baked-in support.
