### ISSUE TITLE
Export to curl

### ISSUE THREAD

**Issue by emmekappa** [tmenier/Flurl#400]
It would be great to have the possibility to export a request in cURL format for diagnostic purpose.

**Comment by tmenier** [comment]
Interesting suggestion. I'm cleaning up the backlog and making some tough decisions, and unfortunately I don't see this making it onto the roadmap anytime soon. To do this in the library where all scenarios are covered, and all of the most common cURL options are supported, would be a substantial undertaking. It would be much easier to just cover the scenarios you need in your app, maybe via an extension method on `FlurlRequest`, or better yet in a `BeforeRequest` [event handler](https://flurl.io/docs/configuration/#event-handlers) where all requests would be caught so you could log them or whatever.

**Comment by marcarl** [comment]
ChatGPT prompt for making this: https://chatgpt.com/share/c2de5234-4c7a-49a7-ba23-853d0a275516
