### ISSUE TITLE
Add support for FileName in  AddFile(string name, string path, string mediaType = null, int bufferSize = 4096) method

### ISSUE THREAD

**Issue by tomasr78** [tmenier/Flurl#402]
There is no way to set file name while uploading file in the method

`CapturedMultipartContent AddFile(string name, string path, string mediaType = null, int bufferSize = 4096);`

Would be useful to have possibility to set uploading file name without renaming actual file.

**Comment by tmenier** [comment]
A possible work-around is to use the [overload](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/Content/CapturedMultipartContent.cs#L99) that takes a stream. I believe the call would looks something like this:

```c#
.AddFile(name, File.OpenRead(path), fileName)
```

**Comment by tomasr78** [comment]
Thank you, I already did that.

**Comment by tmenier** [comment]
I like the suggestion, adding as an optional param.
