### ISSUE TITLE
DownloadFileAsync detect file from content type

### ISSUE THREAD

**Issue by tomasr78** [tmenier/Flurl#403]
I have real examples when file response do not has correct content disposition and file name can't be detected from url. The 3rd option would be to detect file type from content type with default file name.  Are you planning to add it?

https://github.com/tmenier/Flurl/blob/1b072fce15e0bca7f064a2d265fcf49d5125025d/src/Flurl.Http/DownloadExtensions.cs#L25

**Comment by tmenier** [comment]
I think you'd be better off with your own custom extension method here. I'm not sure how Flurl would come up with a "default" filename based on Content-Type. Even the extension would be best-guess in many cases, and to be complete Flurl would need to contain knowledge of [all known media types](https://www.iana.org/assignments/media-types/media-types.xhtml) mapped to (best-guess) file extensions. I think it's better left to you to come up with rules that make the most sense for your application.
