### ISSUE TITLE
FLurl caching httpclient by endpoint

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#409]
I just started using FlUrl and I'm facing the same misunderstanding as here.

https://github.com/tmenier/Flurl/issues/378

 In HTTPClient, I set a base url and reuse httpclient with Base Address, and path1 and path2 being different.

HttpClient client = new HttpClient;
client.BaseAddress = new Uri("http://basesurl/");
HttpResponseMessage response = await client.GetAsync("path1");
HttpResponseMessage response = await client.GetAsync("path2");

From what I'm seeing (correct me if I'm wrong), Flurl is caching baseurl/path1 and baseurl/path2 separately so I can't store 1 single instance of HttpClient for baseurl for all the endpoints. Each endpoint will be opening a new connection?

**Comment by tmenier** [comment]
That's not at all how it works, I'm not sure where you're seeing that. Per the [documentation](https://flurl.io/docs/client-lifetime/), Flurl.Http caches and reuses a single `HttpClient` instance _per host_.

**Comment by tmenier** [comment]
Closing this issue, but feel free to reopen if this doesn't answer your question.
