### ISSUE TITLE
JsonProperty ignored in PostJsonAsync

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#416]
I have a optional variables when doing PostJsonAsync. Using HttpClient, I can choose NetwonSerializeSettings with NullValueHandling.Ignore. With Flurl, I get an exception thrown saying one other parameters cannot be null.

When I do serialize/deserialize, I provide both with strict/non strict versions. I would assume ReceivedJSON are also strict only. For PostJsonAsync, can you provide string overload?

```
    public class UserAccountRegisterNetworkRequest
    {
        [JsonProperty (Required = Required.DisallowNull)]
        public string                                                       Email;

        [JsonProperty (Required = Required.DisallowNull)]
        public string                                                       Phone;

        [JsonProperty (Required = Required.Always)]
        public string                                                       Password;
    }
```

**Comment by tmenier** [comment]
> Using HttpClient, I can choose NetwonSerializeSettings with NullValueHandling.Ignore.

Where are you doing this? Can you provide an example? I'm trying to understand whether this is really a bug or a feature request.

**Comment by imtrobin** [comment]
This is my own newtonjson serializer/deserializer class with httpclient. I'm switching to flurl as it looks much cleaner.

The bug is flurl did not respect my json Required.DisallowNull attribute

The feature request is having both optional/strict serialize/deserialize  e.g ReceiveJsonStrict/ReceiveJsonNonStrict versions

**Comment by tmenier** [comment]
**If this is a bug**, I'd still like to see what you're doing in your own serializer (your _actual code_) where you're getting it to respect the `DisallowNull` attribute. Then we can easily compare that to Flurl see what's different. Flurl's [default implementation]() is dead simple - it basically defers all work to Json.NET. So I don't know how Flurl could have a bug with one random Json.NET property. Please help me figure that out.

**If you can get the behavior you want to through tweaks to [JsonSerializerSettings](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonSerializerSettings.htm)**, you're in luck. Flurl can easily be configured globally with custom serializer settings, and there's an [example](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonSerializerSettings.htm) in the docs of how to do that.

If that still doesn't cover what you're looking for, you can completely customize the serializer by creating a class that either inherits from `NewtonsoftJsonSerializer` or implements `ISerializer` from scratch. (See both links above for help with that.)

In the interest of not bloating the API, I'm going to decline adding ReceiveJsonStrict/ReceiveJsonNonStrict methods to the core. I think you can achieve what you want by customizing the serializer as described above, or if you need the behavior to be different on a call by call basis, implement these as extension methods for your own use.

**Comment by tmenier** [comment]
> The bug is flurl did not respect my json Required.DisallowNull attribute

I tested this and it should looks to me like it works.

```c#
public class Foo
{
    [JsonProperty(Required = Required.DisallowNull)]
    public string x { get; set; }

    [JsonProperty(Required = Required.DisallowNull)]
    public string y { get; set; }
}

[Test]
public async Task disallow_null() {
    using (var test = new HttpTest()) {
        // Fails with Newtonsoft.Json.JsonSerializationException
        await "http://some-api.com".PostJsonAsync(new Foo { x = "x", y = null });

        // Fails with Flurl.Http.FlurlParsingException,
        // where InnerException is Newtonsoft.Json.JsonSerializationException
        test.RespondWithJson(new { x = "x", y = (string)null });
        var foo = await "http://some-api.com".GetJsonAsync<Foo>();
    }
}
```

That's not a proper unit test of course - I just wanted to see if an exception gets thrown on serialization and deserialization when I run it, and as noted it does. What am I missing? Can you write a similar test the repros the bug?

**Comment by imtrobin** [comment]
Remove y. It should be valid

DisallowNull - The property is not required but it cannot be a null value.

**Comment by tmenier** [comment]
Ok, I removed y in both cases (sending and receiving) and no exception was thrown:

```c#
[Test]
public async Task disallow_null() {
    using (var test = new HttpTest()) {
        // does NOT throw
        await "http://some-api.com".PostJsonAsync(new { x = "x" });

        // does NOT throw
        test.RespondWithJson(new { x = "x" });
        var foo = await "http://some-api.com".GetJsonAsync<Foo>();
    }
}
```

The [documented](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Required.htm) behavior of `DisallowNull` is that if the property is included and has a value of `null`, an exception is thrown. But if the property is excluded entirely, no exception is thrown. My tests prove this works exactly as expected.

**Comment by imtrobin** [comment]
Hmm, I'm using flurl in Unity3D, and mine throws with 

Error:Cannot write a null value for property 'y'. Property requires a non-null value. Path ''.

It's using mono with a modified newtonjson. I will check the newtonjson default settings. It might be different, thanks for confirming.

**Comment by imtrobin** [comment]
I tested with json.net c# , it throws too. Then I realize, I'm testing the wrong thing. The DisallowNull is for deserialization, it is throwing on the serialization ,which we should specify in NullValueHandling.

The default is NullValueHandling = true,  DefaultDefaultValueHandling = true, so it should throw. Your test didn't throw, means it has changed the defaults or it is indeed a bug somewhere. I couldn't find in the flurl source where you changed the default so I'm not sure why it did not throw.

In Flurl, I have to pass the serializersettings to Configure everytime, which in my own serializer, I cache the settings and provides these extensions as they are really common usage.

SerializeIncludeNull
SerializeExcludeNull
DeserializeStrict
DeserializezNonStrict

**Comment by tmenier** [comment]
> Your test didn't throw, means it has changed the defaults or it is indeed a bug somewhere.

Again, the meaning of `DisallowNull` is that _**it's ok to exclude the property entirely; you just can't include it with a null value**_. That is why my first test throws with `y = null` and my second test does not throw with `y` excluded from the object.

100% of the code that serializes/deserializes JSON (and 100% of Flurl's interaction with Json.NET) is here:

https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/Configuration/NewtonsoftJsonSerializer.cs

As you can see, there's not much there. Flurl [instantiates](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/Configuration/FlurlHttpSettings.cs#L215) that object with null `settings`, meaning it'll use global defaults. Flurl does not provide its own settings or change the global defaults in any way. If you want different behavior, [Flurl provides ways to do that](https://flurl.io/docs/configuration/#serializers).

There is no bug here. I've shown that through tests and that's why I closed this issue.

**Comment by imtrobin** [comment]
I just did a console test on plain newton json only, by default it throws.
```
using Newtonsoft.Json;
namespace TestConsole
{
    public class Foo
    {
        [JsonProperty(Required = Required.DisallowNull)]
        public string x { get; set; }

        [JsonProperty(Required = Required.DisallowNull)]
        public string y { get; set; }
    }

    class TestConsoleMain
    {
        static void                                                   Main (string [] args)
        {
            Foo f = new Foo{x = "test" };
            string s = Newtonsoft.Json.JsonConvert.SerializeObject (f);
        }
    }
}
```
I had to add a serializersetting to allow it to serialize without y. But this breaks the DisallowNull

```
 string s = Newtonsoft.Json.JsonConvert.SerializeObject (f, new JsonSerializerSettings {
                     NullValueHandling       = NullValueHandling.Ignore,
                     DefaultValueHandling    = DefaultValueHandling.Ignore });
```
