### ISSUE TITLE
Does Flurl.Http uses HttpClientFactory from .Net Core 2.1?

### ISSUE THREAD

**Issue by MNF** [tmenier/Flurl#418]
As I know, Flurl.Http support reuse of HttpClients.   
However ms HttpClientFactory also implements an  lifetime of 2 minutes to rotate them so that DNS doesn’t get stale. Does Flurl.Http address such issue? If not, are you planning to implement something similar?

Reference article 
https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore

**Comment by tmenier** [comment]
Flurl doesn't need to address it. That stuff happens in the new `SocketsHttpHandler`. If you're targeting .NET Core 2.1, you're getting it automatically.

https://stackoverflow.com/questions/51037357/flurl-client-lifetime-in-asp-net-core-2-1-and-ihttpclientfactory
