### ISSUE TITLE
Get Body

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#419]
Hi, I'm trying to do a GET with body but it seems it's not really supported. This fails to run with protocal violation error

await "url".SendJsonAsync (HttpMethod.Get, jsonData).ReceiveJson<T> ();

Postman allows GET with body now, after much debate.

**Comment by imtrobin** [comment]
my bad, is working

**Comment by imtrobin** [comment]
reopening issue

**Comment by tmenier** [comment]
Please provide the full exception details and stack trace. In my tests, sending a GET request with a body works just fine.

**Comment by imtrobin** [comment]
I'm using Unity3d on a modified jsondotnet to support AOT. This is the error

HTTP Error:Call failed. Cannot send data when method is: GET GET http://192.168.1.99:7071/api/localize
Method: GET, RequestUri: 'http://192.168.1.99:7071/api/localize', Version: 1.1, Content: Flurl.Http.Content.CapturedJsonContent, Headers:

And the code is

            Dictionary<string, string> d = await "http://192.168.1.99:7071/api/test".SendJsonAsync (HttpMethod.Get,
                                                                                                                       new List<string> { "x",
                                                                                                                                        "y",
                                                                                                                                        "z"
                                                                                                                                          }).ReceiveJson ();

but it seems the issue is with httpclient, it works on .dotnetcore only? How did you get your test to work?

https://stackoverflow.com/questions/43421126/possible-for-httpclient-to-send-content-or-body-for-get-request

**Comment by tmenier** [comment]
Yes, I most likely tested in on .NET Core. Hmm, it doesn't look like there's a work-around on .NET Framework. It's very unusual to want to send a GET request with a body, but if you have no control over that, the only option I can think of is to move to .NET Core. Flurl wraps HttpClient and I don't know of a work-around for that.

**Comment by imtrobin** [comment]
Yes, looks like we can't do anything about it. I didn't think there would be a difference with dotnet core vs framework. We can close this, thanks.
