### ISSUE TITLE
GetAsync() text get cut off

### ISSUE THREAD

**Issue by fvermeulen** [tmenier/Flurl#42]
Hello @tmenier 
I have a problem by using the flurl httpclient. It won't download the complete data.

> var httpClient = new HttpClient();
> var test = await httpClient.GetAsync("http://rebuy.de");
> var testResponse = await test.Content.ReadAsStringAsync();
>
> var flurl = await "http://rebuy.de".GetAsync();
> var flurlResponse = await flurl.Content.ReadAsStringAsync();

Compare the two strings. `testResponse` has 57697 letters and `flurlResponse`has 32397 letters.

Can you help me with that problem?

**Comment by fvermeulen** [comment]
When i comment these lines out, everything works correctly
https://github.com/tmenier/Flurl/blob/98b32d257bef5ed4098e652a33cfddd41b6d743c/Flurl.Http.Shared/Configuration/FlurlMessageHandler.cs#L58-59

But don't know what is happening in this method

**Comment by tmenier** [comment]
I tested this and the responses were identical for me except for a couple time-related javascript variables at the bottom, which would make sense. Search your code for `FlurlHttp.Configure` to see if any global callbacks are registered, such as `AfterCall`, which could be used to manipulate the response. See [here](http://tmenier.github.io/Flurl/configuration/) for details.

As a side-note, the last 2 lines in your sample could be reduced to:
```c#
var flurlResponse = await "http://rebuy.de".GetStringAsync();
```

**Comment by tmenier** [comment]
Closing this issue as I do not believe there is a bug here.
