### ISSUE TITLE
SetQueryParams Doesn't add second param

### ISSUE THREAD

**Issue by no-stupid-questions** [tmenier/Flurl#421]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.

I'm trying to make a URL with two params, when I test the results for the url I get the first param and not the second one in the url. My code goes something like this:

`
String urltest = "http://" + _ip + ":" + _port;
                var URL = urltest
                                    .AppendPathSegment("coolservice/api")
                                    .SetQueryParams(new { operation = destOpStr, key = _securityKey }); 

`
(destOPStr is just a json string)
the output i expect is "http://<IP>:<PORT>/coolservice/api?operation={"id":1,"name":"jo"}&key=123"
but instead the output is just "http://<IP>:<PORT>/coolservice/api?operation={"id":1,"name":"jo"}"

**Comment by tmenier** [comment]
Is `_securityKey` null? If so it will exclude the entire parameter.

This test passes for me:

```c#
var url = "http://foo.com".SetQueryParams(new { operation = "{\"id\":1,\"name\":\"jo\"}", key = "xyz" });
Assert.AreEqual("http://foo.com?operation=%7B%22id%22%3A1%2C%22name%22%3A%22jo%22%7D&key=xyz", url.ToString());
```

**Comment by no-stupid-questions** [comment]
Thanks that was it! :D
I running low on IQ at the moment, but hopefully ill full up and not miss those details again.
