### ISSUE TITLE
Missing method "System.Net.Http.HttpRequestMessage.get_RequestUri()" on Windows 10

### ISSUE THREAD

**Issue by sibbl** [tmenier/Flurl#43]
When using the library in a Universal Windows Project, I always get the MissingMethodException `System.Net.Http.HttpRequestMessage.get_RequestUri()` when calling `"http://foo.bar/test.txt".GetStringAsync()`.

Is Windows 10 support planned for the library or am I doing something else wrong?

**Comment by tmenier** [comment]
I don't have Windows 10 (yet) so I don't know how much help I can be. Can you post a full stack trace? If you are able to figure this out I'd gladly accept a pull request.

**Comment by tmenier** [comment]
I believe the latest version supports Windows 10 apps. Can you confirm? cc @kroniac

**Comment by kroniak** [comment]
@tmenier NET Platform Standard 1.5 supports win10.

**Comment by kroniak** [comment]
@sibbl please check last beta version on https://www.myget.org/F/flurl/api/v3/index.json

**Comment by tmenier** [comment]
Prerelase containing this fix is now available:

https://www.nuget.org/packages/Flurl.Http/1.0.0-beta7

Please test and provide any feedback.
