### ISSUE TITLE
Expose the base url to IHttpClientFactory

### ISSUE THREAD

**Issue by jonsa** [tmenier/Flurl#431]
I work on a system which queries multiple systems, one of which uses a self-signed certificate. To tackle this I've created my own `IHttpClientFactory` to set `ServerCertificateCustomValidationCallback` on the handler to identify the certificate and approve it. The problem with this is that it makes the requests fail when querying servers with proper certificates. This forces me to re-implement one of two existing wheels; validation of proper certificates or the life-cycle of `HttpClient` which exists in `Flurl`.

So my proposed change would be to add a `string` argument to `IHttpClientFactory.CreateMessageHandler`
```c#
public interface IHttpClientFactory
{
    HttpClient CreateHttpClient(HttpMessageHandler handler);

    HttpMessageHandler CreateMessageHandler(string baseUrl);
}
```

I'm leaning towards implement my own `IFlurlClientFactory` and eagerly resolve the `HttpMessageHandler` and modify it during the client creation but that seems more of a hack.

**Comment by tmenier** [comment]
I think a combo of a custom `IHttpClientFactory` (let's call it `SignedCertFactory`) and a custom `IFlurlClientFactory` is the way to go. The code for both would be pretty minimal and hackish at all, especially if you inherit from one of Flurl's implementations. `PerHostFlurlClientFactory` is probably best:

```c#
public class MyFlurlClientFactory : PerHostFlurlClientFactory
{
    protected override IFlurlClient Create(Url url) {
        var fc = base.Create(url);
        if (url.ToUri().Host == "selfsign.com")
            fc.Settings.HttpClientFactory = new SignedCertFactory();
        return fc;
    }
}
```

**Comment by jonsa** [comment]
Yeah, I implemented something similar. Will try the `HttpClientFactory` on the client settings instead of resolving the `HttpMessageHandler` eagerly, I must have missed it in the documentation since it's clearly there in the [configuraiton settings](https://flurl.io/docs/configuration/#configuring-settings).
