### ISSUE TITLE
url AddHeader runtime

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#432]
I need to build the url header programtically at runtime, and I discovered this does not work properly.

```
Url url = "https://xxx";
url.WithHeader ("x", "y"); // this fails because its a new object
string response = await url.GetStringAsync ();

```

**Comment by tmenier** [comment]
A header is not part of a URL, it's part of an HTTP request. So in my mind it doesn't make sense to store an HTTP header on a `Url` object. The "new object" you're referring to is a `FlurlRequest`, which is the container for request headers. Capture that and use it in your request and this will work fine:

```c#
Url url = "https://xxx";
var request = url.WithHeader("x", "y");
string response = await request.GetStringAsync();
```

**Comment by imtrobin** [comment]
Yes, I figured that out after looking at the source. It's a bit challenging to debug because I was working in unity3d and there is no debugger, and there is things lilke AppendPathSegment which works.
