### ISSUE TITLE
Support Newtonsoft.Json v11.0.2

### ISSUE THREAD

**Issue by IGx89** [tmenier/Flurl#445]
Your latest release dropped support for Newtonsoft.Json v11.0.2. That typically wouldn't be a problem, but due to https://github.com/Azure/azure-functions-host/issues/4049 any Azure Function apps are now unable to use your latest version. Since I'm assuming you didn't bump the minimum supported version of Newtonsoft.Json for any functional reasons, would you be able to revert it back to v11?

This isn't a high priority for me since 2.4.1 is working just fine, but figured I'd let you know and ask anyway :)

Thanks!

**Comment by tmenier** [comment]
Hmm, yeah, they're always a little behind. I'm probably not following best practices on dependency versions, I'll look into that. For now though I agree that 2.4.1 is your best bet. 2.4.2 literally only included an obscure bug fix (#437) and the Json.NET upgrade.
