### ISSUE TITLE
FlurlHttpException lacks non-async GetResponse

### ISSUE THREAD

**Issue by michaelkhalsa** [tmenier/Flurl#446]
VB.net in framework 4.7.2 on Visual Studio 2019 does not support await within catch block
Thus for FlurlHttpException this is impossible

Catch ex As FlurlHttpException
Dim s = Await ex.GetResponseStringAsync()
...

Flurl 2.8.2
Flurl.Http 2.4.2
There are non-eloquent workarounds, however would be nice to have it back for vb.net code

**Comment by tmenier** [comment]
That's disappointing about VB, but I don't want to go back to making that a synchronous call. The way I had to do it previously without blocking was to eagerly read the response stream before throwing the exception, which isn't the most efficient.

The work-around is to use `AllowAnyResponseStatus` (or [similar](https://flurl.dev/docs/error-handling/#allowing-non-2xx-responses)), check the status on the response, and deserialize it differently depending on whether it was a successful response. #354 will make this easier, and it's a top priority for 3.0.
