### ISSUE TITLE
Flurl not working in blazor, httpclient working

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#449]
Reporting the error with  test project

https://github.com/aspnet/AspNetCore/issues/10417

**Comment by tmenier** [comment]
This is a known issue. See [here](https://stackoverflow.com/a/52526415/62600) for the fix.

**Comment by imtrobin** [comment]
Thanks, it works with simple mocky test, but when I tried with azure functino with headers or query parameters, it did not work. I added the details in above link.

**Comment by datvm** [comment]
The solution there does not work for my latest 3.0 preview 5 (`BrowserHttpMessageHandler` is no longer there, the Url is 404). Here is what I currently use, work as far as what I need, but wonder what's the catch:

```
    class BlazorHttpClientFactory : DefaultHttpClientFactory
    {

        public override HttpClient CreateHttpClient(HttpMessageHandler handler)
        {
            return new HttpClient();
        }

        public override HttpMessageHandler CreateMessageHandler()
        {
            return null;
        }

    }
```

**Comment by tmenier** [comment]
@imtrobin Try the fix proposed by @datvm. If it still doesn't work, please provide details on "doesn't work", i.e. a stack trace of specific incorrect behavior.

**Comment by imtrobin** [comment]
I think I found the issue, it's a COR problem on azure function, I will consider this solved. Flurl is confirmed working fine with blazor
