### ISSUE TITLE
Failing installation of Flurl.Http on any non-PCL Xamarin.iOS project

### ISSUE THREAD

**Issue by fex80** [tmenier/Flurl#45]
#### Problem
When I try to add Flurl.Http to any Xamarin.iOS project using NuGet on Visual Studio and Xamarin Studio, the installation fails with the message `Unable to resolve dependency 'Microsoft.Bcl.Build (≥ 1.0.14)'.`

When I install it on a PCL project, it works, however.

#### Expected Behavior
I'd like the installation to work for non-PCL Xamarin.iOS project, too. 

#### Proposed Solution
I suppose the plain .NET 4.5 Flurl.Http would work just fine on Xamarin.iOS. Yet, the current NuGet configuration tries to enforce additional PCL-dependencies on Xamarin.iOS projects – and this fails. 

Thus I believe it should be possible to just make monotouch use the .NET 4.5 version and be done with it. Haven't tried it, yet, though I will.

**Comment by tmenier** [comment]
Thanks for the fix!

**Comment by tmenier** [comment]
Don't know where my head was when I finished this but apparently I never pushed/published it. It's ready now:

https://www.nuget.org/packages/Flurl.Http/0.6.4
