### ISSUE TITLE
SetQueryParam encoding error

### ISSUE THREAD

**Issue by tomvo12** [tmenier/Flurl#450]
I use Flurl to send a POST request to an API service. One of the query parameters is a user display name containing special characters, e.g. "Nuñez". When PostAsync is executed, an exception with the following message text is generated: "Cannot create a Request. Neither BaseUrl nor the first segment passed is a valid URL."

When I replace the name with "Nunez", so skipping the special character, everything works fine.

Encoding manually didn't help, just telling Flurl the name was already encoded didn't work either. The exception is created in all these trials.

**Comment by tmenier** [comment]
Please provide a test or [minimal example](https://stackoverflow.com/help/reprex) that reproduces this. Thanks.

**Comment by tomvo12** [comment]
I'm sorry. I couldn't reproduce with a test. The error had to do with caching of IFlurlRequests.

**Comment by tmenier** [comment]
Ah, yes I could see that getting you into trouble. A FlurlRequest is cheap/disposable/use-once thing. you would not want to cache/reuse it.
