### ISSUE TITLE
Disable follow redirects

### ISSUE THREAD

**Issue by dagostinelli** [tmenier/Flurl#451]
Feature Request: Add ability to not follow redirects.

Example:
`.DisallowFollowRedirects()`

**Comment by tmenier** [comment]
I don't believe there's a way to do this on a _per request_ basis, if that's what you're suggesting. The `HttpClient` stack that Flurl is built on doesn't support it. If you want to disable redirects for all calls, that's fairly simple. [Create and register a custom HttpClientFactory](https://flurl.dev/docs/configuration/#httpclientfactory) that overrides `CreateMessageHandler` and [turn off auto-redirect](https://stackoverflow.com/a/10647245/62600) there.

**Comment by tmenier** [comment]
Thanks for the suggestion but declining due to the reasons mentioned above.
