### ISSUE TITLE
ToString vs implicit conversion

### ISSUE THREAD

**Issue by voroninp** [tmenier/Flurl#454]
Methods like `AppendPathSegment` accept arbitrary values and internally call `ToString`.
However, type hierarchy may contain implicit string conversion operator.

For example I use wrappers for ids:

`UserId` wraps `Guid`, `CountryId` wraps `int`, etc.

The base class contains implementation of `ToString` and implicit conversation operator:

```CSharp
public static implicit operator String(EntityId<TEntity, TId> id) => 
    string.Format(CultureInfo.InvariantCulture, "{0}", id is null ? null : (object)id.Value);

public override string ToString() => $"{GetType().Name}({Value})";
```
So the question is which one should be preferred in case both exist?

**Comment by tmenier** [comment]
Interesting question. Maybe it's just academic but I'll start by saying that having an implicit string conversion and a `ToString` that behave differently would probably not be considered a good practice.

I got curious though and did some testing. Given this class:

```c#
public class Foo
{
    public static implicit operator string(Foo f) => "implicit";
    public override string ToString() => "tostring";
}
```
Let's say you have an instance `foo` that you want to append it to a URL. Without Flurl, I can think of a few ways to do it:

```c#
var s1 = "path/" + foo;
var s2 = $"path/{foo}";
var s3 = string.Format("path/{0}", foo);
var s4 = new StringBuilder().Append("path/").Append(foo).ToString();
```

If I print those out, here's what I get:

```
path/implicit
path/tostring
path/tostring
path/implicit
```

Conclusion: Hard to say what Flurl "should" do. I don't think there's a strong argument for changing it though. I think it does however support my original statement that having those 2 behave differently can lead to some confusing outcomes.
