### ISSUE TITLE
FlurlHttpException  does not have GetResponseJson()

### ISSUE THREAD

**Issue by kgbuddhima** [tmenier/Flurl#456]
catch (FlurlHttpException ex) {
    // For error responses that take a known shape
    TError e = ex.GetResponseJson<TError>();

    // For error responses that take an unknown shape
    dynamic d = ex.GetResponseJson();
}
 I used this but it says FlurlHttpException  does not have a definition for GetResponseJson.

And to add the TError, it asks to insert Mono.Android.dll as a reference . So what should be the correct names that I have to import ?

**Comment by tmenier** [comment]
This was changed to async a while back, so the new method is `GetResponseJsonAsync` and you need to `await` it.

**Comment by kgbuddhima** [comment]
await GetResponseJsonAsync () worked . Thanks !
