### ISSUE TITLE
Support xUnit and rewrite test for it

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#459]
@tmenier  and @kroniak decided support xUnit as main test framework

**Comment by tmenier** [comment]
@kroniak If you choose to work on this soon, be sure and pull latest from dev, or just avoid the URL builder tests for now. I just pushed some significant restructuring of those tests and don't want to set you up for a merge headache. :)

**Comment by SeanKilleen** [comment]
Per my comment: https://github.com/tmenier/Flurl/issues/695#issuecomment-1185080032

I don't see any reason why you should _have_ to switch test frameworks. But if you'd _like_ to, I'd be up for helping to make that happen.

**Comment by tmenier** [comment]
@SeanKilleen Thanks for the offer, but I decided to stick with NUnit. At the time we first started kicking the idea around it seemed like NUnit was on the decline. I don't get that impression anymore, likely thanks to people like you, so I see no good reason to switch. :)

**Comment by michael-freidgeim-webjet** [comment]
Should 4.0 label be removed,as it wasn’t implemented?
