### ISSUE TITLE
dev branch  last Commits on Aug 4, 2019 ,code can't compile

### ISSUE THREAD

**Issue by try3** [tmenier/Flurl#461]
![image](https://user-images.githubusercontent.com/17698581/63013378-b5858180-bebe-11e9-91ab-feda0f6dd367.png)

**Comment by tmenier** [comment]
Oops. I've been doing incremental commits of a major new set of features but if I pushed broken code I certainly didn't mean to. Will fix soon.

**Comment by tmenier** [comment]
Build should be working now. Go ahead and reopen if you're still seeing issues.
