### ISSUE TITLE
False negatives with Url.IsValid

### ISSUE THREAD

**Issue by tomasr78** [tmenier/Flurl#462]
The `SetQueryParam `method produces "**Cannot create a Request. Neither BaseUrl nor the first segment passed is a valid URL.** " exception on some strings like

`var uri = "http://myhost.com/upload".SetQueryParam("name", "Dedant-Simon - ELR & Hollange - IPESS Ougrée pg.2.jpg")`

The exception is throw on POST 

            using (var client = new FlurlClient(uri))
            {
                fileUploadResultDto = client.Request()
                    .WithHeader("accept", "application/json")
                    .PostMultipartAsync(p =>
                    {
                        var fileStream = file.OpenRead();
                        p.AddFile(fileName, fileStream, fileName, GetMimeType(Path.GetExtension(fileName)));
                    })
                    .ReceiveJson<FileUploadResultDto>().Result;
            }

If I replace the string "Dedant-Simon - ELR & Hollange - IPESS Ougrée pg.2.jpg" with simple one everything works fine.

**Comment by tmenier** [comment]
Sorry for the delay. This appears to be legit. The error is thrown from `FlurlClient.Request` when it does not have a valid absolute URI to use as a starting point. Under the hood it uses [Uri.IsWellFormedUriString](https://docs.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring) to make that determination.

```c#
Assert.IsTrue(Uri.IsWellFormedUriString("http://myhost.com/%26", UriKind.Absolute)); // pass
Assert.IsTrue(Uri.IsWellFormedUriString("http://myhost.com/%C3%A9", UriKind.Absolute)); //pass
Assert.IsTrue(Uri.IsWellFormedUriString("http://myhost.com/%26%C3%A9", UriKind.Absolute)); //fail
```

WTF.

After doing some searching I found this:

https://github.com/dotnet/corefx/issues/19630

[This comment](https://github.com/dotnet/corefx/issues/19630#issuecomment-480948012) seems to nail it exactly - it's the _combination_ of different types of encoded characters that seems to trigger the false negative.

I'll keep this open but I'm not quite sure what to do about it yet. Hopefully you have a work-around for now.

**Comment by tmenier** [comment]
[This](https://stackoverflow.com/a/43871973/62600) might be the answer, i.e. testing it in its unescaped form.

**Comment by julian94** [comment]
We had this same issue, and what we did as a workaround as to explicitly make a FlurlRequest instead of just making the request from the string.
I.e: 
`new FlurlRequest(url).WithClient(new FlurlClient(Http)).AllowAnyHttpStatus().WithBasicAuth(username, password).GetAsync()`
instead of:
`url.WithClient(new FlurlClient(Http)).AllowAnyHttpStatus().WithBasicAuth(username, password).GetAsync()`

**Comment by bluewalk** [comment]
This one seems to be back in 3.x? Haven't had any problems with the 2.x builds but since 3.x this error is thrown, using the same code @julian94 mentions (second line)

**Comment by tmenier** [comment]
@bluewalk This is an open issue that hasn't been fixed. If you have a specific example of a scenario that works in 2.x and not 3.x, please provide it.

**Comment by bluewalk** [comment]
@tmenier Of course, you can actually the diff from a project below to see which changes I had to make to get it to work with 3.x

https://github.com/bluewalk/lidlplus-dotnet-client/commit/786f2181c8a9261e3a90360130d5b228294f9cb7

**Comment by kemsky** [comment]
This is definetely a problem:

```csharp
        [Test]
        public void TwoParamsEncoded()
        {
            var url = Url.Parse("https://www.google.com");

            url.SetQueryParam("name", Url.Encode("á"), isEncoded: true);

            url.SetQueryParam("email", Url.Encode("@"), isEncoded: true);

            Assert.That(Url.IsValid(url), Is.True); // fails
        }
```

Literally out of nowhere...

**Comment by tmenier** [comment]
Bummer, I was hoping MS would fix this in .NET 6 but apparently [that won't happen](https://github.com/dotnet/runtime/issues/21626#issuecomment-961668592).

**If you've run into this issue, please [upvote this one](https://github.com/dotnet/runtime/issues/21626).**

**Comment by tmenier** [comment]
More examples reported in #717:

```c#
var x1 = Url.IsValid("http://www.example.com?q=® ts"); // false
var x2 = Url.IsValid("http://www.example.com?q=®ts"); // true
var x3 = Url.IsValid("http://www.example.com?q=%C2%AE%20ts"); //false
var x4 = Url.IsValid("http://www.example.com?q=%C2%AEts"); // true
```

**Comment by tmenier** [comment]
.NET team [reported](https://github.com/dotnet/runtime/issues/72632#issuecomment-1584634895) this won't get fixed in .NET 8 either. A work-around may be something along the lines of what was done in #761 but we're not quite there.

**Comment by tmenier** [comment]
I think somewhere along the line I lost sight of [this advice](https://github.com/dotnet/runtime/issues/72632#issuecomment-1192686739):

> The method should NOT be called at all in 99.9% cases. Uri.TryCreate will be sufficient for all of these 99.9% cases.

I agree! And the [implementation](https://github.com/tmenier/Flurl/blob/dev/src/Flurl/Url.cs#L682-L688) was much simpler than I thought it needed to be. I'm hoping this puts the issue to rest.

**Comment by Janek91** [comment]
Can we get pre-release nuget with that fix, please?

**Comment by tmenier** [comment]
yes, soon

**Comment by tmenier** [comment]
Now available in prerelease 4 https://www.nuget.org/packages/Flurl/4.0.0-pre4

**Comment by sgf** [comment]
> We had this same issue, and what we did as a workaround as to explicitly make a FlurlRequest instead of just making the request from the string. I.e: `new FlurlRequest(url).WithClient(new FlurlClient(Http)).AllowAnyHttpStatus().WithBasicAuth(username, password).GetAsync()` instead of: `url.WithClient(new FlurlClient(Http)).AllowAnyHttpStatus().WithBasicAuth(username, password).GetAsync()`

This method does not solve the problem at the root because the URL may be passed in from the outside.
