### ISSUE TITLE
Response to clear cookie, but not cleared in FlurlClient

### ISSUE THREAD

**Issue by arisliang** [tmenier/Flurl#463]
I was trying login / logout function, and noticed after logout, the cookie in the FlurlClient still present.

Step 1: login and get the session cookie `sessioncookie`
This step is successful
Step 2: logout to clear session cookie
Server has responsed to clear cookie by `sessioncookie=`.
This step is not as expected, because the `sessioncookie` is still present.

The logout api worked with browser, but not with FlurlClient.

Flurl version: 2.8.2
Flurl.Http version: 2.4.2

**Comment by tmenier** [comment]
When you say `sessioncookie` is still "present", does it still have the original value or has it been reset to an empty string?

**Comment by arisliang** [comment]
It has the present value.

**Comment by tmenier** [comment]
Closing because cookies are completely revamped in 3.0 and I won't be fixing any more cookie bugs in 2.x. Have a look at #506, and if you have a chance to test the latest prerelease and leave feedback in that issue, that would be great.
