### ISSUE TITLE
HttpTest Overwrites Existing AfterCall Handler

### ISSUE THREAD

**Issue by carolynvs** [tmenier/Flurl#47]
It would be nice if HttpTest did not overwrite the existing AfterCall handler. Perhaps it could check if an existing handler is in place, and call it as well?

```csharp
public HttpTest() {
  FlurlHttp.Configure(opts => {
	opts.HttpClientFactory = new TestHttpClientFactory(this);
	Action<HttpCall> existingAfterCall = opts.AfterCall;
        opts.AfterCall = call =>
        {
            CallLog.Add(call);
             if (existingAfterCall != null)
                existingAfterCall(call);
         };
```

If you agree, I am happy to submit a pull request with tests.

**Comment by tmenier** [comment]
Going back over some issues I've been sitting on forever (sorry!). If you still want it I think I'd accept this PR, though I may want to think about making it configurable.

**Comment by carolynvs** [comment]
No worries, I ended up needing more customization than just this and just subclassed `HttpTest`. So I don't really need this fix anymore. Feel free to close this issue. 😄
