### ISSUE TITLE
Support for deserialization to type

### ISSUE THREAD

**Issue by Floyddotnet** [tmenier/Flurl#471]
Sometimes you only know the type of the JSON object at runtime. In this case, you cannot provide a generic type. Using the dynamic versions is also not an option because you maybe have attributes on the models.

What we need is an overload of `HttpResponseMessage.ReceiveJson` accepts a `Type` as a parameter and returns `Task<object>`.

**Comment by tmenier** [comment]
Sorry, I don't see this being widely useful enough to warrant the bloat to the library. I think keeping this in your own extension method(s) is the way to go here.

**Comment by Floyddotnet** [comment]
> 
> 
> Sorry, I don't see this being widely useful enough to warrant the bloat to the library. I think keeping this in your own extension method(s) is the way to go here.

i do not agree with the proposed solution. 

`ReceiveJson<T>` based on some internal functions like `HttpRequestMessageExtensions: HttpCall GetHttpCall(this HttpRequestMessage request)` and `FlurlRequest: Task<HttpResponseMessage> HandleExceptionAsync` with calls the internal function `HandleEventAsync` and so on. 

so the only possible solution for this would use reflection to call `ReceiveJson<T>` with a type instance. not a nice solution from a performance perspective.

**Comment by tmenier** [comment]
The internal methods you mentioned are to get at the `JsonSerializer` in case you overrode it at the request level (highly unlikely), and to make sure any deserialization error flows through Flurl's event system. If you're just looking for this functionality for your own application(s), you probably don't need to get that fancy with either. You've got the response and can deserialize it and handle errors however you want.

And just as a side note, #349 sort of has the goal of leveling the playing field for extension methods, but I can't give an estimate on when that will get done.
