### ISSUE TITLE
Accept Header has spaces

### ISSUE THREAD

**Issue by developervariety** [tmenier/Flurl#473]
Code to reproduce this possible bug:

```csharp
object rHeaders = new {
 Accept = "*/*",
  Accept_Encoding = "gzip, deflate",
  Accept_Language = "en-US,en;q=0.5",
  Connection = "keep-alive",
  Content_Type = "application/x-www-form-urlencoded; charset=UTF-8",
  Origin = "redacted",
  Referer = "redacted",
  User_Agent = task.userAgent
};
object rParams = new {
 bda = BdaGenerator.Execute(),
  public_key = "redacted",
  site = "redacted",
  userbrowser = task.userAgent,
  simulate_rate_limit = 0,
  simulated = 0,
  language = "en",
  rnd = Global.Bogus.Random.Float()
};

Captcha captcha = await Endpoint.InitCaptcha("redacted")
 .WithHeaders(rHeaders)
 .PostUrlEncodedAsync(rParams)
 .ReceiveJson < Captcha > ();
```

Flurl.Http v2.4.2

**Comment by developervariety** [comment]
I started messing with this more, and found out if you set the header you desire with no spaces with `.WithHeader` it **will not** add spaces.

Could this possible be fixed for `.WithHeaders`?

**Comment by tmenier** [comment]
Sorry just getting to this. So no bug here?

**Comment by developervariety** [comment]
No rush, but it's a .NET Core bug. [#39260](https://github.com/dotnet/corefx/issues/39260) On .NET Framework there's no issue with the headers though.

**Comment by tmenier** [comment]
Ah, interesting. Good to have it noted here in case it comes up gain.
