### ISSUE TITLE
Quotations around parameter names

### ISSUE THREAD

**Issue by petervanleeuwen** [tmenier/Flurl#475]
As per RFC2388 multipart/form-data parameter names should have quotations around them. I'll try and submit a PR if I get the chance.

https://tools.ietf.org/html/rfc2388

I think dude logged this in issue #255

**Comment by tmenier** [comment]
The spec you referenced doesn't say that at all. Quite the contrary:
```
NOTE ON PARAMETER VALUE LENGHTS: A short (length <= 78 characters)
parameter value containing only non-`tspecials' characters SHOULD be
represented as a single `token'.  A short parameter value containing
only ASCII characters, but including `tspecials' characters, SHOULD
be represented as `quoted-string'.  Parameter values longer than 78
characters, or which contain non-ASCII characters, MUST be encoded as
specified in [RFC 2184].
```
See [here](https://tools.ietf.org/html/rfc2045#section-5.1) for definitions of `token` and `tspecials`.

What the spec is saying is don't use quoted-string values unless there are special characters in it. The `HttpClient` stack follows the spec, and by extension so does Flurl.
