### ISSUE TITLE
FlurlHttp.BeforeCallAsync not executing asynchronously

### ISSUE THREAD

**Issue by kayhustle** [tmenier/Flurl#477]
When I put a long running call inside the BeforeCallAsync function it does not execute asynchronously.  It waits for the function to execute before executing the request.  The following code sample demonstrates this.  Shouldn't it execute and finish the request before waiting for the sleep to finish?

`public static void Main(string[] args)
        {

            FlurlHttp.Configure(async i =>
            {
                i.BeforeCallAsync = doingTheLogging;
                i.AfterCall = after => {
                    Console.WriteLine("Finished call");
                    var resp = after.Response;
                    string res = resp.Content.ReadAsStringAsync().Result;
                };
            });
            var response = getResponse();
            response.Wait();
            Console.WriteLine("Finished response");
            Console.ReadLine();
        }
        private static Task doingTheLogging(HttpCall httpCall)
        {
            return Task.Run(() =>
            {
                Console.WriteLine($"simulating a logging call for{httpCall.FlurlRequest.Url}...");
                Thread.Sleep(4000);
                Console.WriteLine($"finished a logging call for{httpCall.FlurlRequest.Url}...");
            });
        }
        private static async Task<string> getResponse()
        {
            var response = "https://www.google.com"
                .AppendPathSegment("gmail")
               .WithCookie("mycookie", "myvalue")
                .WithHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36")
                .WithHeader("Accept-Language", "en-us")
                .WithHeader("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3")
                .GetStringAsync();
            return await response;
        }`

**Comment by tmenier** [comment]
> Shouldn't it execute and finish the request before waiting for the sleep to finish?

Actually, no. It will await the Task returned from your event handler before proceeding with the call. This is by design. It's not intended to schedule the Task to a background thread or do anything in parallel, it's simply intended to allow you to use an async method as your callback (such as something that contains `await WriteToLogAsycn(...)` for example) without blocking a thread while that method completes.
