### ISSUE TITLE
th-TH CultureInfo causes URL.Combine not working as expected on Linux

### ISSUE THREAD

**Issue by yang-xiaodong** [tmenier/Flurl#485]
Flurl version : 2.4.2

Sample Code: 

```C#
    class Program
    {
        static void Main(string[] args)
        {
            string baseUrl = "api/v2";

            Thread.CurrentThread.CurrentCulture = new CultureInfo("th-TH");

            baseUrl = Url.Combine("http://google.com", baseUrl);

            Console.WriteLine("-----------before----------");

            Console.WriteLine(baseUrl);

            var furl = new Url(baseUrl).WithTimeout(10)
                .AppendPathSegments("test-path", "1-2-3-4");

            Console.WriteLine("-----------after----------");

            Console.WriteLine(furl.Url);
            Console.WriteLine(furl.Url.ToString());
        } 
    }
```

**Windows output:**

```
-----------before----------
http://google.com/api/v2
-----------after----------
http://google.com/api/v2/test-path/1-2-3-4
http://google.com/api/v2/test-path/1-2-3-4
```

**Linux output**

```
-----------before----------
http://google.com?api/v2
-----------after----------
http://google.com/test-path/1-2-3-4?api/v2
http://google.com/test-path/1-2-3-4?api/v2
```
You can see that `api/v2` is incorrectly recognized as a parameter in Linux

**Comment by yang-xiaodong** [comment]
https://github.com/dotnet/runtime/issues/971

**Comment by tmenier** [comment]
Sorry for the delay. I see your fix didn't build for netstandard 1.x. I'll see what I can do.

Note to self: https://github.com/tmenier/Flurl/pull/486/files

**Comment by yang-xiaodong** [comment]
Yes, I tried to fix the issue, but the lower version netstandard that didn't provide culture overloading method, so I close the PR

**Comment by tmenier** [comment]
Good news - 3.0 is dropping netstandard1.x so we can finally fix this. :) I do think I'm going to use `StringComparison.Ordinal` rather than `StringComparison.InvariantCulture` per best practices. Do you have any reason to think that won't work?

**Comment by yang-xiaodong** [comment]
No, According to [best practice](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#recommendations-for-string-usage)  that we should use `tringComparison.Ordinal`.

Is need me submit PR ?

**Comment by tmenier** [comment]
I got it. I made this a bit bigger and went with ordinal string comparisons _everywhere_.

**Comment by tmenier** [comment]
Ready in prerelease 5: https://www.nuget.org/packages/Flurl.Http/3.0.0-pre5
