### ISSUE TITLE
Changes to HttpCall and FlurlHttpException

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#488]
The introduction of [`FlurlResponse`](https://github.com/tmenier/Flurl/issues/354) has highlighted a few redundancies and general design regrets related to `HttpCall` (used mainly in [event handlers](https://flurl.dev/docs/configuration/#event-handlers) and exception handling) and `FlurlHttpException`. Obviously these changes are breaking, but since they're being released in a _major_ version upgrade, and the compiler will catch all of them at build time, I'm hoping this doesn't cause too many pains. 

Summary of the changes:

| 2.x | 3.x |
| --- | --- |
| `HttpCall` | `FlurlCall` |
| `HttpCall.FlurlRequest` | `FlurlCall.Request` |
| `HttpCall.Request` | `FlurlCall.HttpRequestMessage` |
| N/A (`FlurlResponse` is new) | `FlurlCall.Response` |
| `HttpCall.Response` | `FlurlCall.HttpResponseMessage` |
| `HttpCall.HttpStatus` | `FlurlCall.Response.StatusCode` |
|~~`FlurlHttpException.GetResponseJsonAsync`~~|~~`FlurlHttpException.Call.Response.GetJsonAsync`~~|
|~~`FlurlHttpException.GetResponseStringAsync`~~|~~`FlurlHttpException.Call.Response.GetStringAsync`~~|

_Brought back a couple per discussion below._

Another motivation for the `HttpCall` changes is to encourage preferring Flurl objects over their equivalents from the `HttpClient` stack when possible, which should make for more consistent/readable code when standardizing on Flurl for HTTP calls.

**Comment by imtrobin** [comment]
Why not retain FlurlHttpException.GetResponseJsonAsync helper, it is much more to type now

**Comment by tmenier** [comment]
I am open to that. On one hand it seems a little redundant and the new way isn't _that_ much more to type, but on the other hand I know the existing method is very commonly used and I was just waiting for someone to protest. :)

**Comment by imtrobin** [comment]
let me be the first to bring out the pitch fork then. Don't be like System.out.print when cout will do.

**Comment by imtrobin** [comment]
Actually here's why the new API is less desirable. I found that Call can be null. So I will needto do this this

`string responseString = await ex.Call?.Response.GetStringAsync ().ConfigureAwait (false)`

Except I can't because you can't await on a null task (currently). So I have to do a lot more checks compared to previous GetResponseJsonAsync

**Comment by tmenier** [comment]
@imtrobin Yeah, I'll bring those back as shortcuts.

**Comment by tmenier** [comment]
@imtrobin Sorry I meant to bring back those shortcuts for the last prerelease but forgot. They're ready for the next one.

**Comment by tmenier** [comment]
`GetResponseJsonAsync` and `GetResponseStringAsync` are back: https://www.nuget.org/packages/Flurl.Http/3.0.0-pre5

**Comment by imtrobin** [comment]
Thanks, can you also add Status code? Now I have to do this

`HttpStatusCode? httpCode = ex.Call?.Response?.ResponseMessage.StatusCode;`

**Comment by tmenier** [comment]
@imtrobin Yes, I think I agree, especially to clean up `catch/when` expressions, which I think is a good Flurl error-handling pattern. Please create a new issue for this though - 3.0 is final so this will likely go out in 3.0.1.
