### ISSUE TITLE
Support non-global json.net serialization settings

### ISSUE THREAD

**Issue by carolynvs** [tmenier/Flurl#49]
For libraries using Flurl, it would be very helpful to use Flurl with custom json.net serialization settings without clobbering the global json.net serialization settings (see [OpenStack.NET #551](https://github.com/openstacknetsdk/openstack.net/issues/551)). I believe this could be supported in Flurl through something like this:

```csharp
FlurlHttp.Configure(c => {
  c.JsonSerializerSettings = new JsonSerializerSettings { ... }
});
```

Then JsonHelper and CapturedJsonContent, would to specify the serializer settings when serializing/deserializing instead of using JsonConvert directly.

```csharp
// if JsonSerializerSettings is null, it's the same as if you called JsonSerializer.CreateDefault()
JsonSerializer.CreateDefault(FlurlHttp.Configuration.JsonSerializerSettings)
```

Does this seem reasonable? I'll submit a PR with tests if you think this is something you would accept.

**Comment by tmenier** [comment]
Thanks for the well thought out suggestion. I understand the problem and I gave is some thought. The crux of the issue as you put it is to not clobber the global Json.NET settings, but with this solution aren't you just shifting that clobbering to Flurl? If this user were using 2 libraries that use Flurl (unlikely I know!) and you changed Flurl's config settings like in your example, you would be affecting those settings for library B as well.

I think a better solution for libraries like yours would be if I exposed overloads for `GetJsonAsync` etc. that take a `JsonSerializerSettings` object. That seems like it would fall in line better with Json.NET's pattern. Would that work for your case?

I like your implementation idea for changing it globally for Flurl, but I can't off the top of my head think of a scenario where it would be useful. I don't think it's right for libraries.

**Comment by carolynvs** [comment]
Doh! Yes, that's a very good point that it just kicks the can down the road. If *JsonAsync had an optional parameter for the serializer settings then each library (and the application) could use Json.NET and Flurl without stepping on each others toes.

**Comment by tmenier** [comment]
Agreed! I'll work this in soon.

**Comment by carolynvs** [comment]
Awesome, thank you! Let me know if there's anything I can do to help.

**Comment by tmenier** [comment]
I won't lie to you, this got ugly fast. I'll do some more thinking on it, but I'm now thinking creating all these overloads isn't the way to go either. I haven't taken a close look at your library, but would it be feasible to use Flurl to get as far as getting a stream or string, then doing your own deserialization?

I did a little bit of refactoring in my last commit. JsonHelper is gone and replaced by [this extension method](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/JsonExtensions.cs), which is used [here](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/ResponseMessageExtensions.cs#L23). I think that should give you a good pattern to follow for your own extension method(s) for working in your custom settings, if you think that's feasible. Let me know your thoughts.

**Comment by carolynvs** [comment]
Doh! Thanks, I'll take a look and get back to you.

**Comment by tmenier** [comment]
I've already started thinking through some ideas on scoping all global config settings to just your library assembly, then doing something a lot closer to your original suggestion. Should mean far less refactoring for your library. Stay tuned!

**Comment by tmenier** [comment]
Thanks for your patience. After re-thinking it (several times!) I think I've finally arrived at a good solution. Here's a quick run-down:

- There's a simple new interface - `ISerializer` - that serves as a contract for serializing/deserializing objects to/from strings.
- `FlurlHttpSettings` (the thing you configure when you call `FlurlHttp.Configure`) now has a `JsonSerializer` and `UrlEncodedSerializer` property, each of which take an instance of an `ISerializer`.
- The default JsonSerializer is `NewtonsoftJsonSerializer`. This is now the only class in the library that references Newtonsoft; you could in theory swap it out for a different `ISerializer` implementation and not use Json.NET at all.
- The `NewtonsoftJsonSerializer` constructor optionally takes a `JsonSerializerSettings` object. That's your hook.
- `FlurlClient` holds its own `FlurlHttpSettings` instance, which by default is a copy of the global settings. You can overwrite any of the defaults or replace it entirely. That'll be the way for libraries to keep those settings out of global scope. You just need some central point where `FlurlClient`s are created, which it looks like you already have.

I've committed the code changes related to all of this. It includes a few breaking changes that I'll detail; looking at your code you'll definitely need to know about them. I still need to add a few comments and build the NuGet packages. Very interested in your initial thoughts.

**Comment by tmenier** [comment]
Changes above are released in Flurl.Http 0.7.0. Breaking changes noted here:

https://github.com/tmenier/Flurl/wiki/Release-Notes

**Comment by carolynvs** [comment]
Apologies for dropping off the face of the earth for a bit... 

I just grabbed 0.7 and keeping a copy of the settings with the client works great. That, plus the serializer changes, gives me full control without ruining json.net or flurl for anyone else. 

Thank you for hammering out a design that works so well, it is *really* appreciated! :+1: :smile:

**Comment by eestein** [comment]
@tmenier would you have any examples on how to use the ISerializer? I need to set it to use only lowercase, not the TitleCase properties C# uses.

Thanks

**Comment by taleman** [comment]
here is an example. I needed to serialize camelcase proprerty names.

```
var settings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
 
 FlurlHttp.Configure(c => {
 	c.JsonSerializer = new Flurl.Http.Configuration.NewtonsoftJsonSerializer(settings);
 });
```

**Comment by eestein** [comment]
@taleman cool like a cucumber :) Thank you sir 👍
