### ISSUE TITLE
What is the new flurlHttpException.Call.Request.RequestUri.AbsoluteUri

### ISSUE THREAD

**Issue by Methraen** [tmenier/Flurl#499]
I recently updated flurl from 2.4.2 to 3.0.0-pre3, and i have a lot of things that dont work anymore like flurlHttpException.Call.Request.RequestUri.AbsoluteUri, so how do we get that value now ?

**Comment by Methraen** [comment]
It is `flurlHttpException.Call.HttpRequestMessage.RequestUri.ToString()`

**Comment by tmenier** [comment]
Yes, or you can do `flurlHttpException.Call.Request.Url` to stay in the "Flurl world". This and other related breaking changes are detailed in #488. Also keep an eye on the [release notes](https://github.com/tmenier/Flurl/releases/tag/Flurl.Http.3.0.0-pre3b), which will continue to be updated until the full release.
