### ISSUE TITLE
Prepopulate HttpTest's CookieContainer with cookies

### ISSUE THREAD

**Issue by harnocz** [tmenier/Flurl#501]
I would like to prepopulate the CookieContainer of the HttpTest instance so that I can use it to test cookie sending behavior in my unit tests. As I see it this is not possible at the moment, since the HttpMessageHandler is a private readonly field in the test class, thus I can't access the CookieContainer in it. Please let me know if I'm missing something or if there's another recommended way to do this.

**Comment by tmenier** [comment]
This should do it:

```c#
httpTest.RespondWith(cookies: new {x = "foo", y = "bar"});
```

**Comment by harnocz** [comment]
I want to test that even though cookies are present my method does not actually send any cookies to the endpoint. I don't think this is possible with `httpTest.RespondWith()`, is it?

**Comment by tmenier** [comment]
How about:
```c#
httpTest.ShouldHaveCalled("...").WithoutHeader("Cookie");
```

**Comment by tmenier** [comment]
Looking at this again, I think what you're asking to be able to do is use HttpTest to manipulate the request in the SUT? If so, that's not really what it's for. It's only for faking responses and asserting requests.

I might be open to adding an assert like `httpTest.ShouldHaveCalled(...).WithCookie(...)`, but I don't think that's what you're asking for here.

**Comment by tmenier** [comment]
With #508 you can assert that a call did or did not send cookies. Does that resolve this?

**Comment by tmenier** [comment]
Haven't heard back so I'm closing this, but feel free to re-open if you think there's an enhancement needed that isn't covered by #508. Hopefully you've seen the major enhancements around cookies too (#506). CookieContainer is dead to me. :)
