### ISSUE TITLE
Cookies in 3.0

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#506]
Cookies never worked quite right in 2.x. Although you can get and set them using `FlurlRequest.Cookies`, that's deceiving because they actually live at the client level. This is due to a [limitation](https://github.com/dotnet/runtime/issues/1904) with the mechanisms from the HttpClient stack. Flurl.Http 3.0 will get it right by turning off `HttpClientHandler.UseCookies` and processing the raw headers directly.

### `IFlurlRequest.Cookies` and `IFlurlResponse.Cookies`

These read-only collections _directly_ reflect the `Cookie` request header and `Set-Cookie` response headers _for this specific request and response_, respectively. Nothing fancy here; if the cookie wasn't sent or received in this specific request, it won't be in these collections.

Here's how you can set some per-request cookies manually:

```c#
var resp = await "https://cookies.com"
    .WithCookie("name", "value")
    .WithCookies(new { cookie1 = "foo", cookie2 = "bar" })
    .GetAsync();
```
These simply write to the `Cookie` header for this request only.

### `CookieJar`

This is where things get a little smarter. `CookieJar` is a special collection type whose contents (`FlurlCookie`s) contain the full details received in `Set-Cookie` response headers. When a `CookieJar` is passed to `WithCookies`, you get these additional behaviors:
- Values to be written to the `Cookie` header are filtered according to rules involving the origin URL, `Domain` and `Path`, expiration, etc, per [RFC 6265](https://tools.ietf.org/html/rfc6265).
- When the response is received, the `CookieJar` will be populated/updated with any `Set-Cookie` headers present in the response.
- The (updated) `CookieJar` is well suited to reuse in subsequent requests.

In short, `CookieJar` is Flurl's equivalent of `CookieContainer` from the HttpClient stack, **with the notable advantage that it's not bound one-to-one with a client or handler**.

You can create and populate a `CookieJar` (fluently of course):

```c#
var jar = new CookieJar()
    .AddOrUpdate("cookie1", "foo", "https://cookies.com") // you must specify the origin URL if populating manually
    .AddOrUpdate("cookie2", "bar", "https://cookies.com");

await "https://cookies.com/a".WithCookies(jar).GetAsync();
await "https://cookies.com/b".WithCookies(jar).GetAsync();
```

Or, if you don't need to pre-populate it, you can save yourself the trouble of creating it and use an `out` param instead:

```c#
await "https://cookies.com/login".WithCookies(out var jar).PostUrlEncodedAsync(credentials);
await "https://cookies.com/a".WithCookies(jar).GetAsync();
await "https://cookies.com/b".WithCookies(jar).GetAsync();
```

### `CookieSession`

If passing that `jar` with every request feels like a drag, you can do it implicitly:

```c#
using (var session = new CookieSession("https://cookies.com")) {
    // set any initial cookies on session.Cookies
    await session.Request("a").GetAsync();
    await session.Request("b").GetAsync();
    // read cookies at any point using session.Cookies
}
```

That base URL passed in the constructor is optional; you can pass full URLs in the `Request` calls, or even a list of segments that will be `Url.Combine`'d together. These semantics are very similar to those of `IFlurlClient.Request`, and if fact, if you are using a `FlurlClient` explicitly, you can use `new CookieSession(client)` instead to make sure you're creating requests off that client.

### Manipulating cookies

Typically, cookies are set/updated via `Set-Cookie` instructions sent by server, and if you use a `CookieJar` or `CookieSession` as prescribed above, things will just work. But if you do need to manipulate them directly, be aware of these behaviors:

- When you use `WithCookies(jar)`, values relevant to this request are _immediately_ written to the `Cookies` header. If you manipulate the jar _after_ it is attached to the request and _before_ the request is sent, those changes will _not_ be synchronized with the `Cookie` header. So it's best to do any initializing/updating of the jar _before_ attaching it to any requests.
- Successive calls to `WithCookie(s)` will overwrite values of the same name set in previous calls, regardless of whether they came from a jar or direct values. But other than overwriting by name, successive calls are additive.
- Once a cookie is added to `CookieJar`, it becomes immutable and you'll get an exception if you try to change it. Use `jar.AddOrReplace` to "update" a cookie.

### Breaking changes

- **Removed `CookiesEnabled` at all settings levels.** It doesn't serve any purpose anymore. You're in direct control of sending cookies, you can't prevent a server from sending them in the response headers, and processing the `Set-Cookies` headers is done lazily, so there's no overhead involved when you don't need them.
- **Removed Client-level cookies.** This entailed removing the `Cookies` collection and `WithCookie(s)` methods from `FlurlClient`. `CookieSession` is the replacement, and it can even be managed as singleton via DI if that's appropriate. If there are legitimate reasons for client-level cookies I could be persuaded to add it back, but I can't think of any.
- `FlurlRequest.Cookies` is a now simple read-only list of Name/Value pairs.  This more accurately reflects the `Cookie` request header, which doesn't contain all the details of the `Set-Cookie` response header. `WithCookie(s)` is the preferred way to write request cookies. (You could also manipulate the `Cookie` header directly, but I wouldn't recommended it in most cases.)
- `Cookie` and `Set-Cookie` headers are now visible in the `Headers` collections. This is a consequence of disabling `HttpClientHandler.UseCookies`, but I tend to like it better because it's a more accurate representation of the actual headers that were sent and received.

**Comment by Meberem** [comment]
I really like everything proposed here. Particularly the idea of `out var cookies` to get response cookies for a request and keeping the Cookie headers.

My current scenario involves a background hosted service (in asp core) to "login" and persist a Cookie and Controllers that make additional calls to the endpoint with that Cookie. Both places basically end up calling `"endpoint.com".GetJsonAsync()` so would need to share a Cookie Session. I'm wondering if a way to do that would be to have a `Flurl.AspNetCore` package that shared the Cookie Session in a similar way to [Typed Http Clients](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#typed-clients).

**Comment by rcollette** [comment]
I'm curious why not address the underlying cookie issues in httpclient (whatever they may be) with the . Net core team?

What does my injection scenario look like for my DAOs.  It kind of feels like I will need a service factory and then I make calls only using session?   I'm tailing a bit off of @Meberem s question here.

Is session thread safe for updates.   On a cookie token renewal will the cookie be locked at the appropriate time?   There is a challenge here because as soon as the server sends a response and before parsing is complete, a prior token could be expired or invalidated.

**Comment by tmenier** [comment]
@rcollette
> I'm curious why not address the underlying cookie issues in httpclient (whatever they may be) with the . Net core team?

https://github.com/dotnet/runtime/issues/1904

I did my best but have heard nothing back so I'm not going to wait for them.

**Comment by tmenier** [comment]
@Meberem @rcollette An AspNetCore-specific companion lib is definitely something I'm considering, but I want to get 3.0 released first. Flurl.Http will continue to support a very broad range of platforms, and that's the context of this particular feature, so things like typed clients aren't really relevant to this.  Let me know if you see any shortcomings, under the context that it is a platform-agnostic "building block" that may require a little work to marry it to an ASP.NET Core feature.

@rcollette It's possible that I'll need to switch to a thread-safe collection such as a `ConcurrentDictionary` for cookies. I hadn't thought of the possibility that the _same_ "user session" could be hit by multiple threads, if that's what you're saying. I figured the more common scenario was different sessions on different threads concurrently (all using the same FlurlClient).

**Comment by rcollette** [comment]
I don't need to track cookies (for my applications anyway) at a user level, however, I'm going to use the same client for all requests made by a DAO.   That client will often require an expiring access token to hit whatever API it is calling.  It's an application specific token (my application) rather than specific to the users calling my application.   So there could be multiple calls to the DAO and at any point in time, the token/cookie used for all outgoing requests, could get refreshed.

Normally I would just manage all of this cookie outside the client anyway, lock the cookie value when it needs to be updated and include it with the request (.withCookies in this case).   So I'm not necessarily saying I need anything new for that scenario, but I can easily see someone expecting client reuse, with cookie management and potentially running into threading issues since you have a single client being used across multiple requests but having in essence state associated with that client (session really in this case).   It's possibly something addressed with clear documentation, session only to be used with actual user sessions.   But even then, lets say you're storing a token for a specific user to access some other account (twitter, fb, etc.), it's not out of the realm of possibility that you would have multiple threads accessing those external apis for the same user.   Making session have a thread safe implementation would be the way to go.   The analogy would be that in a browser, multiple requests can be made and there's no issues with cookies.

Don't dwell on it as a hard requirement for me.   The withCookies thing works for my scenario  99.9% of the time.  I don't run into the OIDC type scenario where I need cookies per user session.  Just trying to trigger some thought about potential gotchas.

**Comment by tmenier** [comment]
@rcollette I'm trying my best to follow along but I'll admit I'm struggling so bear with me.

First, cookies are first and foremost a browser concept, and I would think that in the majority of cases of people using them with Flurl they are simulating users using browsers to interact with web sites. I'm not sure what API you're working with that uses cookies and expiring auth tokens together, but that sounds very unusual to me.

Second, regarding "I can easily see someone expecting client reuse...", that's the whole point. Whether you're simulating 100 users, each with their own set of cookies, or 1 user with 50 browser tabs open, it's all just 1 client. The `CookieSession` (not the client) holds a cookie collection and passes them with every request, and that's literally _all_ it does. Managing an expiring token seems entirely outside the scope of this. And I'm already starting to think the best advice is don't share a `CookieSession` across threads at all.

**Comment by tmenier** [comment]
Updates since original post:
- `Cookies` (and `Headers`) collection on all relevant Flurl objects backed by `ConcurrentDictionary` so they're fully thread-safe.
- `FlurlRequest.Cookies` and `FlurlResponse.Cookies` contain _only_ what is present in the `Cookie` or `Set-Cookie` headers, respectively. (I originally posted code implying that cookies _sent_ in the first request would be present in `FlurlResponse.Cookies`. Not necessarily true. Issue updated to clarify this.
- New item under Breaking Changes: `FlurlRequest.Cookies` is now `IDictionary<string, string>` instead of `IDictionary<string, Cookie>`.

**Comment by tmenier** [comment]
This is now available in prerelease 4!

https://www.nuget.org/packages/Flurl.Http/3.0.0-pre4

There were enough changes since I first logged this issue that I rewrote the description almost completely. If you've been following this issue I'd encourage you to re-read it.

If you are using cookies with Flurl, **testing this prerelease is absolutely crucial**. It's completely different from 2.x, there's likely going to be some bugs, and it's extremely important to get the behavior right before the full 3.0 release, at which point it'll be too late for breaking changes. I greatly appreciate any and all feedback on this one!

**Comment by gpcaretti** [comment]
To be honest, this change disrupted one of the best features of Flurl.  I use Flurl  in a service invoked via IOC. Ver. 3.0, now requires me to handle explicitly cookies

**Comment by tmenier** [comment]
@gpcaretti If you post some details of what worked before and doesn't work now, I can probably help you with a smooth transition. Nothing with cookies should be harder than it was before.

**Comment by gpcaretti** [comment]
> @gpcaretti If you post some details of what worked before and doesn't work now, I can probably help you with a smooth transition. Nothing with cookies should be harder than it was before.

Thank you very much.

My post intended that with v. 2.x it was enough to configure Flurl to handle cookies and all was in charge to it. This allowed me to wrap Flurl in a class library with a API such has:

    public interface IWanAppService {
        Task Login(string username, string password, bool rememberMe);
        Task Logout();
        Task<ICollection<Court>> GetCourtsAllocation(DateTime date);
        Task<ICollection<CourtSlot>> GetSlots(Court cuort);
    }

A simple API that I invoked via IOC in different ViewModel of my app:

```
    IWanAppService WanAppService => DependencyService.Get<IWanAppService>();
```

With v.3 my understanding is I have to create a `CookieJar` and handle it in my App, as it has to be passed to the business methods of my App because every invocation requires a `WithCookies(jar)` :

    public interface IWanAppService {
        Task<CookieJar> Login(string username, string password, bool rememberMe);
        Task Logout();
        Task<ICollection<Court>> GetCourtsAllocation(DateTime date, CookieJar jar);
        Task<ICollection<CourtSlot>> GetSlots(Court cuort, CookieJar jar);
    }

**Comment by tmenier** [comment]
@gpcaretti Hmm, ok, that's your service interfaces but it doesn't tell me much about how you're using Flurl. Are you injecting `IFlurlClient`? Registering it as a singleton? How are you using it in the service? (`Request` method?) And do you need just 1 cookie "jar" for the entire life of your application?

**Comment by gitfool** [comment]
FWIW, I had trouble deserializing [CookieJar](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/CookieJar.cs#L14) and [FlurlCookie](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlCookie.cs#L29) with `System.Text.Json` in .NET 5.0 and had to write another custom converter. See [gitfool/BoardGameGeek.Dungeon@b0d04ff](https://github.com/gitfool/BoardGameGeek.Dungeon/commit/b0d04ff36ef45e8d2341ef2f35386c020765bc86). (In the end I avoided working with `CookieJar` by using `IEnumerable<FlurlCookie>` instead and only dealt with the `FlurlCookie` ctor issues.)

**Comment by tmenier** [comment]
@gitfool feel free to log a new issue. It does make sense that persisting a CookieJar should be easy and if it's not maybe there's something that can be done about that. I'm open to suggestions on how.

**Comment by gpcaretti** [comment]
> @gpcaretti Hmm, ok, that's your service interface but it doesn't tell me much about how you're using Flurl. Are you injecting `IFlurlClient`? Registering it as a singleton? 

I had an initialize such has

        /// <summary>
        ///     Call once at startup
        /// </summary>
        public IWanAppService Initialize(HttpMessageHandler httpMessageHandler) {
            FlurlHttp.Configure(settings => {
                settings.CookiesEnabled = true;
                settings.HttpClientFactory = new MyHttpClientFactory(httpMessageHandler);
            });
            return this;
        }

Then all methods works in this way:

        public async Task<ICollection<CourtDto>> GetCourtsAllocation(DateTime date) {
            var json = new FlurlRequest(MYBaseUrl)
                .AppendPathSegment("/index.php")
                .SetQueryParam("param1", "myvalue")
                .GetJsonAsync();
             ...
        }

As you can see, the great thing I liked was that cookies where all "automagic", i.e. if a response set some cookies, the successive request automatically executed with the same cookies. All this thanks to the initial configuration.

With v.3 my understanding is I have to create a `CookieJar` and handle it in my App, as it has to be passed to the business methods of my App because every invocation requires a `WithCookies(jar)`.

**Comment by softlion** [comment]
Thank you for being dumb and doing shit breaking changes.

For the other use this class:

```csharp
    public class HttpCookieSession
    {
        private readonly FlurlClient flurlClient;
        
        public CookieJar Cookies { get; } = new CookieJar();

        public HttpCookieSession(Action<FlurlClient> configure)
        {
            flurlClient = new FlurlClient(new HttpClient(new PolicyHandler()));
            configure(flurlClient);
        }

        public FlurlRequest CreateRequest(Uri uri)
            => new FlurlRequest(uri) { Client = flurlClient };

        public FlurlRequest CreateRequest(string uri)
            => new FlurlRequest(uri) { Client = flurlClient };

        class PolicyHandler : DelegatingHandler
        {
            private readonly AsyncRetryPolicy<HttpResponseMessage> retryPolicy;

            public PolicyHandler()
            {
                InnerHandler = new HttpClientHandler();

                //retry on 502
                retryPolicy = Policy
                    .HandleResult<HttpResponseMessage>(r => r.StatusCode == HttpStatusCode.BadGateway)
                    .WaitAndRetryAsync(5, retry => TimeSpan.FromSeconds(0.3));
            }

            protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                => retryPolicy.ExecuteAsync(ct => base.SendAsync(request, ct), cancellationToken);
        }

        public HttpCookieSession WithCookies(Dictionary<string, string> dictionary)
        {
            foreach (var kp in dictionary)
                Cookies.AddOrReplace(kp.Key, kp.Value, null);

            return this;
        }
    }
```

with this scenario:

```csharp
HttpSession = new HttpCookieSession(client =>
            {
                //don't work anymore
                //client.WithCookies(new Dictionary<string, string>                {
                //   { "my", "ddd" },
                //});

                client.WithHeaders(new Dictionary<string, string>
                {
                    { ... },
                });
            }) //New syntax
            .WithCookies(new Dictionary<string, string>
            {
                { "my", "ddd" },
            });
```
