### ISSUE TITLE
Add GetEnumAsync<T> helper

### ISSUE THREAD

**Issue by gitfool** [tmenier/Flurl#509]
This came on my radar because the .NET Core health checks return an [enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.healthchecks.healthstatus) as string [by default](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1#customize-output).

> The default delegate writes a minimal plaintext response with the string value of HealthReport.Status.

`GetEnumAsync<T>` would be a helper leveraging `GetStringAsync` and `Enum.TryParse<T>` under the hood such that a method using Flurl could more conveniently check the health status with something like:
```c#
public Task<HealthStatus> GetLivenessAsync()
    => Client.Request("health", "live").GetEnumAsync<HealthStatus>();

```

**Comment by tmenier** [comment]
Sorry I never replied to this one. To be honest I'm not sure if this is widely useful enough to warrant first-class support. `Enum.TryParse` is such a small extra step, plus it gives you a clear path for dealing with the string if it can't parse into one of those values. Good candidate for having your own extension method, but my bloat alarm is going off a little here as far as adding it to the library.
