### ISSUE TITLE
PCLStorage dependency

### ISSUE THREAD

**Issue by stefandevo** [tmenier/Flurl#51]
Would it be an idea to opt-out for downloading files feature and thereby not needing the PCLStorage dependency?

**Comment by tmenier** [comment]
Sorry for not getting back to you for so long. I had wondered how useful DownloadFileAsync really is and if it's worth the extra dependency, but looking at a few projects that use Flurl, and some questions I get, I have a hunch it's pretty popular. Dropping PCLStorage would be a breaking change for those people, but I think keeping it is pretty harmless. It's a pretty small library. I'll keep this issue open a bit longer in case anyone strongly disagrees with me on that or has a better solution than requiring PCLStorage.
