### ISSUE TITLE
SetQueryParam removes trailing slash from hostname

### ISSUE THREAD

**Issue by slashersvk** [tmenier/Flurl#510]
In version 3.0.0-pre3 I found out that if I have this code

```
        [Fact]
        public void Test()
        {
            var uri = new Uri("https://someurl.net:443/api/somepath");
            string completeUrl = uri.SetQueryParam("ids", new int[1]);
            completeUrl.Should().Contain(".net/api");
        }
```
It does not pass the test. If I add port to my initial Uri, then using SetQueryParam() strips slash between ".net" and "api".

**Comment by tmenier** [comment]
Confirmed. Very bizarre, it seems to be specific to the `Uri` containing the _default_ port. These both work exactly as expected:
```
new Uri("https://someurl.net/api/somepath")
new Uri("https://someurl.net:999/api/somepath")
```
And as a work-around, your example works if you `ToString` it first:
```
uri.ToString().SetQueryParam(...)
```
Will investigate. Thanks for reporting.

**Comment by tmenier** [comment]
The problem turned out to that that `Uri.Authority` doesn't include the port when it's the default port, even if it was included explicitly in the original string. It's debatable whether that's good or bad, but it definitely threw off Flurl's parsing engine. It'll fixed for the next prerelease.

**Comment by tmenier** [comment]
Fixed in prerelease 5: https://www.nuget.org/packages/Flurl.Http/3.0.0-pre5

**Comment by slashersvk** [comment]
Thank you for solving this issue :)
