### ISSUE TITLE
PutUrlEncodedAsync

### ISSUE THREAD

**Issue by TK20466** [tmenier/Flurl#519]
Would like to see an implementation of the UrlEncodedAsync function for PUT method requests, similar to the one that exists for POST method requests.

**Comment by tmenier** [comment]
There isn't a first-class method for that because it's not a very common scenario. But the second-class way is still pretty easy. :)

```c#
await urlOrRequest.SendUrlEncodedAsync(HttpMethod.Put, data);
```

**Comment by tmenier** [comment]
Thanks for the suggestion but closing due to it not being a common scenario. You could even wrap the "second-class way" in an extension method if you need to do this a lot.
