### ISSUE TITLE
CodeGen

### ISSUE THREAD

**Issue by stefandevo** [tmenier/Flurl#52]
Could you explain what the CodeGen exactly is doing? Thx

**Comment by tmenier** [comment]
It's a small console app that generates [this file](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/HttpExtensions.cs) on pre-build of Flurl.Http.

**Comment by stefandevo** [comment]
Ok thx, but this is not something that is executed every time you use Flurl.Http in an application?

**Comment by tmenier** [comment]
Absolutely not. It's not even compiled into the DLLs that get packaged for NuGet. It's a completely independent app that runs as part of the build process because the number of extension methods got big and I'm too lazy to maintain them manually. :)

**Comment by stefandevo** [comment]
:-) Ok that's what I thought (hoped). Thanks
