### ISSUE TITLE
Cookie is invalid

### ISSUE THREAD

**Issue by mincasoft** [tmenier/Flurl#520]
![image](https://user-images.githubusercontent.com/42678520/82584175-53307e80-9bbe-11ea-8dde-8bd8a778a956.png)

I passed the cookie value into the request header, but when I executed the "POST" method, I received an error as shown below. This error occurs when I pass an object of type Dictionary <string, string>

```
var cookies = new Dictionary <string, string>
{
    {"JSESSIONID", "0677235D8C9FB757B79550F7E42AE7C4.passport1686"},
    {"BIGipServerPASSPORT_12", "279441418.60961.0000"},
}

var response = await _flurlClient.Request().WithCookies(cookies).PostUrlEncodedAsync(ct).ConfigureAwait(false);

```
![image](https://user-images.githubusercontent.com/42678520/82584247-6a6f6c00-9bbe-11ea-918c-88d1270d5a06.png)

**Comment by tmenier** [comment]
I can't reproduce this. What platform are you on?

**Comment by mincasoft** [comment]
.NET Core 3.1, wpf

**Comment by tmenier** [comment]
Ah, looking closer at that error message there appears to be a space at the beginning of the cookie name. That's the direct cause of the error. Flurl would not have added that space. Are you hard-coding the cookie name `"BIGipServerPASSPORT_12"` exactly as in your example or is it possible you're reading it in from somewhere and might have a leading space?

**Comment by mincasoft** [comment]
If I pass a cookie value as a string then this does not happen
`"JSESSIONID=0677235D8C9FB757B79550F7E42AE7C4.passport1686, BIGipServerPASSPORT_12=279441418.60961.0000"`

**Comment by tmenier** [comment]
Um...I'm not sure if that answers the question. Let's try this: can you write an isolated unit test that reproduces this issue?

**Comment by tmenier** [comment]
Let me know if the latest prerelease resolves this.

https://www.nuget.org/packages/Flurl.Http/3.0.0-pre4

**Comment by tmenier** [comment]
Feel free to re-open if the latest prerelease doesn't resolve this.
