### ISSUE TITLE
A strange issue with response time

### ISSUE THREAD

**Issue by xjfhnsd** [tmenier/Flurl#521]
Dear Flurl Team,

I have a question when using Flurl.Http, 
If I send a Post per 2 seconds, the response time is in 200ms,
but I send a POST per 2 minutes, the response will take more than 1000ms.
Is this a known issue?

Regards

**Comment by tmenier** [comment]
Response times primarily consist of the time it takes for the request to travel across the network from the client to the server, the server to generate a response, and the response to travel back to the client. With only the information you've given I can't explain why requests sent less often are taking longer, but it almost certainly has nothing to do with the client library. Sorry.

**Comment by rcollette** [comment]
With HTTP 1.2 the connection would not be closed immediately.   The "extra" time you are seeing is likely the HTTPS negotiation.
