### ISSUE TITLE
ParseQueryParams not parsing the parameter name correctly

### ISSUE THREAD

**Issue by Guydraud** [tmenier/Flurl#525]
I would have expected this to return "barId" as the parameter name. But i get the entire uri minus the parameter value instead:

`var p = Url.ParseQueryParams("http://localhost:55512/foo/bars?barId=666");`

Result:
![sc2](https://user-images.githubusercontent.com/29076303/83511574-d5f9e900-a49c-11ea-90e4-f070815b34ac.png)

**Comment by tmenier** [comment]
Closing as similar to #524, same solution.
