### ISSUE TITLE
How to set SecurityProtocolType.Tls12

### ISSUE THREAD

**Issue by howardoi** [tmenier/Flurl#526]

**Comment by tmenier** [comment]
Flurl is using HttpClient under the hood. If you're using .NET Framework 4.7 or above you're using the latest TLS version by default. I think that's true with .NET Core as well, though it depends on the OS and I'm not certain about older versions. For older versions of .NET Framework, see:

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-a-net-framework-version-earlier-than-47
