### ISSUE TITLE
Is this project still going to be maintained?

### ISSUE THREAD

**Issue by mincasoft** [tmenier/Flurl#527]
Is this project still going to be maintained? It has been a long time since I saw the author commit new features. The 3.0 preview version has been released for a long time. I always look forward to a new official version

**Comment by tmenier** [comment]
Yes. This project is a hobby that I work on in my free time, which I've had little of lately. Is there something specific you're waiting on?

**Comment by tmenier** [comment]
Closing the "issue" but feel free to keep the conversation going if you want.
