### ISSUE TITLE
Flurl.Url vs. System.Uri awkwardness

### ISSUE THREAD

**Issue by hut8** [tmenier/Flurl#53]
Thanks for Flurl! I'm using it in a project and it really cuts down on the code required to do HTTP stuff.

My project uses a bunch of `System.Uri` objects. Is there a reason why `Flurl.Url` doesn't have a constructor taking a `System.Uri` (or at least `static implicit operator Url(System.Uri uri)`), or that the `Flurl.Url` functionality even exists outside of extension methods? I have this a lot of places and I hate it.

            var html = await _client
                .WithUrl(new Url(URL.ToString()))
                .GetStringAsync();

I'd be happy to add some code to make the interface a little smoother as long as you approve of this design. I just don't understand why Flurl has its own Url class when it seems like most of the stuff could be done as extension methods of the System.Uri class.

**Comment by tmenier** [comment]
I assume you're re-using a `FlurlClient` instance and it's the `new Url(URL.ToString())` bit that you don't like? `WithUrl` does take a string so you could at least shorten it to:

`var html = await _client.WithUrl(URL.ToString()).GetStringAsync();`

You could further shorten it by writing a `WithUri` extension method on `FlurlClient` to get rid of the `ToString()` bit.

I've thought about incorporating `System.Uri` into the library in some way but haven't really found a need for it to be honest. In most typical cases (for me anyway), I'm starting with some fixed base URL, often from a config file or string constant, and building up the right side of it, which is where I think Uri has some gaps that I've tried to fill with Flurl. That said, I might consider entertaining your implicit conversion idea. Let me know if the ideas above are enough to fix the awkwardness issues.

**Comment by hut8** [comment]
@tmenier Thanks for your quick reply. Yes, I'm re-using the `FlurlClient` instance. `URL.ToString()` with the implicit conversion to `Flurl.Url` is a bit better. What do you think about me just adding an implicit conversion from `System.Uri` to `Flurl.Url` simply by calling `System.Uri.ToString()`? That way my code wouldn't be littered with `systemUriInstance.ToString()` everywhere.

**Comment by tmenier** [comment]
I'd consider accepting that, yes. I do have a few other things I'm currently working on, so if you don't want to have to wait for me to get it packaged and released, it would sure be simple for you to tackle the problem with an extension method like this:

    public static FlurlClient WithUri(this FlurlClient client, System.Uri uri) {
        return client.WithUrl(uri.ToString());
    }

**Comment by tmenier** [comment]
This is done and will be released soon with Flurl 2.0. https://github.com/tmenier/Flurl/commit/fae2680707f80b01765f0e8c9cbccd2623a201ab
