### ISSUE TITLE
FlurlClient Constructor with HttpClient doesn't call message handler

### ISSUE THREAD

**Issue by tomatualus** [tmenier/Flurl#530]
If i register a HttpClient with a request handler(s)

        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<ConsoleCorrelationIdHandler>();
            this.AddHttpClient<ICatalogService, CatalogService>(services, "http://httpbin.org");
        }
        private void AddHttpClient<TClient, TImplementation>(IServiceCollection services, string url = null)
            where TClient : class
            where TImplementation : class, TClient
            => services.AddHttpClient<TClient, TImplementation>(client =>
            {
                if (!string.IsNullOrWhiteSpace(url))
                    client.BaseAddress = new Uri(url);
            })
                .AddHttpMessageHandler<ConsoleCorrelationIdHandler>(); // Appends CorrelationId to all outgoing HTTP requests.

And then create a client which will use initiate FlurlClient with previously setted up HttpClient

    public class CatalogService : ICatalogService
    {
        private readonly IFlurlClient _httpClient;
        private readonly HttpClient httpClient;
        public CatalogService(HttpClient httpClient)
        {
            this.httpClient = httpClient;
            _httpClient = new FlurlClient(httpClient);
        }
        public async Task GetSomething()
        {
            try
            {
                var y = await this.httpClient.GetAsync("headers");

                var x = await this._httpClient.BaseUrl
                    .AppendPathSegment("headers")
                    .GetJsonAsync();
            }
            catch (Exception e)
            {

                throw;
            } 
        }
    }

When i call the httpClient, it goes trough the ConsoleCorrelationIdHandler, but IFlurlClient for some reason doesn't.

I know that i can use factories or what not, but is there really no way to use dependency injection style with chained AddHttpMessageHandler calls?

Also, is it possible to register multiple handlers in the custom httpclientfactory? I see that it can only return a single HttpMessageHandler. 

Thanks in advance.

**Comment by tmenier** [comment]
https://stackoverflow.com/a/62678186/62600

**Comment by tomatualus** [comment]
Oh, i have no idea how you found my question, but very big thank you for helping me out! :)

**Comment by tmenier** [comment]
No worries. I'm subscribed to the `flurl` tag so I get notified of new questions.
