### ISSUE TITLE
An error occurred when parsing the Cookie header

### ISSUE THREAD

**Issue by mincasoft** [tmenier/Flurl#532]
I configured FlurlClient using the `EnableCookies()` extension method;
```
public Authentication(IFlurlClientFactory clientFactory)
{
            _flurlClient = clientFactory.Get(AppConstants.BaseAddress).EnableCookies();
}
```

When I make an A request I receive Cookies returned in the Headers.
![image](https://user-images.githubusercontent.com/42678520/87138410-94910080-c2c8-11ea-8fa1-b842877a5cb9.png)
Then I kept calling request B, now I want to use Cookie in response A to be Header for request B. But I get the following error:
![image](https://user-images.githubusercontent.com/42678520/87138878-49c3b880-c2c9-11ea-8232-f029f1245a60.png)

**Comment by mincasoft** [comment]
Also I discovered that, in case the response returns a Cookie with the following value:

```
if (!response.Headers.TryGetValue("Set-Cookie", out var cookieHeader)) 
    return false;
var lstCookie = cookieHeader.ToKeyValuePairs().ToList();
```

**_lstCookie_** value: 
`"CASPRIVACY=\"\"; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/passportv3, CASTGC=TGT-23508-rrmbIDoeL7La9KdKr77CN7Sh5LR0Z2ofdLYKYOqgsOYtorW4Sw-cas; Path=/passportv3"`

`var toKv = cookieHeader.ToKeyValuePairs().ToList();`

I would like to receive a list of 2 <key, value> pairs **_CASPRIVACY_** and **_CASTGC_** but it returns only 1 pair with the key **_CASPRIVACY_**

**Comment by mincasoft** [comment]
As mentioned in bug #520 
 I noticed that if the response returns any Cookie that contains a double "." will cause an error
Ex: 
BIGipServerPASSPORT_12=279441418**.**60961**.**0000"
or
Cookie: JSESSIONID=339724211C3D868AFA6EDA1398BC91EB**.**node**.**01

**Comment by mincasoft** [comment]
Oh, this problem is found at [](https://stackoverflow.com/questions/1834522/help-with-net-cookiecontainer)

Issue is that .NET complies with the RFC specification for cookie tags, but not all sites do. So, ultimately, the issue is not Microsoft, or .NET for the matter. (Although, IE, manages the cookies fine so it would be better to rewrite their .NET cookie parsing methods using the same parsing methods) The issue is the sites that do not follow RFC specifications.

Nonetheless, an issue I've often encountered is that sites will use commas in the expiration dates in their cookies. .NET interprets these as separators between different cookie fields and strips the ending and everything there after off of the cookie.

RFC spec: "Cookie:, followed by a comma-separated list of one or more cookies." An easy solution to this problem would be for the web server to enclose values with commas in quotation marks, per the RFC document. However, there is no RFC police, so we can only hope that people follow the rules.

**Comment by tmenier** [comment]
Glad you figured that out. Even if it is a bug, Flurl's dependency on CookieContainer to do that parsing would make it awfully hard to provide a fix.

To your other question, `ToKeyValuePairs` is a utility method mostly used internally by Flurl, and mostly for parsing properties of objects. But it does have special case handling for dictionary-like objects and strings. In the case of strings, it parses by URL query format, i.e. `x=1&y=2`, so it's not designed to parse a cookie header.

Final side note, since you're working with cookies, you might be interested in [what's coming in 3.0](https://github.com/tmenier/Flurl/issues/506). Lots of good enhancements, but breaking changes to be aware of too.

**Comment by mincasoft** [comment]
I made a few requests and got a list of Cookies returned in the header. I then made a subsequent request on the same URL. Immediately I received a `System.Net.CookieException: An error occurred when parsing the Cookie header for Uri`
I tried deleting all cookies but I still get the same error.

```
_flurlClient.Cookies.Clear();
response = _flurlClient.Request(authenticatedUrl).GetAsync(ct).ConfigureAwait(false); 
```
But if I use the following way:
```
request.Settings.CookiesEnabled = false;
response = _flurlClient.Request(authenticatedUrl).GetAsync(ct).ConfigureAwait(false); 
```

It works fine, but I don't have the Cookies as originally set

```
FlurlHttp.Configure(settings =>
            {
                settings.HttpClientFactory      = new PollyHttpClientFactory();
                settings.ConnectionLeaseTimeout = TimeSpan.FromSeconds(60);
                settings.Timeout                = TimeSpan.FromSeconds(60);
                settings.JsonSerializer         = new MicrosoftJsonSerialize();
                **settings.CookiesEnabled         = true;**
            }
);
```

**Comment by tmenier** [comment]
Sounds like the same error, no?

I'm pretty sure `Cookies.Clear` won't work as you expect. It's a dictionary that gets synchronized with the underlying CookieContainer only when calls are made, so I wouldn't advise doing that. Probably safest to just create a new client if you really need to clear out the cookies.

As I mentioned in the issue I linked to, cookies in 2.x are quirky, and with the big changes coming in 3.0 I don't plan on making any more enhancements to 2.x.

**Comment by mincasoft** [comment]
An aside question, I am excited to know the official release date for version 3.0

**Comment by tmenier** [comment]
No official date yet. Keep a watch on that issue or follow @FlurlHttp on twitter if you want to stay on top of the updates.
