### ISSUE TITLE
Call failed. The 'Path'='/search' part of the cookie is invalid. 

### ISSUE THREAD

**Issue by hn24** [tmenier/Flurl#548]
Hi,
Just want to enable cookie of the furlClient then import/export them later
I got this error when call IFlurlClient.EnableCookies() and  make a request to GET https://www.google.com/preferences
![Capture](https://user-images.githubusercontent.com/53258318/91662754-a9428580-eb0e-11ea-9a36-78c8e43ded3e.PNG)
Anyone can help me?

**Comment by tmenier** [comment]
Cookies are getting a [major overhaul](https://github.com/tmenier/Flurl/issues/506) in 3.0, so I encourage you to read about the changes and (https://www.nuget.org/packages/Flurl.Http/3.0.0-pre4)[upgrade to the latest prerelease]. I won't likely fix any cookie bugs in 2.x, and I'm fairly certain this one in particular won't be an issue in 3.0.
