### ISSUE TITLE
Download and upload progress

### ISSUE THREAD

**Issue by cordechasse** [tmenier/Flurl#55]
Hi,

Is there a way to get upload and download progress?
I can't find anything about that in the doc.

**Comment by tmenier** [comment]
Nothing that's baked into the library. The HTTP stuff is basically a thin wrapper around [HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.aspx), and there's some decent info on how to implement progress indicators with that:

http://stackoverflow.com/questions/20661652/progress-bar-with-httpclient
http://stackoverflow.com/questions/21169573/how-to-implement-progress-reporting-for-portable-httpclient

In Flurl there are several ways to get at the underlying HttpClient instance and manipulate it directly. So if you decide to implement this yourself and need help hooking it into Flurl, feel free to ping me.
