### ISSUE TITLE
Adding Cookie support breaks Blazor on Net 5

### ISSUE THREAD

**Issue by pablopioli** [tmenier/Flurl#552]
Trying Net 5 RC1 with a blazor app, and apparently the new cookie functionality is breaking the app (https://github.com/tmenier/Flurl/issues/506)

```
Flurl.Http.FlurlHttpException: Call failed. Operation is not supported on this platform. GET https://localhost:26391/information/aboutme blazor.webassembly.js:1:14634
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform. blazor.webassembly.js:1:14634
   at System.Net.Http.BrowserHttpHandler.set_UseCookies(Boolean value) blazor.webassembly.js:1:14634
   at System.Net.Http.HttpClientHandler.set_UseCookies(Boolean value) blazor.webassembly.js:1:14634
   at Flurl.Http.Configuration.DefaultHttpClientFactory.CreateMessageHandler() blazor.webassembly.js:1:14634
   at Flurl.Http.FlurlClient.<.ctor>b__4_0()
```
Related is the new compatibility analyzer for browser apps
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/

I assume the sandbox is blocking the library for handling the cookies. So a way to disable this functionality is needed.

**Comment by pablopioli** [comment]
Closing this since the problem is addressed in https://github.com/tmenier/Flurl/issues/543

**Comment by tmenier** [comment]
wow, I was literally just typing something just like that :)

It'll be in the next prerelease, which should be ready fairly soon.
