### ISSUE TITLE
Remove HttpRequestMessage.GetHeaderValue and HttpResponseMessage.GetHeaderValue

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#553]
These extension methods are no longer needed internally, and although they're public, I suspect they're not very useful, mainly because `FlurlRequest` and `FlurlResponse` contain the `Headers` abstractions that should generally be used.

If there are major objections, I might consider bringing these back, although 3.0 handles the case of multiple headers of the same name (mostly for `Set-Header`) with the exception these methods, so keeping them as-is isn't a very appealing option.

The `SetHeader` extension method is still used internally and has a lot of smarts to it, mainly deciding whether to add a given header the message object itself or its `Content` property, so I'm leaving that one alone.

**Comment by tranb3r** [comment]
Question:
HttpResponseMessage.Headers.GetValues(headerName) is case-insensitive on headerName.
The equivalent using Flurl would be FlurlResponse.Headers.FirstOfDefault(headerName), but I believe it's case-sensitive on headerName, isn't it ?

**Comment by tmenier** [comment]
@tranb3r Good catch. You are correct that they're case-sensitive currently but according to the spec should not be. I'll get that fixed.

**Comment by tmenier** [comment]
@tranb3r Header names are now case-insensitive in prerelease 6. Thanks again for reporting that.
