### ISSUE TITLE
[enhancement] Allow to test for network/socket error conditions

### ISSUE THREAD

**Issue by ModernRonin** [tmenier/Flurl#554]
Hi,

it would be nice if HttpTest had an additional method for simulating socket errors like:
```csharp
_httpTest.SimulateSocketError(SocketError.HostNotFound);
```

Even better (but more work) would be if the `HttpCall` object that is provided in `OnError` and `OnErrorAsync` had properties like:
```csharp
.IsNetworkDownOrUnstable
.IsHostInvalid
```

But I don't just wanna ask for a feature, I also want to say how grateful I am for Flurl and Flurl.Http and how much I appreciate all the work that has gone into it!

Thank you,
MR

**Comment by tmenier** [comment]
Hmm. What if there was something more general like `SimulateException`, and you could provide a `SocketException`? I might be open to that. It would cover other cases where exceptions could be thrown from the HttpClient stack.

As for `IsNetworkDownOrUnstable`, how would that be implemented? I'm not sure where that bit of information actually comes from.

**Comment by ModernRonin** [comment]
`.SimulateException` would be fine. 

Regarding `IsNetworkDownOrUnstable`: by checking the `SocketErrorCode` property of a `SocketException` - if it's either of the following, then it would seem to be a very reasonable guess that the local network connection is either down or unstable:

for sure:
* NetworkDown
* NetworkUnreachable
* NetworkReset
likely:
* Shutdown
* HostDown
* HostUnreachable
maybe:
Interrupted

**Comment by vyppi** [comment]
Hi @ModernRonin, checking if you are going to submit a PR for this change since it seems a good feature to have.

**Comment by ModernRonin** [comment]
@vyppi I never got an answer from the repo owner whether he was interested and in which form. Meanwhile it's a year later and right now I'm in a very hot pre-release phase, so for the next 2 months I will definitely have no capacity for any OS at all, sadly.

**Comment by tmenier** [comment]
Sorry, the backlog is overdue for some scrubbing for sure. @vyppi would a `SimulateException` method be useful by itself in your scenario too? If so I can probably sneak that into the next release.

I'm not so sure about the proposed enhancement to `FlurlCall`. It has an `Exception` property that can be inspected from those error handlers, and I don't see Flurl providing abstractions over the details that `SocketException` provides as being broadly useful, if that makes sense. Seems easy enough for an app developer to just check the exception details like that directly.

Thoughts?

**Comment by tmenier** [comment]
This will be available in the next release. Thanks @Mcphylus12!

**Comment by tmenier** [comment]
Released
