### ISSUE TITLE
HttpTest with Recursive Calls 

### ISSUE THREAD

**Issue by mkeuschn** [tmenier/Flurl#559]
I have created a recursive retry logic if the call raises a FlurHttpException.

Implementation:

        public async Task<bool> DoAsync(int retry = 1)
        {
            HttpResponseMessage response;
            try
            {
                response = await "http://www.google.com".GetAsync();
            }
            catch (FlurlHttpException e)
            {
                if (retry <= 3)
                {
                    Thread.Sleep(new TimeSpan(0, 0, 1 * retry));
                    return await DoAsync(++retry);
                }
                Console.WriteLine(e);
                throw;
            }

            return response.IsSuccessStatusCode;
        }

Test:

        [Fact]
        public async Task DoAsyncTest()
        {
            using var httpTest = new HttpTest();
            httpTest.RespondWith("Internal Server Error", 500);
            var service = new MyService();
            var result = await service.DoAsync();
            result.ShouldBeTrue();
        }

In the first round the 500 response is returned as expected, but in the second round the call responded with 200 OK. 
Do I am using this in the right way or is this a bug?

**Comment by tmenier** [comment]
Depends on the version of Flurl. :) If you're on 2.x, the behavior is by design. With 3.x that changes. See #482.

**Comment by mkeuschn** [comment]
Ok, thank you. I have tried both v2 and v3. I like the v3 behaviour and will stick with this release.
