### ISSUE TITLE
Encode % to %25 in query param

### ISSUE THREAD

**Issue by ivanovevgeny** [tmenier/Flurl#56]
I have an Uri with percent in query params:
<pre>
http://www.remix-shop.ru/catalog/?set_filter=Y&SEASON=%CD%EE%E2%FB%E9%20%E3%EE%E4
</pre>
Next i create new Url

<pre><code>
var url = new Url(initialUri.OriginalString);
</code></pre>
and now my url is

<pre>
http://www.remix-shop.ru/catalog/?set_filter=Y&SEASON=%25CD%25EE%25E2%25FB%25E9%20%25E3%25EE%25E4
</pre>
As you can see, we have additional %25 in query params.

Second url it's not the same as first! I have different pages when open this 2 url in browser.

**Comment by tmenier** [comment]
This will be fixed for Flurl 2.0, to be released soon.
https://github.com/tmenier/Flurl/blob/master/Test/Flurl.Test.Shared/UrlBuilderTests.cs#L298-L304
