### ISSUE TITLE
Feature HTTPStatusCode in exception

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#565]
From issue https://github.com/tmenier/Flurl/issues/488

Like to be able to get StatusCode from exception easier, currently I have to do this

HttpStatusCode? httpCode = ex.Call?.Response?.ResponseMessage.StatusCode

**Comment by tmenier** [comment]
`StatusCode` is back but I decided to make it an `int?` for consistency. I believe you preferred enums and all I can say is it's a difference of opinion. I'm just not a fan of abstracting away the HTTP status. I know not everybody agrees with that, though many do.

**Comment by tmenier** [comment]
Released in 3.0.1
