### ISSUE TITLE
Whether sockes5 agents are supported in the new 3.0 release

### ISSUE THREAD

**Issue by ssuui** [tmenier/Flurl#566]
I saw an update. Thank you very much for the team's maintenance and update. I use Sockes5 when I'm using some other HTTP client

Proxy, encountered a pesky byte beyond error. In the issues of this project, I have seen relevant questions raised by users. I agree with the team on the design specification. I don't know if there's a better way to solve this problem in the new version, but I'm talking about a better support or solution for using Sockes5 Proxy. I have a request on my side. A different proxy might be used to send the request, which seems more relevant to the users in the business. What's a good solution? Thank you very much and have a nice day

**Comment by tmenier** [comment]
Anything involving proxies tends be handled at the `HttpMessageHandler` level. I would suggest learning how to do this with HttpClient, then working that solution into a custom factory as described [here](https://flurl.dev/docs/configuration/#httpclientfactory).

A while back I actually answered a question specifically about SOCKS5: https://stackoverflow.com/questions/43293365/c-sharp-httpclient-tor-socks4-5-proxy

**Comment by tmenier** [comment]
Hopefully I've answered your question. Closing this issue.
