### ISSUE TITLE
Enable HttpTest using more variants other than string extension methods

### ISSUE THREAD

**Issue by sepharg** [tmenier/Flurl#569]
Please describe the feature/enhancement in as much detail as possible.
At this time the only way to use HttpTest in Flurl is to construct the calls using the fluent interface based on string extension methods (i.e. "http://my-api/users/1".GetJsonAsync() ... etc)
It´d be great if the HttpTest could hook to other ways of working with flurl, for example when using a IFlurlClient constructed by the IFlurlClientFactory

**Comment by tmenier** [comment]
HttpTest should work no matter how you use Flurl. If it isn't, I suspect something else is going on. Can you provide a repro?

**Comment by sepharg** [comment]
while trying to repro in a separate solution (from scratch) it actually works. so there has to be something wrong with our code
i'll try to fix it and reopen it if i'm not able to :)

**Comment by sepharg** [comment]
Ok i think I got it. HttpTest seems to hook onto specific instances automagically but not when interfaces are used. In the following code (I can provide the project zipped if you tell me where to upload it to), the test fails, however if we change UrlCaller's constructor to accept a ClientHadler instead of an IClientHandler, it works

```
using System;
using System.Threading.Tasks;
using FluentAssertions;
using Flurl;
using Flurl.Http;
using Flurl.Http.Configuration;
using Flurl.Http.Testing;
using Moq.AutoMock;
using Xunit;

namespace FlurlTest
{
    public class Config
    {
        public virtual string baseUrl { get; set; }
    }

    public interface IClientHandler
    {
        IFlurlClient client { get; set; }
    }

    public class ClientHandler : IClientHandler
    {
        public IFlurlClient client { get; set; }

        public ClientHandler(Config config)
        {
            client = new PerBaseUrlFlurlClientFactory().Get(Url.Parse(config.baseUrl));
        }
    }

    public class UrlCaller
    {
        private readonly IClientHandler _handler;

        public UrlCaller(IClientHandler handler)
        {
            _handler = handler;
        }

        public async Task<string> CallUrl()
        {
            
            var contents = await _handler.client.Request("/tmenier/Flurl/issues/569#issuecomment-726776571").GetStringAsync();
            return contents;
        }
    }

    public class TestClass
    {
        [Fact]
        public async Task Test()
        {
            var httpTest = new HttpTest();
            var autoMocker = new AutoMocker();
            var baseUrl = "http://something";
            autoMocker.GetMock<Config>().Setup(x => x.baseUrl).Returns(baseUrl);
            var urlCaller = autoMocker.CreateInstance<UrlCaller>();
            var sut = new UrlCaller(new ClientHandler(autoMocker.GetMock<Config>().Object));

            var contents = await urlCaller.CallUrl();
            httpTest.CallLog.Count.Should().BeGreaterThan(0);
        }
    }
}
```

**Comment by tmenier** [comment]
Looks like you're calling `CallUrl` on a mocked instance of `UrlCaller`. That's going to bypass the implementation and hence not hit Flurl at all, no?

**Comment by sepharg** [comment]
If I change the following

`public UrlCaller(IClientHandler handler)
        {
            _handler = handler;
        }`

to

`public UrlCaller(ClientHandler handler)
        {
            _handler = handler;
        }`

It also uses a mocked instance but HttpTest somehow works. I was hoping you could shed some light into why?

**Comment by tmenier** [comment]
Can you repro if you take Moq completely out of the equation? I'm not sure if your example has been reduced/minimized enough to pinpoint the issue. There's a lot going on here.

**Comment by sepharg** [comment]
i wasn´t able to reproduce without injecting an interface into the class. it is definitely related to how Moq constructs mocks of types vs interfaces. therefore i don´t think it´s a flurl problem, but something related to Moq and its interactions, so i´ll close the issue. thanks for the support!
