### ISSUE TITLE
Allow captured response to be deserialized to different types

### ISSUE THREAD

**Issue by shack05** [tmenier/Flurl#571]
This is a follow up from a question [How to automatically log responses using Flurl v3.0.0](https://stackoverflow.com/questions/64814837/how-to-automatically-log-responses-using-flurl-v3-0-0) posted on Stackoverflow.

The request is to be able to read the same response more than once using different types of Flurls [Get*](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlResponse.cs#L39-L83) methods.

An example use case would be logging responses in an `AfterCallAsync` handler which uses `GetStringAsync`, but then also using `GetJsonAsync<T>` on the response object in the original calling code. 
Currently, trying to do so would mean that `GetJsonAsync<T>` returns null.

Here is some example code (as provided in the stackoverflow post):
``` CSharp
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var client = new FlurlClient("https://jsonplaceholder.typicode.com/"))
            {
                var post = await client
                            .Request("posts/1")
                            .ConfigureRequest(settings => settings.AfterCallAsync = LogResponse)
                            .GetJsonAsync<Post>();
                Console.WriteLine($"Is null with logging enabled: {post is null}"); // prints True

                post = await client.Request("posts/1").GetJsonAsync<Post>();
                Console.WriteLine($"Is null with logging disabled: {post is null}"); // prints False
            }
        }

        private static async Task LogResponse(FlurlCall call)
        {
            var responseString = await call.Response.GetStringAsync();
            Console.WriteLine(responseString);
        }
    }

    public class Post
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
    }
```
Output:
```
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
Is null with logging enabled: True
Is null with logging disabled: False
```

The change would mean the the second 'post' is not null.

**Comment by eFse7en** [comment]
Available workaround (for most cases) until the issue gets fixed:
use `flurlResponse.ResponseMessage.Content.ReadAsStringAsync()` 
instead of `flurlResponse.GetStringAsync()`

FYI, current GetStringAsync method implementation can be found here: https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/FlurlResponse.cs#L184

**Comment by amaneshi** [comment]
Thanks for workaround! Also encountered this issue in my code.

**Comment by tmenier** [comment]
Finally giving this issue some love.

@shack05 @eFse7en @amaneshi Is it true for all of you that you want to get a string (such as to do logging from the `AfterCall` handler) and a specific type `T` in your normal application flow? I have a fix where you can get a string first and a deserialized object after, or vice-versa, but if you want to JSON-deserialize to 2 different types, it's a little tricky without giving up the [memory-efficient way Flurl deserializes directly from the response stream](https://www.newtonsoft.com/json/help/html/Performance.htm#MemoryUsage). With my fix it won't fail outright, but if you first deserialize to type A and later to type B, and B has properties not present on A, then that information will be lost.

I thought of adding an argument to `FlurlResponse.GetJsonAsync` that effectively lets you opt-out of that efficient deserialization (i.e. capture as a string first), but I think it would be confusing and I think this is a highly unusual scenario anyway. Being able to get a string _and_ deserialize to 1 type is an improvement over how it works today, and if it satisfies everyone's needs I think I'll roll with it.

**Comment by shack05** [comment]
Hi @tmenier, yes, being able to get a string and deserialize to 1 type is what I'm looking for. Thanks

**Comment by RobARichardson** [comment]
@tmenier  For me, being able to deserialize to multiple types would be preferable as I'm dealing with an API that can return a different successful response model depending on different circumstances (e.g. rate limit exceeded). My goal is to use AfterCallAsync to achieve global error handling by checking for a certain response model.

**Comment by tmenier** [comment]
Released

**Comment by bfondu** [comment]
Just ran into this issue trying to deserialize a polymorphic response. I first deserialize the response to a DTO with only a `Type` property, then based on that deserialize again into the correct DTO.

With the current implementation this causes the second deserialization to result in an empty DTO.
Can't you just seek the response stream to 0 and re-read it, instead of serializing the cached response?

Sidenote: I realise this will no longer be necessary when we move away from .NET 6 / Flurl 3, as `JsonPolymorphicAttribute` can then be used instead, but that's not an option at the moment.
