### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by digitalgym** [tmenier/Flurl#58]
Am I missing something? Flurl does not send headers or token in requests.

```
 var url = new Url("endpoint");
            url.WithOAuthBearerToken(token);
            url.SetQueryParam("suggestionTypes", "postcode");
            url.SetQueryParam("q", "380");
            url.SetQueryParam("limit", "20");
            url.SetQueryParam("includeUnits", true);

            try
            {
                Suggestion poco = await url.GetJsonAsync<Suggestion>();
            }
            catch (FlurlHttpException e)
            {

            }

```

**Comment by tmenier** [comment]
The Url object itself is not holding those headers. `Url.WithOAuthBearerToken` is shorthand for `new FlurlClient(url).WithOAuthBearerToken`, so you need to capture that object and use it to make your call. `Url.GetJsonAsync` is shorthand for `new FlurlClient(url).GetJsonAsync`, so you're essentially creating a second client object that has no notion of the headers you set on the first client.

Things flow a little better with the fluent syntax. Try something like this:

````
Suggestion poco = await new Url("endpoint")
    .SetQueryParams(new {
        suggestionTypes = "postcode",
        q = "380",
        limit = "20",
        includeUnits = true
    })
    .WithOAuthBearerToken(token)
    .GetJsonAsync<Suggestion>();
````
