### ISSUE TITLE
Call failed. Cannot send a content-body with this verb-type. Simple Post-Redirect-Get

### ISSUE THREAD

**Issue by andrewpros** [tmenier/Flurl#583]
The docs are lacking in this scenario, expected it to work like browsers, that is according to RFC i guess, this is how my current httpwebrequest was working.

Im doing a simple POST that gets a redirect, i was normally getting the target url source at the end, but it is not working with Flurl.

Sample code representing my use case, httpbingo is an online website so u can test clients

`var src = "http://httpbingo.org/redirect-to?url=http%3A%2F%2Fexample.com%2F".PostUrlEncodedAsync("test=test").Result;`

This returns the error: **Call failed. Cannot send a content-body with this verb-type. GET http://example.com/**

Im expecting it to follow any redirect there is and return the target website src. If i disable auto redirect it works but ofc there is no target src then.

It looks like Flurl for some reason cannot do a PRG so i can obtain the src of the redirect target with just one call. Is this a bug or im missing something here?

**Comment by tmenier** [comment]
Your exact example works fine for me. It sends a GET with no body to http://example.com and receives a 200 response. What version of Flurl are you using, and are you using any sort of custom factory or global config?

**Comment by andrewpros** [comment]
Well that's interesting.
Im using Flurl.Http.Signed and Flurl.Signed v3.0.0 for net472
I dont use custom factory or global Flurl settings, i basically used the default config.
I did create a blank new wpf app with just that test line and it is the same issue.

**Comment by andrewpros** [comment]
Ok i did investigate this further.

The issue on my system seems to be here https://github.com/tmenier/Flurl/blob/Flurl.3.0.0/src/Flurl.Http/FlurlRequest.cs#L251

It copies the preceding request headers, and if the request was POST it copies the POST headers to a GET request. Browser do not do that.
In the test case the POST headers are added automatically and they are `("Content-Type", "application/x-www-form-urlencoded")`, this is added to the GET also.
If i comment out this line it works as intended.
I checked with fiddler, its not even trying to make the redirected GET request, the underlying HttpWebRequest is checking this and just returns.
 ```
  at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
   at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
   at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
   at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```
So not sure what is wrong, any ideas are welcome..

**Comment by tmenier** [comment]
> Browsers do not do that.

Do you have a reference for that that you can point me to? I'm honestly not certain about that.

I think you're right specifically about the `Content-Type` header. If the content is removed on the GET, then it makes sense that header should be removed to. But not forwarding any headers, I'm not certain if that's the correct behavior. I haven't been able to find anything definitive, but maybe you can convince me.

**Comment by andrewpros** [comment]
To be honest im actually surprised the library is copying the POST headers to GET if there was a redirect, never heard of it, is there anything in protocol specification about forwarding headers?

Im really not sure about what the rules are exactly, but it can be tested in any browser dev tools i guess, i used fx dev tools, make a GET to the sample url and then used the modify and send again option to change it to POST, add missing headers and a custom one, it did not copy the headers to the GET request.

Browsers have their own set of headers they add to every request or conditionality like Host, User-Agent, Accept, Accept-Language, Accept-Encoding, Connection, Referer etc. but this is not something forced, custom apps using this or any other http library do not set it, at least if it is not needed and is limited to a small headers set, beyond that, its in the dev total control and responsibility, the client must support custom headers on its own if it is needed.

This issue is a more wide topic, it begs to ask what are the rules of setting headers on a followed GET request after a POST, is there a RFC about it, is there a guide like "why and what headers should be set in redirection scenario", i think there is not and it was always about default client settings and headers like browsers do and the rest was RFC and acting to current request scenario.

That being said, regardless how it is, it should work,, im still curious how is it possible that the initial example works in your environment, but does not in mine, especially when the exception is thrown by the net http stack itself, i dont get it, did you compare it, is it setting the content on your GET also, it shouldn't, cuz then it would throw the same exception as for me, right? But if it isn't setting it, how is this possible it sets it for me?

**Comment by tmenier** [comment]
> im still curious how is it possible that the initial example works in your environment, but does not in mine

I don't know. I added your exact line of code to a test in the test suite (targets netcoreapp3.1 and net48) and confirmed it returns a 200. With the debugger I was able to confirm that the verb is changed to GET and the body is discarded. This is exactly as designed. One difference is I'm using the unsigned package. I don't maintain the signed packages myself and can't speak to whether they're in sync with the unsigned 3.0. I would assume so but you might want to verify.

> im actually surprised the library is copying the POST headers to GET if there was a redirect

The System.Net.Http stack does this too. I didn't find a definitive answer in any spec so I decided it's safest to stick to this. I don't think you've provided a compelling reason for a breaking change to that behavior.

**Comment by andrewpros** [comment]
So what, why this is closed, there wont be a fix for an apparent bug? 

Where exactly is the body discarded? I also debugged this, and there is nowhere where it is discarded or something works not the same way on my end.

I will also check the unsigned packages, but i did already debugged the master and as i noted System.Net.Http stack is throwing the exception cuz the library is setting Content to the GET (its creating HttpRequestMessage.Content from Header), this is at least the direct reason its not working for me.

I just do not have any external control over this, so this must be some kind of bug as it is the easiest example i could check and still no go.

Besides, why is something deigned without a specific reason, i mean if there are no spec about the need of coping headers during redirect, its should not be there forced. Is it still a breaking change if the design is not up to the spec?

I will check where the System.Net.Http stack does this also.

**Comment by andrewpros** [comment]
@tmenier Can you open the issue, its not fixed, and it is an issue in the library itself, there is nothing on my system that would change how the internal code works.

I have found where is the issue, check this https://github.com/dotnet/runtime/issues/25485
The .net core and .net framework HttpClient has a slightly different implementation, the framework stack does not allow GET requests with content, it will throw an exception. (but the RFC allows it to be precise here)

I did check it and on a sample .net core with Flurl and then the same example works, as soon as i try it on framework again, its the same issue. I also modified the master code to omit the content, but leave the headers, and then it works.

I focused too much on the headers, i did check HttpClient redirect and it works, and yes it does copy the headers to GET, so headers are a non issue here, it was the content all along.

Also you said something that got me thinking, that the HttpClient stack is doing the same, but if it is doing the same, then why bother with manual redirection code, the reason is Flurl provides more control over some http functionality, that's why it is not using the build in HttpClient redirection support, but this also means that the stack HttpClient is doing something differently, its there in the underlying HttpClient code, it wont allow GET with content, but it will do the redirect without any issues, so it must somehow get rid of that content or just not setting it when doing a GET after redirect.

Sadly i was not able to step thru the .net HttpClient stack code to see how exactly it happens, but it is somehow happening as it just works.

It makes sense, the error **Cannot send a content-body with this verb-type. GET** is not very popular, i did find some topics, but its clear it doesn't happen very often and mostly it is due to the dev own fault in the code, so there not much info on it.

It is that way cuz the only way to do it is by mistake, when you use the underlying HttpWebRequest or the HttpClient there is basically no way to do it and not see it, if u do a GET u basically dont set any content with HttpWebRequest and HttpClient does it on its own.

This brings me to Flurl, the issue must be somewhere in the custom redirection support code that is done manually and is not doing exactly the same as HttpClient does, thats why it is setting content in a GET request and thats why on .net framework stack it throws and exception, on .net framework it should not set any body with GET requests.

The issue is somewhere in the chain of calls
SendAync https://github.com/tmenier/Flurl/blob/Flurl.3.0.1/src/Flurl.Http/FlurlRequest.cs#L158 
SyncHeaders https://github.com/tmenier/Flurl/blob/Flurl.3.0.1/src/Flurl.Http/FlurlRequest.cs#L205
SetHeader https://github.com/tmenier/Flurl/blob/Flurl.3.0.1/src/Flurl.Http/HttpMessageExtensions.cs#L55

Note that this only happens if there was some headers from the call before, so a redirection, it doesn't need to be POST, it can be GET, knowing all this and how the code looks i can force it with a GET and i will again throw, just a simple is enough `post_redirect_test_url.WithHeader("allow", "true").GetAsync().Result`

All it needs is to add one of the headers that automatically adds content to the request, all of those headers are listed in the SetHeader method.

Its the SetHeader that set the content even if it is GET request and no content. And i know its empty content but still, this is enough to throw.

So i did a simple change to SendAsync, if i do this before the final call it just works
```
 if(verb == HttpMethod.Get && content == null && request.Content != null) {
                        request.Content = null;
                    }
```
Funny enough, every GetAsync method in Flurl do not have a content parameter, but the library sets it internally based on specific headers added, this alone is in my opinion wrong.

Still not sure how it is possible it did work for you under framework as the code shows it will add the content in the examples and it will be thrown by .net, is there content on the GET request under debugger, it is always for me.

I spend hours to check this properly, if this is not a prove then i dont know what is, there is a clear flaw in the library handling the redirects with headers and content under .net framework and nit needs fixes.

**Comment by tmenier** [comment]
Yep, I stand corrected. My test suite targets both Core and Framework and I could have sworn I ran it against both when I first looked at this, but I tried it again and was able to repro in Framework. Apologies for that, I'll re-open.

That said, I think your tone got a bit demanding here. Understand that I'm the sole creator/maintainer of the library. I do this in my spare time and provide it for free. I'm not Microsoft. You're not entitled to bug fixes. I don't want bugs in the library though, so this will be added to the roadmap. I just wrapped up 3.0.1 last week and my available time is limited so I make no promises about when it will be fixed, just that it will happen in the next sprint.

You might also want to look at #500. It details the redirect features and why they were done, and might help you come up with a work-around for now.

**Comment by andrewpros** [comment]
Well i'm terribly sorry if i sounded bad, it was not my intention at all, i just wanted the library to be complete and working in all scenarios as it is really good.
I know why the redirect features are there and i think they are great, very handy.
The workaround for now is to use that features and disabling redirect when expecting it after POST and do the follow up manually with the lib or not if the resulting data is not needed.
The important thing is the bug is identified and will be fixed, that's all we need.

**Comment by tranb3r** [comment]
I'm also interested in a fix.

**Comment by Planutim** [comment]
> Well i'm terribly sorry if i sounded bad, it was not my intention at all, i just wanted the library to be complete and working in all scenarios as it is really good.
> I know why the redirect features are there and i think they are great, very handy.
> The workaround for now is to use that features and disabling redirect when expecting it after POST and do the follow up manually with the lib or not if the resulting data is not needed.
> The important thing is the bug is identified and will be fixed, that's all we need.

i also didn't expect such a drawback from a library with 15M downloads

**Comment by tmenier** [comment]
After some debate I decided to make header forwarding [opt-in](https://github.com/tmenier/Flurl/issues/608), which I think should avoid this bug in most real-world cases. But I'll still do a check and avoid creating an empty HttpContent just to forward a content-level header, which more directly fixes this bug.

**Comment by tmenier** [comment]
Published to NuGet in Flurl.Http 3.1.0
