### ISSUE TITLE
Connection string in web config is not getting changed using web api

### ISSUE THREAD

**Issue by xamarin-demo12** [tmenier/Flurl#588]
Connection string in web config is not getting changed using web api
code for web api:
using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using webapi.Models;

namespace webapi.Controllers
{
    public class Multi_DB_LoginController : ApiController
    {
      
        public static string Key;
        public  string datasrc, IntialCat, UserID, Password;
        string connStringName = "client_db1";
        String cs = ConfigurationManager.ConnectionStrings[0].ConnectionString;
         
        public void  ModifyConnection(Provider_name name)
        {
            try
            {
                Configuration configFile = null;
                if (System.Web.HttpContext.Current != null)
                {
                    configFile =
                        System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("~");
                }
                else
                {
                    ExeConfigurationFileMap map = new ExeConfigurationFileMap { ExeConfigFilename = $"{System.AppDomain.CurrentDomain.BaseDirectory}Web.Config" };
                    configFile = ConfigurationManager.OpenMappedExeConfiguration(map, ConfigurationUserLevel.None);
                }
                // Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
                if (name.provider_name == "Client1")
            {
                datasrc = "DESKTOP";
                IntialCat = "Client1";
                UserID = "sa";
                Password = "admin";
            }
              if (name.provider_name == "Client2")
            {
                datasrc = "DESKTOP";
                IntialCat = "Client2";
                UserID = "sa";
                Password = "admin";
            }
              if (name.provider_name == "Client3")
            {
                datasrc = "DESKTOP";
                IntialCat = "Client3";
                UserID = "sa";
                Password = "admin";
            }
                ConnectionStringSettings oldString = configFile.ConnectionStrings.ConnectionStrings[connStringName];
                configFile.ConnectionStrings.ConnectionStrings.Remove(oldString);
                configFile.ConnectionStrings.ConnectionStrings.Add(new ConnectionStringSettings(name.provider_name, String.Format("Data Source=datasrc;Initial Catalog=InitialCat;User ID=UserID; Password=Password")));
              //  configFile.ConnectionStrings.ConnectionStrings.Add(new ConnectionStringSettings(name.provider_name, String.Format("Data Source={0};Initial Catalog={1};User ID={2}; Password ={3},datasrc, InitialCat,UserID,Password")));
                configFile.Save(ConfigurationSaveMode.Modified, true);
            ConfigurationManager.RefreshSection("connectionString");

            }
            catch (Exception ex)

            {
                throw ex;
            }
        }
    }
}

Code to consume the above api in xamarin forms:
 private async void provider_name_SelectedIndexChanged(object sender, EventArgs e)
        {
            try
            {
                Provider_name names = new Provider_name();
                names.provider_name = name.SelectedItem.ToString();

                using (var client = new HttpClient())
                {
                    var response = await client.PostAsJsonAsync("http://192.168.0.108:8080/api/Multi_DB_Login/ModifyConnection", names);
                    ConnString.Text = response.ToString();
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
Please help, the connection string is not getting changed using the above code'
Thanks

**Comment by tmenier** [comment]
This doesn't appear to be related to Flurl. Did you post this in the wrong repo?
