### ISSUE TITLE
CookieCutter should not UrlEncode cookie values

### ISSUE THREAD

**Issue by ddrinka** [tmenier/Flurl#594]
I'm working with a backend that is particular about cookie formatting.  It's delivering me a cookie like the following:
```
Set-Cookie: cookieName=val1=abc&val2=def;
```

When I make future requests, an identical Cookie header is expected back.  Instead Flurl delivers:
```
Cookie: cookieName=val1%3Dabc%26val2%3Ddef;
```

The backend does not accept this as it's not expecting the cookie to be modified.  Browsers do not UrlEncode in this way.  They only encode semicolon, comma, and whitespace.

The offending code is here:
https://github.com/tmenier/Flurl/blob/422b0486ef9cdedee483c14419f2059929fc78cd/src/Flurl.Http/CookieCutter.cs#L75

Can we adjust this to a simple replace for the reserved characters?

**Comment by tmenier** [comment]
Probably, although with any change like this I want to make absolute certain it is compliant with the RFC, or at least "most common" if there's no applicable RFC. If you believe most browsers behave as you describe, providing link(s) to some definitive evidence would be very helpful. Thanks.

**Comment by tranb3r** [comment]
I also need a fix for this issue. 

There is a good explanation here of which characters should be banned : https://stackoverflow.com/questions/1969232/what-are-allowed-characters-in-cookies

My scenario is actually a redirect: the cookie is set in the first response, and I would expect no modification of cookie name/value in the redirect request, just a copy of name/value from "set-cookie" response header to "cookie" request header.

**Comment by vm0100** [comment]
I have the same problem.
It would be great to add a parameter to control whether it is encoded or not. Because not all cookie needs to be encoded.

**Comment by Pureaznangel** [comment]
I'm facing this problem when sending request to my server. Furl converted all my cookie values so I always got failed with response.

**Comment by Pureaznangel** [comment]
I'm facing this problem when sending request to my server. Flurl converted all my cookie values so I always got failed with response. Any option to turn this off?

**Comment by tmenier** [comment]
@tranb3r

> Most of the time, cookies are set by the server and sent back by the client without any change, so there is no need to decode/re-encode their value.
> If a user needs to read or set a cookie, maybe we should consider it's the user's responsibility to decode/encode the value, according to the escaping scheme used between server and client.

I thought about it some more and I'm in complete agreement. I don't think it even needs any sort of opt-in parameter; there's no standard that says to URL-encode cookie values, so the current behavior is just wrong. The [spec](https://tools.ietf.org/html/rfc6265#section-4.1.1) says servers "should" encode cookie values and even _suggests_ base64, but in any case I don't think the client library should form an opinion about it.

**Comment by tmenier** [comment]
Published to NuGet in Flurl.Http 3.1.0
