### ISSUE TITLE
Invalid redirection when URI scheme is not specified in Location header

### ISSUE THREAD

**Issue by AeonLucid** [tmenier/Flurl#595]
In some cases a http server can respond with the header `Location: //somedomain.com/hello?a=b`. 
Flurl redirects to `https://domain.com/somedomain.com/hello?a=b`, while it should have been `https://somedomain.com/hello?a=b` instead.

Proposal to fix this https://github.com/tmenier/Flurl/pull/593

**Comment by tmenier** [comment]
awaiting test fix #593

**Comment by tmenier** [comment]
Published to NuGet in Flurl.Http 3.1.0
