### ISSUE TITLE
ForCallsTo and ShouldHaveCalled should "pass" when query not specified but actual call contains one

### ISSUE THREAD

**Issue by Plasma** [tmenier/Flurl#596]
Hi,

(Great library, thank you!)

## Problem
It was unclear for a few minutes why the following test was failing. The problem is that `ForCallsTo("*/endpoint")` in this case should be `ForCallsTo("*/endpoint*")` in order for the `urlPattern` to match the query parameters that have been added as a result of `SetQueryParam` in the `Act` portion of the code.

```csharp
// This test currently fails:
//  Expected string length 7 but was 0. Strings differ at index 0.
//  Expected: "success"
//  But was:  <string.Empty>
[Test]
public async Task Should_match_ForCallsTo_using_WithQueryParam()
{
	// Arrange
	HttpTest.ForCallsTo("*/endpoint")
		.WithQueryParam("a", "b")
		.RespondWith("success");

	// Act
	var result = await "https://example.com/endpoint"
		.SetQueryParam("a", "b")
		.GetStringAsync();

	// Assert
	Assert.AreEqual("success", result);
}
```

In comparison, this test passes OK:

```csharp
[Test]
public async Task Does_match_ForCallsTo_using_WithQueryParam_when_asterisk_is_used_at_end_of_ForCallsTo_urlPattern()
{
	// Arrange
	HttpTest.ForCallsTo("*/endpoint*")
		.WithQueryParam("a", "b")
		.RespondWith("success");

	// Act
	var result = await "https://example.com/endpoint"
		.SetQueryParam("a", "b")
		.GetStringAsync();

	// Assert
	Assert.AreEqual("success", result);
}
```

## Discussion
I'm wondering if `Should_match_ForCallsTo_using_WithQueryParam`  should pass when the `WithQueryParam` has been called in the arrange/setup code, without needing a trailing asterisk in the `ForCallsTo` which felt redundant, because I was trying to match the `SetQueryParam` calls in the executing code.

**Comment by tmenier** [comment]
Yeah, I agree with the change and I don't think it's likely to break anyone. Thanks.

**Comment by tmenier** [comment]
It occurred to me that if `ForCallsTo` should work this way, then `ShouldHaveCalled` should too. In short, when a call is made to `https://api.com/endpoint?foo=x`, these should both "pass":

```c#
test.ForCallsTo("*/endpoint")...
test.ShouldHaveCalled("*/endpoint")...
```

**Comment by tmenier** [comment]
I'm hoping to get input from the community on whether this should wait until the next major version (it's technically breaking), or if it's reasonable to call it a bug fix and do it now.

**Comment by tmenier** [comment]
I tweeted out a note about this one and heard nothing there or here, so I'm just gonna make the call and merge this into the upcoming minor release.

**Comment by tmenier** [comment]
Published to NuGet in Flurl.Http 3.1.0
