### ISSUE TITLE
Invalid header hides exception response

### ISSUE THREAD

**Issue by andrejohansson** [tmenier/Flurl#604]
When a server returns headers like this:

```
< HTTP/1.1 500 Internal Server Error
< 500 Unknown
< Date: Fri, 18 Feb 2021 14:40:12 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
```

Flurl returns an invalid header exception due to the malformed `500 Unknown` string.
This is fine, but unfortunately it also hides the response json body of the error for me (the response is null).

Is there any way I can access the response body when an "invalid header" exception have been thrown?

**Comment by tmenier** [comment]
I don't know how to repro this, but have you tried something like this?

```c#
catch (FlurlHttpException ex)
{
    var resp = await ex.GetResponseStringAsync();
}
```
