### ISSUE TITLE
Periods following the first slash in a Url are being added to hostname

### ISSUE THREAD

**Issue by atrauzzi** [tmenier/Flurl#605]
Take any URL and throw this at the end:

```csharp
// ...
    .AppendPathSegment(".well-known/openid-configuration")
```

Or this:

```csharp
// ...
    .AppendPathSegment("/.well-known/openid-configuration")
```

The end result will end up with `https://something.com.well-known/openid-configuration`

**Comment by tmenier** [comment]
I'm not able to repro. What version of Flurl are you on? On 3.0 I do this:

```c#
var url = "https://something.com".AppendPathSegment(".well-known/openid-configuration").ToString();
```

and the result is `https://something.com/.well-known/openid-configuration`.

**Comment by atrauzzi** [comment]
I'll have to come back to this in a bit, next time my hands are in that code.  Feel free to close for now and I'll either reopen or re-report if it happens again.
