### ISSUE TITLE
Opt-in header forwarding on redirect

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#608]
With the redirect features [introduced](https://github.com/tmenier/Flurl/issues/500) in 3.0, all headers sent in the original request are automatically sent in the redirect, with the exception of `Authorization` (not sent by default as a security best practice, but can be allowed at any settings level via `Settings.Redirects.ForwardAuthorizationHeader`) and `Cookie` (also a security risk - use a `CookieJar` to intelligently pass cookies per the rules laid out in the HTTP spec). This is a regret, as there doesn't appear to be any standard for automatically forwarding headers.

Header forwarding will now be an opt-in feature via `Settings.Redirects.ForwardHeaders`, available at the global, client, and request levels, and defaulting to `false`. This setting has no effect on the `Authorization` or `Cookie` headers.

**Comment by tmenier** [comment]
The new properties can be set in the `OnRedirect` handler as well:

```c#
await client.Request(url)
    .OnRedirect(call => {
      call.Redirect.ForwardAuthorizationHeader = false;
      call.Redirect.ForwardCookies = true;
      call.Redirect.ForwardHeaders = false;
   })
   .PostAsync(...);
```

**Comment by hab** [comment]
I tried using the changes but had some issues. To me it looks like the change does not work correctly when using a CookieJar. 

```
	if (CookieJar != null && call.Redirect.ForwardCookies)
		redir.CookieJar = CookieJar;
	...
	redir.WithHeaders(Headers.Where(h =>
		h.Name.OrdinalEquals("Authorization", true) ? call.Redirect.ForwardAuthorizationHeader :
		h.Name.OrdinalEquals("Cookie", true) ? call.Redirect.ForwardCookies :
		h.Name.OrdinalEquals("Transfer-Encoding", true) ? call.Redirect.ForwardHeaders && !changeToGet :
		call.Redirect.ForwardHeaders));
```

When ForwardCookies is set to true it copies the cookies from the CookieJar and then a few lines later it overwrites the Cookie header parameter so any cookies collected before the redirection is lost. 

I would not have expected that new cookies would have been overwritten. Perhaps another flag is needed?

**Comment by tmenier** [comment]
@hab This hasn't been released yet. Did you do your own build or something?

**Comment by hab** [comment]
@tmenier You are right. I did my own build on the latest and greatest :-) I was trying to port some code to use Flurl.Http in order to be able to persist the cookies between invokations and it did not work in the latest release. I saw you worked on the cookie implementation and thought I would see if that fixed it - it did not initially fix my issue but when I removed the overwrite of the CookieJar cookies it did work.

**Comment by tmenier** [comment]
@hab I'm looking into this right now and frankly haven't been able to repro. I think I'm missing something. Would you be able to provide snippet here demonstrating the bug? Doesn't even have to be runnable, just something to give me an idea of the sequence of steps. Thanks!

**Comment by hab** [comment]
I am trying to "script" a sign-in process. The process does several redirects and during the redirects to different sub-domains they adds cookies that  should be stored. One of the cookies is a session ID that is required on one the next 302.

I am not at my workstation at the moment but I can try to see if I can extract the relevant part when I get near it again.

**Comment by tmenier** [comment]
@hab Never mind, I got it figured out. I was setting a cookie on the 3xx response, changing it in the next response, and asserting it changed in the jar, and that passed. But I needed to back that up a step and send a populated jar in the initial request, change it in the 3xx response, and make sure the changed value got sent in the redirect request. That failed. Easy fix, but wanted to prove the bug first. Thanks again.

**Comment by tmenier** [comment]
@hab I'm glad you discovered this bug, it opened my eyes to a bigger problem. I don't think the `ForwardCookies` header even makes sense. See updated description.

**Comment by hab** [comment]
@tmenier Agree. Blindly forwarding the headers could be a huge security risk and the CookieJar should take care of filtering out what is right to send.

**Comment by tmenier** [comment]
Published to NuGet in Flurl.Http 3.1.0
