### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by ritcoder** [tmenier/Flurl#61]
Are there any plans to support .net core? I'm using Flurl.Http with ASP.NET 5 and it says Flurl does not support DnxCore5.0

**Comment by tmenier** [comment]
Consider it on the radar but no timeframe at this point. If you want to fix this yourself and submit a PR I would gladly accept it.

**Comment by eByte23** [comment]
@tmenier I have done this for you, I'll submit a pr later today.

**Comment by tmenier** [comment]
awesome, thanks!

**Comment by eByte23** [comment]
Enables initial support but I duplicated code so not to disturb portable, pcl library.
These could all almost be merge into one project or very few, but the circular dependencies most be removed.
