### ISSUE TITLE
Add the possibility to specify a custom "boundary" value in PostMultipartAsync

### ISSUE THREAD

**Issue by tranb3r** [tmenier/Flurl#611]
The default behavior of System.Net.Http.MultipartContent is to generate a default "boundary" value (a random guid).
But a custom "boundary" value can also be passed to the MultipartContent constructor.

I'd like Flurl to also allow for a custom "boundary" value to be set in CapturedMultipartContent (which inherits form MultipartContent).
I think it should be as simple as adding an optional "boundary" parameter to the PostMultipartAsync method, and using it when creating the CapturedMultipartContent object.

What do you think ? 
I can prepare the PR if you agree.

**Comment by tmenier** [comment]
What would be the reason for wanting to customize the boundary? I can't think of a scenario where it matters. Just trying to decide of this is a good feature or bloat.

**Comment by tranb3r** [comment]
Webkit is using this format: "WebKitFormBoundary2tXJFhrxRsc9y2Yz"
Dotnet is using a guid: "e18c949c-57d4-4230-94a1-2fcd529d3d33"
When the need is to stick to what browsers are doing (as much as possible), then there is a need to customize the boundary (the same way it would be done for the user agent).

Also, some servers expect a specific format, or a timestamp.

**Comment by tmenier** [comment]
Hypothetically, if I were to add this as a feature, I'd much prefer a `CapturedMultipartContent.WithBoundry` method that could be called fluently inline with `AddFile` etc as opposed to a new param on `PostMultipartAsync`, which feels awkward to me. But unfortunately as you probably discovered it's a readonly field of `MultipartContent` that can only be set via the constructor, so making it work as a method would require some significant and potentially breaking refactoring.

I still think this is an unusual thing to want to do, so how about we meet half way and I allow setting boundary in a `CapturedMultipartContent` constructor. Then if you want to wire it into `PostMultipartAsync` yourself, it would be [trivial](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/MultipartExtensions.cs#L21) to do with an extension method.

**Comment by tranb3r** [comment]
I do not need it, but the new `CapturedMultipartContent` constructor could maybe also take a `subtype` parameter (instead of using the default `form-data` value).

**Comment by tmenier** [comment]
Released. Sorry for the delay.
