### ISSUE TITLE
Remove System.ValueTuple PackageReference for consumers on net472 or higher

### ISSUE THREAD

**Issue by SiCoe** [tmenier/Flurl#616]
Would you consider also targeting `net472` (along with `net461` and `netstandard2.0`) within the Flurl package?

The reason I ask is `net472` has _System.ValueTuple_ built in and therefore doesn't require the NuGet package. Unfortunately earlier versions of .NET Framework do require the package.

While there is type forwarding for System.ValueTuple to the framework implementation within the package for `net472` or higher we still occasionally find issues.

I'm happy to create a pull request with the change (and update test project targets to ensure everything works) but wanted to first hear your opinion.

**Comment by tmenier** [comment]
I'd be good with this. Good call on updating the test project - if adding another target is needed to cover all variations of dependencies then I think it's the right thing to do.

**Comment by tmenier** [comment]
Published to NuGet in Flurl 3.0.2 & Flurl.Http 3.1.0
