### ISSUE TITLE
Encoding of ? character in querystring.

### ISSUE THREAD

**Issue by MartijnA85** [tmenier/Flurl#618]
Goodmorning!

It seems to me that the ? character in the querystring is always encoded to %3F, e.g.:

_/api/2/users/check_login?username=test_ **becomes** _api /2/users/check_login%3Fusername=test_

When the Url is build using SetQueryParam, this happens always. Also when setting the isEncoded property to true.  Please note that the ? character is not encoded after building up the url. This seems to happen somewhere in the internals of the GetAsync() method. Which I guess is also the reason why the following assert example from https://flurl.dev/docs/fluent-url/  still works:

var url = "http://www.mysite.com".SetQueryParam("x", new[] { 1, 2, 3 });
Assert.AreEqual("http://www.mysite.com?x=1&x=2&x=3", url)

Is this encoding of the ? character on purpose? And why is it still done when the isEncoded property is set to true? There are multiple APIs that don't accept encoded ? characters in the query string, which is why I'm asking and proposing this as a bug.

Thank you for your time.

Best regards,

Martijn

**Comment by tmenier** [comment]
> /api/2/users/check_login?username=test **becomes** api /2/users/check_login%3Fusername=test

Can you provide a code example of this? A failing test would be ideal. I'm not sure what you mean exactly by "becomes".

**Comment by MartijnA85** [comment]
Indeed, you are right! Sorry about that! Thanks for your time!

**Comment by fairking** [comment]
I had the same issue.
In my use case the path can be anything. Eg.
`/file/abc`
`/file/abc?page=1&pagesize=100`
`/file/abc/?page=1&pagesize=100`
`?page=1&pagesize=100`
`/?page=1&pagesize=100`

So I cannot use your workaround as I have no idea which one is the part and which one is query.

The following test fails:
```
        [Theory]
        [InlineData("http://mysite.com/file/abc?page=1&pagesize=100", "http://mysite.com", "file/abc?page=1&pagesize=100")]
        [InlineData("http://mysite.com/file/abc/?page=1&pagesize=100", "http://mysite.com", "file/abc/?page=1&pagesize=100")]
        [InlineData("http://mysite.com/file/abc", "http://mysite.com", "file/abc")]
        [InlineData("http://mysite.com/file/abc/", "http://mysite.com", "file/abc/")]
        [InlineData("http://mysite.com/?page=1&pagesize=100", "http://mysite.com", "?page=1&pagesize=100")]
        [InlineData("http://mysite.com/?page=1&pagesize=100", "http://mysite.com", "/?page=1&pagesize=100")]
        public void AppendSegment(string expectedPath, string baseUri, params string[] paths)
        {
            var resut = new Url(baseUri).AppendPathSegments(paths).ToString();
            Assert.Equal(expectedPath, resut);
        }
```
