### ISSUE TITLE
Remove (trailing?) newlines from WithHeader values

### ISSUE THREAD

**Issue by christianpanton** [tmenier/Flurl#623]
If the value provided for a header ends with a newline, any subsequent headers do not get sent to the responding HTTP server.

This typically manifests in bugs that are hard to track down, as it is immediately not obvious that it was caused by the (bad) header value.

I dont know what can be done here, but TrimEnd'ing any header values could potentially mean that somebody else did not spend a day trying to debug this issue :)

**Comment by tmenier** [comment]
Released
