### ISSUE TITLE
FlurlHttpException Circular redirects detected

### ISSUE THREAD

**Issue by outman2008** [tmenier/Flurl#627]
when I use Flurl to get some website like this "https://www.yzw.cn" , 
the throw FlurlHttpException "Circular redirects detected"
can you add setting  like "allow-circular-redirects" to ignore this Exception ？
btw：System.Net.Http.HttpClient request it success !

**Comment by tmenier** [comment]
You can turn auto-redirect off entirely, or change `MaxAutoRedirects`.

https://flurl.dev/docs/configuration/#redirects
