### ISSUE TITLE
GetStreamAsync() reads the whole response body?

### ISSUE THREAD

**Issue by kostas-baltsoft** [tmenier/Flurl#630]
This piece of code seems to complete only after the whole stream was read into memory. This causes timeout for some large file requests:

```csharp 
Stream stream = await "http://site.com/music.mp3".GetStreamAsync();
```

Shouldn't it behave something like HttpClient.GetStreamAsync Method? The [Microsoft documentation clearly states](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstreamasync?view=net-5.0) that:

> This operation will not block. The returned Task<TResult> object will complete after the response headers are read. This method does not read nor buffer the response body.

I expect it should Flurl's method GetStreamAsync() should do the same?

**Comment by tmenier** [comment]
Interesting. It looks like you're correct - even though Flurl uses mostly the same mechanisms under the hood, `HttpClient.GetStreamAsync` [defaults to unbuffered](https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/HttpClient.cs#L187-L192) and Flurl defaults to buffered. Fortunately it's easy to change the behavior in Flurl. In both cases, the [`HttpCompletionOption`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcompletionoption?view=net-5.0) is key, and you can change the default directly in the Flurl call:
```c#
stream = await "http://site.com/music.mp3".GetStreamAsync(completionOption: HttpCompletionOption.ResponseHeadersRead);
```
This will get you the same behavior as with `HttpClient.GetStreamAsync`. That said, I'm not sure if or how that's going to affect timeouts. It's certainly more memory-efficient if, for example, you're streaming directly to a file, but I'd recommend Flurl's `DownloadFileAsync` method for that as it's already optimized for that purpose.

**Comment by kostas-baltsoft** [comment]
Oh, I didn't notice this parameter as it goes after the CancellationToken, my bad. I got used to the CancellationToken being the last parameter on the Microsoft stack and didn't look further. Thanks, Todd!

**Comment by tmenier** [comment]
Yeah, if I recall correctly I don't think it was there initially and I had to add it after CancellationToken in order to avoid a breaking change. I'll keep this open - ResponseHeadersRead might be a better default here but I don't think I should change it until 4.0.

**Comment by cremor** [comment]
While it is nice that Flurl allows us to specify `HttpCompletionOption.ResponseHeadersRead`, I noticed that this has a bad effect for error handling. If the HTTP call returns an HTTP error code and I then try to get the error response content with `FlurlHttpException.GetResponseStringAsync()` the return value is always null.

But if I revert the `GetStreamAsync()` call to not specify `HttpCompletionOption.ResponseHeadersRead` then the call to `FlurlHttpException.GetResponseStringAsync()` returns the correct response body.

Is there a way to get both?

**Comment by tmenier** [comment]
ResponseHeadersRead will be the default in 4.0, and this is out in prerelease 2

**Comment by EMostafaAli** [comment]
@tmenier, this new behavior causes a minor headache: `Stream.Length` will not be set. Response header will usually contain "Content-Length", however it is not accessible with `GetStreamAsync()`

**Comment by kostelis** [comment]
In addition to this, how can I read the file name from the "Content-Disposition" header using ```GetStreamAsync()``` method? Or any other header actually. Using ```GetStreamAsync()``` I receive just a stream, but how can I take advantage of the response's headers?

**Comment by kostelis** [comment]
The last question is still relevant. When getting the stream of a file, it is nice to know the file name too. However, it doesn't make sense to make two GET requests to the same endpoint: one to get the stream and the other to read the headers. Is there a nicer way to achieve this?

**Comment by tmenier** [comment]
@EMostafaAli @kostelis Sorry I missed this. Should work if you do it in multiple steps:

```c#
var resp = await url.GetAsync(); // returns an IFlurlResponse
var headerValue = resp.Headers.FirstOrDefault(headerName);
var stream = resp.GetStreamAsync();
```
