### ISSUE TITLE
Create Clients from .Net Core DI Container

### ISSUE THREAD

**Issue by gghoffman** [tmenier/Flurl#631]
Hello all, is there (could there be) a way so that Flurl when globally configured via FlurlHttp.Configure() it can utilize a FlurlClientFactory from DI? My company has a bunch of Azure functions that have a logging context available in DI and we want to seamlessly deal out clients such that before, after/onerror these clients record and report request/response data for logging and diagnosis purposes. We, as an organization are looking for a solution to this so we can seamlessly use these clients and the logging context even when a developer chooses to utilize the string based fluent extensions.

<3 Flurl

**Comment by rcollette** [comment]
I'm there with you.  I find that the lack of being able to use DI causes prevents me from being able to use other DI services such as shown here.
https://stackoverflow.com/questions/66480950/how-to-use-an-injectable-service-in-the-flurl-onbeforecall-event-handler

**Comment by tmenier** [comment]
Sorry for the delay. Event handlers weren't designed to fit the DI pattern very well directly, but if you need DI-controlled dependencies in event handlers, I'd recommend wiring them up in the same place where you register services (Startup or whatever it is in your case). It's right time to do it anyway (once at startup), and you can cheat a little and use service location to fetch dependencies. If there's a non-trivial amount of work being done in the handler, you could encapsulate it in a separate, container-unware class, which should feel less dirty and not clutter your startup class.

At least I think this sort of approach should work, I haven't tried it myself. Does this sort of answer your question?
