### ISSUE TITLE
Flurl.Http API documentation is not shown in Visual Studio IntelliSense

### ISSUE THREAD

**Issue by cremor** [tmenier/Flurl#636]
1. Create a new .NET 5 console applicaton project.
2. Add the Flurl.Http package.
3. Check IntelliSense documentation on Flurl APIs, e.g. the `Url` class or the `AppendPathSegment` string extension method.
  => All fine.
4. Check IntelliSense on Flurl.Http APIs, e.g. the `FlurlHttpException` class or the `GetAsync` string extension method.
  => No documentation is shown.

I'm not sure, but I think the problem might be that the Flurl.Http.csproj file also calls the `DocumentationFile` "Flurl.xml". I assume that should be "Flurl.Http.xml".
Seems like this was broken in Flurl.Http.3.0.0 by https://github.com/tmenier/Flurl/commit/63f61cb309e80cbd878d2abf6e12222e21fb554e

**Comment by tmenier** [comment]
Good catch with the csproj file, I wouldn't have known where to begin looking. :)

I still can't say for sure if it'll fix it but I have to imagine so. It was definitely an unintentional change. I'll get it fixed in the next maintenance release.

**Comment by tmenier** [comment]
Released
