### ISSUE TITLE
'IFlurlResponse' does not contain a definition for 'EnsureSuccessStatusCode' and no accessible extension method 'EnsureSuccessStatusCode' accepting a first argument of type 'IFlurlResponse' could be found (are you missing a using directive or an assembly reference?) [Identity Server Common Unit]

### ISSUE THREAD

**Issue by buckstephenh** [tmenier/Flurl#637]
Hi, just did a library update and have this error.   Looks like I'm going from 2.4.2 to 3.2.0.  I was unsuccessful searching for this error or finding a migration guide.  Thanks for your help in pointing me in the right direction. I have other breaking changes as well like response.Headers.TryGetValues so thanks for your help in pointing me to migration assistance.

**Comment by tmenier** [comment]
That's not a bug but is a breaking change in 3.0. I always publish [release notes](https://github.com/tmenier/Flurl/releases), you'll want to look at [breaking changes in 3.0](https://github.com/tmenier/Flurl/releases/tag/Flurl.Http.3.0.0) specifically.
