### ISSUE TITLE
Why isn't QueryParamCollection an IEnumerable of (string,string)?

### ISSUE THREAD

**Issue by jez9999** [tmenier/Flurl#640]
I've been playing with parsing URLs in Flurl with the Url class, and examining the `QueryParams` property.  No matter how I try to pull out a param (with indexing, LINQ, or the `TryGetFirst` method), it returns me an object which is an instance of a string.  Why not just make that collection a bunch of strings?  The object never seems to be anything else, and I'm not sure whether I can safely cast it to a string or not.  Is there ever a circumstance where it would not be a string?

**Comment by tmenier** [comment]
It's mainly to preserve the type you give it if you do something like `SetQueryParam("x", 5)`. In that example, the value remains an integer when you read it. If you're parsing a URL string, you can safely assume the values will always be strings.
