### ISSUE TITLE
Cookies Issue - Duplicates 

### ISSUE THREAD

**Issue by CreatedAutomated** [tmenier/Flurl#643]
For some reason whilst using flurl it is adding the same cookie to my requests twice. Even though its only set once.

Here is what the cookie looks like:

Cl_b=4|encryptedvaluehere

**Comment by tmenier** [comment]
Please provide a complete/isolated code sample that repro's this and I will investigate.

**Comment by CreatedAutomated** [comment]
All you should have to do is find a website that has cookies formatted like
that.

Create a flurl client
Send a get request to craigslist.org
Cookies are stored in your cookie jar
Send another connection with the client and cookies, and the cookie will
show twice.

**Comment by tmenier** [comment]
That's not a code sample. I don't know how to repro this and I don't believe is valid. If you disagree, re-open and provide a complete/isolated code sample to demonstrate the problem.
