### ISSUE TITLE
Unable to redirect with content on Full Framework

### ISSUE THREAD

**Issue by sanyappc** [tmenier/Flurl#644]
HttpClient disposes HttpContent after request on full framework (not core):
[Why does HttpClient dispose HttpContent?](https://github.com/dotnet/runtime/issues/14612) 
[Stop disposing of request content in HttpClient](https://github.com/dotnet/corefx/pull/19082) 

But FlurlRequest.ProcessRedirectAsync tries to reuse disposed content for redirect request and this leads to CapturedJsonContent disposed exception

**Comment by tmenier** [comment]
I'll look into this. Just so I can repro easily, what's the HTTP verb and status (3??) of the original (redirecting) call?

**Comment by sanyappc** [comment]
it's PUT with 301

**Comment by tmenier** [comment]
Sorry to do this but I think I'm going to mark this a won't-fix. I looked into it and it would be quite an involved fix, I haven't heard about anyone else running into it, and as you noted it only affects people still on full Framework, which is becoming fewer and fewer in a .NET 6 world.

You've probably found a work-around by now, but I'd suggest either trying to recreate the content in the `OnRedirect` event (I'm honestly not sure it that'll work), or disable automatic redirects entirely and handle them manually. See #500.
