### ISSUE TITLE
User-Agent Issue

### ISSUE THREAD

**Issue by CreatedAutomated** [tmenier/Flurl#652]
I am a user agent similar to below:

XXX / XXX 

Any time I add the spaces between the slashes (required btw), the spaces are removed and changed to this:

XXX/XXX

**Comment by tmenier** [comment]
> the spaces are removed

Are you observing this on the client side somehow before the request is sent, or on the server? See if you can get it to work with a raw HttpClient, but I doubt it. There's nothing coded into Flurl that would do that - it just uses [HttpHeaders.TryAddWithoutValidation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders.tryaddwithoutvalidation) under the hood. If something deep down in the HttpClient stack is the culprit, there's likely little I can reasonably do about it. That is a very [weird](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) requirement by the server.

**Comment by CreatedAutomated** [comment]
It's flurl/httpclient side.

I was debugging my app, and my user-agent does in fact have the "XXX /
XXX". But, when I build a flurlrequest and send it, the space is removed.
Very odd

**Comment by tmenier** [comment]
Are you saying it doesn't work with raw HttpClient either?

**Comment by tmenier** [comment]
Works fine based on my tests. If you can prove otherwise, please provide a failing unit test.
