### ISSUE TITLE
Http Status Code

### ISSUE THREAD

**Issue by satishviswanathan** [tmenier/Flurl#654]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.
First of all thanks for sharing this wonderful library.

In my application we have some custom Http status code starting from 512. Using flurl how I can get the status code of such an exception ?

**Comment by tmenier** [comment]
How about [FlurlResponse.StatusCode](https://github.com/tmenier/Flurl/issues/354)

**Comment by satishviswanathan** [comment]
@tmenier thank you. Got it
