### ISSUE TITLE
Help with testing and nunit

### ISSUE THREAD

**Issue by Sabuto** [tmenier/Flurl#666]
Hey all so i have a problem with the testing, i think it may be the way i am using the package itself but when i try and test the ShouldHaveCalled it only checks the base url not the added paths or query parameters.

I have posted the code that i am using here: https://stackoverflow.com/questions/70789339/testing-with-flurl-and-nunit

**Comment by tmenier** [comment]
I left a comment in the question. I get notified of SO questions tagged `flurl` so no need to also open an issue here.

**Comment by Sabuto** [comment]
Makes sense thanks :)
