### ISSUE TITLE
Unable to use Url.SetQueryParams method with a parameter that contains nullable properties.

### ISSUE THREAD

**Issue by ivan213k** [tmenier/Flurl#669]
System.InvalidCastException throws in the case when we call Url.SetQueryParams with the parameter that contains nullable property. 
It reproduces only in the 3.0.3 version.

```C#         
            int? pageId = 1;
            var query = new
            {
                Name = "Test",
                PageId = pageId
            };
            var url = new Url("https://google.com/");
            url.SetQueryParams(query); 
````

**Comment by tmenier** [comment]
Thanks for reporting. Likely a regression related to #641 or #632. I'll confirm and get a fix out ASAP.

**Comment by tmenier** [comment]
Fix has been released. Thanks again for reporting.
