### ISSUE TITLE
System.InvalidCastException: Object must implement IConvertible

### ISSUE THREAD

**Issue by springy76** [tmenier/Flurl#671]
Starting with 3.2.1, means 3.2.2 is still affected - for sure related to #632 (too)

```
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Flurl.Util.CommonExtensions.<>c.<ObjectToKV>b__8_3(<>f__AnonymousType6`2 <>h__TransparentIdentifier1)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Flurl.Url.SetQueryParams(Object values, NullValueHandling nullValueHandling)
```

My model for `Object values` (the same as for #632 in the past, crashed with 3.2.1 (#669) at other places due to the nullables):
```c#
	public class MessageFilter
	{
		public IEnumerable<int> Kinds { get; set; }
		public int? UnprocessedAndBelowMaxTries { get; set; }
		public long? UserId { get; set; }
		public long? AssociatedElementId { get; set; }
		public Guid? UserGuid { get; set; }
		public long? BearerUserId { get; set; }
		public DateTime? OlderThanUtc { get; set; }
		public DateTime? NewerThanUtc { get; set; }
		public bool? IsDrafted { get; set; }
		public bool? HasBlob { get; set; }
		public bool? IsBusyProcessing { get; set; }
		public bool? ProcessedSuccessfully { get; set; }
		public bool? CreatedByBearerUser { get; set; }
		public int MaxCount { get; set; } = 100;
	}
```

I guess the problem source is the `Kinds` property - I'm just investigating (error logs from SEQ), have to set-up repro and see what `Kinds` really is and if a `ToArray()` somewhere helps - will update when knowing more.

**Comment by springy76** [comment]
I edited my OP - passing an Array did not help, but changing the property from `IEnumerable<int>` to `List<int>` seems to fix the problem.

**Comment by tmenier** [comment]
If there is still an bug, please open a new issue with a MINIMAL reproducible example. Providing a 14-property model and no code to repro is sort of the opposite of that. Help me help you. Thanks.
