### ISSUE TITLE
System.InvalidCastException "Object must implement IConvertible" on SetQueryParams

### ISSUE THREAD

**Issue by springy76** [tmenier/Flurl#672]
Full repro;

```c#
Url url = "http://127.0.0.1/api".SetQueryParams(new Model { Values = Enumerable.Range(1, 3).ToArray() });

public class Model
{
	public IEnumerable<int> Values { get; set; }
}
```

Had been working using Flurl.Http (Flurl alone only included transitive) on versions 2.4.x, 3.0.x till 3.2.0 - now fails using 3.2.2

**Comment by tmenier** [comment]
Sorry, sort of let this slip through the cracks. Legit bug, regression related to #632. It'll be fixed in the next maintenance release.

**Comment by tmenier** [comment]
Released
