### ISSUE TITLE
PostJsonAsync to a faulty service displays GET on the Exception message

### ISSUE THREAD

**Issue by TonyHenrique** [tmenier/Flurl#674]
I am calling an service URL that is currently with issues, but I found a bug in Flurl: The error messages displays GET, but I called a PostJsonAsync. When I copied the exception message and sent to the developer he insisted that I was using GET, but my code is calling PostJsonAsync

This is the code:

	var obj = new
	{ Name = "OK"    };
	var res = await "http://[serviceurl].azurewebsites.net/api/login-integracao"
					.PostJsonAsync(obj)
					.ReceiveString()
				;

> Flurl.Http.FlurlHttpException: Call failed with status code 500 (Internal Server Error): GET https://[serviceurl].azurewebsites.net/api/login-integracao at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveString(Task`1 response)

**Comment by tmenier** [comment]
If I had to guess it's probably doing a [PRG](https://en.wikipedia.org/wiki/Post/Redirect/Get) and the error is happening on the redirect. Try adding `.WithAutoRedirect(false)` to your call, that will confirm whether the error is happening on the initial POST.

**Comment by TonyHenrique** [comment]
Great! I did not know about the possibility of this Post/Redirect/Get behaviour.

The developer gave me another URL and it worked. It is solved now!
Thank you very much!
