### ISSUE TITLE
Add a way to obtain `HttpRequest`

### ISSUE THREAD

**Issue by atrauzzi** [tmenier/Flurl#676]
I'm working with a library that only accepts instances of `HttpRequest`.  I'd love to still be able to build my requests using flurl and then prior to issuing them, obtain an `HttpRequest` instance instead.

**Comment by tmenier** [comment]
Not sure which HttpRequest class you're referring to. There's one in System.Web (Framework only) and one under Microsoft.AspNetCore.Http.

**Comment by tmenier** [comment]
Still not sure what you're asking for and haven't heard back. Sorry.

**Comment by atrauzzi** [comment]
Apologies for not getting back sooner, been fairly tied up.

Basically whatever HTTP request Flurl works with under the hood.  If an instance can even just be constructed based on the accrued state Flurl has at the point of call, that would be handy if other libraries work with requests.
