### ISSUE TITLE
Add support for URI Template (rfc6570)

### ISSUE THREAD

**Issue by andresmoschini** [tmenier/Flurl#68]
Since it is not so easy (and [sometimes impossible](http://blog.ploeh.dk/2013/04/29/rest-lesson-learned-avoid-user-supplied-data-in-uri-segments/)?) to encode an arbitrary string as URI segment, I think that it could be really useful to add support for replace segments like `api/{controller}/{id}`, and better yet add support for full [URI Template specification (rfc6570)](https://tools.ietf.org/html/rfc6570).

For example:

```csharp
var uriTemplate = "https://mysite.com/api/products/{productCode}";
var url = uriTemplate.ReeplaceSegment("productCode", "abc 123");
Assert.Equal("https://mysite.com/api/products/abc%20123", url);
```

**Comment by tmenier** [comment]
Flurl encodes URI segments just like your test, it just takes a different approach:

````
var url = "https://mysite.com/api/products".AppendPathSegment("abc 123").ToString();
Assert.Equal("https://mysite.com/api/products/abc%20123", url);
````

Did I misunderstand your point?

**Comment by andresmoschini** [comment]
Well, it is fine for this specific situation, but consider an scenario a little more complex:

```csharp
var template = "htps://mysite.com/api/accounts/{accountName}/invoices/{invoiceNumber}";
var URL = uriTemplate
    .ReplaceSegment("accountName", accountName)
    .ReplaceSegment("invoiceNumber", invoiceNumber);
´´´

Is nicer and easily to parametrize and configure than;

```csharp
var baseUrl = "htps://mysite.com/api";
var accountsSegment = "account";
var invoicesSegment = "invoices";
var URL = uriTemplate
    .AppendPathSegment(accountsSegment)
    .AppendPathSegment(accountName)
    .AppendPathSegment(invoicesSegment)
    .ReplaceSegment(invoiceNumber);
´´´

**Comment by tmenier** [comment]
Well, in fairness, there's no need for the extra variables. Personally I'd just do this:
```csharp
var URL = "htps://mysite.com/api/accounts"
    .AppendPathSegment(accountName)
    .AppendPathSegment("invoices")
    .AppendPathSegment(invoiceNumber);
```

If you prefer URI Templates, there's a great .NET implementation [here](https://github.com/tavis-software/Tavis.UriTemplates). It certainly has its merits, it's just matter of personal preference. I'm not going to change Flurl's builder API or provide an alternative one in the same library though.

**Comment by andresmoschini** [comment]
Thanks! and the alternative looks nice.

**Comment by tmenier** [comment]
What's more, it looks like `.Resolve()` from that URI Templates library I referenced returns a string, so you could even mix & match it with Flurl HTTP calls if you wanted:
```csharp
var result = await new UriTemplate("http://example.org/{tenant}/customers")
    .AddParameter("tenant", "acmé")
    .Resolve()
    .GetAsync<T>();
```

**Comment by andresmoschini** [comment]
Yep :) I am doing that.
