### ISSUE TITLE
RestClient with SSL certificate

### ISSUE THREAD

**Issue by satishviswanathan** [tmenier/Flurl#680]
dotnet 5 and using flurl  url builder to make an https call.

at the app start up I'm configuring the FlurlHttp as follows.

_**Code**_ 
FlurlHttp.Configure(settings => settings.HttpClientFactory = new X509HttpFactory(caCertificate));

 public class X509HttpFactory : DefaultHttpClientFactory
    {
        private readonly X509Certificate2 _cert;

        public X509HttpFactory(X509Certificate2 cert)
        {
            _cert = cert;
        }

        public override HttpMessageHandler CreateMessageHandler()
        {
            var handler = new HttpClientHandler();
            handler.ClientCertificates.Add(_cert);
            return handler;
        }

    }
}

_**Exception**_

Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established

 System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.\r\n ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors\r\n   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)\r\n   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)\r\n   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)\r\n   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   --- End of inner exception stack trace ---\r\n   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)\r\n   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at 
RestServiceClient

I was trying to follow the link https://stackoverflow.com/questions/41033337/c-sharp-flurl-add-webrequesthandler-to-flurlclient/41044686#41044686

Please let me know if I'm missing something. Any help is appreciated !

**Comment by Hokenh** [comment]
Your exception indicates that the problem is in the name of the certificate, **The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch** , I guess that this is in the server part and not in the client using Flurl. Try to access the host server with a browser and check the certificate.

**Comment by satishviswanathan** [comment]
@Hokenh  Thank you for sharing your thoughts on this.

From an implementation perspective. Does it look good ?

**Comment by satishviswanathan** [comment]
Also I guess I shared the wrong stack trace.

Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established, see inner exception:
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)

**Comment by Hokenh** [comment]
The error is still in the server's certificate. Certificate chain presents
problems. Maybe it's an invalid CA authority. Anyway the problem I guess
that isn't in Flurl. Check server's certificate from another software, an
online ssl checker website (
https://www.google.com/search?q=online+ssl+checker+tool ), a browser, etc.

El dc., 9 de març 2022, 17:44, Satish Viswanathan ***@***.***>
va escriure:

**Comment by tmenier** [comment]
I concur that this is not a Flurl bug. I would change this part of your implementation slightly, so it uses Flurl's default configured HttpClientHandler instead of creating a new one:

```c#
    public override HttpMessageHandler CreateMessageHandler()
    {
        var handler = base.CreateMessageHandler();
        handler.ClientCertificates.Add(_cert);
        return handler;
    }
```

Other than that everything looks fine.

**Comment by Im-PJ** [comment]
@tmenier handler doesnt show up ClientCertificates property. I'm using Flurl 4 in Xamarin. Is it removed? What is the way of certificate validation in Flurl pls help
