### ISSUE TITLE
is flurl going to be supported for .net 6?

### ISSUE THREAD

**Issue by github-ojha** [tmenier/Flurl#682]
In out application we are using flurl and its .net core 3.1. 
As microsoft is going to end support for .net core 3.1 in december 2022, We will move to .net 6 then. I am wondering it flurl going to be supported on .net 6?

**Comment by tmenier** [comment]
Yep. Flurl targets .NET Standard 2.0 which covers a very broad number of platforms and versions, including .NET 6.
