### ISSUE TITLE
AppendPathSegment appends all slashes

### ISSUE THREAD

**Issue by laviritel** [tmenier/Flurl#687]
Hello,
I have the follow test case:

```csharp
// Arrange
 var uri = new Uri("http://example.com");
 var client = new System.Net.Http.HttpClient { BaseAddress = uri };
 WebServiceClient sut = new WebServiceClient(client);

 // Act
IWebServiceRequest result = sut.AppendPathSegment("a");

// Assert
result.Url.ToString().Should().Be("http://example.com/a");
```
After I execute this test the result is: `http://example.com////a/`

Shouldn't it be, according to documentation, `http://example.com/a/`?

I use .NET6
Flurl: 3.0.5
Flurl.Http: 3.2.3

**Comment by tmenier** [comment]
If you think there's a bug in Flurl, you need to reproduce it using _just_ Flurl. I have no idea what `WebServiceClient` is or what's happening inside of it.

This example uses just Flurl and works as expected:

```c#
var url = new Url("http://example.com");
url.AppendPathSegment("a");
var result = url.ToString(); // http://example.com/a
```

**Comment by laviritel** [comment]
Thanks for your response.
Even if I use *just* Flurl the result is the same:

```csharp
var url= new Url(new Uri("http://example.com"));
url.AppendPathSegment(segment: "/////a/",false);
var result = url.ToString(); // http://example.com/////a/
```
I expected, thet result should be `http://example.com/a/`

**Comment by tmenier** [comment]
Not a bug. The only time Flurl assumes your intent isn't to add extra slashes is in cases like this:

```c#
"http://example.com/".AppendPathSegment("/a");
```

A URL with 5 consecutive slashes is technically valid, and you if you pass a string containing that as you did in your second example, Flurl won't assume you want it reduced to 1 slash. That's by design.

**Comment by laviritel** [comment]
> Not a bug. The only time Flurl assumes your intent isn't to add extra slashes is in cases like this:
> 
> ```cs
> "http://example.com/".AppendPathSegment("/a");
> ```
> 
> A URL with 5 consecutive slashes is technically valid, and you if you pass a string containing that as you did in your second example, Flurl won't assume you want it reduced to 1 slash. That's by design.

Thank you for your response.
Oh, I thought, that Flurl reduce it to one slash.
