### ISSUE TITLE
SetQueryParams - option to add prefix

### ISSUE THREAD

**Issue by djfoxer** [tmenier/Flurl#691]
In ASP.NET Core we have `[FromQuery]` attribute to map query to object in request. We can use `SetQueryParams` to build such url. It will be great to have option to add prefix to QueryParams. So something like this:
```csharp
var req = new Request() 
{
    Param1 = "P1",
    Param2 = "P2"
};
 var url = "http://myurl".SetQueryParams(req,"MyPrefix.");
```
will generate query params with additionla prefix "MyPrefix.":
```python
http://myur?MyPrefix.Param1=P1&MyPrefix.Param2=P2
```

What do you think about it?

**Comment by tmenier** [comment]
Thanks for the suggestion, but I don't think this is broadly useful enough to warrant a first-class feature. I work on ASP.NET Core APIs myself and I would consider using query strings to represent complex objects to be a bit of a smell, to be honest. A widely accepted best practice is to keep query params simple and "flat".

You do have a couple work-arounds to deal with the fact that C# identifiers can't contain dots. Either use a dictionary (where keys can be any string) or do multiple calls to `AddQueryParam(string, string)`.

**Comment by djfoxer** [comment]
Thank you for you answer. It's right that it could be too easy to make url too complex.
