### ISSUE TITLE
Add support for cancellation tokens on HTTP calls

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#7]

**Comment by julianpaulozzi** [comment]
Today there is no way to cancel the http request?

**Comment by tmenier** [comment]
There are a couple ways I can think of:
- You can set a timeout and handle the exception.
- You can capture the underlying HttpClient (`FlurlClient.HttpClient`) and call `CancelPendingRequests`.
- You can write your own extension methods that allow passing `CancellationToken`s as needed.

This issue is to add CancellationToken support to built-in methods like `GetJsonAsync`, etc. This didn't make it in for 0.3 as planned but is a high priority and will definitely be there for 1.0, which I hope to release within a month or so as time allows.

**Comment by johnnymumbles** [comment]
Can I +1 this.

I have only just started playing around with Flurl but I really like it.  However, the lack of support for cancellation is an issue.  The first two workarounds suggested by @tmenier are not going to be viable options in many scenarios.  I may, just for fun, take a stab at writing my own extensions for the handful of HTTP requests I anticipate using..

**Comment by julianpaulozzi** [comment]
Since the alternatives were given not had time to test them, so do not know the complexity or the effectiveness thereof.
However an extension method that receives an Action delegate that when called cancels the request would be useful.

**Comment by tmenier** [comment]
@johnnymumbles @johnnymumbles All HTTP-calling methods now have CancellationToken overloads. Sorry for the delay but as it doubled an already [long list of extension methods](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/HttpExtensions.cs), I wanted to get some code gen bits in place first, which I did.

Following Flurl's conventions, you should handle cancellations by catching `FlurlHttpException`, whose `InnerException` will be a `TaskCanceledException`. Let me know if you think this makes sense; I went back and forth on it a bit.

https://www.nuget.org/packages/Flurl.Http

**Comment by johnnymumbles** [comment]
@tmenier You say you went back and forth, just curious what the alternative was that you were considering.

**Comment by tmenier** [comment]
@johnnymumbles Throwing a `TaskCanceledException` directly was the alternative I considered. With `FlurlHttpException` you get a bunch of [diagnostic info](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/HttpCall.cs) and still have access to the `TaskCanceledException` if you need it. So in that regard I like it and it's consistent with Flurl's exception handling in general. The downside is that if you set up a try/catch expecting that `TaskCanceledException` will get thrown on cancellation, that won't work, and in that regard it strays from conventions/best practices for async libraries. So it was a tough call.

**Comment by mario-d-s** [comment]
@tmenier Unfortunately, I think the other option was better... I like to avoid locking in to specific libraries (i.e. containing/wrapping their specific types as much as possible) and the way it works now, one has to make each try/catch for cancellation specific to Flurl.

As a workaround, you _can_ of course set `FlurlHttpSetttings.OnError` callback and throw the raw `TaskCancelledException` from there, but it feels like jumping through hoops that should not have been there.

Any chance you could reconsider this for future versions? Provided of course there is enough support for such a revision, if I'm the only one complaining then ignore this of course 😃

**Comment by tmenier** [comment]
@mario-d-s Changing the type of exception thrown would be a breaking change, and a relatively dangerous one, because the compiler won't catch it (and error handling is obviously something you don't want to break unexpectedly).

Inheriting from `TaskCancelledException` or `OperationCancelledException` helps with that issue, although it would require Flurl to build up those objects. Containment via `InnerException` is preferable here, and it fits the [definition](https://msdn.microsoft.com/en-us/library/system.exception.innerexception.aspx) perfectly: "the Exception instance that caused the current exception."

If hiding Flurl is more important to you than providing the extra diagnostic info to the caller, then I think using `OnError` is actually a nice clean way to go. Another way would be to use an exception filter in the caller:

```c#
catch (Exception ex) when (ex.InnerException is TaskCanceledException) { ... }
```

**Comment by mario-d-s** [comment]
> Changing the type of exception thrown would be a breaking change, and a relatively dangerous one, because the compiler won't catch it (and error handling is obviously something you don't want to break unexpectedly).

Yes, I hadn't really considered that. That is something you obviously can't do.

> Another way would be to use an exception filter in the caller

That _is_ a neat alternative, thanks for pointing it out.

--

Would you perhaps consider introducing a setting for cancellation handling? Not that I'm a fan of configuration myself, but I guess there _are_ some points to be made here:

- I would not consider cancellation scenarios to be actual _errors_.
- I don't see a real use for the diagnostics in this case. Cancellation is usually done somewhere in your own code in a controlled and anticipated manner, hence I'd argue it isn't even an _exceptional_ case.
- Since cancellation is detected and handled through `OperationCancelledException`, I'd expect everyone coding for it is going to catch that. I can't believe I would be the only one using Flurl to run into aforementioned surprise.

My proposal: turn the current [exception handling block](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/FlurlRequest.cs#L148-L161), specifically [the part on cancellation](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/FlurlRequest.cs#L155-L156) into something along these lines:

```
if (ex is OperationCanceledException)
{
    if(!userToken.IsCancellationRequested)
        throw new FlurlHttpTimeoutException(call, ex);

    if(!Settings.TreatCancellationAsError) // new proposed setting, name is up for discussion
        throw;
}

...

throw new FlurlHttpException(call, ex);
```
