### ISSUE TITLE
Newtonsoft package issue. 

### ISSUE THREAD

**Issue by shenjiawei** [tmenier/Flurl#707]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.
Hi,

There's a vulnerability in Newtonsoft.Json prior version 13.0.1. https://github.com/advisories/GHSA-5crp-9r3c-p9vr. Could you upgrade the Newtonsoft.Json dependency in Flurl.http package? Currently, the latest Flurl.http nuget (3.2.4) uses Newtonsoft.Json 12.0.2.

Thanks,
Jiawei

**Comment by shenjiawei** [comment]
> Flurl.Http 4.0 is dropping Newtonsoft entirely, and 3.x is "done". You can of course upgrade Newtonsoft in your project and it will happily work with 3.x.

@tmenier Thank you for your reply. Sorry that I didn't check the option to include pre-releases and therefore didn't see that the 4.0.0 pre-release has already been available on nuget.org. Do we have a timeline for official 4.0.x release?

**Comment by tmenier** [comment]
No problem, I wouldn't expect most people to know unless they're specifically following the repo or my Twitter updates. No timeline yet (the time I have available to work on it has been very unpredictable lately), but follow [@FlurlHttp](https://twitter.com/flurlhttp) for the most up-to-date announcements.
