### ISSUE TITLE
字串BUG的问题

### ISSUE THREAD

**Issue by mluyong** [tmenier/Flurl#713]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.

http://100.100.100.100:8080/dyapp/search_goods

            var url = "http://100.100.100.100:8080/dyapp/search_goods".SetQueryParams(new
            {
                key = "8a7ac39003831f70755526b4b9601122",
                key_word = Message,
                cursor = 0
            }).GetStringAsync().Result;

get url：http://100.100.100.100/dyapp/search_goods/?key=8a7ac39003831f70755526b4b96ba17f&key_word=%E6%89%8B%E6%9C%BA&cursor=0

【8080】remove port

http://100.100.100.100:8080/dyapp/search_goods【/】

            var url = "http://100.100.100.100:8080/dyapp/search_goods/".SetQueryParams(new
            {
                key = "8a7ac39003831f70755526b4b9601122",
                key_word = Message,
                cursor = 0
            }).GetStringAsync().Result;

get url：http://100.100.100.100:8080/dyapp/search_goods/?key=8a7ac39003831f70755526b4b96ba17f&key_word=%E6%89%8B%E6%9C%BA&cursor=0

【8080】 port

**Comment by tmenier** [comment]
Not sure I understand the issue. Flurl is not removing the port, if that's what you are suggesting.

```c#
var url = "http://100.100.100.100:8080/dyapp/search_goods".SetQueryParams(new {
   key = "8a7ac39003831f70755526b4b9601122",
   key_word = "x",
   cursor = 0
});
Console.WriteLine(url.ToString()); // http://100.100.100.100:8080/dyapp/search_goods?key=8a7ac39003831f70755526b4b9601122&key_word=x&cursor=0
```
Maybe a redirect is happening.
