### ISSUE TITLE
Documentation of `Url.IsRelative` is confusing

### ISSUE THREAD

**Issue by DmitriyMaksimov** [tmenier/Flurl#723]
From my reading of the code, `IsRelative` return **false** for "https://www.site.com", **true** for "//www.site.com".
But documentation says the opposite:
```
/// <summary>
/// True if URL does not start with a non-empty scheme. i.e. true for "https://www.site.com", false for "//www.site.com".
/// </summary>
public bool IsRelative => string.IsNullOrEmpty(Scheme);
```

**Comment by tmenier** [comment]
Thanks, good catch. I'll fix this up for the next (pre)release.
