### ISSUE TITLE
FlurlHttpException includes request URL in `Message` property

### ISSUE THREAD

**Issue by yunusefendi52** [tmenier/Flurl#729]
Currently if there is an exception the `Message` shows the requesting URL, which is not really undesirable in some cases, maybe it's okay if it's just base url but currently it's showing whole URL

I have some suggestions:
- Don't include url at all
- Include only base url

**Comment by yunusefendi52** [comment]
Sorry, I can handle it using `OnError`, I'd still think the exception shouldn't include whole URL tho

**Comment by tmenier** [comment]
Why is it bad for the error to provide the URL?

**Comment by yunusefendi52** [comment]
It's not bad really. It's just for example if the endpoint has guid or something similar on the segment of the url it will shown to the user and its not user friendly IMO.

Right now I use custom handler exception to change the exception message

**Comment by tmenier** [comment]
I guess I would argue that the message is "shown" to the developer, not necessarily to the user. It's human-friendly but detailed, and I agree that it won't necessarily be appropriate to display to users in every scenario. Note that `FlurlHttpException` has a `Call` property that is an instance of [FlurlCalll](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlCall.cs), a very detailed diagnostic object that's used internally to [build](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlHttpException.cs#L40) `Message`, but you can catch the exception and use that same object build any message that is appropriate for your application.
