### ISSUE TITLE
Support for FormData with PUT

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [tmenier/Flurl#730]
Please describe the feature/enhancement in as much detail as possible.

Similar Flurl Github issue: https://github.com/tmenier/Flurl/issues/113

Request: I would like the ability in Flurl to send a request using PUT (not POST) that sends form data similar to POST `.PostMultipartAsync`

**Comment by tmenier** [comment]
That's a very unusual request. I don't think browsers can even do that. Is there some public API that works this way? I'd be curious to know which one.

In any event, I'll decline to implement this as a first-class feature, but you should be able to add your own extension method like [this one](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/MultipartExtensions.cs#L22-L26).
