### ISSUE TITLE
SetQueryParam with spaces

### ISSUE THREAD

**Issue by maxfridbe** [tmenier/Flurl#731]
I am just trying to 
"bob.com"
.SetQueryParam("scope", "a b")
.ToUri()

or

"bob.com"
.SetQueryParam("scope", "a%20b",true)
.ToUri()

and have it output
bob.com/&scope=a%20b

it either outputs with spaces or does not encode properly (%20), not sure where the fault is here

**Comment by tmenier** [comment]
Can't repro. I'm not sure what you mean by "have it output" but if you just mean `ToString`ing the Uri it works exactly as I'd expect:
```
var s = "bob.com".SetQueryParam("scope", "a b").ToUri().ToString() // "bob.com?scope=a%20b"
```
