### ISSUE TITLE
Misc breaking changes for 4.0

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#738]
Some general refactoring aimed at simplifying some core Flurl.Http classes and interfaces resulted in a few breaking changes. This issue is catch-all to make sure those get documented.

- `FlurlClient.Settings` and `FlurlRequest.Settings` container objects are read-only.
- `FlurlClient.HttpMessageHandler` removed.
- `FlurlCall.RedirectedFrom` moved to IFlurlRequest.
- `FlurlResponse` ctor takes a `FlurlCall` instead of an `HttpResponseMessage`.
- `FlurlRequest.Client` is no longer instantiated on demand by just referencing the property. If it hasn't been set explicitly, or (more common) by calling `FlurlClient.Request`, it will remain null until the request is sent.

**Comment by ngoquoctoandev** [comment]
I'm looking forward to significant improvements in version 4.0. Long time no see a maintainer/contributor to this super awesome project.
