### ISSUE TITLE
3.0.7 dlls are x86 only 

### ISSUE THREAD

**Issue by BrianJonesNMI** [tmenier/Flurl#742]
Flurl is breaking our builds because the DLL is only x86 compatible. This breaks the applications that we have set to a specific x64 bitness.

Can the DLLS be built as either ANY CPU or can you create packages that contain both bitnesses?

**Comment by tmenier** [comment]
Flurl already targets any CPU. When I create a console app targeting x64 and install Flurl 3.0.7 via NuGet, it installs without errors and the project builds successfully. Can you provide steps to reproduce? I suspect the problem is related to something else.

**Comment by tmenier** [comment]
Feel free to re-open if you can provide any more details, but as it stands I think it's simply incorrect.
