### ISSUE TITLE
Url object doesn't sort params on equality check

### ISSUE THREAD

**Issue by bazarniy** [tmenier/Flurl#743]
Hi there!

Please check this code: 
```var expectedTrueButWasFalse = new Url("/xxx?x=1&y=2").Equals(new Url("/xxx?y=2&x=1"));```

Logically it is same urls, but they are not equals. I think query params should be ordered by name in equality check to use it in test assertions for example. Or there should be custom method for this type of check.

**Comment by bazarniy** [comment]
Or you can add extension method 
```public Url SortQueryParams(this Url url)```

**Comment by tmenier** [comment]
I'm going to have to disagree on a few points:
1. This isn't a bug.
2. "Logically it is same urls..." I disagree. Many server-side web frameworks (such as ASP.NET Core) don't care about parameter order, but there's no standard dictating that URI query strings `x=1&y=2` and `y=2&x=1` are equivalent.
3. "Or you can add extension method" I don't believe this feature is broadly useful enough to bake into the library, but it's a fine idea to add to your application if you find it useful.

**Comment by pboisso** [comment]
@tmenier 
I, too, would love to see some "sort" features built into this library.  A Sort() method on QueryParamCollection for example. While the order of parameters does not matter for the returned content, for canonical purposes, some engine treat them as two different urls if they are not in the same order. Thus, sorting feature would come very handy to generate canonical urls. I would prefer the sort to be done in the library than having to do it outside. Thanks for the consideration.
