### ISSUE TITLE
Security issue with NewtonSoft

### ISSUE THREAD

**Issue by uchinago** [tmenier/Flurl#747]
https://github.com/advisories/GHSA-5crp-9r3c-p9vr

I mean we can upgrade newtonsoft ourselves,  but thinking making the base requirement higher will stop the warnings from happening

**Comment by TonyLandi-Insight** [comment]
Encountered the same issue. Newtonsoft 12.0.2 has a known vulnerability that is being flagged by Mend in our CI/CD pipelines.  
https://www.mend.io/vulnerability-database/WS-2022-0161
