### ISSUE TITLE
I really like this library, why not update it

### ISSUE THREAD

**Issue by hjslovehr** [tmenier/Flurl#756]

**Comment by tmenier** [comment]
Because it's perfect the way it is?

Kidding. I haven't had much free time in the past few months (it's a side gig that doesn't pay well), but I expect to soon so I'm hoping to pick up where I left off and get 4.0 released by early fall. Stay tuned.

**Comment by hjslovehr** [comment]
I like the way Flurl operates, it looks very smooth. Thank you for developing this library.
