### ISSUE TITLE
User-Agent from HttpClient.DefaultRequestHeaders is not set properly in FlurlClient

### ISSUE THREAD

**Issue by tranb3r** [tmenier/Flurl#778]
`User-Agent` from `HttpClient.DefaultRequestHeaders` is not set properly in `FlurlClient`, when `User-Agent` is composed of multiple `ProductInfo`.

Example: 
```
const string userAgent = "Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/120.0";
var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Add("User-Agent", userAgent);
var flurlClient = new FlurlClient(httpClient);
foreach (var (name, value) in flurlClient.Headers)
{
    Console.WriteLine(name + ": " + value);
}
```
will output to console: `User-Agent: Mozilla/5.0`
instead of `User-Agent: Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/120.0`

So, an important part of the `User-Agent` is lost.
I guess the logic of headers initialization in `FlurlClient` constructor is incorrect. 
What do you think? Am I missing something?

**Comment by tmenier** [comment]
Have you tried it with 4.0? It handles `DefaultRequestHeaders` more explicitly so I think it should work. If it's just the opposite (regression bug from 3 to 4), that might be the only case where I'd let it slow down the 4.0 train.

**Comment by tranb3r** [comment]
I've been using 4.0 for a verrrrry long time. So the problem is, I do not remember how Flurl managed Headers in 3.x.
Doing a quick test with Flurl.Http 3.2.4, I can see that Headers in FlurlClient are not initialized from httpClient.DefaultRequestHeaders. This seems to be new in 4.0.
So, is it possible in 3.x to properly set a User-Agent? And is there a solution in 4.0? I do not have answers right now but I'll let you know if I manage to figure it out.

**Comment by tranb3r** [comment]
Ok, here is some code that shows this could be considered a regression in 4.0:
```
            const string userAgent = "Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/120.0";
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Add("User-Agent", userAgent);
            var flurlClient = new FlurlClient(httpClient);
            var page = await flurlClient
                .Request("https://httpbingo.org/headers")
                .GetStringAsync();
            Console.WriteLine(page);
```

With 4.0:
```
{
  "headers": {
    "User-Agent": [
      "Mozilla/5.0"
    ]
  }
}
```
With 3.2.4:
```
{
  "headers": {
    "User-Agent": [
      "Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/120.0"
    ]
  }
}
```
But maybe there is a workaround when using 4.0.

**Comment by tranb3r** [comment]
Here is how I will workaround this issue for now:
```
        public static FlurlCLient FixUserAgent(this FlurlClient flurlClient)
        {
            var userAgent = flurlClient.HttpClient.DefaultRequestHeaders.UserAgent.ToString();
            flurlClient.Headers.AddOrReplace("User-Agent", userAgent);
            return flurlClient;
        }
```
But the issue is probably not specific to the User-Agent header.

**Comment by tranb3r** [comment]
Thank you Todd for the fix! 
I agree, MS implementation of user-agent split/join is a bit weird.

Also, I've tested pre7, it works for me.
