### ISSUE TITLE
Allow for customizable parameter ordering

### ISSUE THREAD

**Issue by DamianReeves** [tmenier/Flurl#78]
Some APIs (for example certain Amazon APIs) require signing and lexical parameter ordering. 
Right now I am handling this by sorting my parameters before signing them, but it would be convenient if we could change the order to not use insertion order only.

Until then this has been my solution:

```C#
        public static Url WithLexicalParameterOrder(this Url url)
        {
            // Get query parameters using lexical ordering
            var queryParams = url.QueryParams.OrderBy(kvp => kvp.Key, StringComparer.Ordinal);
            var newUrl = new Url(url.Path);
            foreach (var param in queryParams)
            {
                newUrl.SetQueryParam(param.Key, param.Value);
            }
            return newUrl;
        }
```

**Comment by tmenier** [comment]
What you came up looks like it would work pretty slick. What would you suggest as an alternative, specifically?

**Comment by DamianReeves** [comment]
If I add any parameters after this they will be added in insertion order requiring me to sort again. It would be great if QueryParamCollection allowed for passing along an IComparer... if that IComparer is null use defaults, otherwise use the comparer for enumerating.

**Comment by tmenier** [comment]
QueryParamCollection will now inherit from List<T>, meaning you can can call `Sort(IComparer)` on it as desired. Here's a test demonstrating:

https://github.com/tmenier/Flurl/commit/647f2f0a3072f97bdf3b81491f7f4b03d00860c2

Flurl 2.0 will be released soon!
