### ISSUE TITLE
Event Handler Changes

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#784]
While testing 4.0 I was reminded that I've soured on how event handlers work. Currently they are assigned to the `Settings` object, most commonly on `FlurlClient` or `FlurlRequest`:

```c#
client.Settings.BeforeCall = call => DoSomething();
```

There's a few reasons that I've come to think this is less than ideal:
1. You can only assign 1 handler per event type at each level. (Well, technically 2. There's also an async version of each, i.e. `Settings.BeforeCallAsync`.) Most event-based patterns allow for any number of handlers (or subscribers).
2. The fact that they're lambda-based and not class/interface-based make using them in conjunction with DI a little harder. It's possible, but you have to write a wrapper class and Flurl doesn't really give you anything prescriptive for that.
3. They muddy up Settings a bit, accounting for about [half](https://v3.flurl.dev/docs/configuration/) of the available properties. And as "actions", they don't quite feel like typical configuration settings - they feel like something different.

### What's Breaking

Quite simply, all 8 event handler properties are being removed from Settings. Instead, `IFlurlClient`, `IFlurlRequest`, and the new `IFlurlClientBuilder` will have a new `EventHandlers` property, defined as an `IList<(FlurlEventType, IFlurlEventHandler)>`.

`FlurlEventType` is an enum with 4 values: `BeforeCall`, `AfterCall`, `OnError`, and `OnRedirect`. These should be familar if you've used events in 3.x, and there's no change to when they fire.

`IFlurlEventHandler` defines 2 methods:
```c#
void Handle(FlurlEventType eventType, FlurlCall call);
Task HandleAsync(FlurlEventType eventType, FlurlCall call);
```
There's also a default implementation - `FlurlEventHandler` - that defines both methods as `virtual` noops. Inheriting this should be more convenient than implementing the interface since it's extremely likely you'll want to implement either the sync or async method and not both.

### What's Staying the Same

Flurl 3.x introduced fluent methods that let you assign event handlers like this:
```c#
client
    .BeforeCall(call => DoSomething())
    .OnError(call => HandleError(call.Exception))
    .AfterCallAsync(call => LogAsync(call))
    ...
```

These still work, with the subtle difference that they're now "additive", as opposed to overwriting any existing handler at the same level. That's probably rare, so if you're already doing event handlers this way, you should be in good shape. If you've configuring handlers on `Settings` directly, switching to the above approach is the easiest path to making them 4.0-compatible. Under the hood, those actions attach themselves to `IFlurlEventHandler` implementations, but maintain the 3.x-compatible lambda approach at the surface.

In the future I may look at adding helpers for using the class-based approach more directly and recommend DI-friendly patterns, but those enhancements can go in a minor version. I wanted to get the breaking aspects in place ahead of the official 4.0 release.

**Comment by rcdailey** [comment]
@tmenier I wanted to share some feedback with you about this change. Unlike most of the changes in v4, I feel like we took a simple thing here and make it unnecessarily harder. I'm a firm believer in DI just like you are, but I can't help but feel like this change added complexity that I'm not able to justify or appreciate.

My application performs a few tasks:

- When a request is sent or a response is received, log the body to a verbose log file.
- Sanitize (mask) hostnames so that those do not appear in the logs.
- Log when redirects are detected since that indicates a problem the user should be warned about.

Prior to v4, the way I implemented this was through a static method:

```cs
// In a static class named `FlurlLogging`
public static void SetupLogging(FlurlHttpSettings settings, ILogger log, Func<Url, Url>? urlInterceptor = null)
{
    urlInterceptor ??= SanitizeUrl;

    settings.BeforeCall = call =>
    {
        var url = urlInterceptor(call.Request.Url.Clone());
        log.Debug("HTTP Request: {Method} {Url}", call.HttpRequestMessage.Method, url);
        LogBody(log, url, "Request", call.HttpRequestMessage.Method, call.RequestBody);
    };

    settings.AfterCallAsync = async call =>
    {
        var statusCode = call.Response?.StatusCode.ToString() ?? "(No response)";
        var url = urlInterceptor(call.Request.Url.Clone());
        log.Debug("HTTP Response: {Status} {Method} {Url}", statusCode, call.HttpRequestMessage.Method, url);

        var content = call.Response?.ResponseMessage.Content;
        if (content is not null)
        {
            LogBody(log, url, "Response", call.HttpRequestMessage.Method, await content.ReadAsStringAsync());
        }
    };

    settings.OnRedirect = call =>
    {
        log.Warning("HTTP Redirect received; this indicates a problem with your URL and/or reverse proxy: {Url}",
            urlInterceptor(call.Redirect.Url));

        // Must follow redirect because we want an exception to be thrown eventually. If it is set to false, HTTP
        // communication stops and existing methods will return nothing / null. This messes with Observable
        // pipelines (which normally either expect a response object or an exception)
        call.Redirect.Follow = true;
    };
}
```

I simply called this method from my builder class which configures my clients:

```cs
builder.WithSettings(settings =>
{
    settings.JsonSerializer = new DefaultJsonSerializer(GlobalJsonSerializerSettings.Services);
    FlurlLogging.SetupLogging(settings, log);
});
```

After my transition to v4, I ended up with the following handler classes:

```cs
[SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification =
    "Naming convention borrowed from and determined by Flurl")]
public abstract class FlurlSpecificEventHandler : FlurlEventHandler
{
    public abstract FlurlEventType EventType { get; }
}

[UsedImplicitly]
public class FlurlBeforeCallHandler(ILogger log) : FlurlSpecificEventHandler
{
    public override FlurlEventType EventType => FlurlEventType.BeforeCall;

    public override void Handle(FlurlEventType eventType, FlurlCall call)
    {
        var url = FlurlLogging.SanitizeUrl(call.Request.Url.Clone());
        log.Debug("HTTP Request: {Method} {Url}", call.HttpRequestMessage.Method, url);
        FlurlLogging.LogBody(log, url, "Request", call.HttpRequestMessage.Method, call.RequestBody);
    }
}

[UsedImplicitly]
public class FlurlAfterCallHandler(ILogger log) : FlurlSpecificEventHandler
{
    public override FlurlEventType EventType => FlurlEventType.AfterCall;

    public override async Task HandleAsync(FlurlEventType eventType, FlurlCall call)
    {
        var statusCode = call.Response?.StatusCode.ToString() ?? "(No response)";
        var url = FlurlLogging.SanitizeUrl(call.Request.Url.Clone());
        log.Debug("HTTP Response: {Status} {Method} {Url}", statusCode, call.HttpRequestMessage.Method, url);

        var content = call.Response?.ResponseMessage.Content;
        if (content is not null)
        {
            FlurlLogging.LogBody(log, url, "Response", call.HttpRequestMessage.Method,
                await content.ReadAsStringAsync());
        }
    }
}

[UsedImplicitly]
public class FlurlRedirectHandler(ILogger log) : FlurlSpecificEventHandler
{
    public override FlurlEventType EventType => FlurlEventType.OnRedirect;

    public override void Handle(FlurlEventType eventType, FlurlCall call)
    {
        log.Warning("HTTP Redirect received; this indicates a problem with your URL and/or reverse proxy: {Url}",
            FlurlLogging.SanitizeUrl(call.Redirect.Url));

        // Must follow redirect because we want an exception to be thrown eventually. If it is set to false, HTTP
        // communication stops and existing methods will return nothing / null. This messes with Observable
        // pipelines (which normally either expect a response object or an exception)
        call.Redirect.Follow = true;
    }
}
```

The reason for the custom, intermediate base class is to simplify the injection into my `ServarrRequestBuilder` helper class (which builds my clients, configures them, and allows other objects to easily build requests:

```cs
public class ServarrRequestBuilder(
    ILogger log,
    IFlurlClientCache clientCache,
    ISettingsProvider settingsProvider,
    IEnumerable<FlurlSpecificEventHandler> eventHandlers)
    : IServarrRequestBuilder
{
    public IFlurlRequest Request(IServiceConfiguration config, params object[] path)
    {
        var client = clientCache.GetOrAdd(
            config.InstanceName,
            config.BaseUrl.AppendPathSegments("api", "v3"),
            Configure);

        return client.Request(path)
            .WithHeader("X-Api-Key", config.ApiKey);
    }

    [SuppressMessage("SonarCloud", "S4830:Server certificates should be verified during SSL/TLS connections")]
    [SuppressMessage("Security", "CA5359:Do Not Disable Certificate Validation")]
    private void Configure(IFlurlClientBuilder builder)
    {
        foreach (var handler in eventHandlers.Select(x => (x.EventType, x)))
        {
            builder.EventHandlers.Add(handler);
        }

        builder.WithSettings(settings =>
        {
            settings.JsonSerializer = new DefaultJsonSerializer(GlobalJsonSerializerSettings.Services);
        });

        builder.ConfigureInnerHandler(handler =>
        {
            if (!settingsProvider.Settings.EnableSslCertificateValidation)
            {
                log.Warning(
                    "Security Risk: Certificate validation is being DISABLED because setting " +
                    "`enable_ssl_certificate_validation` is set to `false`");

                handler.ServerCertificateCustomValidationCallback = (_, _, _, _) => true;
            }
        });
    }
}
```

The common base class allowed me to register my types (using Autofac) as follows:

```cs
builder.RegisterTypes(
        typeof(FlurlAfterCallHandler),
        typeof(FlurlBeforeCallHandler),
        typeof(FlurlRedirectHandler))
    .As<FlurlSpecificEventHandler>();
```

That allowed me to pass in a `FlurlSpecificEventHandler` and use a for-loop to register everything together. Without this, I ended up having to pass 3 additional arguments to my constructor (each for the after, before, and redirect handlers) and then have 3 lines to call `EventHandlers.Add()` which got pretty ugly.

I also found the fact that `Add()` took a tuple to make the syntax even more weird because of the double parenthesis, e.g.:

```
Add((FlurlEventType.AfterCall, afterCallHandler));
```

It would have been really easy to just introduce service locator here to create any number of handler objects, but I wanted to avoid that at all cost.

Again, I feel like what we had was simple and "good enough" before. As a proponent of DI-driven design, I personally feel like this was just a step too far.

Either way, I appreciate your hard work and I hope my feedback here is constructive!

**Comment by tmenier** [comment]
@rcdailey I think you could have eased this transition by using the shortcuts I mentioned.

> Prior to v4, the way I implemented this was through a static method

With the disclaimer that I haven't tested this, let's take that same static method but change it to take an `IFlurlClientBuilder` instead of `FlurlHttpSettings`. Better yet, let's make it an extension method of `IFlurlClientBuilder`:

```c#
public static void SetupLogging(this IFlurlClientBuilder builder, ILogger log, Func<Url, Url>? urlInterceptor = null)
{
    urlInterceptor ??= SanitizeUrl;

    builder.BeforeCall(call =>
    {
        ...
    });

    builder.AfterCall(call =>
    {
        ...
    });

    builder.OnRedirect(call =>
    {
        ...
    });
}
```
> I simply called this method from my builder class which configures my clients

Let's keep it just as simple then:

```c#
builder .WithSettings(settings =>
  {
      settings.JsonSerializer = new DefaultJsonSerializer(GlobalJsonSerializerSettings.Services);
  })
  .SetupLogging(log);
```

**Comment by rcdailey** [comment]
@tmenier Thank you! I am not sure why I didn't consider doing it that way. I guess I was hyper-focused on the new object model.

I think I'm still a bit unsure of where you're going with the individual objects. There seems to be two distinct mechanisms to do the same thing. Is there perhaps a use case the individual classes are more suitable for?

**Comment by tmenier** [comment]
@rcdailey 

> There seems to be two distinct mechanisms to do the same thing

2 different approaches for the user, yes. [Same mechanism under the hood](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/IEventHandlerContainer.cs#L71-L79).

> I think I'm still a bit unsure of where you're going with the individual objects.

It makes using DI inside your handlers more straightforward, something that's been a source of confusion for people in the past.

I'll be expanding on the idea soon, probably for the next minor release. This was a last-minute change, and I prioritized ease of adapting existing code (via those shortcuts) over ease of doing it the new way, for now, so it didn't delay the release even more. At a minimum, I think there will be a similar set of helpers for objects, e.g.: `builder.BeforeCall(myHandlerObject)`. I think you also highlighted the need to document this trasition better.

**Comment by rcdailey** [comment]
@tmenier Thank you for all the explanation. I retract my previous negative feedback. Understanding more ways to accomplish a simple vs DI-based solution was really helpful. It shows that users still have the flexibility to choose how they want things to be done. My opinion now is that I think you're offering more choice for different use cases which I think is a good thing. So, great work!
