### ISSUE TITLE
Can't use Flurl for Xamarin

### ISSUE THREAD

**Issue by IDontEatSoap** [tmenier/Flurl#79]
The System.Reflection.TypeExtensions package doesn't have a valid Xamarin IOS or Xamarin Droid assembly in it's nuget feed, despite saying it support those platforms.

As a result, Flur doesn't work with Xamarin.

**Comment by IDontEatSoap** [comment]
Downgrading to Flur 1.0.10 and Flur.Http 0.70 is a potential workaround - those versions work with Xamarin

**Comment by tmenier** [comment]
Hmm. What platform(s) are you targeting? Have you tried pulling in the System.Reflection.TypeExtensions NuGet package directly into your project? @kroniak Any thoughts here?

**Comment by kroniak** [comment]
It will be fixed by moving to the ASPNET CORE RC2 and targeting other target like netcoreapp. Now it's netstandard 1.4 which includes Xamarin.
When RC2 will be released I will make some PR. 

@tmenier  Assignee this to me.

**Comment by tmenier** [comment]
@kroniak Thanks, and welcome aboard. :)

**Comment by IDontEatSoap** [comment]
System.Reflection.TypeExtensions is bugged in the version Flur depends o, it doesn't have a valid portable target.

Is that dependency crucial for v2's functionality?

**Comment by morrisonbrett** [comment]
I had a problem loading 0.9.0 and 0.10.0 until I added "dotnet5.4" to my packages.json.  Now it works:

      "imports": [ "portable-net40+sl5+win8+wp8+wpa81", "dotnet", "dotnet5.4" ]

**Comment by kroniak** [comment]
@morrisonbrett you are testing net core rc2? Or Xamarin project?

**Comment by morrisonbrett** [comment]
.NET Core RC2.  Sorry if my response is out of context.

**Comment by kroniak** [comment]
@morrisonbrett its right. with next release this is not needed.

**Comment by kroniak** [comment]
@morrisonbrett with 1.0.0-beta3 you dont need using imports. Please check it.

**Comment by kroniak** [comment]
@IDontEatSoap please checkout last night build (1.0.0-beta3) with Xamarin.

**Comment by kroniak** [comment]
I didn't receive feedback and have tasted with Xamarin myself. Close this issue when merge to master.

**Comment by tmenier** [comment]
Prerelase containing this fix is now available:

https://www.nuget.org/packages/Flurl.Http/1.0.0-beta7

Please test and provide any feedback.
