### ISSUE TITLE
Make Flurl.Http compatible with Polly v8

### ISSUE THREAD

**Issue by jassent** [tmenier/Flurl#790]
Flurl and Flurl.Http are an awesome combo. Unfortunately they are currently incompatible with Polly v8 for implementing retry/resilience logic. 

The Flurl.Http AddMiddleware() method works great with Polly v7 but is incompatible with Polly v8.

The issue is that Polly v8 doesn't provide a DelegatingHandler. So I guess this more of a Polly v8 issue than a Flurl.Http issue. 

This [Sundry.Extensions.Http.Polly](https://github.com/sundryoss/Sundry.Extensions.Http.Polly) seems to get pretty close on how to setup a DelegatingHandler. Refer to the [PollyStrategyHttpMessageHandler.cs](https://github.com/sundryoss/Sundry.Extensions.Http.Polly/blob/31486a32d189c1e0cfff2fbac60a452f30e84800/src/PollyStrategyHttpMessageHandler.cs#L8)

Here is a post on StackOverlow with a [workaround](https://stackoverflow.com/questions/40745809/how-to-use-polly-with-flurl-http/77672447#77672447) for getting Flurl.Http to work with Polly v8.

Thank you again for a great library!

**Comment by tmenier** [comment]
I think there could be some useful information here for #346, which is a high post-4.0 priority. Could you add these comments there? At its core I don't think this a separate issue, and I'd rather keep it all together. Thanks!

**Comment by jassent** [comment]
Moved to #346
