### ISSUE TITLE
HttpCompletionOption.ResponseHeadersRead with GetJsonAsync<T> = Stream cannot be read exception

### ISSUE THREAD

**Issue by rwasef1830** [tmenier/Flurl#794]
Hello,

Flurl.Http: 4.0.0, default system.text.json deserializer, .net 7.0:

Using the GetJsonAsync convenience helper with HttpCompletionOption.ResponseHeadersRead gives an exception when trying to use automatic decompression. The exception is thrown from DeflateStream (Stream cannot be read). In debugger Stream.CanRead is false.

The helper is not properly explicitly reading the response when the response is not yet loaded.

Example API: https://openexchangerates.org/api/
(needs API Key)

**Comment by tmenier** [comment]
ResponseContentRead is the default in Flurl so I don't believe that's related to the exception. Have a look at #474, I think that's more likely the issue here.

**Comment by rwasef1830** [comment]
@tmenier It works correctly, the same request to the same URL if I use ResponseContentRead, but I don't wish to buffer the entire response in memory, so I use ResponseHeadersRead which then produces the exception. 

The same request with ResponseHeadersRead if I change the code to GetStreamAsync and then manually deserialize it, it works fine, and that's how I worked around it. I think this is definitely not deliberate, so it's probably a bug, because it was working correctly with same code in Flurl 3.0 (which defaulted to ResponseContentRead it seems).

**Comment by tmenier** [comment]
I think a _minimal_ example would help. Please provide a small sample that works in Flurl 3 and not in Flurl 4. I can't think of what might have changed in this area.

**Comment by rwasef1830** [comment]
@tmenier I just realized i got mistyped in the original issue report and wrote ResponseContentRead instead of ResponseHeadersRead, that's why I got confused by your response. I apologize. I will provide a PR with unit test and will try to fix it as well.

**Comment by rwasef1830** [comment]
Addd PR with fix #800
