### ISSUE TITLE
Please upgrade `Flurl.Signed` and `Flurl.Http.Signed` to 4.0.0

### ISSUE THREAD

**Issue by astrohart** [tmenier/Flurl#796]
@tmenier  FYI, the `Flurl` and `Flurl.Http` NuGet packages are distributed at version `4.0.0` but the `Flurl.Signed` NuGet package is still at v`3.0.6`, and the `Flurl.Http.Signed` NuGet package is still at `3.2.4`.  

Please move the *.Signed packages to `4.0.0`.  Thanks!

**Comment by tmenier** [comment]
I don't actually maintain the signed packages, I'd suggest opening an issue here: https://github.com/ellenfieldn/Flurl.Signed

cc @ellenfieldn
