### ISSUE TITLE
FlurlResponse breaking change in the latest version 

### ISSUE THREAD

**Issue by iamkinetic** [tmenier/Flurl#799]
I'm trying to update some library to Flurl.Http 4, and I'm having a problem updating a few unit tests.  These tests were using this code: 

```c#
var response = new HttpResponseMessage(); 
response.Headers.Add(headerName, "Some Value"); 
response.StatusCode = code; 
return new FlurlCall { Response = new FlurlResponse(response) }; 
```

I know the FlurlResponse constructor is now using a IFlurlCall, but I can't figure how to rewrite this code and I can't find any help from the docs.  Thank you!

**Comment by tmenier** [comment]
Technically this was disclosed as a breaking change (under [smaller stuff](https://github.com/tmenier/Flurl/releases/tag/Flurl.Http.4.0.0)), but I get how it flew under the radar - I didn't imagine there would be many cases where people would need to create a FlurlResponse directly. It's a bit of a chicken-and-egg now, but basically you'll want to create a FlurlCall first, use it in the FlurlResponse constructor, then assign that response to FlurlCall.Response.

A direct replacement for your code would probably be:

```c#
var response = new HttpResponseMessage(); 
response.Headers.Add(headerName, "Some Value"); 
response.StatusCode = code; 
var call = new FlurlCall { HttpResponseMessage = response };
call.Response = new FlurlResponse(call);
return call;
```

**Comment by iamkinetic** [comment]
Yeah, I've seen the mention in the smaller stuff, but I still couldn't figure the new way to do this.

We have implemented a few extensions methods for a FlurlCall response (think something like `response.AccessTokenIsExpired()`) and we are generating mock response to test theses methods.  This is why we use FlurlResponse directly.

Thanks, I have fix everything that was not working with your example code.
