### ISSUE TITLE
return 302  "Moved Temporarily" with flurl, but using httpclient is normal

### ISSUE THREAD

**Issue by DreamTom** [tmenier/Flurl#802]
using Flurl.Http;

string host = "https://www.hongkongdisneyland.com/zh-cn/merchstore/general/load";
var res = await host.GetAsync();

using (var client = new HttpClient())
{
    var res2 = await client.SendAsync(new HttpRequestMessage
    {
        RequestUri = new Uri("https://www.hongkongdisneyland.com/zh-cn/merchstore/general/load"),
        Method = HttpMethod.Get,
    });
    var resss = await res2.Content.ReadAsStringAsync();
}
Console.ReadKey();

.net version: .net 8.0 windows 11  ConsoleApp

**Comment by tmenier** [comment]
I got the same result as you, until I enabled cookies. At a minimum, if you're just making a single call, do this:

```c#
var res = await host.WithCookies(out _).GetAsync();
```

But if you're making multiple calls you'll want to capture that `CookieJar` pass it to subsequent calls:

```c#
var resp1 = await host.AppendPathSegments(...).WithCookies(out var jar).GetAsync();
var resp2 = await host.AppendPathSegments(...).WithCookies(jar).GetAsync();
...
```

Or better yet, use a `CookieSession`. See the [docs](https://flurl.dev/docs/fluent-http/#simulating-a-browser) for details.
