### ISSUE TITLE
4.0.0

### ISSUE THREAD

**Issue by liujinwww** [tmenier/Flurl#815]
Subject: Bug Report: Signature Error with Flurl.Http Version 4.0.0 and Above When Making WeChat Pay Requests

Hello,

I've encountered a bug while upgrading Flurl.Http from version 3.2.4 to 4.0.0 and above, which affects my ability to make successful WeChat Pay requests. The issue seems to revolve around a signature mismatch error.

Environment:
Flurl.Http version: 4.0.0+
Previous working version: 3.2.4
Code Snippet:
Here is the code snippet that produces the error:
```
var headers = new Dictionary<string, string>
{
    {"Content-Type", "application/json;charset=UTF-8"},
    {"Authorization", "WECHATPAY2-SHA256-RSA2048 " + auth},
    {"Accept", "application/json"},
    {"User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)"}
};

var response = await url.WithHeaders(headers).PostJsonAsync(wxPayParamIn).ReceiveString();
```
Error Message:
The following error message is returned when attempting to process a WeChat Pay transaction:

`{"code":"SIGN_ERROR","detail":{"detail":{"issue":"sign not match"},"field":"signature","location":"authorization","sign_information":{"method":"POST","sign_message_length":404,"truncated_sign_message":"POST\n/v3/pay/transactions/jsapi\n1711459174\n2mi1q0t0.npa\n{\"mchid\"\n","url":"/v3/pay/transactions/jsapi"}},"message":"签名错误，请检查后再试"}`
Summary:
This error suggests a problem with how signatures are being generated or matched in the WeChat Pay API requests when using Flurl.Http 4.0.0 and above. This was not an issue in version 3.2.4. The headers I'm using for the request include Content-Type, Authorization, Accept, and User-Agent, as detailed in the code snippet above.

I would appreciate any guidance or fix you can provide to resolve this issue.

Thank you for your support.

**Comment by tmenier** [comment]
I can't directly support use cases against specific APIs and it's hard to know where to start with this. Have you read the [upgrade guide](https://flurl.dev/docs/upgrade/)? One of the biggest changes was with the default JSON serializer, you might try swapping in the Newtonsoft serializer as described to make sure you're getting 3.x-like serialization behavior. Other than that, that best I can suggest is looking at WeChat's documentation and find out what that error means. I don't imagine there's a Flurl bug here.

**Comment by liujinwww** [comment]
Thank you for your advice and help. I'll go back and carefully read the upgrade guide, especially the part about changes to the default JSON serializer. I'll try swapping in the Newtonsoft serializer as suggested to ensure I'm getting serialization behavior similar to version 3.x. Additionally, I'll look into WeChat's documentation to understand the specific meaning of that error code. I really appreciate your guidance, and I'll try out these solutions.
