### ISSUE TITLE
Add option to disable conversion of plus signs to spaces for query parameters

### ISSUE THREAD

**Issue by GordianSchudaBGHM** [tmenier/Flurl#818]
Currently, the `QueryParamValue` constructor always uses `true` for the `interpretPlusAsSpace` parameter of `Url.Decode()` ([link to source](https://github.com/tmenier/Flurl/blob/363416c4e60911ccce4f82a5dc9012eab7e833a9/src/Flurl/QueryParamCollection.cs#L177)).

I have a use case where I have a [Base64](https://en.wikipedia.org/wiki/Base64) encoded query parameter and therefore do not want the automatic conversion of plus signs to space characters. It is fine as the default behaviour, but I would like an easier option to disable it: I cannot use `Url.QueryParams` and must resort to using `Url.Query.ToKeyValuePairs()` and transforming the values with `Uri.UnescapeDataString()` manually (as well as selecting the desired parameter).

I am not sure, what the API should look like. My idea would be adding an optional parameter to both `Url` constructors (storing it as a new private field) and passing the value through the relevant call chain, but this does not seem ideal.

Apart from this niche issue, I like Flurl. Thanks for developing it as open source!

**Comment by tmenier** [comment]
Hmm, I may consider it but if the use case is base64 characters, just know that coming up with a scheme to do URL-safe base64 is [a pretty common thing](https://stackoverflow.com/a/26354677/62600). I'd strongly recommend looking into that as your best option in the near term.

**Comment by tmenier** [comment]
At my day job we still use code from [this classic post](https://www.madskristensen.net/blog/a-shorter-and-url-friendly-guid) for shortened GUIDs. It employs URL-safe base64 and has never let us down. 😃

**Comment by GordianSchudaBGHM** [comment]
Thanks for your quick and helpful response!

While our previous solution for Base64 encoded data (in this case not GUIDs, but a similar number of bytes) did work correctly, you convinced me to use the safer route of avoiding characters that need encoding. The request for not treating plus signs as space characters was caused by some clients mangling the generated URLs in the first place (replacing `%2B` with `+` on their side).
