### ISSUE TITLE
Set up build on AppVeyor

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#83]
Also add http://shields.io badge to readme.

Low priority. @kroniak If you have any experience with this and are interested let me know.

**Comment by kroniak** [comment]
I did it with other project.  But it is only xproject, no msbuild. 
When rc2 cli tools will be available on appveyor I can do this.

I want add badges to Readme with closed PR.

**Comment by kroniak** [comment]
@tmenier please add webhook on project settings page to https://ci.appveyor.com/api/github/webhook?id=hec8ioqg0j07ttg5 and send to them only this events: 
1. PR 
2. push

Content type is x-www-form...

**Comment by tmenier** [comment]
Ok the webhook is set up.

**Comment by kroniak** [comment]
@tmenier thanks, I will review It at Monday.

**Comment by tmenier** [comment]
FYI, seeing these errors:
```
'build.flurl.cmd' is not recognized as an internal or external command, operable program or batch file.
Could not find a part of the path 'C:\projects\flurl\nuspec\Flurl.nuspec'.
```

**Comment by kroniak** [comment]
@ I see errors. I will fix it. Into dev branch.

**Comment by tmenier** [comment]
sweet!
