### ISSUE TITLE
SetQueryParam() parameters with the same name will be overwritten, either not overwritten or optionally overwritten

### ISSUE THREAD

**Issue by wuxinheng** [tmenier/Flurl#835]
The api's parameters look like this:
`
[[HttpGet]]
public Task GetBomTreeListByItemNoList(List<string> itemCodeList)
`

**Comment by wuxinheng** [comment]
Please confirm this problem and hope to contribute

**Comment by wuxinheng** [comment]
@tmenier

**Comment by tmenier** [comment]
SetQueryParam overwrites, AppendQueryParam doesn't. https://flurl.dev/docs/fluent-url/
