### ISSUE TITLE
Exception processing an empty array from the GET requests

### ISSUE THREAD

**Issue by alekdavis** [tmenier/Flurl#843]
I'm not sure if this is a bug or if I'm not doing it right, but I'm wondering: if I make a GET call that expects an array (or a single element) to be returned, but the GET call returns HTTP status 200 with no content body (or empty content body), what's the right way to handle it? Currently, I am getting an exception when Flurl is trying to deserialize the response:

Exception message:
_Response could not be deserialized to JSON: GET https://baseaddress.com/Samples?filter=filtervalue._

Inner exception message:
_Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'._

Exception call stack:
```csharp
at Flurl.Http.FlurlClient.<HandleExceptionAsync>d__28.MoveNext()
   at Flurl.Http.FlurlResponse.<GetJsonAsync>d__18`1.MoveNext()
   at Flurl.Http.Newtonsoft.ExtensionMethods.<GetJsonAsync>d__0.MoveNext()
   at Flurl.Http.Newtonsoft.ExtensionMethods.<ReceiveJson>d__2.MoveNext()
   at MySample.<GetSampleListByFilter>d__8.MoveNext() in C:\PROJECTS\....cs:line 220
```
Inner exception call stack:
```csharp
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Flurl.Http.Newtonsoft.NewtonsoftJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.<GetJsonAsync>d__18`1.MoveNext()
```

WHen I look at the `FlurlException` object's `Call.Response` properties, the content-length header has the value of 2, which is weird because when I run the same GET call manually (via a tool), the content-length returned is 0. Content-type is "application/json" in both cases.

Any ideas?

UPDATE: When I get the response string from the `FlurlException`, the `Result` field holds `[]`, so this explains the content-length of 2, which means that it is an empty array:

```csharp
    private static string? GetResponseContent
    (
        FlurlHttpException ex
    ) 
    {     
        Task<string> task = ex.GetResponseStringAsync();

        return task?.Result;
    }
```
I would assume that `[]` should be serializable to an empty array or list object. Would it be a problem with Newtonsoft? Generally, it should be more forgiving than the standard JSON deserializer (that's why we continue using it). Any thoughts?

**Comment by alekdavis** [comment]
I did a bit more research and switched the call from `GetJsonAsync()` to `GetStringAsync()` then deserializing the string (I validated that it contained "[]") via `JsonConvert` and it worked fine: I get back an empty array. So, seems like a bug to me.

**Comment by alekdavis** [comment]
Also, I tried calling the `GetJsonAsync` method that returns a `dynamic` object and it caused the same exception. So, I suspect that the strongly typed `GetJsonAsync` calls the dynamic `GetJsonAsync` and the latter cannot handle empty arrays (and possibly objects, but I haven't tried non-array types). For now, I will change my code to always get string values and then to manually convert them to objects, but I hope it can get fixed, because this condition is not uncommon and should not be hard to handle.

**Comment by tmenier** [comment]
`dynamic`s have fallen out of favor a bit in .NET, but if you must use them AND you know to expect an array (you just need flexibility with the shape of the array _items_), then use `GetJsonList` instead.

**Comment by alekdavisintel** [comment]
@tmenier I don't really worry about the shape flexibility. If the GET succeeds, it will return either an empty array or an array of one or more strongly typed items. So, I do not need (and prefer not) to use `dynamic`s. I only mentioned them because both the strongly typed and the `dynamic` versions of `GetJsonAsync` cause the same error. So, if the `dynamic` version is internally called by the strongly typed `GetJsonAsync` and it fails due to `dynamic` been out of favor in .NET, maybe `GetJsonAsyn` should call the `GetStringAsync` internally and then convert it to the object or array, since it seems to be more reliable?

**Comment by tmenier** [comment]
> if the `dynamic` version is internally called by the strongly typed `GetJsonAsync`

It isn't. Can you post your code that causes the exception?

**Comment by alekdavisintel** [comment]
This causes the exception (I changed some variable names):
```csharp
List<Sample> samples = await _restClient
    .Request(_settings.SamplesEndpoint)
    .SetQueryParams(new 
    {
        top,
        filter
    })
   .WithBasicAuth(_settings.ClientId, _settings.ClientSecret)
   .WithHeaders(GetHeaders())
   .GetJsonAsync(); 
```
This works fine:
```csharp
string result = await _restClient
    .Request(_settings.SamplesEndpoint)
    .SetQueryParams(new 
    {
        top,
        filter
    })
   .WithBasicAuth(_settings.ClientId, _settings.ClientSecret)
   .WithHeaders(GetHeaders())
   .GetStringAsync(); 

List<Sample> samples = JsonConvert.DeserializeObject<List<Sample>>(result) ?? [];
```

**Comment by tmenier** [comment]
You want to use `.GetJsonAsync<List<Sample>>()`.

**Comment by alekdavisintel** [comment]
Ah, makes sense. Thank you, thank you, thank you!
