### ISSUE TITLE
[docs] Difference between HttpClient and Flurl

### ISSUE THREAD

**Issue by lonix1** [tmenier/Flurl#847]
We use `HttpClient` extensively, in a production system.

Why would we change that to Flurl? What extra benefits does it provide / what need does it fill?

Hoping an experienced user could provide some guidance. Thanks!

(Incidentally, it would be helpful to new users if that were explained in a small paragraph on the docs site, either the main page or a FAQ page.)

**Comment by tmenier** [comment]
Flurl uses HttpClient under the hood and basically just provides an alternative, opinionated, fluent API. Many people find it reduces code and simplifies common tasks and is fun to use, but that's about it. If you're happily using HttpClient without Flurl, there may not be a compelling reason to introduce a wrapper library.
