### ISSUE TITLE
Potentially Contradicting (`HttpClient` vs `FlurlHttpSettings`) HttpVersion Settings

### ISSUE THREAD

**Issue by jedmonds-tiplu** [tmenier/Flurl#850]
This may be a stupid question, however we are dealing with a Load Balancer that does not support `HTTP/1.*` requests. Not a problem we attempted to bump the `HttpClient.DefaultRequestVersion` to `HTTP/2.0` with `HttpClient.DefaultVersionPolicy` set to `HttpVersionPolicy.RequestVersionOrLower` (see below) expecting this would be enough for Flurl.

However this seemingly does nothing to push Flurl to send a `HTTP/2.0` requests:
```
FlurlHttp.Clients.WithDefaults(builder =>
    builder
        .ConfigureHttpClient(client =>
        {
            client.DefaultRequestVersion = HttpVersion.Version20;
            client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrLower;
        })
);
```

Users additionally need to set `FlurlHttpSettings.HttpVersion` to send requests are sent via `HTTP/2.0` (which I find relatively confusing); to be fair this setting is in the [Flurl Configuration Documentation](https://flurl.dev/docs/configuration/):
```
FlurlHttp.Clients.WithDefaults(builder =>
    builder
        .ConfigureHttpClient(client =>
        {
            client.DefaultRequestVersion = HttpVersion.Version20;
            client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrLower;
        }).Settings.HttpVersion = "2.0"
);
```

What is the need for the additional setting here, why not use the `HttpClient` configuration here. My concern is around these values contradicting (`HttpClient => 1.0`, `FlurlHttpSettings.HttpVersion => 2.0`).

**Comment by tmenier** [comment]
[This documentation](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion) points at the reason, under Remarks:

> The DefaultRequestVersion property doesn't apply to the SendAsync method. The HttpRequestMessage parameter passed as the argument to the SendAsync method has its own Version property that controls the HTTP version used for the request.

Flurl uses SendAsync, so basically it needs its own defaulting mechanism, which for the clientless pattern looks like this:

```
FlurlHttp.Clients.WithDefaults(builder =>
    builder.WithSettings(s => s.HttpVersion = "2.0"));
```

**Comment by jedmonds-tiplu** [comment]
I see, thank you for the clarity :). I'll close this Question.
