### ISSUE TITLE
Bug in net core environment with encoding

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#86]
In tests and package tester on net core rc2 in net_core_rc2_full branch there are exceptions: {"'windows-1251' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.\r\nParameter name: name"}

Exception is in method
```c#
public static async Task<string> ReceiveString(this Task<HttpResponseMessage> response) {
			return await (await response.ConfigureAwait(false)).Content.ReadAsStringAsync().ConfigureAwait(false);
		}
```

@tmenier What are you think?

**Comment by tmenier** [comment]
Note to self
http://stackoverflow.com/questions/31638035/httpclient-throws-system-argumentexception-windows-1251-is-not-a-supported-en

**Comment by kroniak** [comment]
Build on dev branch passed but issue are live because Appveyor are not in win-1251.

**Comment by tmenier** [comment]
@kroniak Is this still an issue? Can you tell me how to I repro? NETCore package tester runs fine for me and as I mentioned earlier I'm not able to run Flurl.Test.NETCore.

**Comment by kroniak** [comment]
@tmenier yes, it is. I think the problem are live for any non utf coding page. I see error on Vs running, but cmd scripts OK ( Test.cmd). And I see exception on package tester projecrs too. How to reproduce? Hmmmm.

**Comment by kroniak** [comment]
@tmenier I fixed test runner. https://github.com/tmenier/Flurl/commit/5f2f468fb3713585961ff0eda069058aa9f68f12

**Comment by kroniak** [comment]
I have fixed this issue.

**Comment by tmenier** [comment]
Thanks! Changing assignee so it's not on my plate, but per #89 do we want a way to mark an issue "done but not released"?

**Comment by kroniak** [comment]
OK. Mark it as "done".
