### ISSUE TITLE
Document Dev/Build Processes

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#89]
@kroniak,
Going from a team of 1 to 2, adding AppVeyor, etc have some big implications on the whole dev workflow of this project. It might be good to get them documented in the wiki or something. For now I'll fire off some random questions here.

1. What exactly are we using MyGet for and what do you need from me?
2. Will AppVeyor be producing the NuGet packages for publishing from now on or do we still do that locally?
3. Do you think we should do most things in feature branches off dev? At what point do you think we should merge to master? Only when we publish, so that master always represents the latest released packages? (Related: Will AppVeyor build both dev and maser?)

**Comment by kroniak** [comment]
@tmenier Agree.

1. Myget is cool for fast upload and **delete** test packages while developing. You are free to upload, delete, update packages at myget. Register on myget and tell me email\username. I add you to Flurl feed owners.
2. Yes, I want to do this. AppVeyor will be producing Nuget packages. Appveyor can builds all branches or only 2 or 3. As you wish. Now is branches contains yml. I want left only dev and master.
3. I think that master must contains only production published code (x.x.x without beta and etc.). All developing make to dev branch and when we want to publish it we will make PR to master.

**Comment by kroniak** [comment]
@tmenier How I see clean dev process:

1. After release a new version create new dev branch from master.
2. All idea and issue assign to milestone and implement by new branches from dev branch and merge to dev branch. All PRs must be build passed. If needed nugets from build upload to myget.
3. When issues from milestone are over create PR from dev to master and release final x.x.x-beta nuget package before main release.
4. If all is OK, merge dev to master and release a new tag, wait build and upload version to nuget.
5. Again and again and again dev.

If need small bug fix, create new branch from specified tag and fix to master.

**Comment by tmenier** [comment]
Do you think we need a label to indicate that an issue is fixed, tested, merged to dev, and ready for the next release? I assume we don't want to close it until it's actually released.

**Comment by kroniak** [comment]
I think We can close this issue.

For next release I want implement parallel http test.

**Comment by kroniak** [comment]
May be 

bug\enhancement ---> progress ---> testing ---> done ---> fixed

**Comment by tmenier** [comment]
I thought it might be fun to give this a try:
https://waffle.io/tmenier/Flurl

The new label/status is called "ready", which means done/tested but not not released. I also color-coded the labels a little different:
green = status (waffle columns)
yellow = category
orange is still reserved for bugs

I'm still new to using labels and open to changes if you have suggestions.

**Comment by tmenier** [comment]
oh...and gray = dead :)

**Comment by kroniak** [comment]
Can we close this?

**Comment by tmenier** [comment]
I'm going to keep it open as a reminder (to myself) to add some of this info to the wiki.

**Comment by kroniak** [comment]
@tmenier I think you have protect master brunch with AppVeyor check (continuous-integration/appveyor/pr) here https://github.com/tmenier/Flurl/settings/branches.

**Comment by tmenier** [comment]
@kroniak Does not appear so: http://screencast.com/t/uflnkuVBFQOn

**Comment by kroniak** [comment]
@tmenier Add protect master by "Choose a branch..."

**Comment by tmenier** [comment]
Done. (misunderstood, thought you wanted it _not_ protected.)

**Comment by kroniak** [comment]
@tmenier I want to protect it. Em... have\must. My English is bad. =)

**Comment by tmenier** [comment]
your english is FAR better than my russian :)
