### ISSUE TITLE
Flurl.Http 0.10.0 nuget package has wrong dll

### ISSUE THREAD

**Issue by tfxdevelopment** [tmenier/Flurl#90]
Hey,

The nuget package Flurl.Http.0.10.0 has the Flurl.Http.dll version 0.7.0.0 in it, intead of the new 0.10.0.0 version. 

We weren't using any features that would break between the API changes, so normally this wouldn't be a big issue. But MsTest in vs2012 won't respect assembly binding redirects, so the tests won't run because 0.7.0.0 is compiled against an older version of Json.net. 

Any chance you could update the nuget packages with the correct versions of the dll's?

**Comment by tmenier** [comment]
Thanks. You are correct, the assembly version hasn't been bumped in the last view versions.

@kroniak I've already pulled your first big PR into dev, but I'd like to release this fix very soon. Here's our options:

1. I could do a hotfix in master and release immediately as 0.10.1
2. If you feel your work is stable enough, we could take what you've got and release as 0.11.0
3. We could go to 1.0. I don't think there's any need to rush this though, so this wouldn't be my top choice.

Thoughts?

**Comment by kroniak** [comment]
@tmenier this is bug fix on current master branch, pull and release master branch. Option 1. Appveyor will not build it.

I can not understand where you found 0.7.0. I look in master and there are not.

**Comment by tmenier** [comment]
Good. I agree. Will get it released tonight.

It's here:
https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/Properties/AssemblyInfo.cs

I know there's more clever ways to keep that in sync with the nuspec etc but I've always just done a global search & replace on the previous version. Works fine until you miss it once, then it's easy to miss going forward!

**Comment by tmenier** [comment]
Fixed/released:
https://www.nuget.org/packages/Flurl.Http/0.10.1

The DLL version appears to be correct for all 3 targets when downloading the package manually, so I assume this fixes it. If I missed something, re-open.
