### ISSUE TITLE
Can't send body with DELETE

### ISSUE THREAD

**Issue by georgiosd** [tmenier/Flurl#91]
I know it's kinda non-standard but some APIs expect to send data in the body of a DELETE request.

Please add an overload with content.

Thanks!

**Comment by tmenier** [comment]
I think this uncommon enough that we won't add it to the library, but adding it via your own extension method is quite easy:

```c#
public static Task<HttpResponseMessage> DeleteJsonAsync(this FlurlClient client, object data) {
    var content = new CapturedJsonContent(client.Settings.JsonSerializer.Serialize(data));
    return client.SendAsync(HttpMethod.Delete, content: content);
}
```

If that's not exactly the method signature you need, just follow the pattern used by any or all of the `PostJsonAsync` overloads:

https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/HttpExtensions.cs#L422-L479

**Comment by tmenier** [comment]
Good news: A better way to support unusual verb/content type combinations such as this will be available soon in Flurl.Http 1.0. See #111. You will soon be able to do this:

`url.SendJsonAsync(HttpMethod.Delete, object);`

**Comment by tmenier** [comment]
Prerelase containing this fix is now available:

https://www.nuget.org/packages/Flurl.Http/1.0.0-beta7

Please test and provide any feedback.

**Comment by georgiosd** [comment]
That's great! It's an easy-enough callback to provide so I'm glad it's there for these not-so-uncommon (for me) cases :)

Thanks!

**Comment by matt-raffel-kiva** [comment]
I think this is more common than not.   The work around is fine but would like to see this issue reopened.

**Comment by JimmyGouraud** [comment]
I know this topic is old, but just in case, you can simply create a `FlurlExtension` with a `DeleteJsonAsync` (which is exactly the same as `PostJsonAsync` but using `HttpMethod.Delete` instead of `HttpMethod.Post`).

````
public static class FlurlExtension
{
    /// <summary>
    /// Sends an asynchronous DELETE request.
    /// </summary>
    /// <param name="request">This IFlurlRequest</param>
    /// <param name="body">An object representing the request body, which will be serialized to JSON.</param>
    /// <param name="completionOption">The HttpCompletionOption used in the request. Optional.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <returns>A Task whose result is the received IFlurlResponse.</returns>
    public static Task<IFlurlResponse> DeleteJsonAsync(this IFlurlRequest request, object body, HttpCompletionOption completionOption = HttpCompletionOption.ResponseContentRead, CancellationToken cancellationToken = default)
    {
        request.EnsureClient();
        var content = new CapturedJsonContent(request.Settings.JsonSerializer.Serialize(body));
        return request.SendAsync(HttpMethod.Delete, content, completionOption, cancellationToken);
    }
}
```
