### ISSUE TITLE
Drop support for NET 4.0

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#94]
I am suggesting drop support NET4 for Flurl package.

**Comment by tmenier** [comment]
I am open to the idea, if there is a good reason. I would definitely want to give users a chance to weigh in on Twitter, etc.

What are your reasons?

**Comment by tylerlong** [comment]
I don't think we should drop it unless there are really good reasons.
My company is still using .NET 4.0 by the way.

**Comment by kroniak** [comment]
OK
