### ISSUE TITLE
Eliminate shared projects under src?

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#97]
It seems that the shared projects under src are now only referenced by one project each:

Flurl.Library -> Flurl.Shared
Flurl.Http.Library -> Flurl.Http.Shared

This would seem to defeat the purpose of using shared projects. Would it simplify things to eliminate them and just roll the code up to the library projects themselves?

**Comment by kroniak** [comment]
@tmenier You are not right.

https://github.com/tmenier/Flurl/blob/dev/Test/Flurl.Test.NET45/Flurl.Test.NET45.csproj#L61
https://github.com/tmenier/Flurl/blob/dev/Test/Flurl.Test.PCL/Flurl.Test.PCL.csproj#L69

**Comment by tmenier** [comment]
But do you see any problem if those Test projects referenced the Library projects instead of the Shared projects?

It's not a big deal and I can make the change, I just want to understand if there is any benefit to the shared projects anymore.

**Comment by kroniak** [comment]
I think that Cs project cannot reference xproj in rc2. I think use shared projects is right. And in this case code is tested directly.

**Comment by kroniak** [comment]
Can we close this?
