### ISSUE TITLE
Run CodeGen as pre-build event of Flurl.Http.Library

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#98]
This was lost as part of the conversion to xproj/project.json. I don't think it needs to hold up the release Flurl.Http 1.0 but I just want to get it logged.

It looks like it is (or was) supported in the "scripts" node of project.json, but as noted this documentation is out of date.
https://github.com/aspnet/Home/wiki/Project.json-file

**Comment by kroniak** [comment]
Look build\build.flurl.http.cmd. It works. And in appveyor too. Learn build cmds too.

It is a part of full non Vs and windows build. If you need pack use cmd from build folder. Appveyor build packages and using msbuild is not necessary. Only for developing.

**Comment by tmenier** [comment]
Got it. Yes I'll probably want this back in VS build at some point, but thanks for pointing out that it's there for appveyor. That's more important. Good stuff!

**Comment by kroniak** [comment]
And I will look for scripts tag of project.json.

**Comment by kroniak** [comment]
@tmenier no more non node.js runner with cli. This will realise only after moving back to csproj.

**Comment by kroniak** [comment]
@tmenier I have realized this feature. And I dont like. Code is running before every compiling, before every target. I think we can refuse this feature.

**Comment by tmenier** [comment]
yeah, that's fine. it probably only ever needs to run when the generator itself changes.
